### ISSUE TITLE
suggestion: add some options

### ISSUE THREAD

**Issue by btpka3** [FrDH/jQuery.mmenu#466]
I an trying to write a simple angular [plugin](https://github.com/btpka3/btpka3.github.com/blob/master/js/jQuery.mmenu/ng-mmenu/src/mmenu.js) for jQuery.mmenu.

Here is the [demo](http://btpka3.github.io/js/jQuery.mmenu/ng-mmenu/test/ng-mmenu-test.html#/) for a single page application which using angular ui-router.

The main method I'am using is : when left page, I need to undo what the jQuery.mmenu  has changed in the dom (especially dom changes outer the angular controller or ui-router's ui-view):
1.  delete the `nav` prepended to body
2.  unwrape the mm-page node or just remove the `mm-*` class names。
3.  delete the "#mm-blocker"
4. unregister anchor onClick handler.

For better to do  these above, I suggest jQuery.mmenu:
1. add option to avoid register onClick handler on anchors
2. when wrapper mutiple html nodes to a single html node, the new html node add a tag class to mark it. e.g. class="mm-wrapped". With this class, when undo the dom changes, I can decide unwrape the mm-page node or just remove the `mm-*` class names。
3. wish can provide a  `destroy` api 
4. provide status check api such as `isOpened()`

**Comment by FrDH** [comment]
You could have a look at the jQuery mobile wrapper and the turbolinks wrapper
https://github.com/BeSite/jQuery.mmenu/blob/master/src/wrappers/js/jquery.mmenu.jquerymobile.js
https://github.com/BeSite/jQuery.mmenu/blob/master/src/wrappers/js/jquery.mmenu.turbolinks.js

These two fix most (if not all) issues when loading a new page/view without actually leaving the webpage.

General info on framework wrappers:
http://mmenu.frebsite.nl/documentation/framework-wrappers.html

Hope this helps.

**Comment by villanus** [comment]
Links above are broken
