### ISSUE TITLE
Scrolling not working using pageSelector config parameter

### ISSUE THREAD

**Issue by alexlabarces** [FrDH/jQuery.mmenu#467]
Hello,

After implementing the mmenu plugin, we currently have the issue where the menu does not scroll when using the offCanvas pageSelector parameter. 

The code used to initialize the mmenu is:

```javascript
jQuery("#off_canvas_menu").mmenu({
        classes: "mm-zoom-menu mm-zoom-panels mm-light",
        "header": {
            "title": 'Site Title',
            "add": true,
            "update": true
        }
    }, {
    // config
    offCanvas: {
        pageSelector: ".mm-page"
    }
});
```

The corresponding HTML is as follows:

```html
<body>
    <nav id="off_canvas_menu">
       <!-- Menu Contents in Here -->
    </nav>
    <div class="mm-page mm-slideout">
        <!-- Site Content in Here -->
    </div>
</body>
```

If we remove the offCanvas configuration for the pageSelector parameter, the menu works as expected and scrolling is enabled. If we keep it, you can see the scroll bar moving on screen but neither the menu nor the actual page move. 

Below is the code that actually works on the page:

```javascript
jQuery("#off_canvas_menu").mmenu({
        classes: "mm-zoom-menu mm-zoom-panels mm-light",
        "header": {
            "title": 'Site Title',
            "add": true,
            "update": true
        }
});
```

Note that we had to remove the config parameters in the code above in order to get the menu to work.

Setting the pageSelector config parameter prevents the plugin from firing the Javascript contents of the page twice, once on load, and once when it wraps the content. This is why it's important to be able to use that parameter. 

We've tried to adjust the overflow:hidden parameter in the CSS files, but that has not solved the issue.

Some help to get this resolved would be much appreciated.

Thanks!

**Comment by FrDH** [comment]
The class "mm-page" is added to the DIV by the plugin., you're probably better of not using it manually.
Could you upadate to the latest version of the plugin? The "header" option has been deprecated for a few versions.

Is there an online example I could have a look at?

**Comment by FrDH** [comment]
Is this issue still relevant? Otherwise I'm going to close it.
