### ISSUE TITLE
Keyboard navigation of panels

### ISSUE THREAD

**Issue by RaffaeleSgarro** [FrDH/jQuery.mmenu#472]
It should be possible to have a keyboard selection that fires an event when the user presses <kbd>ENTER</kbd>. The selection should be changed with the arrow keys

**Comment by FrDH** [comment]
Because the menu is mainly intended for mobile usage, keyboard navigation is low on the priority list. If you want, you can create your own add-on though.

**Comment by RaffaeleSgarro** [comment]
Sure! I created these issues mainly because I want to contribute code back, so it's better to understand your development-testing-releasing cycle before sending any pull request

**Comment by propertunist** [comment]
i've been looking for a way to open and close the menu with a keyboard shortcut. an add-on or just a jquery snippet would be great.

**Comment by RaffaeleSgarro** [comment]
That is trivial: in my application I use CTRL+SPACEBAR to toggle the menu
for example. Just google for jquery keybindings

Il giorno sab 21 nov 2015 01:34 ura soul <notifications@github.com> ha
scritto:

**Comment by propertunist** [comment]
sure, i haven't looked for a solution yet - i just mentioned it to futher inspire an addon for keyboard shortcuts!

**Comment by fuzzy76** [comment]
In a responsive webpage you can't be sure mmenu is only shown to mobile users (sniffing mobiles is terrible). Anyone can shrink their browser window (or zoom in on the text) enough to trigger the menu. This breaks accessibility.

**Comment by fuzzy76** [comment]
Strongly related / duplicate : #73

**Comment by FrDH** [comment]
In version 5.7 there now is a "keyboard navigation" add-on available.
