### ISSUE TITLE
Browser autojumping when trying to close menu with #insertnamehere type navigation

### ISSUE THREAD

**Issue by RazzaFrazza** [FrDH/jQuery.mmenu#474]
So I have a mobile nav that uses mmenu & ids to jump to different parts of the page when links are clicked. 

Originally this didn't work at all however after I commented out all of the onclick related JS in the plug-in file the browser does jump to the section however when I click off of mmenu the browser jumps back to the middle of the site. This is a spa that uses Meteor. Any thoughts as to what to do here would be great. My code is below. 

    $("#mobileMenu").mmenu({
              "offCanvas": {
                  "zposition": "front",
                  "position": "top"
               }
            })
    .on( "closing.mm", function(e) {
      e.preventDefault();
    })
    .on( "closed.mm", function(e) {
      e.preventDefault();
    });
   $("#mobileMenu").mmenu();

**Comment by FrDH** [comment]
Have you tried the one-page example that comes with the download?
Have you tried if the custom events actually do anything? They've been replaced with an API a couple of versions ago...
