### ISSUE TITLE
Add plugin for AngularJS

### ISSUE THREAD

**Issue by tiagocedrim** [FrDH/jQuery.mmenu#475]
Create jQuery.mmenu form in AngularJS =D

**Comment by FrDH** [comment]
Thank you for the suggestion. Has been added to the whishlist.

**Comment by tiagocedrim** [comment]
:+1:

**Comment by FrDH** [comment]
I found that to get things working with AngularJS, all you need to do is work around the default behavior when clicking an anchor which `href` is equal to or starts with "#":

````javascript
$('#menu').mmenu({
    onClick: {
        close: true,
        preventDefault: false
    }
});
````

In addition, both options can also take a function that returns a valid value. Inside the function, `this` refers to the anchor clicked.

For more information, see the documentation:
http://mmenu.frebsite.nl/documentation/options/

Hope this helps.
