### ISSUE TITLE
One page website scroll jumps to top...

### ISSUE THREAD

**Issue by WKDONE** [FrDH/jQuery.mmenu#484]
I've tried adding this to a simple one page site but the page jumps back to the top when you click on the menu icon... eg: you scroll down to the bottom of the page, you then hit the menu icon, the page jumps back to top and the menu opens.... 
What am I missing? I have it setup as a push from left....

**Comment by FrDH** [comment]
Have you tried the one-page example in the download pack?
You probably need to "delay" jumping/scrolling to the sections until the menu has closed.

**Comment by cmdillon** [comment]
i have the same problem...
i'm not making a one-page site with scroll-to points. i just have a fixed position menu at the top of the page. when i scroll to the bottom of the page and click a button i've made to open mmenu, the page scrolls to the top. when i close mmenu the page scrolls back to the position where i clicked to open mmneu.

i've used mmenu on a previous project last year and this effect was not there. 
here is the open code and the init for the menu:
// off canvas navigation
    $( '#mmenu-nav' ).mmenu({
        navbars: false,
        slidingSubmenus: false,
        extensions: ['theme-black','pageshadow'],
        onClick: {
            close: true,
            setSelected: true
        },
        clone: true,
        offCanvas: {
            position: 'right',
            classNames: {
                vertical: 'expand',
                selected: 'active'

            }
        },
        classNames: {
            fixedElements: {
                fixed: 'mmenu-nav'
            }
        }
    });

   // trigger menu open
    $('#btn-nav-hamburger').on( 'click', function ( event ) {
        event.preventDefault();
        $( '#mmenu-nav' ).data( 'mmenu' ).open();
    } );
any help would greatly be appreciated...

**Comment by cmdillon** [comment]
well found the problem, but not a solution...

seems that mmenu doesn't play well with '<html>' element having a attribute of 100%

as always any help on this would will be greatly be appreciated...

**Comment by FrDH** [comment]
Not sure what you mean with '', but setting `height: 100%;` on either the HTML or BODY doesn't make any sense sementically.
There's a section about this on the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html).

**Comment by toffy-digital** [comment]
hi FrDH, 
unless we set the body, html height to 100% can we make any container div expand to a 100% height. So this is why we want to make some containing div a 100% height as its part of the design.

So I am facing the exact same issue: when the button is clicked to open the entire page scrolls up to the top.

Is there another workaround to this problem without removing the height from the HTML ?

**Comment by FrDH** [comment]
Have you trad the page I linked to?
It suggests you use 'height: 100vh'.

**Comment by toffy-digital** [comment]
yes, I saw that that did not work.

I, however managed to get it working by doing this to the wrapper:

.my-wrapper{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100%;
  display: block;
}

I am not sure why this worked for me, but it worked.

My body and HTML classes look like:

html{
    background-color: $dark;
    font-size: 14px;
    position: relative;
    padding: 0px;
    margin: 0px;
    min-height: 100%;
}

body{
  background-color: $dark;
}
