### ISSUE TITLE
location of DIV changes after i add class=Fixed

### ISSUE THREAD

**Issue by propertunist** [FrDH/jQuery.mmenu#486]
i have a DIV element here that acts as a background image and is intended to stay fixed on the screen (after having been sized, placed and faded in using jquery). the DIV is within the containing DIV for the body of my page.
when i added mmenu to the site, the fixed value was ignored, so i just added class=Fixed to the background image DIV and the DIV disappeared behind other objects on the page.
after examining the page in firefox's inspector, i see that the background image DIV has been moved within the DOM and now appears outside of the page's main container DIV - thus breaking the layout and hiding the DIV that needs to stay fixed.
is this an intended behavior in some way?

i don't have a live example you can look at presently, but i could put it on my test site if necessary. thanks

**Comment by FrDH** [comment]
That's exactly what the `FixedElements` add-on does. Here's why:
The page (".mm-page") slides out using `transform: translate3D( x, y, z );`, this inconveniently creates a new viewport from the page. Meaning, all elements inside it that have `position: fixed;` are positioned relative to the page, not the window. This probably is what you mean with "the fixed value was ignored".

In short, fixed elements can have either one of the following:
- positioned relative to the window, but outside of the page
- inside the page but positioned relative to the page

**Comment by propertunist** [comment]
ok, thanks for the info - i'll come back to this when i have more time available

**Comment by evanre** [comment]
@FrDH Hi, please, note on [this feature tutorial page](http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html) that, if user wants to define custom class for element (not `Fixed`), he need to write a new one. Because addon will replace this class to `mm-slideout`. And if you specify it to main class (that contains CSS properties for this element), it would disappear from all DOM.
