### ISSUE TITLE
menu not opening on android

### ISSUE THREAD

**Issue by janaslani** [FrDH/jQuery.mmenu#488]
Can you kindly take a look at www.pinzoo.com. it works on every device, including ie9, but not on android. it wont open/collapse.

thanks in advance,
Edwin

**Comment by FrDH** [comment]
Sounds odd. I haven't had any complaints about android for a while so my guess is, it's either a specific combination of your options, extensions and add-ons or some of your custom CSS.
You could try to disable all, options, extensions and add-ons and see if that helps. At least then you can start adding them back one by one and see where it stops working.

**Comment by janaslani** [comment]
Thanks for the response, the culprit appears to be 

"offCanvas": {
   "position": "bottom"
},

If I set it to "right", the menu slides properly. This is only true for Android. it's a galaxy sII running Android 4.1.2

Any thoughts?

**Comment by FrDH** [comment]
What happens if you keep the `position: "bottom"` but remove all other options?
