### ISSUE TITLE
mmenu moves ALL divs in body causing div contained iframes to reload

### ISSUE THREAD

**Issue by sirugh** [FrDH/jQuery.mmenu#489]
I'm the maintainer of a Chrome extension that appends a div to the body of a page on document.ready. Inside this div is an iframe with some specific state necessary to the plugin.

It was reported recently that the plugin contents were appearing blank, and after some research I found that it is due to the fact that:

1. You [wrap everything](https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/js/jquery.mmenu.offcanvas.js#L334) in your div when you `mmenu` is called, even divs that don't belong to you.

2. iframes are reloaded when moved via appendChild. This is an implementation of HTML that I doubt is changing any time.

I would ask that this plugin provide for a specific class selector for the elements that need to be wrapped.

**Comment by sirugh** [comment]
[this](https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/js/jquery.mmenu.offcanvas.js#L45) may be the answer. It looks like I could add a selector. This may be an implementation issue then with the end user failing to provide a class selector.

**Comment by jeroentja** [comment]
Hi,

I think we have the same problem on our site. Adsense banners are being reloaded en show very often blanks. What can we do?

**Comment by FrDH** [comment]
As explained in [the tutorial](http://mmenu.frebsite.nl/tutorials/basic/setting-up-the-html.html), it is recommended to wrap all your HTML in one DIV, that way the plugin doesn't need to wrap the DIVs.
You can also specify what node the plugin should consider to be the "page":
````javascript
$("#my-menu").mmenu({
   // options
}, {
    // config
   offCanvas: {
      pageSelector: "#my-page"
   }
});
````

**Comment by jeroentja** [comment]
Hi!
Tnx for the comment. I solved it :) :)

**Comment by sirugh** [comment]
@FrDH I don't think that selector is mentioned in the tutorials. Maybe add it?
