### ISSUE TITLE
any way to detect if menu panel is open / closed?

### ISSUE THREAD

**Issue by xstortionist** [FrDH/jQuery.mmenu#490]
Is there any way to detect if the menu panel is open / closed?

I have an animated hamburger menu icon that animates into an "X" when the panel menu is open and I'm having a hard time removing class on the icon when you click outside of the menu to close it.

Any help / suggestions would greatly be appreciated. This is an awesome menu!

**Comment by FrDH** [comment]
You could use the [API](http://mmenu.frebsite.nl/documentation/api.html) to bind a new function to the `open` and `close` method to keep track of the menu state if you need javascript. But if CSS is all you need for the animation, I'd use `html.mm-opened` in the selector:
````css
#hamburger {
   /* css for the hamburger */
}
html.mm-opened #hamburger {
   /* css for the X */
}
````

**Comment by xstortionist** [comment]
Thank you. I'll give it a go.

**Comment by xstortionist** [comment]
Closing this now. Pure CSS worked as expected. I feel like a certified dumbass now. LOL! Usually the easiest solution is the best and CSS class was. Thanks!
