### ISSUE TITLE
vertical submenu + iconPanels incompatibiilty

### ISSUE THREAD

**Issue by maciekkus** [FrDH/jQuery.mmenu#491]
Hi,

I am using iconPanels = true, and vertical menu on 2nd level panel.
Clicking on vertical submenu removes class mm-iconpanel-xxx from parent panel

**Comment by FrDH** [comment]
Thank you for reporting the issue, I'll have to look into the code to see if it can be fixed.
For now I'd say having vertical submenus is incompatible with the iconpanels addon.

**Comment by FrDH** [comment]
Found it, will be fixed in the next version.

**Comment by FrDH** [comment]
Should be fixed in 5.6
