### ISSUE TITLE
vertical submenu - panels not opening

### ISSUE THREAD

**Issue by maciekkus** [FrDH/jQuery.mmenu#492]
to illustrate this issue I need to introduce such menu:

A  (http://domain/A)
- B (has vertical class) (http://domain/A/B)
- - B1(http://domain/A/B/B1)
- - B2 (http://domain/A/B/B2)
- C (http://domain/A/C)
- D (http://domain/A/D)
E (http://domain/E)

If url is http://domain/B (and B has current item class) then mmenu is not opening panel A (whereas subdomenu of B is opened after manually opening A panel)

if url is http://domain/B/B1 (and B1 has current item class) then mmenu is opening correctly panel A (with B (B1/B2), C, D)

**Comment by FrDH** [comment]
Thank you for reporting the issue, I'll have to look into the code to see why it's not working as expected.

**Comment by FrDH** [comment]
Found the issue, will be fixed in the next version.

**Comment by FrDH** [comment]
Should be fixed in 5.6
