### ISSUE TITLE
Smooth scrolling in mmenu tooltip

### ISSUE THREAD

**Issue by apod42** [FrDH/jQuery.mmenu#494]
Hello,

In a mmenu tooltip (I see you no longer show examples of a mmenu tooltips on the main page) I use anchor links to navigate through the content; for example the link Chapter 3 scrolls the page down to Chapter 3. All works fine.

Is there any way I can make the jquery Smooth Scrolling code found here

https://css-tricks.com/snippets/jquery/smooth-scrolling/ 

work with a mmenu tooltip? No luck so far. I understand that the tooltip does not act as a regular html page, but maybe there is still a chance. Thank you :)

**Comment by FrDH** [comment]
I'm not sure I understand the issue. 

Do you need that script to scroll to a section on the page OR open up a tooltip using mmenu?
If so, I'd suggest only firing the scroll animation if the var `target` isn't a mmenu (e.g. does not has the class "mm-menu").

Hope this helps.

**Comment by apod42** [comment]
The issue I am trying to fix is that the smooth scroll script does not work inside a mmenu tooltip (i.e. with a mmenu tooltip opened). I have a mmenu tooltip with a lot of content (text, anchor links etc), I was just wondering why the external script does not work when clicking an anchor link in this mmenu tooltip.

I know that an external script is not your problem, I was hoping for a "miracle quick fix" :)

**Comment by FrDH** [comment]
There's not much I can tell you without an online example. Even then this seems a lot like a question you'd be better of asking on a website like stackoverflow.com

I guess you could try and set the `offCanvas.blockUI` option to false. That should prevent the plugin from blocking the user interface while the menu is open.

**Comment by apod42** [comment]
Thank you, I will start expermimenting with this. Will post again here if I find a solution, please close this issue.
