### ISSUE TITLE
Feature request: ltr/rtl support

### ISSUE THREAD

**Issue by maciekkus** [FrDH/jQuery.mmenu#497]
Hi,
Although menu can be displayed on the right side of page, it would be great for full rtl support from mmenu plugin.

**Comment by FrDH** [comment]
Hi,
I'm not much of a RTL expert but I'll have a look at what that would include.

p.s. 
have you tried the (3rd party) extension [leftSubpanels](http://mmenu.frebsite.nl/documentation/extensions/left-subpanels.html)?

**Comment by maciekkus** [comment]
Will try it, thanks.

**Comment by FrDH** [comment]
Try the new [RTL" add-on](http://mmenu.frebsite.nl/documentation/addons/rtl.html)
