### ISSUE TITLE
MMenu treating all sub divs inside the menu as panels and menus with or without the classes

### ISSUE THREAD

**Issue by Sammaye** [FrDH/jQuery.mmenu#499]
I am getting it that I have a menu (drawn up from long ago) which looks like:
```html
<li>
<div class="navitem">whatever</div>
</li>
```
Whereby the nested div is being factored out and treated like a separate menu despite there being nothing to tell it to.

**Comment by FrDH** [comment]
Every direct descendant of an `LI` that matches the `panelNodetype` configuration option is considered to be a "panel" (a `DIV`, `UL` or `OL`).
To change this behavior, you can either override this configuration option or add the class "mm-nopanel" to it (the latter is undocumented I now realize).

````javascript
$.mmenu.configuration.panelNodetype = "ul, ol";
$("#my-menu").mmenu();
````

Hope this helps.

**Comment by Sammaye** [comment]
Indeed thanks

**Comment by Webtransformer** [comment]
I try to exclude one list item with <li class="mm-nopanel">...</li>.
Does it only work on non list items?
Is there another way to ignore parts/markup completly?
