### ISSUE TITLE
Disable scroll in tooltip

### ISSUE THREAD

**Issue by apod42** [FrDH/jQuery.mmenu#502]
Hello,

I open a mmenu tooltip using this:

$(function() {
$("#my_id")
.mmenu({
classes		: "mm-tooltip",
offCanvas	: {
position	: "bottom",
zposition	: "front",
modal		: true
},
header		: {
add			: true,
update		: true,
content		: ["title", "close"],
title		: "My Title"
}
})
});

Is there any way I can compleately disable vertical scroll inside this tooltip? (even if there is a lot of content and vertical scroll in needed).

**Comment by FrDH** [comment]
What version of the plugin are you using? The "header" option has been preceded by the "navbars" addon for quite some time.

**Comment by apod42** [comment]
Hello,

Older version, don't have the number, but from early 2015. I think I should update... Any chance to disable scroll, in this veresion or if necessary a recent one?

**Comment by apod42** [comment]
Needed this (scroll disable) because I was opening an Iframe in the tooltip and as a result I had two vertical scroll bars. Fixed it with css:

.iframe {
width:100%;
height: calc(100% - 50px);
margin-top: 50px;
display:block;
}

50px is the height of the header. Now, the Iframe is the exact height of the tolltip, no longer two vertical scrollbars.
