### ISSUE TITLE
Update API documentation with open/close methods

### ISSUE THREAD

**Issue by wguldin** [FrDH/jQuery.mmenu#503]
Hi there, 

I wasn't sure of the process for updating your demo website, but I think the API documentation needs a little clarification. 

At first I was thinking `closePanel` was the only method to close the entire menu, since it seemed to be the closest API method mentioned on the website to doing that. 

http://mmenu.frebsite.nl/documentation/api.html

Of course, this didn't work, but I did find out about the `open` and `close` methods, which worked perfectly. A simple addition of these might help out others. 

Another tiny API thing I noticed:
You might want to clarify that when using the `clone` option, the api is still tied to the original element. This took some messing with for me to figure out. 

Great plugin all the way around!

**Comment by FrDH** [comment]
From the API documentation:
> If you're looking for methods for an add-on, check the add-ons pages.

But I guess I could add another notice about the off-canvas behavior being an add-on.

The API + `clone` option bug will be resolved in the next version, sorry you had to figure that out by yourself.

**Comment by wguldin** [comment]
Since it's turned on by default, I guess I didn't think of it as an add on. A note might help make that clearer.

Thanks for getting back to me so soon!
