### ISSUE TITLE
How does the radio button work?

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#504]
Hi I am new with JS and your amazing pluging too. I am trying to set items with radio buttons, I expect the following behavior: no more than one item can be "selected" at the same time. However, it doesn't seem to work in that way.  This is the simple html file.
Thanks a lot in advance. Best!

        <script src="js/jquery203.js" type="text/javascript"></script>
    <script src="js/jquery.mmenu.min.all.js" type="text/javascript"></script>
	   <link href="css/jquery.mmenu.all.css" type="text/css" rel="stylesheet" />
	   <script src="js/jquery.mmenu.toggles.min.js" type="text/javascript"></script>
       <link href="css/jquery.mmenu.toggles.css" type="text/css" rel="stylesheet" />
	   <script type="text/javascript">
			$(function() {	
				$('nav#menu').mmenu({
        			onClick: {
            			close: false
        			}
    			});
			});
		</script>
	</head>   
<body>
		<div id="page">
			<div class="header">
				<a href="#menu"></a>				
			</div>
			<div class="content">

			</div>
			<nav id="menu">
				<ul>
					<li><a href="#">Home</a></li>
					<li>         				            				
            				<a href="#Item1">Item1</a>	            				         				
        				 <input type="radio" class="Check" />
      				</li>
      				<li>
            				<a href="#Item1">Item2</a>	            				 
        				 <input type="radio" class="Check" />
      				</li>					
					<li><span>About us</span>
						<ul>
							<li><a href="#about/history">History</a></li>
							<li><a href="#about/team">The team</a>
								<ul>
									<li><a href="#about/team/management">Management</a>										
									</li>
									<li><a href="#about/team/sales">Sales</a></li>
									<li><a href="#about/team/development">Development</a></li>
								</ul>
							</li>
							<li><a href="#about/address">Our address</a></li>
						</ul>
					</li>
					<li class="Spacer"><a href="#contact">Contact</a></li>
				</ul>
			</nav>
		</div>

**Comment by FrDH** [comment]
There is no additional behavior added (or removed from) the radio buttons, it's just the default behavior:
http://www.w3schools.com/html/html_forms.asp

**Comment by rossanag** [comment]
Well, I know how the radio buttons behave, that's why I am asking. I attach an image, it is supposed that Item1 and Item 2 are mutually exclusive due to the radio buttons behavior. But they don't behave as such since both kept checked and I can't reverse it, ie: if I want to uncheck some item, nothing happens.
I don't know if this is the correct syntax.

This is the meaningfull part of the code, since the rest have the proper libraries and style sheets, otherwise this couldn't to be displayed.
Thanks for your response.
    
![check](https://cloud.githubusercontent.com/assets/1948071/12335136/74f63892-badc-11e5-9930-1b33ff04fcb4.png)
<li><a href="/">Home</a></li>
					<li>
         				<span>
            				<a href="/item1/">Item1</a>		
            				<input type="radio" class="Check" />	 
        				 </span>        				 
      				</li>
      				<li>	
         				<span>
            				<a href="/item2/">Item2</a>
            				<input type="radio" class="Check" />            				            				 
        				 </span>        				 
      				</li>
