### ISSUE TITLE
Conflict with Leaflet library

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#505]
Hi, me again. I did a basic menu, as your first examples like to combine it with the Leaflet plugin. For some reason the header bar, the one that uses to has the "Demo" word on it, isn't displayed.
If you look behind the zoom in/out control of the map, appears the white "burger" icon (near the + sign), but the header bar. 
I tryed using the z-index attribute without luck.

    .mm-menu {   
      background: #279650 !important; 
     z-index: 10 !important;
    }

Another try I did

    .header{
         	    background: red !important;
             	z-index: 9999999;	
            }
It only works (changes the bar to red) when Leaflet plugin isn't used. It seems it remains behind the map layer or so.

    
I appreciate any suggestion, thanks so much.

![leaflet](https://cloud.githubusercontent.com/assets/1948071/12315820/3ba373da-ba5e-11e5-95e7-47c4f9a31ae4.png)

**Comment by FrDH** [comment]
> ...combine it with the Leaflet plugin

What is the Leaflet plugin?

**Comment by rossanag** [comment]
Here it is, my bad is rather a famework to work with maps http://leafletjs.com/

**Comment by rossanag** [comment]
It seems it's fixed now, however I open to your suggestion if you think there are better options, that the reason because I don't close the thread yet.
It has to do with the html tags (lack of) styling, neither leaflet library elements nor mmenu elements weren't part of the conflict.

Html code:

       <div id="map"></div>
    <div id="page">                     
        <div class="header">
            <a href="#menu"></a>                
        </div>                      
        <nav id="menu">
            <ul>
                <li><a href="/">Home</a></li>
                <li>
                    <span>                          
                        <a href="/item1/">Item1</a>     
                        <input type="radio" class="Check" />     
                     </span>

                </li>
                <li>    
                    <span>

                        <a href="/item2/">Item2</a>
                        <input type="radio" class="Check" />                            

                     </span>                         
                </li>                   
                <li><span>About us</span>
                    <ul>
                        <li><a href="/about/history">History</a></li>
                        <li><a href="/about/team">The team</a>
                            <ul>
                                <li><a href="/about/team/management">Management</a>                                     
                                </li>
                                <li><a href="/about/team/sales">Sales</a></li>
                                <li><a href="/about/team/development">Development</a></li>
                            </ul>
                        </li>
                        <li><a href="/about/address">Our address</a></li>
                    </ul>
                </li>
                <li><a href="/contact/">Contact</a></li>
            </ul>
        </nav>
    </div> 

I added the following attributes properties value to the .header class:
CSS code

    .header{  
    position: relative;   
    }

In Firefox it's displayed in a different manner than in Chrome is, in the first the menu bar is behind the map control, in Chrome the otherwise.
![ff](https://cloud.githubusercontent.com/assets/1948071/12345438/8c42035a-bb27-11e5-8986-21f7f0514d20.png)
![chrome](https://cloud.githubusercontent.com/assets/1948071/12345443/91c946f8-bb27-11e5-9d30-247d43736f5c.png)

I will move down the map control by tinkering with CSS.

Thanks :)

**Comment by FrDH** [comment]
If adding `position: relative;` fixed the styling issue, I'd stick to it.
As this isn't an issue with the plugin but more a request for help with CSS/webdevelopment, I'm going to close it now.
