### ISSUE TITLE
A possible radio button solution

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#506]
Hi, first of all sorry to open a thread again but since I am totally new in the web development world and with your plugin in particular, I would like to understand things better.
Secondly, I am plenty aware of how radio buttons are expected to behave, however **following the mmenu documentation steps** I couldn't achieve their behavior as I could with the check buttons. 

The radio buttons allow me to "select" more than one menu item, plus I can't "uncheck" them afterwards. The radio buttons should make the item selection mutually exclusive, and it isn't happening (I attached images showing this in the closed issue).

this is the (wrong) way I did it: https://jsfiddle.net/rossig7/3bgL5afa/

I opened in stackoverflow an issue with my problem, someone gently gave me a workaround what it seems according to him to be the way to go and not just a workaround (basically it handles the radio events inside the plugin):
http://stackoverflow.com/questions/34799315/strange-radio-buttons-behavior-with-mmenu/34800314#34800314
Although it works, I thought there was a more automatic-like way to do it. If in fact there is, I appreciate any little example.

I don't know if there's some sort of bug or I totally misunderstood the way to handle it. 
Thanks in advance.

**Comment by FrDH** [comment]
Again, there is no additional behavior added to the radio buttons.
Try making it work without the mmenu plugin first.

SMALL HINT:
Radio buttons require a "name" attribute to be grouped together.

**Comment by rossanag** [comment]
Thanks so much for your patience, done it works.
I left the jsfiddle just another newbie search into the closed items (as I used to do)
https://jsfiddle.net/rossig7/3bgL5afa/
