### ISSUE TITLE
Add new content to menu

### ISSUE THREAD

**Issue by aaronhb** [FrDH/jQuery.mmenu#507]
I am trying to append a second menu to mmenu but the sub menu items are not getting the styles/classes as the first cloned menu.

https://jsfiddle.net/abennington/3vyqyh9j/8/

Any help on how to make it rerun it on the menu after appended to the cloned mmenu?

**Comment by FrDH** [comment]
Try the [dynamic content tutorial](http://mmenu.frebsite.nl/tutorials/dynamic-content.html)
Should be exactly what you need.

**Comment by aaronhb** [comment]
ok so i tried messing with it but it does not seem to clone the menu and append the html of the menuB UL in the cloned mmenu. The menu and menuB are for desktop and i want to clone them for smaller screens. Ugh...thank for any help or more guidance you can give :)

Updated fiddle trying to use the dynamic content and API but does not append the menuB into mmenu.
https://jsfiddle.net/abennington/3vyqyh9j/27/

**Comment by FrDH** [comment]
Updated fiddle now works:
https://jsfiddle.net/3vyqyh9j/31/

p.s. please note that the older version incorrectly binds the API to the original menu, not the cloned menu.
This is fixed in version 5.6.

**Comment by FrDH** [comment]
There now is a [tutorial](http://mmenu.frebsite.nl/tutorials/dynamic-content.html) on dynamically adding content to a menu.
