### ISSUE TITLE
List Item Functionality

### ISSUE THREAD

**Issue by sintakonte** [FrDH/jQuery.mmenu#509]
Hey guys,

as far as i can remember, this plugin had the functionality that a click on the arrow on the right side caused the slide effect and the text on the left side could be a link to a site

i tried to find this functionality in the docs but it seems it disappeared - does anyone know about this ?

**Comment by FrDH** [comment]
There's a section about this on the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html#tt-subopenlinks).
