### ISSUE TITLE
AJAX search field

### ISSUE THREAD

**Issue by canfiax** [FrDH/jQuery.mmenu#510]
The search package really lacks some way of fetching the results through AJAX. The searchfield is a genius idea, but a bit miss-executed as is.

A simple way to dynamically load the result set through a callback function, i.e. AJAX or some other provider.

Thanks for an otherwise awesome plugin!

**Comment by FrDH** [comment]
Apart from its default behavior, the searchfield add-on can also be configured as a fully functional searchform. Like this:
````javascript
$("#menu").mmenu({

    // lets add a fixed searchfield
    navbars: {
        content: ["searchfield"]
    }
}, {
    searchfield: {
        // set the attributes for the FORM tag
        form: {
            name: "my-form",
            action: "/search.php",
            method: "post"
        },

        // add a submit-button
        submit: true
    }
});
````

If you want to do an AJAX call when typing into the searchfield, I'd suggest something like this:
````javascript
$("#menu").mmenu({

    // lets add a fixed searchfield
    navbars: {
        content: ["searchfield"]
    },

    // don't do the search, just add the field
    searchfield: {
        add: true,
        search: false
    }
});

$("#menu").find( ".mm-search input" ).on( "keyup", function() {
    // make your ajax call here and add the results to an empty panel
});
````

I guess something like that would work.

**Comment by canfiax** [comment]
Thanks! How do I add an empty panel?

And can I style the result set? I.e. How it render based on response from server

**Comment by FrDH** [comment]
Sorry for the late response.
Adding an empty panel would be easy:
````html
<nav>
  <ul>
    <!-- your menu -->
  </ul>
  <ul id="search-results">
    <!-- insert ajax result here -->
  </ul>
</nav>
````
JS could look something like this:
````javascript
$("#menu").mmenu({

    // lets add a fixed searchfield
    navbars: {
        content: ["searchfield"]
    },

    // don't do the search, just add the field
    searchfield: {
        add: true,
        search: false
    }
});

var  api = $("#menu").data( "mmenu" );

$("#menu").find( ".mm-search input" ).on( "keyup", function() {
    $.ajax({
        // the call
    }).done(function( data ) {
        $("#search-results").html( data );
        api.openPanel( $("#search-results") );
    });
````

Haven't tested it, but should help explain the process.
Hope this helps.

**Comment by canfiax** [comment]
Thanks @FrDH !! Great solution.

however, calling openPanel bugs badly on our menu, preventing us from implementing your solution. See my latest response to: https://github.com/FrDH/jQuery.mmenu/issues/525
