### ISSUE TITLE
Menu opening lags

### ISSUE THREAD

**Issue by marcovelii** [FrDH/jQuery.mmenu#511]
Hey there, 

ive faced a Problem that affects the opening of the menu.

If u use divs with border-radius:px; in your content,
opening of the menu will be delayed of like 500ms instead of being opened smooth.

Regards

**Comment by marcovelii** [comment]
Btw, on desktop is it smooth, it just affects in mobile.

**Comment by FrDH** [comment]
For some reason, some CSS styles are really difficult for browsers to animate, for example box-shadow and border-radius.
Basically, browsers on mobile devices are not near as fast as a desktop. There's not much I can do about that.

**Comment by marcovelii** [comment]
Hey,

yeah just wanted to let everyone know because it took me almost a week to find this out :/

Regards
