### ISSUE TITLE
Menu icon disappears

### ISSUE THREAD

**Issue by eladnova** [FrDH/jQuery.mmenu#512]
I had a weird issue today I've never experienced before.

I introduced a custom, hosted  Fontastic icon set to my page and the MMenu burger menu disappeared.

Eventually, I solved it by adding icon-list to my new font library.

Obviously, MMenu is using 
<a href="#mmenu" class="burger-link icon-list"></a>

but I thought it was called independently etc?

**Comment by FrDH** [comment]
I'm not sure what you mean with
> Obviously, MMenu is using

Is there something missing there?

Anyway, the hamburger icon is not part of the plugin so I can't do much about that.
