### ISSUE TITLE
NPM package needs to be updated

### ISSUE THREAD

**Issue by sdornan** [FrDH/jQuery.mmenu#514]
This project's package on NPM is still version 5.3.1. Is it possible to make it current?

**Comment by FrDH** [comment]
I honestly have no idea who manages the package on NPM.

**Comment by DavidOliver** [comment]
I think it's @aburkut. (https://www.npmjs.com/~aburkut)

**Comment by aburkut** [comment]
@FrDH Hello! Give me your npm username and email. And i will transfer ownership to you.

**Comment by FrDH** [comment]
I've send you an email.

**Comment by vitorbaptista** [comment]
Any updates on this? @aburkut still is the owner of the NPM package, which is still on 5.3.1.

**Comment by FrDH** [comment]
Finally got around to updating the NPM package. Sorry about the delay.
