### ISSUE TITLE
iOS 8.4 Support

### ISSUE THREAD

**Issue by metaskills** [FrDH/jQuery.mmenu#515]
I noticed that the latest version does not support iOS 8.4 due to CSS transitions/transforms/etc still needing -webkit prefix. iOS 8.4 is still about 6% of our mobile traffic. I have not checked other major stats. That said, was it a conscious decision to remove iOS 8.4?

**Comment by FrDH** [comment]
It is specified the the autoprefixer should support the [last 2 versions](https://github.com/FrDH/jQuery.mmenu/blob/master/gulpfile.js#L37). If you have a better suggestion, I'd be happy to implement it.

**Comment by metaskills** [comment]
Oh... I'm not used to this concept. When I use Sass, I tend to use tools like Broubon.io since they are really good at dropping prefixes/helpers about the same time others do. 

So yea, in this case I am using the source Sass and changing variables. at the top of my Sass render context. So I guess we can close this issue since if someone like me is doing that, they need to take on the autoprefixer responsibilities. In my case, I just went back into a few files and replaced `transform: ...` with `@include transform(...`. Do you think there is more I should be on the lookout for? Other thoughts?

**Comment by FrDH** [comment]
I'll do some debugging to see what browsers I can add in addition to the "last 2 versions".
Thanks for the feedback.
