### ISSUE TITLE
Nested Menu Behavior When Using openPanel or Selected Panel

### ISSUE THREAD

**Issue by metaskills** [FrDH/jQuery.mmenu#516]
When using a nested menu and either opening or setting selected of the nested menu, the animations are not setup right. I don't expect this is a big issue for us, but wanted to report it.

### Expected

![expected](https://cloud.githubusercontent.com/assets/2381/12706985/931e8414-c85b-11e5-89cc-37b80e2bfc70.gif)

### Actual 

![actual](https://cloud.githubusercontent.com/assets/2381/12706986/97733668-c85b-11e5-9cc2-d3b92ad450a2.gif)

**Comment by FrDH** [comment]
Is there an online example of this issue, because I haven't seen it before. The menu on mmenu.frebsite.nl does not seem to have this issue.

**Comment by metaskills** [comment]
There is! Go to this page http://www.customink.com/about/ and make sure browser width is < 700. The open the console and type the following JS to set the Products => Ladies & Juniors panel to selected.

```javascript
panel = $('a[href*="undies/38/styles"]').parents('.mm-panel')
StyleBitz.Menu.setSelectedPanel(panel)
```

You will see the behavior when you open the menu.

**Comment by FrDH** [comment]
Ok I see, what exactly does `StyleBitz.Menu.setSelectedPanel` do?

**Comment by metaskills** [comment]
It just calls the API's `openPanel(panel)`. The idea is that we wanted some JS solution to set the menu's pre-selected state so when a user opens the menu, it shows the level they are at. Works well for the 1st level.

**Comment by FrDH** [comment]
Have you read the [basic tutorial](http://mmenu.frebsite.nl/tutorials/basic/styling-lists.html), it show how you can specify at what panel the menu should be pre-selected. Visiting that page will also demonstrate it works, just open the menu.

Anyway, there currently is no way to resolve your issue. Traversing the menu is not bound to the original nested menu structure, but default usage (where the visitor clicks through the menu) would result in logical traversal.

**Comment by metaskills** [comment]
> Have you read the basic tutorial, it show how you can specify at what panel the menu should be pre-selected.

I have and we do use that feature. However, the interface I built in our style guide did not expose the second level at first. Thinking it would be harder to implement that logic, I wanted to explore the JavaScript interface. 

> there currently is no way to resolve your issue. Traversing the menu is not bound to the original nested menu structure, but default usage (where the visitor clicks through the menu) would result in logical traversal.

Yup, you are right.

**Comment by metaskills** [comment]
> Have you read the basic tutorial, it show how you can specify at what panel the menu should be pre-selected.

I have and we do use that feature. However, the interface I built in our style guide did not expose the second level at first. Thinking it would be harder to implement that logic, I wanted to explore the JavaScript interface. 

> there currently is no way to resolve your issue. Traversing the menu is not bound to the original nested menu structure, but default usage (where the visitor clicks through the menu) would result in logical traversal.

Yup, you are right. However, I just realized we could do this in JavaScript if needed using something like this. Since we know the menu structure, it works quite well!

```javascript
ladiesPanel = $(".mm-title:contains('Ladies & Juniors')").parents('.mm-panel');
productsPanel = $(".mm-title:contains('Products')").parents('.mm-panel');
StyleBitz.Menu.setSelectedPanel(productsPanel);
StyleBitz.Menu.setSelectedPanel(ladiesPanel);
```

Thanks so much for your work and time!
