### ISSUE TITLE
How to get .mm-fullsubopen for my .mm-next item?

### ISSUE THREAD

**Issue by bardtian** [FrDH/jQuery.mmenu#517]
I created my first jQuery.mmenu by following Basic tutorial, all works fine but I found lose .mm-fullsubopen for .mm-next item. And I didn't see options about this.
Do I miss something?

**Comment by FrDH** [comment]
There's a section about this in the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html)

Hope this helps.

**Comment by bardtian** [comment]
Thanks,
after I added this JS to the page:
$( ".mm-next" ).addClass("mm-fullsubopen");
it works now.
