### ISSUE TITLE
Latest download incorrectly calls the min js

### ISSUE THREAD

**Issue by dirtandrust** [FrDH/jQuery.mmenu#519]
Hi, 
So I've noticed this file is called incorrectly so the downloaded demo files don't work. This: `"<script type="text/javascript" src="../dist/js/jquery.mmenu.min.all.js"></script>"` should be this `"<script type="text/javascript" src="../dist/js/jquery.mmenu.all.min.js"></script>"`. I'm also unable to fire add ons or extensions to the demo files and it starts open by default. Please fix.

**Comment by FrDH** [comment]
Hi, thanks for bringing this issue to my attention, I indead changed the naming from ".min.all.js" to ".all.min.js".

I'm not sure what you mean with being unable to fire add-on or extensions, the "advanced" demo uses both and work as expected (after changin the path to the ".all.min.js" file ofcourse).

As of version 5.6 the menu will open by default if its ID is appended to the URL, for example if you link to "your-website.com#menu-id" (and your menu has the ID "menu-id"), the menu will open after being initiated. This way, the menu will open as expected when clicking the hamburger icon before the plugin was fired.

Hope this helps.

**Comment by dirtandrust** [comment]
Yes but the call for the file in the HTML is incorrect as I stated. 

Cheers

Nathaniel Flick
dirtandrust.com
http://nz.linkedin.com/in/nathanielflick
Mobile: 021 065 3240

**Comment by FrDH** [comment]
Has been fixed.

**Comment by dirtandrust** [comment]
Awesome thanks!

Cheers

Nathaniel Flick
dirtandrust.com
http://nz.linkedin.com/in/nathanielflick
Mobile: 021 065 3240

**Comment by dirtandrust** [comment]
While I jane your ear, menu isn't working with fixed position in ie11: mgp.stagephos.co.nz do I need to use the fixed position js fix?

Cheers

Nathaniel Flick
dirtandrust.com
http://nz.linkedin.com/in/nathanielflick
Mobile: 021 065 3240

**Comment by dirtandrust** [comment]
Never mind not using it there. 

Cheers

Nathaniel Flick
dirtandrust.com
http://nz.linkedin.com/in/nathanielflick
Mobile: 021 065 3240
