### ISSUE TITLE
Location of jquery.mmenu.all.css

### ISSUE THREAD

**Issue by Luckyfella73** [FrDH/jQuery.mmenu#520]
Hi,

I just installed jQuery.mmenu with Bower into my project. The docs [http://mmenu.frebsite.nl/tutorials/basic/] ask to load the mmenu base css file like this:

`src/css/jquery.mmenu.all.css`

but there is no such file but "jquery.mmenu.oncanvas.scss". I just want to get sure if it's only the filename that changed or is the file located elsewhere?

edit:
seems I overlooked that I need to set up the files correctly by using gulp..

**Comment by FrDH** [comment]
The distribution files are located in the "dist" folder:
https://github.com/FrDH/jQuery.mmenu/tree/master/dist/css

**Comment by Luckyfella73** [comment]
Thank you!
