### ISSUE TITLE
Keep seeing first li or div while navigating in sub menu or sub panel ?

### ISSUE THREAD

**Issue by pascalf22** [FrDH/jQuery.mmenu#521]
Hello!

Thanks for this wonderful menu !!
I wonder if, while navigating in submenu.. if we can always see the first li or div as header...
because i show users avatar and somes others important link in the first li....

` <nav id="menu-sm-md-lg-membre">
      <ul>
        	 <li>
		      <span>
		               <img of users>
                                <a >....</a>
		       </span>
		   </li>
                   <li>
                          <span>other menu</span>
                          <ul>
                                  <li>....</li>
                          </ul>
                   </li>
              </ul>`

so i would like when user click to show sub menu... that the first li of the main menu is still there... as a header.. so always visible

is it possible ?

Thanks !

Pascal

**Comment by FrDH** [comment]
Have you tried the [navbars add-on](http://mmenu.frebsite.nl/documentation/addons/navbars.html)?
Here's an example how you can add an image: http://mmenu.frebsite.nl/demo/index.html?demo=wp-widescreen

**Comment by pascalf22** [comment]
Hello !!

Thanks so much for the reply. I think that what i need.
I did not find it on your website but i check the source and i have to add the 
<link type="text/css" rel="stylesheet" href="../mmenu/extensions/widescreen/jquery.mmenu.widescreen.css?v=6" media="all and (min-width: 650px)">

and the all.min.js

I'll try it soon and i come back tell you if it works!

Thanks again!
I really appreciate !

Pascal

**Comment by pascalf22** [comment]
Hi Again !!!

I use navbars to create my 2 fixed top menu

> $("#menu-sm-md-lg-membre").mmenu({
	extensions: ["theme-dark"],
			   navbar: {
			    title: ""
			       },
offCanvas : {
	 position : "right", // changing this alters the position of the menu
         zposition : "front"
			       		 		},
	navbars: [{
	 position: "top",
	content: [
		'<img style="margin:auto;height:100%;" class="img-circle" src="/img/Vignettes/<?php echo $_SESSION["mainimg"];?>">'
			       ],
	 height: 2 },{
		 position: "top",
		content: [
                             '4 links ....'
			       ]
			       		          }]
			       	      });



Is that the good way ?

Thanks

**Comment by FrDH** [comment]
That seems to be the correct way yes. For more examples on how you can use the navbars add-on, check out the example after clicking the "more examples" button: http://mmenu.frebsite.nl/documentation/addons/navbars.html

**Comment by pascalf22** [comment]
Thanks a lot  for all your quick response.. I really appreciate !!!
Have a great day !!!
