### ISSUE TITLE
Not working on Latest Firefox

### ISSUE THREAD

**Issue by Mulegoat** [FrDH/jQuery.mmenu#522]
Hi there

For some reason the menu does not open in latest Firefox or IE11. I don't get any console errors so hard to debug

http://80.82.116.216/

The code I'm using in my js file:

`        (function initMainMenu() {

            var $menu = $('#menu-location-primary_navigation');

            //  Toggle menu
            $('#js-main-menu').click(function( e ) {
                $menu.trigger( $menu.hasClass( 'mm-opened' ) ? 'close.mm' : 'open.mm' );
                e.preventDefault();
            });

            //  Create the menu
            $('#menu-location-primary_navigation').mmenu({
              extensions  : [ "effect-slide-menu", "pagedim"],
              counters  : true,
              offCanvas: {
                position: "right",
                zposition: "front"

              },
              onClick: {
                preventDefault: null
              },
              classNames: {
                fixedElements: {
                  fixed: "fixed-header"
                }
              },
              scrollBugFix: {
                fix: true
              },
              navbars   : [
                {
                  position  : 'bottom',
                  content   : [
                       '<a class="fa fa-envelope">Email</a>',
                       '<a class="fa fa-twitter">Twitter</a>',
                       '<a class="fa fa-facebook">Facebook</a>'
                  ]
                }, {
                  position  : 'top',
                  content   : [
                    'prev',
                    'title',
                    'close'
                  ]
                }
              ]
            });

        })();`

Any help would be awesome

**Comment by FrDH** [comment]
First, your JS won't work because the custom events have been replaced with an API some time ago:
````javascript
$('#js-main-menu').click(function( e ) {
    $menu.trigger( $menu.hasClass( 'mm-opened' ) ? 'close.mm' : 'open.mm' );
    e.preventDefault();
});
````
So why does the menu open in Chrome? Because the anchor links to the menu:
````html
<a href="#menu-id">
````
But why does this not work in FireFox? My guess is, putting an `A` in a `BUTTON` is invalid:
http://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

Hope this helps.
The API: http://mmenu.frebsite.nl/documentation/api.html

**Comment by Mulegoat** [comment]
Hi Fred,

Ok, so I've removed the button and the menu now works on FF & IE - thank you. I'm now rewriting the JS to make sure it's configured properly to work with the API. So far I've got this,

`
        (function initMainMenu() {

          $("#menu-location-primary_navigation").mmenu({
             // options
                extensions  : [ "effect-slide-menu", "pagedim"],
                counters  : true,
                offCanvas: {
                position: "right",
                zposition: "front"

              },
              onClick: {
                preventDefault: null
              },
              classNames: {
                fixedElements: {
                  fixed: "fixed-header"
                }
              },
              scrollBugFix: {
                fix: true
              },
              navbars   : [
                {
                  position  : 'bottom',
                  content   : [
                       '<a class="fa fa-envelope">Email</a>',
                       '<a class="fa fa-twitter">Twitter</a>',
                       '<a class="fa fa-facebook">Facebook</a>'
                  ]
                }, {
                  position  : 'top',
                  content   : [
                    'prev',
                    'title',
                    'close'
                  ]
                }
              ]

          });

          var api = $("#menu-location-primary_navigation").data( "mmenu" );
          api.bind( "openPanel", function( $panel ) {
             console.log( "This panel is now opened:" + $panel.attr( "id" ) );
          });
          api.openPanel( $("#mm-1") );

        })();

`

Everything seems to work ok but the bottom navbar does not appear so i'm wondering if I've gone wrong somewhere? Thanks again

**Comment by FrDH** [comment]
Seems OK to me.
Is there an online example?

**Comment by Mulegoat** [comment]
Hi Fred

Not sure why it wasn't loading using the navbar. I just added it within my template. Displays fine. One thing that is causing issues me some issues is the fixed header. Everything works fine but when I am logged in to WordPress and then browsing the site admin menu dropdowns appear under the header - this was not the case before I added the plugin. I've tried playing with z-index and have also tried installing the WP plugin but the issue remains. Would it be possible to send you a PM with login details for you to have a quick look?

**Comment by FrDH** [comment]
The WP admin bar is really nasty, it doesn't play well with fixed elements at all. There's nothing I can do about that. 
Fortunately, no visitor of your site will ever see the WP admin bar so I don't really see why it would be an issue.

**Comment by Mulegoat** [comment]
Hi Fred,

 

No problem, thanks again for the support. The reason I queried this is because I used an older version of the regular plugin on another site which also has a fixed header and does not have the same problem

 

Anyhow, I’ll try and see if I can fix it. Cheers

 

 

Marco Terrinoni - Director
MULARAM  PRODUCTIONS
web design // animation // illustration
uk: +44 7876 652 643
e:  <mailto:marco@mularam.com> marco@mularam.com  
w:  <http://www.mularam.com/> www.mularam.com
