### ISSUE TITLE
Submenu Arrows Covered on iPhone 6S Portrait View

### ISSUE THREAD

**Issue by qnacreative** [FrDH/jQuery.mmenu#523]
I've noticed this issue since testing on an iPhone 6S and only in portrait view the the submenu arrows are being covered and cannot be clicked. I've attached a screenshot below to demonstrate the issue but you can also check it out at http://thestonecoldfox.com

When testing this issue in Chrome using the mobile simulator it works as expected.

![photo feb 10 11 01 50 am](https://cloud.githubusercontent.com/assets/3101568/12958477/cd04ac02-cfe6-11e5-9064-0899a203424c.png)

**Comment by FrDH** [comment]
That's pretty odd.
Could be due to the `float: left;` on the `div#home` and `footer` not being cleared.
On the other hand, there have been some improvements to the plugin since version 4.1.6 so I'd try upgrading to a newer version first.

**Comment by qnacreative** [comment]
I'll check that out. Thanks for your time!
