### ISSUE TITLE
Click on navbars' links not working

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#524]
Hi, I am not very experienced in web development (js, jquery) I am facing some problems. I want to have a navbar with options to open links, send mail and open facebook.  When I click on the icons, nothing happens. It doesn't work as I expected. The rest of the menu's features are working correctly (sliding menu, open a submenu, etc).
Thanks in advance. 

This is the code:

    function() {
                menu =  $('nav#menu').mmenu(

                {   
                    navbars     : [{
                        position: "top",    
                        height  : 1,
                        content : [ 

                            '<img src="imagenes/wheel32.png" /><p class="navbartxt">bikemvd</p>',               

                        ]
                    },
                    {
                        position: "bottom",
                        content: [                              
                            '<a href="mailto:xyz80@gmail.com" class="fa fa-envelope"></a>',

                            '<a href="https://www.facebook.com/" target="_blank"class="fa fa-facebook"></a>'
                        ]
                    }
                    ],                  
                    extensions: ["multiline"],  
                     onClick: {
                        close: false
                     },
                    navbar:{
                        title: "Inicio"                     
                    },
                    offCanvas: {
                      zposition : "next"
                    }

            });                     

        });

**Comment by FrDH** [comment]
I tried reproducing the issue but both a "mailto" and a "http" link worked as expected. My guess is, there's some other script messinh with the links.
Without an online example, there's not much I can do.

**Comment by rossanag** [comment]
Thanks! I'm going to build the app script by script to see what happens.
I close the thread, and I will post again if I figured out how to fix it.
Best!.

**Comment by rossanag** [comment]
It was easier as I expected. The error was to the incorrect path to the script that contains the code that is above.
