### ISSUE TITLE
Menu cutout on open

### ISSUE THREAD

**Issue by canfiax** [FrDH/jQuery.mmenu#525]
In some situations, when you open the menu, it looks like this (stuck):

![image](https://cloud.githubusercontent.com/assets/3786627/12976061/88b70780-d0c1-11e5-87fe-c0a32c42125e.png)

I don't know if it is related to "open" being triggered multiple times, but it does occur. Not always though.

**Comment by ITZAP** [comment]
I have experienced this also with extension "**effect-panels-zoom**" activated, especially when using the Microsoft EDGE browser.
Resolved by removing "effect-panels-zoom"

**Comment by FrDH** [comment]
Have you tried using the debugger? It should log know incompatteble options/extensions/addons to the console.
Without an online example there's not much I can do.

**Comment by ITZAP** [comment]
I don't think there is any compatibility issue Fred. What I found was a CSS rendering glitch **specific to the Microsoft EDGE** browser on large Desktop screens in HD resolution with this combination of extensions running:

extensions: ["theme-light", "multiline", "border-full", "effect-menu-zoom", "**effect-panels-zoom**", "widescreen", "pageshadow", "panelshadow"],

MMENU renders fine and dandy in Firefox, Chrome, Safari iPad and iPhone mobile browsers.
Just Microsoft EDGE alone would initially shrink MMENU to half defined width inside the **div.mm-menu** outer container.

**canfiax** doesn't mention what extensions he had active or what browsers he tested in.

For me, removing that one "**effect-panels-zoom**" extension resolved the Microsoft EDGE rendering issue.  All good.

**Comment by canfiax** [comment]
I will provide more details but I was testing on OSX Chrome latest version on a MBP 15"

**Comment by canfiax** [comment]
Hi there.

This is how I init my menu:

	extensions : [ 'theme-white', 'effect-slide-menu' ],
	offCanvas: {
		position  : "right",
		zposition : (document.documentElement.clientWidth < 768) ? 'back' : 'front'
	},

I don't use the effect-panels-zoom. I have tried removing "effect-slide-menu" as well, but menus still slide, and issue still persists.

It's very strange. It seems as though, if I open the menu and call `api.openPanel` from the console it works.

But if I run a callback against the searchfield, to open the menu when input changes, then it bugs very badly. See this piece of code:

				$('#my-menu').find( ".mm-search input" ).on( "keyup", function() {
					menu.openPanel($('menu-page-search-results'));
					console.log('calling openPanel, because input changed');
					$.ajax({
						url: '/api/page/search',
						method: 'POST',
						data: {
							name: $(this).val()
						}
					}).done(function( data ) {
						console.log(data);
					});
				});

Video: https://youtu.be/6nd0QzpWRQc.

@FrDH can you help?

**Comment by FrDH** [comment]
I don't think this has anything to do with the issue described here.
You could try using the `searchfield.resultsPanel` option, that way opening and closing the panel is already done and all you'd need to do is populate it with results.

Besides that, populating a panel with the results from an AJAX request is outside the scope for the searchfield so I can't really help you out there.

**Comment by canfiax** [comment]
I think you misunderstand @FrDH - the issue is with the menus being cut out, when you call the menu.openPanel, for some strange reason.

**Comment by FrDH** [comment]
Could you provide an online example I could debug?

**Comment by canfiax** [comment]
I haven't seen this bug for a long time now after updating using bower. guess it was fixed :)
