### ISSUE TITLE
Menu opens/closes without animation.

### ISSUE THREAD

**Issue by altinselimi** [FrDH/jQuery.mmenu#526]
Here's a live demo  https://jsfiddle.net/altinselimi/uyty3we6/1/

**Comment by katsar0v** [comment]
Here is the solution: https://jsfiddle.net/uyty3we6/2/

**Comment by FrDH** [comment]
Basically, your <BODY> needs a background color for the "page" to inherit.

**Comment by katsar0v** [comment]
This is missing in the docu, would be good if it was there, I guess
