### ISSUE TITLE
Menu load event

### ISSUE THREAD

**Issue by katsar0v** [FrDH/jQuery.mmenu#527]
Hello, as the menu is collapsing with a lot of other scripts I use (because of playing with the DOM tree), I would like to ask if there is a load() event of the menu, from where I can trigger other methods? If not, I think this should be considered rather an issue, than a feature request. Thank you in advance.

Edit: $.when().done() is a temporary solution for this.

**Comment by FrDH** [comment]
I dont think I understand the question, if you want to run some script after the menu is created, just run it after running the plugin:

````javascript
$("#my-menu").mmenu();
// other scripts here.
````

**Comment by katsar0v** [comment]
Unfortunately your plugin causes DFP ads not to load sometimes. Putting it in $.Deferred fixed, but you need a proper loaded event when your function stops playing with the DOM tree.
