### ISSUE TITLE
Heading moves over and down when mmenu opens..

### ISSUE THREAD

**Issue by djlerman** [FrDH/jQuery.mmenu#528]
Hello.

I have an issue where the heading moves down and over when mmenu opens.

I would like the heading to stay in place and mmenu to open underneath it.

Here is an example: https://www.iqaat.com/bs/

Closed:
![mmenu1](https://cloud.githubusercontent.com/assets/3476509/13370951/e9d22230-dccd-11e5-901b-ff91a5afb070.png)

Open:
![mmenu](https://cloud.githubusercontent.com/assets/3476509/13370940/b4b5ea1e-dccd-11e5-89ef-256fa603b0cc.png)

Any suggestions would be greatly appreciated.

Thank You,
~Donavon

**Comment by FrDH** [comment]
The fixedelements addon is included in the .all.js file, you do not need to include it separately.
From [the documentation](http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html):
> If your page contains elements with position: fixed; that suddenly disappear when opening the menu, first include the "fixedElements" add-on .js file.

> Next, add the class Fixed to the fixed elements.

Does that help?
