### ISSUE TITLE
id from <nav> deletes the complete link in the addressbar - just the domain stays

### ISSUE THREAD

**Issue by dstN** [FrDH/jQuery.mmenu#529]
hi.

i have this menu running on my site:

`var API = $("#mainnavigation").mmenu({
            extensions: ["effect-menu-slide", "effect-listitems-slide", "multiline", "border-full"],
            scrollBugFix: true,
            screenReader: true,
            backButton: {
                close: true
            },
            offCanvas: {
                zposition: "next",
                position: "left",
                moveBackground: true
            },
            setSelected: {
                current: true,
                parent: true
            }
        }
        )
        .data( "mmenu" );
    $("#canvastoggle").on("click", function(e) {
        e.preventDefault();
        if ($("html").hasClass('mm-opened')) {
            API.close();
        }
        else {
            API.open();
        }
    });`

and it works fine. the only error i get, if i'm on a subpage like example.org/test/test/test.html and click on the #canvastoggle (href="#") then the complete link gets deleted and it says example.org/#mainnavigation in the addressbar. i tried to figure out on the example-page how it is done there, but there is actually no difference. so, why is my addressbar doing this? on your demopage it doesn't happen for me.

**Comment by FrDH** [comment]
Sounds like there's an error in your JS preventing the plugin from doing what it should do. Are you getting any erros in the console?

**Comment by dstN** [comment]
nope, i don't get any errors in the console. and mmenu is the first thing which get initialized in my init.js-file. and the menu works - actually. just the addressbar shows the false link if i click on the burger.

**Comment by FrDH** [comment]
The plugin seems to be working fine in the documentation website (and its examples), so I don't think there is much I can do for you without an online example of the issue.

**Comment by dstN** [comment]
can i send you an online-example via PM?

**Comment by dstN** [comment]
i've found the problem. the "backButton: close: true"-feature does this.
