### ISSUE TITLE
Mmenu click delay

### ISSUE THREAD

**Issue by nishantambab** [FrDH/jQuery.mmenu#530]
Hi,

We are facing delay after click on menu option on mmenu plugin i.e. is is taking sme delay to display menu. You can check it on our site http://www.thelabellife.com/, please open it in mobile browser.
What can we do to resolve this issue?

Regards.
Nishant

**Comment by FrDH** [comment]
Mobile browsers need a 300ms delay after a "touchend" to be sure you're not doing another gesture like a double tab. There's not much I can do about that.
There is [fastclick](https://github.com/ftlabs/fastclick), but that introduces new issues more difficult issues.

**Comment by FrDH** [comment]
I've put a "fastclick-like-addon" on the TODO list.
