### ISSUE TITLE
Need to destroy the menu

### ISSUE THREAD

**Issue by ArthurianX** [FrDH/jQuery.mmenu#533]
I saw there was an issue here https://github.com/FrDH/jQuery.mmenu/issues/28 about this, and @FrDH, your response doesn't answer the user's question.

I'm running a ruby app and the same thing happens, page change isn't really a page reload, more something like a ruby driven ajax/$http call that changes content, and breaks the layout mmenu is making, I'm reinitializing the menu on each change, but after a few page changes the menus fire erroneously (I have two menus, I click the right one and the left one opens).

**Comment by ArthurianX** [comment]
I fixed my problem with updating the menu on 'page change', but I still think we need to be able to destroy the menu.

I'll try to take a look at it in the weekend and I'll make a pull request if I come up with something.

**Comment by FrDH** [comment]
Have a look at the [jQuery mobile framework wrapper](https://github.com/FrDH/jQuery.mmenu/blob/master/src/wrappers/jquerymobile/jquery.mmenu.jquerymobile.js), it adresses the issues with jQuery mobile.
