### ISSUE TITLE
navbar title empty no matter the setting

### ISSUE THREAD

**Issue by viktoras** [FrDH/jQuery.mmenu#535]
I used the latest version in a project and I noticed that the usual "Menu" doesn't appear although navbar is supposed to be true by default. Now I call the script as:
```
 $("#mobile-menu").mmenu({
        slidingSubmenus: false,
	    navbar: {
	        title: "Menu"
	    },
	    navbars: [{
	        position: "top",
	        content: ["title"]
	    }],
		onClick : {
			preventDefault: true
		}
     });
```
   
This adds a navbar but the <a> tag is empty. Tried with mmenu.all.js, tried with loading navbars on it's own. Same deal. Any other keyword appears just fine - title sets an empty a tag.

**Comment by FrDH** [comment]
I think this is because "vertical" panels (all panels when you use `slidingSubmenus: false`) do not have a navbar. I'll see if I can do something about that.
For now, I guess it's either slidingSubmenus or no title.

**Comment by viktoras** [comment]
Oh. So far I had only been using it with sliding panels - but it looks interesting with vertical submenus. I guess I can go back to sliding, no big deal for me.

**Comment by FrDH** [comment]
I've put this issue on the TODO list to be reviewed. Thank you for bringing it to my attention.
