### ISSUE TITLE
I can't understand the example with toggle

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#536]
Hi :) a subject very explanatory I guess. Here is the link
http://mmenu.frebsite.nl/documentation/addons/toggles.html

What's the difference? I don't realize how you work with checkboxes.
This is my code to check if a checkbox was checked:

//bicisenda is the input id.
`<input id="bicisenda" type="checkbox" name="poi" value="Bicisenda" class="Toggle">`

    $('ul li ul li #bicisenda').click(function() {
      var _checked = $("#bicisenda").is(":checked"); 
      if (_checked) {
        console.log("Checked");    
      }

` });`

Thanks so much

**Comment by FrDH** [comment]
With the toggles add-on, the input is hidden. Instead what you see is a label that's linked to the input. 
In other words, you don't `click` the input.
Try changing the `click` function to `change`, that should do the trick I think:
````javascript
$('ul li ul li #bicisenda').change(function() {
  var _checked = $("#bicisenda").is(":checked"); 
  if (_checked) {
    console.log("Checked");    
  }
});
````

**Comment by rossanag** [comment]
Thanks for your response, but it didn't work either. So, my question it would be how to check if checkbox is checked?

**Comment by rossanag** [comment]
Well after digging deeper with the plugin code, I finally get it working.

The solution was the following:
**HTML**
`<input id="bicisenda" type="checkbox" name="bic" value="Bicisenda" class="Toggle">`
