### ISSUE TITLE
would it work with mega main menu wordpress plugin

### ISSUE THREAD

**Issue by renathy** [FrDH/jQuery.mmenu#537]
I have a question about Wordpress plugin.
I have two level menu. First level is defined inside Wordpress Menu-s. 
However, second level menu is created using 'mega main menu' plugin.
It allows to define "submenus" for second level choosing 'Submenu Type = Widget area".

For instance, I have menu item "Video" with SbumenuType = Widget area 1.
Then I have widget that shows list with "Custom taxonomy - video categories". I put this widget into Widget area 1 and mega main menu plugin displays it as dropdown. 
As example - http://themeforest.net/item/video-magazine-wordpress-magazine-theme/full_screen_preview/7993898 - here menus are using mega menu (but I have more simple menus, without images). 

Now I need mobile menu. Before buying plugin, I wonder if your plugin for wordpress would work?

**Comment by FrDH** [comment]
Hi, I think most of it should work but can't guarantee all of it will.
Basically, the mmenu plugin expects an A,  SPAN, DIV, UL or OL directly inside a LI, where the A and SPAN are assumed to be the "text" and the DIV, UL and OL to be a submenu.

Quote from the download section:
> Before purchasing a license, please make sure the mmenu WordPress plugin is suitable for your project. You can do this by downloading the free version and purchasing a license later on.

This goes for both the jQuery and the WordPress plugin :)

FYI, It's on the TODO list to make the mmenu WordPress plugin compattible with other menu plugins (like Mega Main Menu).

**Comment by dmbostan** [comment]
Hi! Any progress with this issue ?
