### ISSUE TITLE
mmenu contents are display at start

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [FrDH/jQuery.mmenu#538]
hi,
i use mmenu for mobile versions

it works perfectly after website open completely

but at startup of website loading mmenu content display at screen and then after js running it hides.

it looks so bad at startup

**Comment by FrDH** [comment]
There's a section about preventing FOUC on the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html).
Basically, you need to hide the menu untill the plugin is fired:
````css
#my-menu:not(.mm-menu) {
   display: none;
}
````
