### ISSUE TITLE
API not loaded

### ISSUE THREAD

**Issue by Locutus4884** [FrDH/jQuery.mmenu#539]
I am trying to use the API bind function to handle the opened and closed events (to fire some custom Javascript), but I don't seem to get it right. Firefox is giving me the following error:

TypeError: api is undefined

As a test I am using the code from the website, with selector changes to my situation:

```
$(document).ready(function() {
	$("#nav").mmenu({
	      	"offCanvas": {
			"position": "right"
		}
	},{
			clone : true
	});
			
	var api = $("#nav").data( "mmenu" );
	api.bind( "openPanel", function( $panel ) {
		console.log( "This panel is now opened:" + $panel.attr( "id" ) );
	});
});
```

**Comment by ChezFre** [comment]
Did you figure out what was happening? Because I've run into the same issue.

**Comment by Locutus4884** [comment]
Hi,

I think I was using an older version which didn’t support the function.

Met vriendelijke groet,

Robbert Gorter

[cid:image001.png@01D1A782.962E9F80]<http://www.joepiedepoepie.nl/>[cid:image002.png@01D1A782.962E9F80]
-----------------------------------------------------------------------------
La Carte Internet B.V. / JoepieDePoepie / Babysite.nl
Cobaltstraat 36                 2718 RN Zoetermeer
Postbus 73                         2700 AB Zoetermeer
Tel:                                        +31(0)79 - 361 34 65<tel:%2B31%280%2979%20-%20361%2034%2065>
Fax:                                       +31(0)79 - 361 72 65<tel:%2B31%280%2979%20-%20361%2072%2065>
E-mail:                                 info@lacarte.nl<mailto:info@lacarte.nl>
WWW:                                 http://www.geboortekaartjes.nl<http://www.geboortekaartjes.nl/>
                                               http://www.trouwkaarten.nl<http://www.trouwkaarten.nl/>
                                               http://www.kerstkaarten.nl<http://www.kerstkaarten.nl/>
                                               http://www.joepiedepoepie.nl<http://www.joepiedepoepie.nl/>
                                               http://www.babysite.nl<http://www.babysite.nl/>

-----------------------------------------------------------------------------
 Deze e-mail, inclusief eventuele bijlage(n), is uitsluitend bestemd voor gebruik door de geadresseerde(n). Indien u dit bericht abusievelijk heeft ontvangen, mag de informatie daarvan niet worden gebruikt of openbaar gemaakt, noch aan derden worden verstrekt. Wij verzoeken u om in dat geval direct contact op te nemen met de afzender en de e-mail te vernietigen.

Van: Chez Fre [mailto:notifications@github.com]
Verzonden: vrijdag 6 mei 2016 09:33
Aan: FrDH/jQuery.mmenu <jQuery.mmenu@noreply.github.com>
CC: La Carte Internet - Robbert <robbert@lacarte.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [FrDH/jQuery.mmenu] API not loaded (#539)


Did you figure out what was happening? Because I've run into the same issue.
