### ISSUE TITLE
stutter with dual instances

### ISSUE THREAD

**Issue by smockensturm** [FrDH/jQuery.mmenu#540]
See here:

http://shot.madmadmad.net/mmenu/

Any way to get rid of that little mmenu stutter when switching from left to right? Thank you.

**Comment by FrDH** [comment]
Honestly I don't that'll work all too well. The first menu should be closed before opening a second one.
I guess you could get it to work using the "closed" callback method in the API. Somewhat similar to how [this example](http://mmenu.frebsite.nl/demo/index.html?demo=menu-behavior-4) starts scrolling after the menu closed.

Hope this helps.
