### ISSUE TITLE
rtl problem

### ISSUE THREAD

**Issue by MohandesaliRahnema** [FrDH/jQuery.mmenu#543]
hello
when i set the body direction to rtl 
mmenu design will be destroyed
in rtl language text are right and the counter number or direction to open the list must be to left
thank you

**Comment by FrDH** [comment]
Thank you for pointing this out.
Having a solid solution that works throughout the entire plugin for RTL support is on the TODO list. For now I'd recommend setting the `offCanvas.position` option to `"right"`.

**Comment by MohandesaliRahnema** [comment]
thank you i do it manually by changing your code

**Comment by FrDH** [comment]
Just FYI, there's a "RTL" add-on coming in the next version.
