### ISSUE TITLE
Download link on http://mmenu.frebsite.nl/download.html not working on Safari or Firefox

### ISSUE THREAD

**Issue by tanc** [FrDH/jQuery.mmenu#544]
For some reason the download link on http://mmenu.frebsite.nl/download.html does not work in Safari or Firefox. It just reloads the page. It does work in Chrome however.

**Comment by FrDH** [comment]
The download appears to be interrupted. I'll see if I can fix that, for now you could just download the files directly from GitHub.
Thanks for pointing this issue out to me.
