### ISSUE TITLE
jquery mmenu close button undefined

### ISSUE THREAD

**Issue by StefanKern** [FrDH/jQuery.mmenu#547]
issue described here: http://stackoverflow.com/questions/31684201/jquery-mmenu-close-button-undefined-in-chrome

(Sry, I can't create a js bin for it..)

**Comment by FrDH** [comment]
I guess you've stumbled upon an "undocumented feature" :)
Try setting an ID on the "page" DIV, that should do the trick.
````html
<div id="page">
    ... all other HTML
</div>
````

**Comment by FrDH** [comment]
What version of the plugin are you using? I had a closer look at the code and it should have been fixed I think.
