### ISSUE TITLE
navbar clickable title change to "back"

### ISSUE THREAD

**Issue by kingmauri** [FrDH/jQuery.mmenu#548]
hello
what is the easiest way to change the clickable(!) title to a custom text like "back" instead of the automatic updating current level?

when i try this code, the title change to "back" but it's not clickable anymore and level1 is also "back" which is wrong because it's level  and not "Menu". i had a very hacky solutions with some jquery cloning stuff...but i'm sure there is a easier way. thx!

			$("#mainnav-mobile").mmenu({
				"navbars": [
			          {
			             "position": "top",
			             "content": [
			                "prev",
			                "<span>back</span>",
			                "close"
			             ]
			          }
				],
				"extensions": [
	                  "effect-listitems-fade",
	                  "multiline",
	                  "fullscreen"
               ],
				navbar:{
               		add: true,
                    title: "Menu",
               		titleLink: "parent"
                }
			});

**Comment by FrDH** [comment]
Hi,

Unfortunately, there's no build-in way to do that.
But I guess you could bind a new function to the "init" method using the [API](http://mmenu.frebsite.nl/documentation/api.html).

Something like this should work I think:
````js
var $menu = $("#my-menu");

$menu.mmenu({
   // options
});

var $main = $("#my-menu").find( ".mm-panel" ).first();

var API = $menu.data( "mmenu" );
API.bind( 'init', function( $panels ) {
    $panels.each(function() {
        if ($(this)[ 0 ] !== main[ 0 ] ) {
            $(this).find( ".mm-title" ).text( "Back" );
        } 
    });
} );
````

**Comment by kingmauri** [comment]
thx a lot!

for those who needs this: don't forget to add this line:

api.init( $menu.find( ".mm-panel" ) );

**Comment by kingmauri** [comment]
hey ...again me sorry :)
works perfectly! just the current title is still the current panel title. is there a easy way to fix that?
