### ISSUE TITLE
Two menus on one page - conflict in widescreen

### ISSUE THREAD

**Issue by tmetzger** [FrDH/jQuery.mmenu#549]
Hello,

I've got two mmenus in one application, a main navigation and a "user menu" (surely a fairly typical arrangement). They almost play nicely with each other, but in widescreen mode, when you select the user menu and then move off it to close it, the other menu also starts to close. I guess because it's looking at the transient "mm-closing" class on the html tag.

Any clever way to prevent the user menu from affecting the side navigation in this way?

T

**Comment by FrDH** [comment]
Hi,

I'm not sure I exactly understand the setup/issue, is there an online example?
Basically, the widescreen-extension should always keep the menu it applies to opened.

**Comment by tmetzger** [comment]
Yes, you can take a look here:

http://shar.dev.groupanizer.com/

You can log in as:
username: fred
password: fred

Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
Direct +1 604.451-7447

Groupanizer: +1 604.451.7464
North America Toll Free: 866.436.6565 x101

**Comment by FrDH** [comment]
Ok I see what's going on there: The "effect-menu-slide" extension conflicts with the "widescreen" extension when closing a second menu... 
If you remove the "effect-menu-slide" extension from the menu, you should be OK.

I'll see if I can fix this issue in the next version.
Thanks for reporting it.

**Comment by tmetzger** [comment]
I can confirm this fix - removing effect-menu-slide worked. Thanks!

Tom

Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
Direct +1 604.451-7447

Groupanizer: +1 604.451.7464
North America Toll Free: 866.436.6565 x101
