### ISSUE TITLE
Best way to temporarily disable widescreen

### ISSUE THREAD

**Issue by tmetzger** [FrDH/jQuery.mmenu#550]
I love the widescreen extension - really helpful. However, sometimes my users have legitimately wide content and screen width is a huge asset. So I'd like to let them click on the hamburger button to move the menu off the screen temporarily.

I've got a bit of javascript that accomplishes the task (below), but I feel like it's a hack. Is there a nicer way to accomplish this?

````javascript
$('#hamburger')
        .on( 'click',
          function( e )
          {
            e.preventDefault();

            if( $wndw.width() >= 1200 ) {
              if( $gmenu.hasClass( 'mm-widescreen' ) ) {
                $gmenu.removeClass( 'mm-widescreen' );
                $('#page').removeClass( 'mm-slideout' );
              } else {
                $gmenu.addClass( 'mm-widescreen' );
                $('#page').addClass( 'mm-slideout' );
              }
            } else {
              if ( $html.hasClass( 'mm-opened' ) )
              {
                API.close();
              }
              else
              {
                $gmenu.addClass( 'mm-widescreen' );
                $('#page').addClass( 'mm-slideout' );
                API.open();
              }
            }
          }
        );
````

(Sorry I can't figure out how to make the code tags recognize the whole snippet there...)

**Comment by FrDH** [comment]
Personally, I'd add a second hamburger-icon so you can use CSS to show or hide the one you need depending on the screen-width.
Second, I guess the easiest way to en-/disable the widescreen CSS, would be to change the href on the `<link />`.

Put together you'd get something like this:
````html
<a id="hamburger-1" href="#my-menu"></a>
<a id="hamburger-2" href="#"></a>
````
````css
@media (max-width: 1200px) {
   #hamburger-1 { display: block; }
   #hamburger-2 { display: none; }
}
@media (min-width: 1201px) {
   #hamburger-1 { display: none; }
   #hamburger-2 { display: block; }
}
````
````js
// since the href for #hamburger-1 links to the menu, it'll open the menu by default

// store href for widescreen
var $link = $('link[href*="jquery.widescreen.css"]');
var href = $link.attr( "href" );

$("#hamburger-2").click(function() {
   if ( $link.attr( "href" ) ) {
      $link.removeAttr( "href" );
   } else {
      $link.attr( "href", href );
   }
});
````

I do like the idea of being able to close a widescreen-menu, I'll see if I can make some additions to the extensions to get this to work by default.

**Comment by tmetzger** [comment]
Hi Fred,

We wound up putting the hamburger into a "tab" that appears to be attached
to the side menu, so it would be visible when the menu was closed. Clicking
on it when the menu is open in widescreen closes the menu, but the
hamburger remains visible.

We have some custom CSS attached to the mm-widescreen class, so removing
the HREF isn't enough in our case. I've got a solution (above) that is
working well.

Cheers,
Tom


Tom Metzger, CEO
www.groupanizer.com
Facebook <http://www.facebook.com/groupanizer> | Twitter
<http://www.twitter.com/groupanizer>
Direct +1 604.451-7447

Groupanizer: +1 604.451.7464
North America Toll Free: 866.436.6565 x101

**Comment by FrDH** [comment]
After doing some more research I could not find an absolute (and unobstrctive) solution for this request. Here's what I came up with that should work pretty well I think:
````css
.mm-slideout {
   transition: width, margin;
}
html.mm-widescreen-closed .mm-slideout {
   width: 100% !important;
   margin: 0 !important;
}
````
Now all you'd need to do, is toggle the class "mm-widescreen-closed" on the HTML with some custom JS:
````js
$("#hamburger-2").click(function() {
   $("html").toggleClass( "mm-widescreen-closed" );
});
````
