### ISSUE TITLE
Adding logo to the Header

### ISSUE THREAD

**Issue by XplodeF** [FrDH/jQuery.mmenu#554]
Hey thanks for Development this plugin.

I need help to add a logo on the header .

https://github.com/FrDH/jQuery.mmenu/issues/209

I need one tutorial, PLIS. Very thanks.

**Comment by FrDH** [comment]
Here's some sample code:
````js
$("#menu").mmenu({
   navbars: [{
      content: [ "<img src="logo.jpg" />" ],
      height: 4
   }]
});
````
This adds a fixed image above all panels.

**Comment by XplodeF** [comment]
Here is my code:

// Menu Left
		var navMenu=$("nav#menu");
		navMenu.each(function(i) {
			var nav=$(this), data=nav.data();
			nav.mmenu({
				searchfield   :  data.search ? false : true,	
				slidingSubmenus	: true,
				navbars: [{
			      content: [ "<img src='Recursos/img/picture.jpg' />" ],
			      height: 4
			  	}]
			}).on( "closing.mm", function(){
				var highest=$(this).find("ul.mm-highest");
				highest.find(".mm-subclose").trigger('click');
				setTimeout(function () { closeSub() }, 200);
			});
		});

It doesn't work :(

**Comment by XplodeF** [comment]
content: [ "< ixg src="logo.jpg" />" ],

**Comment by FrDH** [comment]
What version are you using?
The "closing" custom event has been deprecated for quite some time.

Older versions might not have the navbars add-on implemented.
