### ISSUE TITLE
Search with hidden input

### ISSUE THREAD

**Issue by aaronhb** [FrDH/jQuery.mmenu#555]
Is there a way to have another input for the search and make it hidden with a value?

So you would have

searchfield: {
            form: {
               name: "my-form",
			   action: "SearchPage.asp",
               method: "post"
            },
            input: {
               name: "Srch_Text"
            },
            input: {
               type: "hidden",
			   name: "MODE", 
			   value: "FINDRESULTS"
            },
            submit: true
         }

**Comment by FrDH** [comment]
No not really, but I guess you could insert it manually after the plugin fired:
````js
$("#menu").mmenu({
   ...
});
$("#menu").find( ".mm-searchfield" ).append( "<input type="hidden" />" );
````

Or, if it's just to pass some variable to the search-script, I guess you could use the "action" attribute:
````js
searchfield: {
    form: {
        name: "my-form",
        action: "SearchPage.asp?key1=val1&key2=val2",
        method: "post"
    }
}
````
