### ISSUE TITLE
mmenue does not ope after update WP 4.5. Error [href=#]

### ISSUE THREAD

**Issue by Togemaxx** [FrDH/jQuery.mmenu#556]
Hi, 
After updating WordPress to 4.5 the plugin App look-alike menus V2.3.1 does not work any more. Further it affectes the complete website, (Revolution slider does not apear and many others) 
the only error i get is). If i deactivate it, every thing else runns just fine. 
the only information i have is: 
Error: Syntax error, unrecognized expression: [href=#]

**Comment by FrDH** [comment]
Try updating the plugin, I uploaded a bugfix version yesterday :)

**Comment by Togemaxx** [comment]
Hi FrDH, 

i updated it. but version is still 2.3.1 and some funktions are better now, but still defect and the mobile navigation is still not working. 

Do you have a work arround for this? 

best Regards.

**Comment by FrDH** [comment]
Version 2.4.1 is the latest, I guess CodeCanyon did not yet approave the update at the time.

**Comment by Togemaxx** [comment]
How can i get the latest version?

**Comment by FrDH** [comment]
Updating from 2.3.1, I'd advice to just override all files. Should not mess up any of the settings.

**Comment by Togemaxx** [comment]
Hi FrDH, 
Current version is 2.4.1. is now online, but it is still not working...

**Comment by FrDH** [comment]
For anyone reading this issue after it was closed:
After updating to the latest version, you'll have to hit the "save" button onces.
