### ISSUE TITLE
When adding two WordPress menus the second one gets hidden

### ISSUE THREAD

**Issue by filip-van-hoeckel** [FrDH/jQuery.mmenu#560]
As per title: if we do wp_nav_menu twice in one <nav> the second one gets hidden. Any idea why, and how to solve? Thanks.

**Comment by FrDH** [comment]
Is this related to the WP or the jQuery plugin?

**Comment by filip-van-hoeckel** [comment]
jQuery. The WP version only supports one menu out of the box. However, I managed to concatenate two menus using wp_nav_menu and wrapped the menu function around that.
