### ISSUE TITLE
Set and then Open subMenu.

### ISSUE THREAD

**Issue by djlerman** [FrDH/jQuery.mmenu#561]
I posted a question on stackoverflow but I have not received any solutions so I thought I would post here.

I am trying to make 2 functions.  1 to set the active mmenu submenu and 1 to open mmenu.

Please let me know if you have any suggested solutions,.

Thank You,
~Donavon

http://stackoverflow.com/questions/36799814/open-jquery-mmenu-to-selected-sub-menu
https://jsfiddle.net/djlerman/3zs1mo3x/

**Comment by FrDH** [comment]
Hi,

The open-function seems to work, but opening a panel should be debugged:

Your HTML `<a href="javascript:setMMenu('Options2');openMMenu();">` passes the string "Options2".
Your function then uses that string to find the panel: `var current = myMenu.find(subMenu).closest("li");`.
This is wrong, `myMenu.find( "Options2" )` will result in 0 elements.

You probably should set an ID on the ULs and use that as a selector for the `find` method: `<a href="javascript:setMMenu('#options-2');openMMenu();">`.

You should also note that opening a panel without opening its parent panel first, will probably result in some illocigal routing (when trying to close it, the parent panel will come flying in from the right).

**Comment by djlerman** [comment]
I updated the jsfiddle: https://jsfiddle.net/djlerman/3zs1mo3x/

I set an id on the <ul> that follows the options I want to set.

The menu opens empty.  Any other things I should look for?

**Comment by theodorosploumis** [comment]
Check also #929.
