### ISSUE TITLE
Slide occurs with a gap white space between the menu and page content

### ISSUE THREAD

**Issue by rossanag** [FrDH/jQuery.mmenu#563]
Hi, I've experienced that in some browsers (Chrome, but not in Chromium) on desktop, and when seeing the site in smartphones in a portrait mode.
Is there a css value I have to modify?
![desktop](https://cloud.githubusercontent.com/assets/1948071/14806201/65129090-0b47-11e6-889c-fefd71825029.png)

bicimapuy.herokuapp.com

Thanks

**Comment by FrDH** [comment]
Hi,

I haven't seen big gaps like that before, could you maybe check if it is due to the large google map in the page?
