### ISSUE TITLE
How to add class in Searchfield input?

### ISSUE THREAD

**Issue by claudchan** [FrDH/jQuery.mmenu#564]
Hi,
Anyone can guide me how to add class in Searchfield input?
Thanks.

**Comment by FrDH** [comment]
You can use the searchfield.input configuration option:
````javascript
$("#menu").mmenu({
   // options
}, {
   // configuration
   searchfield : {
      input: {
         class: "my-custom-classname"
      }
   }
});
````
Alternatively, you could find the input after the menu was created and add the class using jQueries `addClass` method.

**Comment by claudchan** [comment]
It doesn't work on the options and configurations.

**Comment by FrDH** [comment]
That should work. What version of the plugin are you using?
Could you please provide an online example of the issue?

**Comment by claudchan** [comment]
I am using jQuery mmenu v5.6.3

**Comment by claudchan** [comment]
Sorry, I notice my mistake, I was put in the option. Put in configurations works.
Thanks.
