### ISSUE TITLE
Dynamically add product categories to mmenu

### ISSUE THREAD

**Issue by willlawrence** [FrDH/jQuery.mmenu#565]
Hi there,

Is it possible to dynamically pull through the Woocommerce product categories into the mmenu so that i dont have to add them manually each time a new one is created?

Thanks
Will

**Comment by FrDH** [comment]
I'm not sure I understand the issue. What do you mean with "dynamically pull through the product categories"?

Here's a tutorial on how you can dynamically add menu items and panels:
http://mmenu.frebsite.nl/tutorials/dynamic-content.html

**Comment by willlawrence** [comment]
So i want to display all of the product categories within the menu, but without manually adding them each time through the menu area. Is it possible to automatically add the product categories when they are created?

Thanks

**Comment by FrDH** [comment]
I have no idea what you mean with "when product categories are created". How does this involve the jQuery.mmenu plugin?
