### ISSUE TITLE
IE 9 (IE <10) doesn't work

### ISSUE THREAD

**Issue by kbreynck** [FrDH/jQuery.mmenu#566]
Website: http://mmenu.frebsite.nl/ 

IE 9 doesn't display the menu when one tries to open it with the burger"-navigation button.
There is only a semi transparent overlay and the browser scroll bars are dissapearing. But the navigation menu doesn't slide in.
Isn't IE 9 supported?

The console doesn't show any errors.

**Comment by FrDH** [comment]
The Gulp autoprefixer has been set up to support the latest 5 versions of each browser and all browsers that are used more than 5%:
````
return sass( 'src/**/*.scss', { style: 'expanded' })
    .pipe( autoprefixer( [ '> 5%', 'last 5 versions' ] ) )
````
I had a look at the generated CSS and it includes only the -webkit- vendor-prefixe, so I guess IE9 is not included by the autoprefixer.

If you need support for IE9 (not that Microsoft dropped support in January), I guess you could change the settings for the Gulp autoprefixer and run `gulp css` in the commandline.

**Comment by kbreynck** [comment]
Thank you for the fast response.

Configuring the “Autoprefixer“ for IE 9 support, doesn’t change anything. I looked a bit deeper into the CSS source. All animations are done by [CSS3 3D transforms](http://caniuse.com/#search=3d%20transforms).
Unless the library doesn’t provide any fall-back methods or CSS-classes (like 2d transforms) IE <=9 won’t work.

I know, that support for IE <11 has already expired and the usage of IE9 is less than 0.5% but when your client is forced to use it in his company, you don’t have a good chance to get the product approved. :/

I’ll find a workaround for this special case. I still like this project but for a commercial product like this, I miss a modular concept of “Graceful Degradation”. You could make use of 2d transforms if the browser doesn’t support 3d transforms. This is just my opinion.

**Comment by FrDH** [comment]
You're right, I didn't realize the support for 3D transforms is different from 2D transforms.
Allthough most (if not all) transitions are 2D, the 3D transform is needed to force hardware acceleration on the transition. 
If you need an easy fix, just search the css file(s) and add the 2D transform. Shouldn,t be that much work I guess.
