### ISSUE TITLE
Issue with dropdown add on

### ISSUE THREAD

**Issue by Akhoy** [FrDH/jQuery.mmenu#568]
Hi, I'm using the dropdown add-on to open the menu as a dropdown in desktop. When opening it from the right side, I've noticed that the menu appears for a moment on the left side before appearing on the right side. Any ideas on how to fix this? Thanks.

**Comment by FrDH** [comment]
Is there an online example I could have a look at?

Not sure, but I guess this could be due to a delay in the "automatic position detection". If your menu will always open on the right side of the page, you can configure it to do so (and so remove the delay):
````js
$("#menu").mmenu({
   dropdown: {
      drop: true,
      position: {
         of: "#my-button",
         x: "left",      // or "right"
         y: "bottom"    // or "top"
      },
      tip: true
   }
});
````

**Comment by Akhoy** [comment]
Thanks for the response. The delay seems to have reduced but is still there sometimes. I tried to replicate in codepen but was unsuccessful. Please check what is wrong here. https://codepen.io/anon/pen/mPvKmo

**Comment by FrDH** [comment]
Odd issue, I tried to but could not reproduce it in my test environment.
The menu should have `display: none;` until it is positioned correctly, but some how this does not seem to work in your case.

**Comment by smth** [comment]
I have the same problem. Have you come across this since @FrDH ? Did you find a solution @Akhoy

**Comment by smth** [comment]
I think the reason you cannot replicate this @FrDH may have something to do with whether or not elements are wrapped in `mm-page`. It looks like in the CodePen example above, this isn't being applied. In my case, the site header is outside of `mm-page` (not intentionally), and the glitch is only visible over that area of the page.
