### ISSUE TITLE
Creating top level links that just slide to submenu

### ISSUE THREAD

**Issue by tmetzger** [FrDH/jQuery.mmenu#569]
Hi folks,

I've been scouring the docs and issues but haven't been able to figure out how to do this. I want my top level item not to be a link. Clicking on it would slide open its submenu which is full of real links.

Behavior actually the exact same as http://mmenu.frebsite.nl/ for Tutorials and Documentation.

Thanks for any tips!

T

**Comment by tmetzger** [comment]
Bah - after all that I found it on the tips and tricks page:
http://mmenu.frebsite.nl/support/tips-and-tricks.html

Excerpt:

"If you replace the A with a SPAN, the entire menu item becomes clickable."

**Comment by FrDH** [comment]
:)
