### ISSUE TITLE
menu not working

### ISSUE THREAD

**Issue by mrabor** [FrDH/jQuery.mmenu#574]
can anyone please help me ....i just purchased a license but my menu isnt working....this is how it looks on the site that im working on...
![menu](https://cloud.githubusercontent.com/assets/19478177/15437666/fec24b56-1efa-11e6-97aa-e0d0f04ce8a2.jpg)

**Comment by FrDH** [comment]
Seems like yout page is broken. Have you tried the [problem solving-page](http://mmenu.frebsite.nl/support/problem-solving.html)?
