### ISSUE TITLE
Two panels visible at the same time

### ISSUE THREAD

**Issue by Snowbell92** [FrDH/jQuery.mmenu#575]
Is it possible to have two panels visible at the same time?I have a language switcher which I'd like to put immediately after the first level menu (it is ok if it is visible only for the first level panel). Currently the panel is hidden or more accurately, a new panel is created. I can't use the navbar-plugin because there's a lot of content (language switcher is just the start) and putting the switcher in the footer hides my already long menu partially (the menu is scrollable which I don't want. Please see the firebug snip I made to better demonstrate what I need. Thanks a lot in advance. Awesome plugin. 
![mm](https://cloud.githubusercontent.com/assets/338241/15453119/681d2e4c-202a-11e6-8a4f-70da029170f7.jpg)

**Comment by FrDH** [comment]
The plugin assumes every direct descendant of the menu to be a "panel", so you can simply wrap your ULs in a DIV:
````html
<nav id="menu">
   <div>
      <ul>...</ul>
      <ul>...</ul>
   </div>
</nav>
````
Hope this helps.
