### ISSUE TITLE
mmenu compatibility with old opera mini browser

### ISSUE THREAD

**Issue by faseyi** [FrDH/jQuery.mmenu#578]
please how do i make mmenu work with old opera mini browser

**Comment by FrDH** [comment]
update to a newer opera mini browser?

**Comment by faseyi** [comment]
I'm using the menu on an e-commerce site where most viewers are accessing the site through mobile platform and from our analysis 60% of our visitors on mobile uses old opera  mini. So there should be a way out as its costing us of huge revenue 

    On Wednesday, May 25, 2016 3:12 PM, Fred Heusschen <notifications@github.com> wrote:
 

 update to a newer opera mini browser?—

**Comment by FrDH** [comment]
I am not able to do any testing on a phone with old opera mini. If you can figure out what the issue is, that would be helpfull.
If it is due to lack of support for (even 2D) [CSS transforms](http://caniuse.com/#search=translate), there's not much I can do.
