### ISSUE TITLE
mmenu off-canvas addon doesn't work on IE9

### ISSUE THREAD

**Issue by ali-hellani** [FrDH/jQuery.mmenu#582]
Hi,

The **off-canvas** addon doesn't work on **IE9**, even on the website (http://mmenu.frebsite.nl/documentation/addons/off-canvas.html)

**I am using the latest version (5.6.4)**

**Comment by TheAdamP** [comment]
It's not working for me in the latest versions of Chrome and Firefox either.   Both examples behave the same way, the menu pushes the page off the screen rather than sliding over top.

**Comment by FrDH** [comment]
The issue with IE9 is, that it's not a modern browser :)
I'm working on a fix for IE9, but am not sure when that will be ready.
For now, I guess you could do a search/replace on the CSS and replace all `translate3d` with `translate`, omitting the last argument.

**Comment by ali-hellani** [comment]
Actually, based on **modernizr**, i did the following:

`
.no-csstransforms3d .mm-offcanvas.mm-menu.mm-current.mm-opened {
    z-index: 10;
}
`
it works but not smoothly.

**Comment by FrDH** [comment]
@ali-hellani would you mind doing some testing if I'd send you a (better) potential fix for IE9?

**Comment by FrDH** [comment]
Please give the new version (5.7) a try, it should have better support for older browsers.
Please make sure you include [Modernizr](https://modernizr.com/) as the plugin uses it for feature detection.
