### ISSUE TITLE
Not working with asp forms

### ISSUE THREAD

**Issue by Shigerux** [FrDH/jQuery.mmenu#583]
Hello,

first. Thanks for your very cool jQuery Menu. For HTML files this works perfect.
But I got a Problem with the <form></form> tag in ASP.NET files. All Texts/Inputs I put in a form tag are hidden when I open the menu.
The form tag in HTML files are fine, only got the problem with ASP Form Tags. Would be nice if there is a solution. Thanks!

**Comment by FrDH** [comment]
I don't see why a server side script would cause an issue if the HTML it outputs is OK.
Could you show some of the HTML it outputs?
