### ISSUE TITLE
Remove dynamically added panel

### ISSUE THREAD

**Issue by longmd** [FrDH/jQuery.mmenu#588]
I have multiple pages where there will be a list of associated tags & categories. Im adding a panel in the menu that I only want available to the user while you're on that specific page. Is there a way to dynamically remove a panel after its been added and had init() called upon it?

**Comment by FrDH** [comment]
Is there an online example of what you're trying to achieve?
Simply removing the DIV from the HTML does not do the trick?

**Comment by longmd** [comment]
Here is a Punker of what Im working with.... 
If you click Training -> Training Catalog in the menu, you get the additional menu of categories and tag. I'd only like that panel available when on that page. 

Its not represented here, but I can do a .remove() of the panel on the route change, but the arrow indicator on the "Training Catalog" menu item itself stays put as it doesnt know the panel has been removed. 

https://plnkr.co/edit/SCCBV9ycndYSLjtNa6Bv?p=preview

**Comment by FrDH** [comment]
Sorry for the late reply, but for now it is not possible to remove a panel other than doing it manually. Something like this should probably work, but might cause issues if the panel is opened at the time of removal:
````js
var $the_panel = $("#the-panel");
var $the_anchor = $the_panel.data( "mm-parent" ).find( ".mm-next" );

// maybe check if the panel is opened?
if ( $the_panel.hasClass( "mm-current" ) ) {
  var api = $("#the_menu").data( "mmenu" );
  api.closePanel( $the_panel );
}

$the_panel.remove();
$the_anchor.remove();
````

Hope this helps.

**Comment by longmd** [comment]
Thanks! That should work fine for the moment. Will maybe try to come up with something and do a PR in the future that handles this with a single API call. Appreciate the help!
