### ISSUE TITLE
Wordpress Plugin can not be uninstalled

### ISSUE THREAD

**Issue by Cloudchoice** [FrDH/jQuery.mmenu#589]
I made a test in wordpress multisite, but the menu was not called unless do the manual insertion of "fire script". 
When uninstall, the subsite where the installation took place lost several CSS settings not operationg properly! 

To operate must maintain the plugin active!

Basically once installed can not be removed without damaging the site!

**Comment by FrDH** [comment]
Sounds odd, all the plugin does on de-installation, is remove the stored values from the database. I don’t know how that would affect the content of pates or (sub)menus.

If you want, you can remove the file "uninstall.php" from the plugin root and see if that makes any difference.
