### ISSUE TITLE
Change the breakpoint

### ISSUE THREAD

**Issue by leakingminds** [FrDH/jQuery.mmenu#591]
Hey,

is it possible to change the breakpoint for the responsive menu? if yes, where can i do that?

**Comment by FrDH** [comment]
You can change the media-query for the [widescreen extension](http://mmenu.frebsite.nl/documentation/extensions/widescreen.html) to finetune when it should kick in:

````html
<link href="path/to/jquery.mmenu.widescreen.css" type="text/css" rel="stylesheet" 
   media="all and (min-width: 900px)" />
````
