### ISSUE TITLE
angular $locationProvider.html5Mode(true) causes menu to not close after selection

### ISSUE THREAD

**Issue by chungconscious** [FrDH/jQuery.mmenu#593]
After adding 

`$locationProvider.html5Mode(true);`

to my controller and 

`    <head>
        <base href="/">...
`

to my template, the mmenu no longer closes after selecting a menu item / new state

However,
1) browse does go to the new state and shows the new page under the dimmed out mmenu section
2) browse history shows the new state I select

Note that this is a new issue - the mmenu closes just fine on selection as soon as I remove

`$locationProvider.html5Mode(true);`

Please advise!

**Comment by FrDH** [comment]
By default, the menu should close if the `href` for the clicked anchor is equal to or starts with `#`.
