### ISSUE TITLE
Instance within page

### ISSUE THREAD

**Issue by smth** [FrDH/jQuery.mmenu#594]
It'd be nice if you could have a Mmenu within the flow of the page, fit to the width of its container etc. As far as I can see this isn't possible. The use-case I'm thinking of is the same of that of the widescreen extension, but where you'd like more control over the layout.

**Comment by FrDH** [comment]
Try not-using the default off-canvas behavior:
http://mmenu.frebsite.nl/on-and-off-canvas.html
(I just found the example on this page is broken, will fix it later on)

The documentation uses this feature for the example (the list next to the phone):
http://mmenu.frebsite.nl/documentation/addons/off-canvas.html

**Comment by smth** [comment]
Thanks @FrDH I'm getting close, by:
- using `"offCanvas": false` for my inline menu
- including the `oncanvas.js` (but not the CSS)

I have two problems though:
- on-canvas menu seems to need a fixed height applied to it (otherwise its height is 1px).
- off-canvas menu (on the same page) is now continuously visible (As I only need one menu working at a time, I guess this could be overcome by switching which JS file is included, depending on browser size).

**Comment by FrDH** [comment]
- Withou a fixed height, the sliding submenus won't work. If you have no submenus, or if you set the `slidingSubmenus` option to `false`, you can set the css property `position` to `relative` for the menu (.mm-menu), the panels wrapper (.mm-panels) and the panels (.mm-panel). 
- The off-canvas menu will need the off-canvas add-on. Only including `oncanvas.js` is not enough.
