### ISSUE TITLE
clickable entire menu item

### ISSUE THREAD

**Issue by Egretta** [FrDH/jQuery.mmenu#595]
from mm-menu page: _"The plugin assumes every A element in the menu should be clickable, it therefor adds the link to open a submenu next to it. If you replace the A with a SPAN, the entire menu item becomes clickable:"_

but in my site http://piirissaareturism.ee/ somehow it doesn't.

code i'm using:

`$("#main-menu").mmenu({
               "extensions": [
                  "pagedim-black"
               ],
               "offCanvas": {
                  "position": "right"
               },
               }, {
              // configuration
               clone: true
            });`

what i am missing?

**Comment by Egretta** [comment]
just for clarification - i use this script for A replacment:

`$('.mm-listview li:nth-child(2) .mm-next+a').replaceWith(function() {
   return '<span>' + $(this).text() + '</span>'
 });`

could this causing the problem?

**Comment by FrDH** [comment]
You should replace the `A` with a `SPAN` before firing the plugin. You do not need to do this with JS if you can change the HTML for the menu to something like this:
````html
<nav id="my-menu">
   <ul>
      <li><a href="/">Home</a></li>
      <li><span>About us</span>
         <ul>
            <li><a href="/about/history">History</a></li>
            <li><a href="/about/team">The team</a></li>
            <li><a href="/about/address">Our address</a></li>
         </ul>
      </li>
      <li><a href="/contact">Contact</a></li>
   </ul>
</nav>
````
