### ISSUE TITLE
Lazy Dynamic Content Sub Menu

### ISSUE THREAD

**Issue by kchojhu** [FrDH/jQuery.mmenu#597]
I'm really loving the script and using it for my personal project!

I've read on how to add dynamic sub-menu and that works well but it doesn't meet my needs.  Basically, I have hundred menus and each menu could have a submenu of 50~200 each.  So that equates to a lot of li tags being generated on client's browser.

Is there a way to load the submenu content when the user clicks on the menu? This way I don't have to generate every submenu.  Appreciate the help!

**Comment by FrDH** [comment]
Not by default, that would interfere with the internal structure for the add-ons. For example, the "counter" add-on would not be able to count the number of submenus.

I guess you could create this behavior manually using the "dynamic content" tutorial for inspiration.
