### ISSUE TITLE
Non-plugin mmenu interference with WordPress Admin bar

### ISSUE THREAD

**Issue by runofthemill** [FrDH/jQuery.mmenu#598]
Since the WP plugin is less customizable and can't be concatenated/minified in my build process, I added the jquery plugin instead.

The plugin works nearly fine, but it's causing the Admin bar to be hidden, *only* at the very top of the page. As soon as I scroll, it's no longer hidden. I can't see any code that would be affected the z-index or anything, and I tried debugging a bit and narrowed down the problematic code to the `$[ _PLUGIN_ ].prototype.setPage = function( $page )` function in `jquery.mmenu.offcanvas.js`. When I enqueued the 3 unminified scripts and selectively disabled them, the admin bar was no longer affected when that function was commented out. Granted, the plugin no longer worked, but at least I pinpointed where the issue is coming from.

I tried using the WP wrapper, but that didn't do anything, and setting my configuration as follows didn't work either:

```
                $('#side_menu').mmenu({
                            extensions: [
                               'pagedim-black',
                               'theme-dark',
                               'pageshadow'
                            ],
                            offCanvas: {
                              position: 'right',
                              pageSelector: '#wrapper'
                            },
                            navbars: [
                                  {
                                  position	: 'top',
                                  content		: ['breadcrumbs']
                                }
                                  ]
                          });
```

(Note I had no better success with a basic config either.)

Any thoughts?

I'm running WP 4.5.3; here's a gif of the issue:

http://www.giphy.com/gifs/3o72FfcIfFsuTYNCr6

**Comment by FrDH** [comment]
The 'offCanvas.pageSelector' option is a configuration option. It should be in the second object you pas to the plugin. Also, are you sure "#wrapper" tragets your DIV that should be considered to be the page?
