### ISSUE TITLE
Scroll not working for touch devices but does with mouse wheel

### ISSUE THREAD

**Issue by nuclearape** [FrDH/jQuery.mmenu#600]
The menu doesn't scroll on touch devices with the wordpress plugin.

Adding: 
.wpmm-menu {
overflow-y: auto;
}

makes it scroll with the mouse wheel but doesn't work with touch :(

example here: https://growitmowit.co.uk/?swoof=1&x=0&y=0&post_type=product click the filter button to open the menu

**Comment by FrDH** [comment]
Ji, I haven't heard about this issue before, it could be due to some js or css from your theme. I'll have a look at the online example later on.

**Comment by FrDH** [comment]
Sorry for the late reply, but I think I found what's wrong with the menu. Kind of a weird issue here, the `<div id="secondary">` is used for buttons in the header. That places all content from the menu in the navbar, making the navbar really long and leaving the menu empty.

Try removing `#secondary` from the "header > add buttons" option.
Hope this helps.
