### ISSUE TITLE
Where is the browser compatibility documentation?

### ISSUE THREAD

**Issue by kubik101** [FrDH/jQuery.mmenu#602]
Can't find it on site: http://mmenu.frebsite.nl
Thanks.

**Comment by FrDH** [comment]
Basically: "modern browsers", including IE10 and up (fallbacks for IE9 are coming). 
Note that not all possible cominations of options, extensions and add-ons have been testen on all browsers.

**Comment by FrDH** [comment]
P.s. I'm updating the "support" pages on the website with a FAQ section and will ensure to include somerhing about browser compatibility.

**Comment by kubik101** [comment]
Great glad to hear it.
=)

Trent Turner  
www.kubikdesign.com.au

> ecommerce  > content management systems  > website design & construction  > website maintenance  > email marketing   > web hosting   > domain registration
