### ISSUE TITLE
Mmenu won't close after upgrade

### ISSUE THREAD

**Issue by coffeeneed** [FrDH/jQuery.mmenu#603]
The bower.json in mmenu folder says version 5.6.5. This worked before. Anyone know what is wrong?
My JavaScript is as follows:

    $("#menu-hovedmeny").mmenu({

            navbar: {
              title: ""
            },
               "extensions": [
                  "effect-panels-zoom",
                  "pagedim-black",
                  "theme-dark"
               ],
               //autoHeight: true,
               "offCanvas": {
                  "position": "top",
                  "zposition" : "front"
               },
               "counters": true,
               "navbars": [
                  {
                     "position": "top",
                     "content": [
                        "<div class='close'><a href='#' id='close' class='close'>&#10006;</a></div>"
                     ]
                  }
               ]
            },{clone: true});

      var API = $("#menu-hovedmeny").data( "mmenu" );

      $("#close").click(function() {
         API.close();
      });

**Comment by FrDH** [comment]
As far as I can see, that should work.
Is there an online example?

**Comment by coffeeneed** [comment]
No, unfortunately. Will provide if necessary. Care to take a look at this? Chrome notices me about this error:

main.js:59 Uncaught TypeError: Cannot read property 'close' of undefined(anonymous function) @ main.js:59

dispatch @ jquery-1.12.4.min.js:3
r.handle @ jquery-1.12.4.min.js:3

**Comment by coffeeneed** [comment]
I just now figured out what is causing this. It's the cloning method. By removing this, the close button suddenly works: `,{clone: true}`

Any idea on why this happens? Is this a bug?

**Comment by coffeeneed** [comment]
Is this thread open?

**Comment by FrDH** [comment]
The `clone` option indeed adds the API to the cloned node, not the original node. Unfortunately, the plugin returns the original node. I'll see if I can change this behavior in the next version.
For now, you could try the following:
````js
$("#menu-hovedmeny").mmenu({
   // your options
}, {
   clone: true
});
var API = $("#mm-menu-hovedmeny").data( "mmenu" );
````

Sorry I didn't noticed the `clone` option before :/
