### ISSUE TITLE
transitionDuration issue

### ISSUE THREAD

**Issue by smachi** [FrDH/jQuery.mmenu#604]
I've noted two issues:

1. Adding transitionDuration option to the mmenu is not getting the value for me. It always has 400

2. When I close the menu it disappears before the animation ends.

I've solved the animation issue commenting these lines:

`$e.one( _e.transitionend, _fn );
$e.one( _e.webkitTransitionEnd, _fn );`

But I guess is not a good solution. 
What is happening here?

**Comment by smachi** [comment]
The problem is that there are child elements that are bubbling up the transitionend event continuously (in my case a Swiper slider or the hamburger button).

I've solved it updating the __transitionend method like this:

`__transitionend: function( $e, fn, duration )
		{
			var _ended = false,
				_fn = function(e)
				{

					if (typeof e !== 'undefined') {

						if ( $(e.target).hasClass('mm-page') ) {
							$e.unbind(_e.transitionend);
							$e.unbind(_e.webkitTransitionEnd);
						}
						else {
							return false;
						}

					}

					if ( !_ended )
					{
						fn.call( $e[ 0 ] );
					}
					_ended = true;
				};
	
			$e.on( _e.transitionend, _fn );
			$e.on( _e.webkitTransitionEnd, _fn );
			setTimeout( _fn, duration * 1.1 );
		}`

**Comment by FrDH** [comment]
The documentation states "The value should match the associated CSS value."
This means changing the `transitionDuration` configuration setting alone is not enough, you should also change the CSS, this works best if you use the SCSS files and [override the `$mm_transitionDuration` variable](http://mmenu.frebsite.nl/documentation/custom-css/override-variables.html).

**Comment by FrDH** [comment]
The bubbling issue should be fixed in the latest version. Does that resolve this issue?
