### ISSUE TITLE
toggles in navbars

### ISSUE THREAD

**Issue by gavinwwf** [FrDH/jQuery.mmenu#606]
## I added two toggles in navbars, and found the toggles lost its style. why? The code like this:
```
navbars		: [
						{
							position	: 'top',
							content		: [ 'searchfield' ]
						}
						, {
							position	: 'top',
							content		: [
								'<ul id="search-options">',
								'	<li>',
								'	  <a href="#">A toggle</a>',
								'	  <input type="checkbox" class="Toggle" />',
								'	</li>',
								'	<li>',
								'	  <a href="#">A toggle</a>',
								'	  <input type="checkbox" class="Toggle" />',
								'	</li>',
								'</ul>'
							]
						}, 
```

**Comment by FrDH** [comment]
Unfortunately, the JS for creating toggles is bound to panels (an `<UL />`).
Fortunately, the CSS for toggles is not and the JS does not add any events or somting like that.
So you should be able to insert the HTML that would normally be generated by the add-on and everything should work.

Instead of this:
````html
<a href="#">A toggle</a>
<input type="checkbox" class="Toggle" />
````

Try this:
````html
<input id="[unique_id]" class="mm-toggle" checked="checked" type="checkbox">
<label for="[unique_id]" class="mm-toggle"></label>
<a href="#">A toggle</a>
```
Where `[unique_id]` should be an actual unique id.

Hope this helps.

**Comment by gavinwwf** [comment]
@FrDH Thanks for your reply. I tried your method is effective, but the toggle's trackball just below its track and no response to click it. So, would you help me verify the toggle in navbars? Thank you again for your help.

**Comment by gavinwwf** [comment]
@FrDH sorry, I try place toggle not in "ul li", and it can be click, but the position of its trackball is not correct yet.

**Comment by FrDH** [comment]
Try adding the class "mm-listview" to the `<ul />`, that should fix the styling for the `<ul />`, `<li />` and `<a />`.
If that doesn't help, is there an online example?

**Comment by gavinwwf** [comment]
@FrDH demo: https://jsfiddle.net/gavinwwf/ev8k2j6g/1/ and https://jsfiddle.net/gavinwwf/tey3bnwe/7/.  The first demo add the class "mm-listview" to the <ul /> , the second adding toggle in content directly.

**Comment by FrDH** [comment]
The first fiddle almost works, I updated it here: https://jsfiddle.net/ev8k2j6g/2/

First you should use the plug sign (`+`) to combine strings, not a comma (`,`). A comma starts a new entry in the array.

Second, the `<ul>` is self-closing: `<ul class="mm-listview" />`, that should be `<ul class="mm-listview">` (without the slash at the end).

And third, I added `height: 2` to preserve 2 rows for the toggles.


You still might need to add `text-align: left` somewhere, but for the rest it seems to be working.

**Comment by gavinwwf** [comment]
@FrDH  thank u  very much!
