### ISSUE TITLE
Fixed header with mmenu as a mobile website

### ISSUE THREAD

**Issue by ChrisChun** [FrDH/jQuery.mmenu#607]
Mmenu is a good solution for me to develop a personal website of mobile design. And I have a question about the fixed header, Can the mmenu stick the header on the top, while the users click the nav menu if they are scrolled down the webpage? 

Thanks a lot. 

            jQuery(document).ready(function() {
		      	$("#navbar_main").mmenu({ //mmenu
		        	"slidingSubmenus": false,
		        	"extensions": ["effect-listitems-slide"],
               		"extensions": ["pagedim-black"],
               		"navbars": [{ 
               			"position": "top",
	                    title: "",
                  	}], 
               		"offCanvas": {
			            "zposition": "next"
			    	},
			        // configuration
			        classNames: {
			        	fixedElements: {
               				fixed: "nav_header"
            			},
			            vertical: "expand",
			        }
		      	});

		    });

**Comment by FrDH** [comment]
If your HTML contains an element with `class="nav_header"`, and it already has `position: fixed;` applied to it, that should work (assuming the fixedElements add-on is included in the webpage).
