### ISSUE TITLE
Better scss variables

### ISSUE THREAD

**Issue by jantimon** [FrDH/jQuery.mmenu#608]
Hi,

why do you reuse the `$mm_dimmedTextColor` for the arrow icons?

I would like to have different colors for the title and the icons:

<img width="441" alt="mmmenu" src="https://cloud.githubusercontent.com/assets/4113649/17550022/58e9a79a-5ef3-11e6-90cd-807108142274.png">

Could you please separate them?

**Comment by FrDH** [comment]
Mainly to prevent overconfiguration and maintain some of the aesthetics.
But I see your point and will split up the variables.

**Comment by jantimon** [comment]
Cool! 👍

**Comment by jantimon** [comment]
Can you give any eta?
I would create a merge request however I don't know you would do it because of the mixins

**Comment by FrDH** [comment]
I implemented in the (private) dev-branch, in the next version there will be a variable `$mm_navbarColor` available and the `mm_colors` mixin will be accepting an extra argument which defaults to `$mm_navbarColor`.

**Comment by jantimon** [comment]
So how would I set the back and forward icons to be red?

Like this?
```css
$mm_navbarColor: red;
```
