### ISSUE TITLE
Howto use addons with umd?

### ISSUE THREAD

**Issue by jantimon** [FrDH/jQuery.mmenu#609]
Hi,
is there any example on how you would use addons together with umd?

Thanks
Jan

**Comment by FrDH** [comment]
Due to issues with maintaining the dependencies in the automated (gulp) proces, there is no umd file created for each individual addon.

You could use the "jjuery.mmenu.all.min.umd.js" file which includes all add-ons or create an umd file manually.

**Comment by jantimon** [comment]
Okay I guess this will work for me.
