### ISSUE TITLE
Custom HTML Code

### ISSUE THREAD

**Issue by Webtransformer** [FrDH/jQuery.mmenu#610]
I know you can can add some content to the navbars with navbars/content.
But is there another way so that certain code stays that way?

I want to put some code above the ul lists.

**Comment by FrDH** [comment]
You can wrap the UL along with the custom HTML in a DIV.

**Comment by Webtransformer** [comment]
It works fine on first load but if you are slide to a submenu then code vanishes behind completely.

**Comment by FrDH** [comment]
Could you please provide a working example, or at least some HTML I could have a look at.
 [contribution guidelines](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md)
