### ISSUE TITLE
Z-Index painting issues

### ISSUE THREAD

**Issue by iandstanley** [FrDH/jQuery.mmenu#611]
I am Using Slick Slider from  http://kenwheeler.github.io/slick/ as a slider (client insisted that I use a slider in design although I feel they look dated)

Anyhow

Got mmenu working quite quickly but I am getting overpainting by the slider in the browser 

Trying to figure out what I need to push out with the z-index as nothing seems to make any difference

My source code is at 

[see this branch of my github repository](https://github.com/stereocats/jenniferbrickwell/tree/feature/Responsive_Meun_with_mmenu_%2315)

applicable source code is contained in ...
- _includes/nav.html
- js/main.js
- sass/nav.sass

**Comment by iandstanley** [comment]
![jennifer_brickwell_event_management_ltd_and_main_js_-_jenniferbrickwell](https://cloud.githubusercontent.com/assets/6939289/17616247/6a6fbbfc-606b-11e6-846c-1b760dbd5f46.jpg)

**Comment by iandstanley** [comment]
Dug around in /slick/ slider and it paints on z-index:1000

Poking around in the menu source I see a lot of z-index references (notably 0,1,2,3)

**Comment by FrDH** [comment]
A z-index is relative to the z-index of an ancestor node, so if the slider is inside the `<div class="mm-page">` (which has `z-index: 0`), the menu (with `z-index: 1;`) should be in front of the slider.

**Comment by iandstanley** [comment]
Thanks, tried it but couldn't get this to work this time 

I've fixed it with another css file (loading last to avoid the overriding by some of your ) loading

```
.mm-menu.mm-offcanvas {
  z-index: 2000;
}
```

Which sorted out the problem for now. 

Will go back an look at your suggestion when I finish the new few pages and look at refactoring on a separate branch.
