### ISSUE TITLE
Weird Scrolling + Bottom Bar bug on Safari on iOS9

### ISSUE THREAD

**Issue by ZohraS** [FrDH/jQuery.mmenu#612]
Hey guys,

Great plugin! I love it! I'm having a weird issue though. I have a pretty long menu, with a bottom bar that has social media links. The device I'm using is an iphone 6S Plus.

On Chrome, I can scroll the menu, and the bottom bar is visible.

On Safari though, once you open the menu, you can't close it. You can't scroll up an down in the menu, and the bottom bar doesn't show.

Any ideas?

**Comment by FrDH** [comment]
The [scrollBugFix add-on](http://mmenu.frebsite.nl/documentation/addons/scroll-bug-fix.html) (included and used by default) tries to prevent (default) unwanted scrolling behavior. You could try to turn it off:
````js
$("#menu").mmenu({
   scrollBugFix: false
});
````

If that doesn't help, is there an online example I could have a look at?
