### ISSUE TITLE
No scroll possibility with autoHeight

### ISSUE THREAD

**Issue by Webtransformer** [FrDH/jQuery.mmenu#613]
Everything is working fine but when I am using autoHeight: true and the viewport is smaller than the menu then I cant scroll in the menu (touch and mouse). It doesnt work with any Browser or Mobile Device.
I disabled my custom css to see if my theme is causing these.
With some CSS logic (overflow-y) I had no luck.

Here are my options:

    var mobileNavOptions = {
        extensions: ["theme-white", "multiline", "border-full"],
        clone: false,
        autoHeight: true,
        panelNodetype: "ul",
        offCanvas: {
            position: "top",
            zposition: "front"
        },
        classNames: {
            selected: "active"
        },
        navbar: {
            title: ""
        },
        onClick: {
            preventDefault: null
        },
        scrollBugFix: {
            fix: true
        },
        navbars: [
            {
                position: 'top',
                content: ["prev"],
                height: 1
            },
            {
                position: 'top',
                content: [
                '...'
            ],
                height: 1
            },
            {
                position: 'top',
                content: ["title"],
                height: 1
            },
            {
                position: 'bottom',
                content: ['...'],

                height: 1
            },
            {
                position: 'bottom',
                content: [
                '...'
            ],
                height: 1
            }
                 ],
        extensions: [
            "border-offset"
         ]
    }

**Comment by FrDH** [comment]
Hi, thanks for reporting the issue.
The menu should have a max-height of 100%. I'll fix this issue in the next version, for now you can add a max-height manually:

````css
.mm-menu.mm-autoheight {
   max-height: 100% !important;
}
````

**Comment by FrDH** [comment]
should be fixed in 5.7.2
