### ISSUE TITLE
fixed header not working in Wordpress

### ISSUE THREAD

**Issue by mkaragosian** [FrDH/jQuery.mmenu#614]
Running latest version of the Wordpress plugin plus a jQuery plugin for a sticky header.  Mmenu setup in Wordpress is using ".nav-secondary .wrap" for the selector.  Added "Fixed" class to the div.wrap element (identified by the selector), and verified it's there.  The sticky header is accomplished with a div wrap hierarchically above the nav.nav-secondary element.  When sticky, the site header has position:fixed and top:0.  Mmenu works great.  But when the site header is sticky, the site's sticky header disappears.  No other plugins used than the two just described.  The parent theme is Genesis 2.3.1.  Any suggestions?

**Comment by FrDH** [comment]
Is there an online example I couls have a look at? You can send me a PM with a login if needed.

**Comment by mkaragosian** [comment]
Hi Fred,

The site is at http://cinepedia.com.  It’s under development, so access is normally limited to my ip address.  But the limitation is now removed.  Thanks for taking time to look.

If you need Wordpress access, I set up a login for FrDG with the same initials for password.

Best,
Michael


On Aug 22, 2016, at 4:54 AM, Fred Heusschen <notifications@github.com> wrote:

Is there an online example I couls have a look at? You can send me a PM with a login if needed.

**Comment by mkaragosian** [comment]
Site is at http://cinepedia.com.  Under development, access restrictions now removed.

If you need access to Wordpress, please write me at michael.karagosian@mkpe.com.
