### ISSUE TITLE
SCSS variables are inconsistent

### ISSUE THREAD

**Issue by jantimon** [FrDH/jQuery.mmenu#615]
Just tested the #608 improvements in `5.7.0` and it works quite nice.
Unfortunately the back button is not using the same variable as the forward button:

<img width="440" alt="pattern__offscreen-menu__organisms_" src="https://cloud.githubusercontent.com/assets/4113649/17844870/08c8286e-683e-11e6-9d2e-d0062316270d.png">
<img width="454" alt="pattern__offscreen-menu__organisms_" src="https://cloud.githubusercontent.com/assets/4113649/17844878/15c10680-683e-11e6-85a9-163644bf9915.png">

**Comment by FrDH** [comment]
Correct. As of version 5.7, there's a variable for the navbar color, it will paint text and buttons inside the navbar.
If you're trying to change the color of all arrows (in listviews and navbars), I'd suggest you manually add this CSS:
````css
.mm-prev:before,
.mm-next:after
{
    border-color: blue !important;
}
````

**Comment by jantimon** [comment]
important is forbidden as it is unmaintainable..
why isn't it possible just to set the color for the icons?

**Comment by FrDH** [comment]
`!important` isn't the only way to override CSS, an more extensive selector will also work:
````css
.mm-menu .mm-listview > li .mm-next:after,
.mm-menu .mm-btn::after, 
.mm-menu .mm-btn::before {
  border-color: blue;
}
````

As stated in #608, preventing overconfiguration is the main reason to not have a variable for every possible color. 
It is possible to add up to 4 navbars at the top and 4 navbars at the bottom, each navbar can have a title, prev- and next icon. So for completeness, you'd end up with the following variables just for navbars:
- navbar top 1 text color
- navbar top 1 prev icon color 
- navbar top 1 next icon color
- navbar top 1 close icon color 
- navbar top 2 text color
- navbar top 2 prev icon color 
- navbar top 2 next icon color
- navbar top 2 close icon color 
- navbar top 3 text color
- navbar top 3 prev icon color 
- navbar top 3 next icon color
- navbar top 3 close icon color
- navbar top 4 text color
- navbar top 4 prev icon color 
- navbar top 4 next icon color
- navbar top 4 close icon color 
- navbar bottom 1 text color
- navbar bottom 1 prev icon color 
- navbar bottom 1 next icon color
- navbar bottom 1 close icon color 
- navbar bottom 2 text color
- navbar bottom 2 prev icon color 
- navbar bottom 2 next icon color
- navbar bottom 2 close icon color 
- navbar bottom 3 text color
- navbar bottom 3 prev icon color 
- navbar bottom 3 next icon color
- navbar bottom 3 close icon color
- navbar bottom 4 text color
- navbar bottom 4 prev icon color 
- navbar bottom 4 next icon color
- navbar bottom 4 close icon color

**Comment by jantimon** [comment]
Actually I would just have on for icons - so that you can specify a color for interaction element, a color for boder, a color for links and maybe a color for headlines

Just one color per interaction element.

Is it possible to include the css which does only the layout and animation without using css for design and colors?

**Comment by FrDH** [comment]
> Actually I would just have one for all icons - so that you can specify a color for icon interaction elements, a color for border, a color for links and maybe a color for headlines
You want to paint all icons, others might want to paint everything in a navbar, someone has to make a decision on where the configuration stops. I choose to paint navbars as it seemed more logical.

I agree overriding using CSS is not ideal, but I doubt there is a better way in this case.

You could try to override the mixins in the [mixinx_colors scss file](https://github.com/FrDH/jQuery.mmenu/blob/master/src/css/_imp/_mixins_colors.scss). But I'm not sure that'll work.

I'll see if I can split up the SCSS more in the next release, with variables that let you opt-out of certain styling. Thanks for the suggestion.

**Comment by jantimon** [comment]
wow cool 👍
