### ISSUE TITLE
Jumps to the top on click on API Close Button

### ISSUE THREAD

**Issue by maltehelmhold** [FrDH/jQuery.mmenu#617]
Hello, 

I researched for a time and found the solution for the issue jumping to the top when opening the offcanvas. 

But we have the problem that it jumps to top on click on the button which triggers: 
API.close();

this is our code: 
$("#oc-close").click(function() {
API.close();
});

THANK you for giving a fix or solution,
Malte

**Comment by FrDH** [comment]
You need to prevent the default behavior:
````js
$("#oc-close").click(function( event ) {
  event.preventDefault();
  API.close();
});
````

**Comment by maltehelmhold** [comment]
hey! thank you, I forgot about this issue :D 

but I solved it. We should not have used: 

<a id="oc-close" href="#".... >Close</a>

but rather <span id="#oc-close">Close</span>

because # makes it jumping on close

thank you anyway,
Malte
