### ISSUE TITLE
How to use only the hamburger + flyout with my already existing menu

### ISSUE THREAD

**Issue by jacargentina** [FrDH/jQuery.mmenu#618]
I have a scrollable TOC menu like the one found on http://cordova.apache.org/docs/en/latest/

Now i would love to use jquery.mmenu on it, but i want to reuse all my markup without having jquery.mmenu touching or adding classes to it. I really need these parts:

 - Show the hamburger only when on mobile
 - Event when clicking the hamgurber to show the menu i already have from the left

I've searched for an option for that, but cant find. Any advice? Or should i implement my own custom js to achieve this?

Cheers!

**Comment by FrDH** [comment]
Showing/hiding HTML based on screen-size can be done with media-queries:
````css
@media (min-width: 500px) {
  #hamburger {
    display: none;
  }
}
````

Mmenu needs to add classes and rearrage the markup, it can't do without.

**Comment by FrDH** [comment]
Not sure if this is what you're looking for, but you can let the plugin create a clone of the menu, leaving the original untouched.
