### ISSUE TITLE
mmenu won't close with API.close() if it's cloned

### ISSUE THREAD

**Issue by coffeeneed** [FrDH/jQuery.mmenu#621]
The bower.json in mmenu folder says version 5.6.5. This worked before. Anyone know what is wrong?
Really need help with this? :) If I remove the clone method, everything work OK.

My JavaScript is as follows:

$("#menu-hovedmeny").mmenu({

        navbar: {
          title: ""
        },
           "extensions": [
              "effect-panels-zoom",
              "pagedim-black",
              "theme-dark"
           ],
           //autoHeight: true,
           "offCanvas": {
              "position": "top",
              "zposition" : "front"
           },
           "counters": true,
           "navbars": [
              {
                 "position": "top",
                 "content": [
                    "<div class='close'><a href='#' id='close' class='close'>&#10006;</a></div>"
                 ]
              }
           ]
        },{clone: true});

  var API = $("#menu-hovedmeny").data( "mmenu" );

  $("#close").click(function() {
     API.close();
  });

**Comment by FrDH** [comment]
The `clone` option adds the API to the cloned node, not the original node. Unfortunately, the plugin returns the original node. Thank you for reporting this issue, I'll see if I can change this behavior in the next version.

For now, you could try the following:
````js
$("#menu-hovedmeny").mmenu({
   // options
}, {
   clone: true
});
var API = $("#mm-menu-hovedmeny").data( "mmenu" );
````

**Comment by coffeeneed** [comment]
Thanks a lot! :)

**Comment by FrDH** [comment]
Will be fixed in the next version, should work like this:
````js
var $menu = $("#menu-hovedmeny").mmenu({
   // options
});
var API = $menu.data( "mmenu" );
````

**Comment by artursopelnik** [comment]
+1 bug still exists
