### ISSUE TITLE
How to add seperators (non clickable)

### ISSUE THREAD

**Issue by 450b** [FrDH/jQuery.mmenu#624]
Is it possible to add seperators for my services, usually you break a list into a couple of sub menu levels, but I want all items in 1 list, seperated by categories (same as menu items but not clickable and with a different style).

I almost got what I want by using span tags instead of anchor tags, but the style is exactly the same as any other menu item. How can I style only those items?

**Comment by FrDH** [comment]
Have you read the [basic tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/styling-lists.html)?
On the "Styling lists" page, there's a section called "dividers". Try that.

**Comment by 450b** [comment]
Thanks, missed it!

**Comment by FrDH** [comment]
np
