### ISSUE TITLE
Menu not opening on iPad Air

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#625]
I've downloaded the jQuery plugin and copied it onto a webserver. It works very nice on my laptop, iPhone and my old iPad. But on my iPad Air the menu will not open when I click on the hamburger icon. When I try the demo's on http://mmenu.frebsite.nl/ then they work without any problems on my iPad Air. Does anyone know what I need to do to get it working on my iPad Air?

**Comment by FrDH** [comment]
I don't see any reason the plugin shouldn't work on an iPad air.
Only difference could be the iOS version I guess.

**Comment by heusd045** [comment]
![ipad 2](https://cloud.githubusercontent.com/assets/22277976/18683025/dbcf1000-7f6e-11e6-8122-5bab4d3b05f1.png)
![ipad air](https://cloud.githubusercontent.com/assets/22277976/18683023/dbc220fc-7f6e-11e6-9f7b-fc1386109658.png)
![iphone 5](https://cloud.githubusercontent.com/assets/22277976/18683024/dbcb828c-7f6e-11e6-989d-003e0b842340.PNG)

I've attached 3 screenshots: one from my iPad 2, one from my iPad Air and one from my iPhone 5. On the iPhone 5 and iPad Air the screen is shown correctly, but on the iPad 2 the screen is not full screen (there is a white column on the left side of the screen). Can you please tell me how I can fix this?

Thank you.

**Comment by heusd045** [comment]
There is also something else strange happening. I've set the Widescreen extension. On my laptop it works correctly and also on the old iPad. But on the iPad Air the menu is not shown. I would expect to see the menu also on the iPad Air because the resolution is higher than the old iPad?

Both iPad's have the same iOs version (9.3.5) and the Safari look identical.

Can you please help me fix this? Thank you.

![ipad 2](https://cloud.githubusercontent.com/assets/22277976/18683445/a3f7e448-7f70-11e6-989f-f46cdbff5dc4.png)
![ipad air](https://cloud.githubusercontent.com/assets/22277976/18683446/a3faa494-7f70-11e6-8670-5e9d6697ca98.png)

**Comment by FrDH** [comment]
If the demo files from the download-pack work, there's probably something "wrong" with your website. 
Is there an online example I could have a look at?

**Comment by heusd045** [comment]
Please look at http://www.mijndgpi.nl/test2/index.html

**Comment by FrDH** [comment]
I find it very strange the plugin doesn't work only on an iPad Air. You could ofcourse close Safari, clear cache and restart the iPad. See if that helps.
Does javascript work at all on the iPad Air? If you add an alert, does it show?
````js
alert( "javascript works" );
````
