### ISSUE TITLE
Fullscreen only on iPhone

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#626]
Is it possible to only use the Fullscreen option when the menu is viewed on an iPhone?

Thank you.

**Comment by FrDH** [comment]
Not by default, but if you can detect the browser, you should be able to enable/disable the widescreen extension by changing the href for the css file.

**Comment by heusd045** [comment]
Is this something that you could develop for me?

**Comment by FrDH** [comment]
Something like this I guess:
````js
var iphone = '???'; // however you think you should target an iPhone
if ( iphone ) {
   $('#an-emty-link-tag').attr( "href", "path/to/widescreen.css" );
}
````

**Comment by heusd045** [comment]
In PHP I have a variable $iPhone that is true when the page is opened on an iPhone.
I always link the fullscreen CSS, even when the page is not opened on an iPhone.
How can I add "extensions: ["fullscreen"]" to 

		<script type="text/javascript">
			$(function() {
				$('nav#menu').mmenu({

when $iPhone == true ??

**Comment by heusd045** [comment]
I fixed it with 

<?php if($iPhone) { echo ",extensions: [\"fullscreen\"]"; } ?>
