### ISSUE TITLE
Localization of subpanel titles

### ISSUE THREAD

**Issue by longmd** [FrDH/jQuery.mmenu#627]
We've added localization to a platform in which we're using the plugin. The only caveat being the subpanel titles in the "navbar" are not updating when the parent menu item titles get updated. I've tried running a loop of the init method from the API on all the panels, in hopes it would go grab the parent menu item titles, with no luck. Do we have a way to reinit the panels to allow those titles to update?

**Comment by FrDH** [comment]
The navbars are created only once and are not updated (nor is there a function to manually update them).
I'll see if I can split up the process and create a callable method for each part of the functionality.

For now, you can grap the parent menu item with`$("#some-panel").data( "mm-parent" )`, that'll return the parent `LI` (if any). Use `$("#the-li").closest( ".mm-panel" )` to find the parent panel.

**Comment by longmd** [comment]
That would be awesome if those were incorporated in an update or init function. Ill play with getting the parent... Would the logic here be to go get the parent LI, do a .text() to get the new title, then replace the mm-title anchor text within the panel with the text we got from the LI?

**Comment by longmd** [comment]
Here's what I ended up with... Seems to work through initial testing... 

```
$(".mm-panel").each(function (i,e) {
    var _this = $(e)[0];
    var _api = $(e).data("mm-parent");
                    
    if ($(_api)[0]) {
        _api = $(_api)[0];
        $timeout(function () {
             var _text = $(_api).find('span').text();
                 _text = _.trim(_text.replace('Open submenu', ''));
             $(_this).find('.mm-title').text(_text);
                            
             //If this panel is open, swap the main titlebar text.
             if ($(_this).hasClass('mm-current')) {
                 $('.mm-navbar-top-3').find('.mm-title').text(_text);
             }
         });
     }
 });
```
If you do end up coming up with a method to simplify this process down, that would be fantastic. Just give me a shout and I'll do some testing for you on it. Thanks for your continued help!

**Comment by FrDH** [comment]
will do :)
