### ISSUE TITLE
Hover not working in combination with class="Inset" ?

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#628]
I've added the class="Inset" to a submenu so it opens straight away. But now when I hover over an item the line is not selected but the whole submenu. You can check this out on https://www.mijndgpi.nl/test4/ 

How can I get a hover working on a single line?

**Comment by FrDH** [comment]
I don't see an inset-submenu in the example you've provided.

**Comment by heusd045** [comment]
Sorry, you just caught us while we were testing something else. Please look again.

**Comment by FrDH** [comment]
The :hover state applies only to anchors in a listview:
````css
.mm-listview > li > a:hover {}
````
I guess you could manually add it to inset submenus as well, but it would probably look pretty odd:
````css
.mm-inset > li > a:hover {
   background: #123456;
}
````
