### ISSUE TITLE
Don't show menu title on first page

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#629]
I'm using sliding submenu's. Is it possible to hide the menu title of the menu and only show it for submenu when they are opened? I've done this:

					navbar 		: {
						title		: ''
					},

but then an empty row is displayed. I would like to kill this empty row so the whole menu becomes smaller.

**Comment by FrDH** [comment]
You can remove the navbar from all panels using `add: false`:
````js
navbar: {
   add: false
}
````

To remove the navbar from only the first panel, you'd have to manually remove the class `mm-hasnavbar` from the panel:
````js
$("#my-menu").mmenu();
$("#my-menu").find( ".mm-panel" ).first().removeClass( "mm-hasnavbar" );
````

**Comment by heusd045** [comment]
This works. Thanks.
