### ISSUE TITLE
Loading fullscreen extension only when phone is in portrait orientation

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#630]
Hi, I have added a Javascript function that detects the orientation of a phone. What I would like to do is to only show the menu in full screen when the phone is in portrait orientation, not when it is in landscape orientation. Is it possible with Javascript to load the fullscreen extension when the phone is in portrait orientation and unload it when it is in landscape orientation?

Thx

**Comment by FrDH** [comment]
The easiest way would be to [create a custom CSS file](http://mmenu.frebsite.nl/documentation/custom-css/concatenate-files.html) where you do not load the "fullscreen" CSS. Instead you load the "fullscreen" CSS seporately with a media query. Mutch like intedended for the [widescreen extension](http://mmenu.frebsite.nl/documentation/extensions/widescreen.html).

Hope this helps.

**Comment by heusd045** [comment]
I already tried

<link rel="stylesheet" type="text/css" href="css/jquery.mmenu.fullscreen.css" media="all and (max-width: 400px) and (orientation: portrait)">

but when the orientation changes to landscape the menu is still shown in fullscreen.

**Comment by heusd045** [comment]
I think the problem is not loading the jquery.mmenu.fullscreen.css file but how can I prevent the extensions: ["fullscreen"] command when the screen is in portrait? I noticed that even when I don't load the fullscreen.css but use the extensions: ["fullscreen"] command the menu is shown in fullscreen.

`   <script type="text/javascript">
      $(document).ready(function() {
         $("#my-menu").mmenu({
            extensions: ["fullscreen"]
         });
      });
   </script>`

**Comment by FrDH** [comment]
Extensions are CSS only. Therefor, if you do not load the CSS, any classname added to the menu won't have any effect.

Note that the "fullscreen" extension (unline the "widescreen" extension) IS included in the ".all"-css file. Meaning you should either [create a custom .css file](http://mmenu.frebsite.nl/documentation/custom-css/concatenate-files.html) where you exclude the "fullscreen" extension or include all .css files seporately into the webpage.

I can not debug your website if you do not provide an online example, as requested by the [contributing guidelines](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md)
