### ISSUE TITLE
Selected menu state on child pages in WordPress plugin

### ISSUE THREAD

**Issue by benhuson** [FrDH/jQuery.mmenu#631]
Hi,

Just trying out the WordPress plugin version of mmenu.
http://mmenu.frebsite.nl/wordpress-plugin.html

I found that if you have a menu with child items and you are viewing a child item page, the menu will correctly default selecting the child page, but if you navigation back in the menu to view the primary menu items, it's parent will not be highlighted.

I think this is because WordPress only adds the `current-menu-item` class to the current item and different class to select parent items: `current-menu-ancestor`, `current-menu-parent` etc, so menu does't know to highlight these parent items as it does't recognise the selected classes.

Using the jQuery menu script (not the plugin) I can fix this issue by ensuring a consistently named class is added to all selected menu items, then specifying menu should use this to identify this as the selected class.

Here's an example of how to add the consistent class to selected menu items in WordPress:

```
<?php

/**
 * Add Generic Current Menu Item Class
 *
 * Adds a `current-item` class to selected menu items; parents, ancestors.
 *
 * This is required for compatibility with mobile mmenu which expects all
 * selected menu items to have the same selected class name.
 *
 * @param   array   $classes  Classes.
 * @param   object  $item     Menu Item.
 * @return  array             Filtered classes.
 */
function mmenu_add_generic_current_menu_item_class( $classes, $item ) {

    // Add generic selected menu item class
    if ( count( array_intersect( $classes, array( 'current-menu-item', 'current-menu-parent', 'current-menu-ancestor' ) ) ) > 0 ) {
        $classes[] = 'mmenu-current-item';
    }

    return $classes;

}

// Do the filter late (priority 50) so we only check classes after other plugin have probably done their stuff
add_filter( 'nav_menu_css_class', 'mmenu_add_generic_current_menu_item_class', 50, 2 );

?>
```

**Comment by FrDH** [comment]
Hi,

I don't think that would help, the jQuery plugins would remove the selected class from all LI's except for the last one:
````js
var $s = this.__findAddBack( $panels, '.' + _c.listview )
    .children( '.' + _c.selected )
    .removeClass( _c.selected )
    .last()
    .addClass( _c.selected );
````

The `parent`-option in the [setSelected add-on](http://mmenu.frebsite.nl/documentation/addons/set-selected.html) does something similar, but for now that is not included in the WP plugin.
