### ISSUE TITLE
Close submenu when opening another

### ISSUE THREAD

**Issue by ixaxi** [FrDH/jQuery.mmenu#632]
(Using mmenu on Drupal 7.51 site)

I'm using a left mmenu for the site, at all screens (mobile to desktop). It would be great if there could be an toggle added so opening a submenu would automatically close any other open submenu. Currently clicking on a second menu item opens a second submenu and leaves the first open as well, causing part of the menu to fall off the screen. 
Good choices to have would be: 
1)  + icon on right of menu button that changes into a - icon so you know you need to close submenu  yourself (or similar symbols)
2) opening one closes other submenu automatically
I've tried adding a script loop catching the second click, but only manage to let the whole menu remain stubbornly closed altogether. Would be amazing  this was a simple toggle in the script / Drupal module out of the box..

**Comment by FrDH** [comment]
Have you read this issue:
https://github.com/FrDH/jQuery.mmenu/issues/559

You can use CSS to change the + icon into a - icon:
````css
.plus,
html.mm-opened .close {
   display: block;
}
.close,
html.mm-opened .plus {
   display: none;
}
````
Also, here's a tutorial on how to create an animated hamburger icon that might help you:
http://mmenu.frebsite.nl/tutorials/animated-hamburger.html

**Comment by ixaxi** [comment]
Thanks for that! Very helpful.
I did get working code that does the open/close trick on stackexchange, wanted to share that here too: http://drupal.stackexchange.com/q/216137/53163
