### ISSUE TITLE
Automatically open

### ISSUE THREAD

**Issue by coffeeneed** [FrDH/jQuery.mmenu#633]
Hi. I want the current menu location (in the path nested hierarchy) to be pre-opened when I open the menu with my hamburger icon. As it is now, only the upper start location is opened when I click the hamburger icon.

I found this issue: https://github.com/FrDH/jQuery.mmenu/issues/383 and I managed to add the selected class, but the problem didn't get fixed. Any idea on how I can fix this, please? This didn't work for me.

Is this feature removed?

Cheers :-)

**Comment by FrDH** [comment]
If you add the classname "Selected" to a `LI`, that should set the `LI` to selected and open the panel it is in by default. This should work, if it doesn't, changes are you've done something wrong...

Also, you could set the `current` option for the `setSelected` add-on to `"detect"`, that should automatically set the correct `LI` to selected based on the URL:
http://mmenu.frebsite.nl/documentation/addons/set-selected.html

Please provide an online example if you still feel something is wrong with the plugin.

**Comment by renderlife** [comment]
Class has is **S**elected 
not **s**elected
fack!
