### ISSUE TITLE
Problem with stylesheet

### ISSUE THREAD

**Issue by heusd045** [FrDH/jQuery.mmenu#637]
I'm having a problem with a stylesheet. I've been looking at it for hours now but I cannot find the problem. Can you please help me?

When I open the webpage with the menu then the background is white:

![screenshot1](https://cloud.githubusercontent.com/assets/22277976/19342510/71b0fe74-9132-11e6-8bfa-24c0761f6fb8.png)

When I open the menu then the background is set to the color that I've set in the stylesheet:

![screenshot2](https://cloud.githubusercontent.com/assets/22277976/19342539/8689b4d0-9132-11e6-8407-aae7ad13a522.png)

Can you tell me why the background is not applied directly when I open the webpage? 

This is the part of the stylesheet where I set the background color:

`body
{
	background-color: #34495e;
	font-family: Arial, Helvetica, Verdana;
	font-size: 14px;
	line-height: 22px;
	color: #fff;
	position: relative;
	-webkit-text-size-adjust: none;
}`

**Comment by FrDH** [comment]
When the menu is opened from behind the "page", the "page" needs a background(-color). Therefor, the "page" inherits the background from the body while the menu is opened:
````css
html.mm-opened .mm-page {
    background: inherit;
}
````
The [Tips & Tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html) suggests to "set a background(-color) on the body".

**Comment by heusd045** [comment]
Sorry, but I don't understand your comment. 

The problem is that there is set a background color to the body but it is not shown. Only when I open the menu the correct background color is shown.
