### ISSUE TITLE
Justified ListView Extension

### ISSUE THREAD

**Issue by MROALI** [FrDH/jQuery.mmenu#638]
Hello everyone, 

I want to report an issue concerning the JustifiedListView Extension.   I made the test using an iphone 5 on IOS 8.4 (safari) . 
When I have lots of items that doesn't fit on the menu, the scrollbar is not showing, and all the item is missed up. 
I have no issue with the android devices (google chrome) neither in desktop devices (Google chrome) .

Thankyou in Advance

Best regards

![mms_20161019_173630](https://cloud.githubusercontent.com/assets/22939696/19525997/37b8bc16-9623-11e6-97c3-f6ff44ffdbcc.png)

**Comment by MROALI** [comment]
Thank you FrDH for your answer. 
 
I added the css that you provided, but still not working ;(.  The display bug still persisting, and i didn't notice any changes . Even i tried a bigger value than 40px but no changes. 

Do you have any other solution ?

Thank you in advance

Best Regards

**Comment by FrDH** [comment]
For my understanding: is "test 5" the last list item? Or are there more list items below it?
Have you tried adding a `min-height` to the LI?
````css
.mm-menu .mm-listview > li:not(.mm-divider) {
   min-height: 40px;
}
````
Not the most ideal solution, but might work in this case.

**Comment by FrDH** [comment]
Update: 
After some more debugging, I found the issue, flex-shrink should be set to `0` and flex-basis to `auto`:
````css
flex: 1 0 auto
````
This issue will be fixed in the next version.
