### ISSUE TITLE
Cannot remove mmenu title navbar when using navbar addon

### ISSUE THREAD

**Issue by clselin** [FrDH/jQuery.mmenu#639]
I have been using mmenu to develop a menu and it's going quite well. I had no navbar at the top, as I don't want one, I just want the menu. 

I was asked to add some navbars to the bottom of the menu, which I did by adding the navbars addon. 

Since adding the navbars addon to add my two bottom navbars to the bottom of the page, an unwanted header navbar has appeared. 

I've tried using add:false to remove it, I've tried adding 'title: ""', but it just won't go away! 

Am I missing something or is this a bug? 

```  
var API = $("#side-menu").mmenu({
             extensions   : [ "pagedim-white", "custom-width" ],
             navbar: {
              add: false
              },
             "navbars": [
                  {
                     "position": "bottom",
                     "content": [
                        '<div>login links</div>'
                     ]
                  },
                  {
                     "position": "bottom",
                     "content": [
                        '<div class="social-menu">...</ul></div>'
                     ]
                  }
                  ,true
               ],
             // configuration
             offCanvas: {
                pageSelector: "#page"
            }
          })
          .data( 'mmenu' );
```

Thanks for any help.

**Comment by clselin** [comment]
Thank you! based on the doc I was looking at I thought the 'true' was related to turning on navbars completely. I appreciate the clarification.

**Comment by Staceysol** [comment]
I have been using mmenu to develop a menu and it's going quite well until i wanted to remove navbar top title

I did try removing it by adding the navbars addon.

but its not working 

<script>
        document.addEventListener(
            "DOMContentLoaded", () => {
                new Mmenu("#menu").mmenu({
                    navbar: {
                        title: "Shop By Category"
                    },
                });
    </script>
