### ISSUE TITLE
mmenu and IE Edge flicker problem

### ISSUE THREAD

**Issue by icehawk-de** [FrDH/jQuery.mmenu#640]
In my MS Edge Browser (WIN 10), all sites with mmenu are flickering, black screen an not working correctly. Is this Issue known.
![test](https://cloud.githubusercontent.com/assets/19264337/19598257/3bc4b166-979a-11e6-9fc3-f54c7c30eca9.PNG)

**Comment by FrDH** [comment]
I never heard about it before. Is that a screenshot from the documentation website?? That looks really bad! I have no idea why the background would become black.

**Comment by icehawk-de** [comment]
Problem is resolved. It was a problem with my graphic drivers in IE Edge.
Sorry!

**Comment by FrDH** [comment]
NP
