### ISSUE TITLE
accessibility issues regarding empty links (e.g., used for next indicators)

### ISSUE THREAD

**Issue by marthasa** [FrDH/jQuery.mmenu#642]
we are using the wave web tool (accessibility tool) to verify our site and are finding numerous errors because of the empty links associated with the styling of the next indicators.

If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.

this raises another accessibility flag and without accessible links we won't be able to deploy this  on our sites.

is it possible to please add accessible text for all links?
thanks!

**Comment by FrDH** [comment]
Have you tried the [screenreader add-on](http://mmenu.frebsite.nl/documentation/addons/screen-reader.html)?

**Comment by marthasa** [comment]
thanks for the quick response.
 
our university's Campus Web Accessibility and Adaptive Technology Coordinator suggests that we use wave (aim tool) to validate/verify our sites; which flagged all the empty links as errors.  seems minor but as a university we have to be as compliant as possible for multiple readers/etc. 
 
seems like adding hidden text that explains the link could be added?

thanks.

**Comment by ffoodd** [comment]
@marthasa May you try (or at least read) my pull requests #636 on this topic? I think it solves the problem you described.

**Comment by marthasa** [comment]
yes this sounds like it addresses the issue. i'll try to pull and test later today.
thanks!

**Comment by marthasa** [comment]
thanks for the quick response.

this was reported to us by our university’s Campus Web Accessibility and Adaptive Technology Coordinator and then i confirmed using the “wave” aim tool that flagged all the empty links as errors.  seems minor but as a university we have to be as compliant as possible for multiple readers/etc.

seems like adding hidden text that explains the link could be added?

**Comment by marthasa** [comment]
sorry i'm just getting back to this;  yes we've tried the screenreader addon, it still appears there are empty links:

<a class="mm-next" href="#menu-tree-mlid-363" data-target="#menu-tree-mlid-363" aria-haspopup="true"><span class="mm-sronly"></span></a>
<a href="/medschool/about/test-basic-page">Test Basic Page</a>

so in the above <span class="mm-sronly">THIS NEED SOME DESCRIPTIVE HIDDEN TEXT</span>

repeating some aim "why it matters"
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.

can you please provide text within the link that describes the functionality and/or target of that link?

thanks!!

**Comment by FrDH** [comment]
The mm-sronly span should have text in in (that's the only reason it's added at all).
The [screenReader add-on](https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/screenreader/jquery.mmenu.screenreader.js) has a configuration object that tells the add-on what text to use for the anchors:
````js
$.mmenu.configuration.screenReader = {
	text: {
		closeMenu		: 'Close menu',
		closeSubmenu	: 'Close submenu',
		openSubmenu		: 'Open submenu',
		toggleSubmenu	: 'Toggle submenu'
	}
};````

Without an online example (as requested by the [contributing guidelines](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md)), I cannot tell you why the text appears to be empty.

**Comment by ffoodd** [comment]
Those texts aren't enough for accessibilty, they don't give any context to those anchors.

With some screen readers you may navigate using a list of links in the page: with those titles, you'd see some links identically entitled "Open submenu", which is not very helpful for user. You don't even know which submenu it'll open.

My PR get the span text content and inject it inside the mm-sronly span, e.g. "About Us". I think I should still improve this, getting back "Open submenu" and "Close submenu" (which I removed) to give a sufficient context.

Still working on it, but I hope it helps.

**Comment by FrDH** [comment]
The text should probably be: 
- Open menu
- Close submenu for {text from menu item}
- Open submenu for {text from menu item}
- Toggle submenu for {text from menu item}

But in the given HTML, there is no text at all, indicating an issue or error of some kind.

**Comment by marthasa** [comment]
i hadn't added any text - was assuming there would be some by default.  that being said the above solution would be absolutely great;  i agree that simply adding generic text would probably suffice but would lack meaningful context.

thanks!!

**Comment by marthasa** [comment]
i've added text, however it appears the text only appears on first level menus, not children; i cannot share our link as it's currently on an internal server while in development.  so i can only share output.  we have 4 top menus - here is an example of the output from our education menu

education
-   md program test  
  -   curriculum highlights 
  - class profiles
-   admissions - test
- test promo landing page
- md  profiles
- phd  admissions

< div class="mm-panel mm-hasnavbar mm-hidden" id="menu-tree-mlid-1884" aria-hidden="true">
< div class="mm-navbar">< a class="mm-btn mm-prev" href="#off-canvas-menu" data-target="#off-canvas-menu" aria-haspopup="true">**< span class="mm-sronly">Close submenu</span>**</a>< a class="mm-title" href="#off-canvas-menu">Education</a></div>
< ul class="sub-nav mm-listview">
< li class="first expanded menu-mlid-941">< a class="mm-next" href="#menu-tree-mlid-941" data-target="#menu-tree-mlid-941" aria-haspopup="true">< span class="mm-sronly"></span></a>< a href="/medschool/education/md-program-test">M.D. Program Test</a></li>
< li class="expanded menu-mlid-1465">< a class="mm-next" href="#menu-tree-mlid-1465" data-target="#menu-tree-mlid-1465" aria-haspopup="true">**< span class="mm-sronly"></span>**</a>< a href="/medschool/education/admissions-testing">Admissions - test</a></li>
< li class="leaf menu-mlid-1883">< a href="/medschool/education/test-promo-landing-page">Test Promo Landing Page</a></li>
< li class="expanded menu-mlid-2244">< a class="mm-next" href="#menu-tree-mlid-2244" data-target="#menu-tree-mlid-2244" aria-haspopup="true">**< span class="mm-sronly"></span>**</a>< a href="/medschool/education/md-profiles">M.D. Profiles</a></li>
< li class="last expanded menu-mlid-2449">< a class="mm-next" href="#menu-tree-mlid-2449" data-target="#menu-tree-mlid-2449" aria-haspopup="true">**< span class="mm-sronly"></span>**</a>< a href="/medschool/education/phd-admissions">Ph.D. Admissions</a></li>
</ul></div>


thanks!

**Comment by FrDH** [comment]
I'm not sure what you mean with 
> i've added text

These texts are added by default:
````js
$.mmenu.configuration.screenReader = {
    text: {
        closeMenu       : 'Close menu',
        closeSubmenu    : 'Close submenu',
        openSubmenu     : 'Open submenu',
        toggleSubmenu   : 'Toggle submenu'
    }
}
````
Please wrap you HTML in a code-block, I cannot read/debug plain text like that.

**Comment by FrDH** [comment]
Also, the screenReader add-on has been updated in the latest version (5.7.6), you might want to try and update the plugin and see if that makes any difference.

More updates on the screenReader add-on are still under construction.

**Comment by marthasa** [comment]
this is great - thanks!

the only remaining issue is in the keyboardnavigation- missing labels for input fields:
<input class="mm-tabstart" tabindex="0" type="text">
<input class="mm-tabend" tabindex="0" type="text">

locally i added an id for the above 2 input classes and a label pointing to the input:
				var $start = $('<label for="' + _c.tabstart + '" class="mm-sronly">Menu Start Tab</label><input id="' + _c.tabstart + '" class="' + _c.tabstart + '" tabindex="0" type="text" />'),
					$end   = $('<label for="' + _c.tabend + '" class="mm-sronly">Menu End Tab</label>Menu End Tab<input id="' + _c.tabend   + '" class="' + _c.tabend   + '" tabindex="0" type="text" />');

maybe not the best approach but it clears our last 2 errors.

again thanks!

**Comment by FrDH** [comment]
I'm not sure I understand why those input fields would need a label. The only reason they're their is to limit where to the user can tab.

**Comment by marthasa** [comment]
wave aim tool flags as an error :  (using screenreader and keyboardnavigation addons)
here's the documentation:
What It Means
A form control does not have a corresponding label.
Why It Matters
If a form control does not have a properly associated text label, the function or purpose of that form control may not be presented to screen reader users. Form labels also provide visible descriptions and larger clickable targets for form controls.
How to Fix It
If a text label for a form control is visible, use the <label> element to associate it with its respective form control. If there is no visible label, either provide an associated label, add a descriptive title attribute to the form control, or reference the label(s) using aria-labelledby. Labels are not required for image, submit, reset, button, or hidden form controls.

anyway to suppress the error i just added the label --- i don't know if styling the <input> with different aria classes would suppress the need for a label ....

this was just an fyi regarding webaim standards.

**Comment by FrDH** [comment]
I agree form controls should have a properly associated text label, but I don't think these input fields should be considered to be form controls. Their presence is purely functional.

As these input fields are not visible, adding a label to these input fields would only confuse the visitor. IMHO, I'd rathar get an error from the robot than confuse the human.

I'll investigate if there is an aira-attribute or something similar that makes the input fields be ignored.

Anyway, thanks for the heads-up.

**Comment by ffoodd** [comment]
Hi,

You might be searching for aria-hidden, or input type=hidden?

My two cents: I'd rather go with button type=button instead of input.

But I think this way to handle keyboard nav isn't easy. If focus is placed on those input, we shouldn't hide them since it might confuse user too. However if they are used to listen focus events and move the focus to the right element, then why not...

**Comment by FrDH** [comment]
`aria-hidden` will probably do the trick :) Thank you for the suggestion.

> However if they are used to listen focus events and move the focus to the right element, then why not...
That's correct, their precense is purely functional.

I agree `button[type="button"]` is probably better, will put this on the TODO list.
