### ISSUE TITLE
2 off-canvas menus and one with widescreen

### ISSUE THREAD

**Issue by Daltonmedia** [FrDH/jQuery.mmenu#645]
Hey,

I'm trying to have two menus, one site menu on the left, using the widescreen addon, so it's open on widescreens. And one usermenu on the right.

I don't know if this is a bug or just simple not possible in the plugin, but when the widescreen left menu is open on widescreens, it's impossible to toggle the right menu open.

on smaller screens, when the left menu is closed, it works again.

**Comment by FrDH** [comment]
I don't think that'll work. The widescreen css for the page will override the css for the second menu.
Ti's om the todo list to turn the widescreen extension into na add-on (with JS attached to it), that might bring a bit more flexibility to the widescreen options.
