### ISSUE TITLE
Configuration for Dropdown is ignored.

### ISSUE THREAD

**Issue by nrsimha** [FrDH/jQuery.mmenu#648]
Hello, I am trying to set max-width to dropdown to 150px.  But it seems my custom configuration for dropdown is ignored and menu's max-width is set to default 440px.

Here is code used:
```
$("#language-menu").mmenu({
    navbar: {
        title: "Select language"
    },
    dropdown: {
        drop: true,
        event: "hover",
        tip: true,
    },
    searchfield: true,
    autoheight: true
}, {
    dropdown: {
        width: {
            max: 150
        }
    }
});

```

Is it bug or I suppose to define configuration for max-width in different way?

**Comment by FrDH** [comment]
The config option tells the plugin what value the CSS uses, not the other way around.
Therefor (as the documentation states):
> Changing the value probalby requires changing some associated CSS.

**Comment by nrsimha** [comment]
But what does the settings do then? As following style with 440px instead of custom settings is added to the menu element:

```style="top: 95.875px; bottom: auto; max-height: 261.125px; right: calc(100% - 1117.27px); left: auto; max-width: 440px;"```

So it seems that value from custom settings is ignored.

**Comment by FrDH** [comment]
That's odd, I'd need an online example to do some debugging.

FYI:
The menu has a CSS max-width. CSS can not measure the position of the menu, so to prevent the menu from overflowing of the page, Javascript needs to do some measuring. To do that, it needs to know what the CSS value is.

**Comment by nrsimha** [comment]
Here is online example: http://mayapurmedia.com/mmenu/648.html

Although setting is to have max-width of 150px Javascript injects style with 440px.

**Comment by FrDH** [comment]
Ok, this is a bit embarrassing.
Seems like the configuration isn't used AT ALL. The add-on simply ignores everything you put in the config-object :/

Will fix this in the next version.

For now, you could override the global default value:
````js
$.mmenu.configuration.dropdown.width.max = 150;
$("#my-menu").mmenu({
   dropdown: true
});
````

Hope this helps.

**Comment by nrsimha** [comment]
Unfortunately that didn't help as I have more then one menu and they have different sizes.

So before new release I will use css:
```
#language-menu {
  max-width: 220px !important;
}
#view-switcher {
  max-width: 300px !important;
}
#settings-menu {
...
}
...
```

Thank you for mmenu, it is super.

**Comment by FrDH** [comment]
You could , re-override the defaults for each menu, I guess that should work:
````js
$.mmenu.configuration.dropdown.width.max = 150;
$("#menu-1").mmenu({
   dropdown: true
});

$.mmenu.configuration.dropdown.width.max = 440;
$("#menu-2").mmenu({
   dropdown: true
});

$.mmenu.configuration.dropdown.width.max = 900;
$("#menu-3").mmenu({
   dropdown: true
});
````

Using `!important` is probably bad because the plugin does some calculations to prevent the menu from overflowing the page.

**Comment by nrsimha** [comment]
I tried exactly that, but last one overwrites size `$.mmenu.configuration.dropdown.width.max = 900;` for all of them.

**Comment by FrDH** [comment]
Update: this issue will be fixed in the next version.
