### ISSUE TITLE
If your page contains two elements with position: fixed;, how to use the "fixedElements" add-on?

### ISSUE THREAD

**Issue by lzt7** [FrDH/jQuery.mmenu#649]
If your page contains two elements with position: fixed;, how to use the "fixedElements" add-on?

**Comment by lzt7** [comment]
`, {
                // configuration
                classNames: {
                    fixedElements: {
                        fixed: ["header","footer"],
                        //fixed: "header",
                    }
                }`
not working

**Comment by FrDH** [comment]
Well first, it should be a classname. `"header"` and `"footer"` are not classnames.
Second, it should be a string, not an array.

The best approach would be to add a single classname to the elements in the HTML. But if you do need to add multiple classnames, I guess this should work as well:
````js
{
   classNames: {
      fixedElements: {
         fixed: "class-1, .class-2"
      }
   }
}
````
This will eventually result in the JS:
````js
$page.find( ".class-1, .class-2" )
````

If you can not make any changes to the HTML, You can still add a classname using JS:
````js
$("header, footer").addClass( "Fixed" );
````

Hope this helps.
