### ISSUE TITLE
Scss Variable

### ISSUE THREAD

**Issue by jrean** [FrDH/jQuery.mmenu#652]
Hi,

I just updated a project with the very last version of the package and I find myself stuck customizing a scss variable! (the package and so the menu work perfectly)

```
app.scss >
@import "components/menu";

_menu.scss >
// <768px
.Menu:not(.mm-menu) {
    display: none;
}

.mm-divider {
    color: $light !important;
}

.mm-btn.mm-prev:before {
    border-color: $dark !important;
}

$mm_highlightedBackgroundColor: pink;
$mm_textColor: $dark;
$mm_fontSize: 16px;

.Menu--item.mm-selected {
    font-weight: bold;
}


@import "node_modules/jquery.mmenu/src/css/jquery.mmenu.oncanvas";
```

Don't understand why but when I run gulp the variable overriding is not taking into account!

Did I miss something?
It was perfectly working in the past version I used

Thank you for the help and for the amazing work.

**Comment by jrean** [comment]
I solved the first "issue" which was a question of order.

The last thing I don't understand is why do I need to import into my gulp file the following `.css`:

```
    // CSS Front final file
    mix.styles([
        'node_modules/jquery.mmenu/dist/css/jquery.mmenu.css',
        'resources/assets/builds/app.css',
    ], 'public/css/askjong.css', './');
```

When I do that it works.
If I try to use `scss` instead it doesn't. Any clue?

```
app.scss >
@import "components/menu";

_menu.scss >
// <768px
.Menu:not(.mm-menu) {
    display: none;
}

.mm-divider {
    color: $light !important;
}

.mm-btn.mm-prev:before {
    border-color: $dark !important;
}

$mm_highlightedBackgroundColor: pink;
$mm_textColor: $dark;
$mm_fontSize: 16px;

.Menu--item.mm-selected {
    font-weight: bold;
}


@import "node_modules/jquery.mmenu/src/css/jquery.mmenu.oncanvas";
```

I thought I could simply import the scss file.
Can you give me some light?

Cheers

**Comment by FrDH** [comment]
If you have a look at the gulpfile, you'll find jquery.mmenu.css is a combination of two css files:
````js
return gulp.src([
      outputDir + '/css/jquery.mmenu.oncanvas.css',
      outputDir + '/addons/offcanvas/jquery.mmenu.offcanvas.css'
   ])
   .pipe( concat( 'jquery.mmenu.css' ) )
   .pipe( gulp.dest( outputDir + '/css' ) );
````

Therefor, including only the oncanvas.scss file will not include the css needed for the off-canvas behavior.

This should work:
````css
$mm_highlightedBackgroundColor: pink;
$mm_textColor: $dark;
$mm_fontSize: 16px;

@import "node_modules/jquery.mmenu/src/css/jquery.mmenu.oncanvas";
@import "node_modules/jquery.mmenu/src/addons/offcanvas/jquery.mmenu.offcanvas";
````

Note:
Due to the lack of a ".all" scss file; If you're using any of the other add-ons or an extension, you should  include all of their scss files seporately.

**Comment by FrDH** [comment]
FYI, in the next release there'll be a better solution for customizing the CSS.
