### ISSUE TITLE
Content visible at all levels

### ISSUE THREAD

**Issue by CBeghin** [FrDH/jQuery.mmenu#653]
Hello !
First of all, thank you for your plugin, it's great.
I watched several times in the documentation and I believe there is no option to view content in all menu levels.

Let me explain, I'd displayed a box where users can connect / disconnect. I would like this box is independent of the menu (visible at all levels).

I wanted to know if it was possible or if you were going to add this functionality in the future?

Thank you in advance.

**Comment by FrDH** [comment]
Try using the [navbars add-on](http://mmenu.frebsite.nl/documentation/addons/navbars.html):
````js
$("#menu").mmenu({
   navbars: [{
      content: ['<a href="#connect">Connect</a>']
   }]
});
````
You can basically put any HTML in the `content` option, might need some additional CSS though :)
