### ISSUE TITLE
consider i18n?

### ISSUE THREAD

**Issue by ffoodd** [FrDH/jQuery.mmenu#654]
Some strings are kinda hardcoded, like in the screenReader add-on. 
It's already quite good that we're able to customize those with conf, but I wonder if it could be doable to internationalize those in order to handle multilingual sites.

Not really an issue but more than a feature request :)

**Comment by FrDH** [comment]
Yes, but unfortunately there's more than one solution out there to internationalize JS and I'm not going to support just one.

If I'm correct, there is no hardoced text in the plugin, it should all be manageble via the configuration object. You could use a server side script to override the defaults in this object like this:
````php
echo '
    <script src="path/to/mmenu.js"></script>
    <script>
        $.mmenu.configuration.screenReader.text.closeMenu : "' . i18n( 'Close the menu' ) . '";
    </script>';
````

**Comment by ffoodd** [comment]
You're right, I can do this :)

Thank you!

**Comment by FrDH** [comment]
Having given it a bit more thought, I do like the idea of simplyfied translations, somewhat of how jQuery UI does it where you can include a seporate js file with the translations.
