### ISSUE TITLE
mmenu - Gravity Form conflict

### ISSUE THREAD

**Issue by zim182** [FrDH/jQuery.mmenu#655]
Hello,

I have reported a conflict between mmenu wordpress plugin and Gravity form plugin.

If mmenu is enabled and in the form there is some conditional logic active, there is a conflict and the mmenu doesnt work and the form is not displayed.

Anyone else has reported the same issue?
How did you solve it?

Thank you for your help

Simone

**Comment by FrDH** [comment]
Does the Gravity form plugin add inline `<script>` tags? If so, this issue might be due to the mmenu plugin wrapping all content in a new `<div>`. 
See [this tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html) for more info on how to setup the HTML for the page.
