### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addons' of undefined - Navbars Add On

### ISSUE THREAD

**Issue by dryving** [FrDH/jQuery.mmenu#657]
Since updating to the most recent version, I'm getting this error in the console and the navbars add on is not working:

Uncaught TypeError: Cannot read property 'addons' of undefined

It worked fine before updating versions and works if I revert to a previous version. Is there some change in the implementation that I'm not seeing on the website?

The line throwing the error is:

`!function(n){var a="mmenu",t="navbars";n[a].addons[t]={setup:function(){var r=this,s=this.opts[t],o=this.conf[t];if(i=n[a].glbl,"undefined"!=typeof s){s instanceof Array||(s=[s]);var c={};if(s.length){n.each(s,function(i){var l=s[i];"boolean"==typeof l&&l&&(l={}),"object"!=typeof l&&(l={}),"undefined"==typeof l.content&&(l.content=["prev","title"]),l.content instanceof Array||(l.content=[l.content]),l=n.extend(!0,{},r.opts.navbar,l);var d=l.position,h=l.height;"number"!=typeof h&&(h=1),h=Math.min(4,Math.max(1,h)),"bottom"!=d&&(d="top"),c[d]||(c[d]=0),c[d]++;var f=n("<div />").addClass(e.navbar+" "+e.navbar+"-"+d+" "+e.navbar+"-"+d+"-"+c[d]+" "+e.navbar+"-size-"+h);c[d]+=h-1;for(var v=0,u=0,p=l.content.length;u<p;u++){var b=n[a].addons[t][l.content[u]]||!1;b?v+=b.call(r,f,l,o):(b=l.content[u],b instanceof n||(b=n(l.content[u])),f.append(b))}v+=Math.ceil(f.children().not("."+e.btn).length/h),v>1&&f.addClass(e.navbar+"-content-"+v),f.children("."+e.btn).length&&f.addClass(e.hasbtns),f.prependTo(r.$menu)});for(var l in c)r.$menu.addClass(e.hasnavbar+"-"+l+"-"+c[l])}}},add:function(){e=n[a]._c,r=n[a]._d,s=n[a]._e,e.add("close hasbtns")},clickAnchor:function(n,a){}},n[a].configuration[t]={breadcrumbSeparator:"/"},n[a].configuration.classNames[t]={};var e,r,s,i}(jQuery),`

The files are being enqueued in wordpress like this:

```
wp_enqueue_style( 'mmenucssaddlogo', get_stylesheet_directory_uri() . '/lib/inc/js/responsive-nav/jquery.mmenu.navbars.css','', '1', 'all' );
wp_enqueue_script( 'mmenujsnavbars', get_stylesheet_directory_uri() . '/lib/inc/js/responsive-nav/jquery.mmenu.navbars.min.js', array( 'jquery' ),'1',false);
```

The Navbar is being set like this ( it's pulled from a function and all the variables are correctly set and working with the older version of the plugin ) :

```
<script type="text/javascript">
jQuery(document).ready(function ($) {
      var $menu = $(".mobile-wrap").mmenu({
         // Options	 
   clone: true',
 "navbars": [
 		{
 			"position": "top",
 			"content": [
			"<div class=\'menu-logo\'><a href=\'' . $cleaned_home_url .'\'><img src=\'' . $logo_url . '\' style=\'width: 100%; max-width: ' . $logo_width . 'px; height: auto;\' alt=\'' . $description . '\' /></a></div>"
			],
 			"height": 2
 		}
 		]
});
   var API = $menu.data( "mmenu" );
      
      $("#mobile-menu-link").click(function() {
         API.open();
      });
});
</script>
```

**Comment by FrDH** [comment]
Sounds odd, I can't think of any reason for that error.
I checked and the current version seems to be working OK.

Is there an online example of the issue?

**Comment by dryving** [comment]
Found it. It was a conflict between this and another plugin. For some reason it didn't trigger on the old version of the mmenu plugin, but it did on the updated version.

**Comment by FrDH** [comment]
Still odd. 
`$.mmenu` should not be undefined, it has been defined since version 4.0.0

**Comment by dryving** [comment]
Well...I feel dumb. It wasn't a conflict, The navbars js file was getting loaded before the core mmenu js file.
