### ISSUE TITLE
lazySubmenus Bug

### ISSUE THREAD

**Issue by Webtransformer** [FrDH/jQuery.mmenu#658]
Hi, I think I found a bug if lazySubmenus (true) is used. With "false" it works.
I have a fixed menu on the top and targeting the panels directly.
If I am jump from #mm-4 to #mm-3 the panels arent loading correcty (see the screenshots).
This only happens if I am jumping backwards:
#mm-3 to #mm-2 , #mm-5 to #mm-4  etc..

<img src="http://www.webtransformer.de/images/mm1lazy.png"/>

**mm-opened mm-hidden**

<img src="http://www.webtransformer.de/images/mm2lazy.png"/>

**Comment by FrDH** [comment]
Hi, thank you for reporting this issue.

If I understand correct, you're opening the page with a sub(sub)menu opened by default?
I think that should work, but I'll have to check.

**Comment by Webtransformer** [comment]
Yes, by using:
mobileMenuAPI.open().openPanel($(navigationTarget));

It´s working without lazySubmenus.

**Comment by FrDH** [comment]
I'll investigate later on and see if it can be fixed.
Thanks for reporting the issue.

**Comment by FrDH** [comment]
Update: this should work in the next release.

**Comment by Webtransformer** [comment]
Thanks :-)
