### ISSUE TITLE
mobile scroll is locked after click menu item with turbolink 5 boosted

### ISSUE THREAD

**Issue by ksuntechnology** [FrDH/jQuery.mmenu#659]
Thanks for the great menu library! Everything is great except that while i integrated it with Rails 5 and turbolink 5! After menu item is clicked, turbolink can successfully switch page, but at the moment, the mobile scroll is locked, and I can click any link or select dropdown within the screen, but can not scroll.

And I have no idea why this can not be re-produced in Chrome with development console ( in Chrome, I can scroll anyway ), but after I deployed to a remote server and access it using my mobile Safari, the scroll is locked. ( I will create a sample application in Heroku later )

Here's how i do, please correct me if i am wrong!

I know there's a wrapper for turbolink, but that's for turbolink-classic, so I didn't required it at the moment, instead i add some code based on turbolink wrapper, and here's what it is in coffee script.

```
$(document).on 'turbolinks:before-visit', ->
  $('html').attr('class', '')
  $['mmenu'].glbl = false
  true

$(document).on 'turbolinks:load', ->
  $('#mobile-menu').mmenu
    extensions: ['theme-dark', 'pagedim-black']
```

**Comment by FrDH** [comment]
Have a look at the "turbolinks" framework wrapper:
https://github.com/FrDH/jQuery.mmenu/blob/master/src/wrappers/turbolinks/jquery.mmenu.turbolinks.js

Not sure if it still works as it has not been updated for quite some time, but still might point you to the right direction.

**Comment by simoniong** [comment]
Ooops, seems I accidentally using my robot account to create a issue, anyway, here's the repo i just create to demonstrate this issue.

`https://github.com/simoniong/mmenu_app`

and javascript require code is [here](https://github.com/simoniong/mmenu_app/blob/master/app/assets/javascripts/application.js)

and stylesheet require code is [here](https://github.com/simoniong/mmenu_app/blob/master/app/assets/stylesheets/application.scss)

and init mmenu code is right [here](https://github.com/simoniong/mmenu_app/blob/master/app/assets/javascripts/init.coffee)

for testing purpose, I already create a [heroku app](http://mmenu-app.herokuapp.com/),  noted that while you using your PC and chrome, it's totally fine, but while u are using your Safari browser in your iPhone, the bug will hit!

You can easily try to scroll it while loading this page, but after you click any menu item in the mmenu, mmenu will closed, then page will load successfully, but the view can not scroll anymore, you can still click on any link in the page.

**Comment by simoniong** [comment]
@FrDH  Thanks for your reply,  I notice that we have a wrapper for turbolink-classic, and I did some research on how to migrate that into` turbolinks 5`,  after translate that wrapper into a event binding to `turbolinks:before-visit` would be fairly enough for my case to  destory mmenu before every visit ( page load in Turbolink ), and re-init it again in `turbolinks:load`. I don't know if there's something setup globally, maybe in `scrollBugFix` add-on, and i didn't notice that to clear it.

**Comment by simoniong** [comment]
@FrDH  after some dig into the code for scrollBugFix, after remove some binding event, seems fixed.

here's the fix that i did: ( please refer [here](https://github.com/simoniong/mmenu_app/blob/fix_version/app/assets/javascripts/init.coffee) )
``` ruby
$(document).on 'turbolinks:before-visit', ->
  $('html').attr('class', '')
  # disable all binding form scrollBugFix add-on
  $.mmenu.glbl.$docu.off('touchmove')
  $.mmenu.glbl.$body.off('touchstart')
  $.mmenu.glbl.$body.off('touchmove')
  $.mmenu.glbl.$wndw.off('orientationchange')
  $['mmenu'].glbl = false
  true

$(document).on 'turbolinks:load', ->
  $('#mobile-menu').mmenu
    extensions: ['theme-dark', 'pagedim-black']
```

**Comment by FrDH** [comment]
Thank you for debugging the issue.
I'll have a look at it later on and will surely update the turbolinks wrapper to turbolinks 5

**Comment by metaskills** [comment]
FWIW, I found the following to work fine for me and we even use the scrollbugfix.

```javascript
/*
 * Turbolinks wrapper for jQuery mmenu
 * Include this file after including the jquery.mmenu plugin for default Turbolinks support.
 */


(function( $ ) {

	var _PLUGIN_ = 'mmenu';

	//	Vars
	var classnames, $html;

	//	Store the HTML classnames onDocumentReady
	$(document).on(
		'turbolinks:before-visit',
		function()
		{
			$html = $('html');
			classnames = $html.attr( 'class' );
		}
	);

	//	Reset the HTML classnames and reset the $.mmenu.glbl variable on page:change
	$(document).on(
		'turbolinks:load',
		function()
		{
			$html.attr( 'class', classnames );
			$[ _PLUGIN_ ].glbl = false;
		}
	);

})( jQuery );
```

We changed our menu JavaScript to use `'turbolinks:load'` event and everything works great.

**Comment by FrDH** [comment]
Update: this will be implemented in the next version.
