### ISSUE TITLE
Columns for specific breakpoint only

### ISSUE THREAD

**Issue by abombelli** [FrDH/jQuery.mmenu#660]
Hello

Is there a way to enable the columns add-on for higher breakpoints only?
On a smartphone we would like to disable them.

Thanks,
Aldo

**Comment by FrDH** [comment]
Because most (if not all) styling is done by CSS, I guess you could seporately include the css file for the columns add-on using a media-query.
````html
<link rel="stylesheet" href="path/to/jquery.mmenu.css" />
<link rel="stylesheet" href="path/to/jquery.mmenu.columns.css" media="screen and (min-width: 800px)" />
````
Note that you can not use the ".all" css file because this also includes the columns css, you'll have to include all needed css files seporately or manually concatenate them.

**Comment by abombelli** [comment]
So the columns behavior is set via CSS only?

**Comment by FrDH** [comment]
The JS only adds and removes classnames that are exclusively for the columns add-on.
So yeah, I think that would work.

**Comment by FrDH** [comment]
p.s. if you've purchased a license for commercial usage, you can create a custom build, concatenating only the extensions and add-ons you need:
http://mmenu.frebsite.nl/download-custom.html

**Comment by abombelli** [comment]
I tried to use a media-query. But the menu is not fullscreen anymore and the borders are back. Actually the two extensions ('fullscreen', 'border-offset') are ignored. Is the inclusion order important?

**Comment by FrDH** [comment]
Please provide an online example (as requested by the [contributing guidelines](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md)).
