### ISSUE TITLE
openPanel Target/ID

### ISSUE THREAD

**Issue by Webtransformer** [FrDH/jQuery.mmenu#662]
Hi :-)

I have a header navigation like this to open the Panels directly. This worked well:
<a data-navigation="#mm-2" title="XXX">XXX</a>

But suddenly the IDs have changed #mm-1 etc.  (I dont know why):
<img src="http://www.webtransformer.de/images/mmlink.png"/>

Is there a pattern how the IDs are created? Can I give my own IDs?
What is the best way to open the Open the Panel?

**Comment by FrDH** [comment]
The plugin adds a unique ID to elements (mm-x, where x is a numeric value that increments) on elements that need an ID, but do not yet have an ID.
In other words, you should be able to give an `UL` and the plugin should respect that ID and not change it.

**Comment by Webtransformer** [comment]
Thanks, it worked!
