### ISSUE TITLE
There is no wordpress menu location to select

### ISSUE THREAD

**Issue by dush88gs** [FrDH/jQuery.mmenu#667]
In wordpress menu, i can't see any menu location to select which is corresponding to mmenu.

**Comment by Maffyou** [comment]
I'm going to guess you're using a custom theme and haven't enabled theme menus in your theme's functions.php

https://codex.wordpress.org/Navigation_Menus

I'm using mmenu on a custom Wordpress theme. I found it easier to use the raw jQuery plugin version rather than the Wordpress plugin version.

**Comment by FrDH** [comment]
If your theme does not use any menu locations, or if the plugin somehow can't find any, you can still provide the needed selector manually, just click the (?) icon for more information.
Hope this helps.
