### ISSUE TITLE
Demo (onepage.html) has path errors out-of-the-box

### ISSUE THREAD

**Issue by Maffyou** [FrDH/jQuery.mmenu#668]
Hey,

The path ../dist/addons/dragopen/jquery.mmenu.dragopen.min.js doesn't exist in the zip I just downloaded.

However, the folder "drag" does exist in /addons/, and the file jquery.mmenu.drag.min.js also exists.

In the demo, I replaced all instances of "dragopen" with "drag". I've tested on a touchscreen chromebook and android, and dragopen only seems to work very intermittently. FYI - I'm not getting any console errors.

Thanks for your otherwise excellent work on this plugin.

Matt

**Comment by FrDH** [comment]
Thanks, I'll update the demo file shortly.
Just FYI, the "dragOpen" add-on was indead replaced with the "drag" add-on (as it is also capable of closing panels with a swipe gesture).
