### ISSUE TITLE
Options and configurations for specific breakpoints

### ISSUE THREAD

**Issue by 033MaX** [FrDH/jQuery.mmenu#669]
Hi MMenu team,

This is more a suggestion than an issue.

I would love to see an options / configurations system allowing us to create a different configurations for several breakpoints.

I messed around with the API, trying to manually set options in the instance then using the update method... but it doesn't work.

As an example, I could use on resolutions above 768px the dropdown version of the menu. For everything under 768px and above 540px, the normal version. And finally, for everything under 540px, the normal version with fullscreen enabled.

Keep me informed if this is something that you would consider.
Great work on the plugin.

Thanks in advance.

**Comment by FrDH** [comment]
Hi, 
Something like that is on the todo-list.
Untill then, updating options using the API is not supported.

**Comment by FrDH** [comment]
FYI: the next version will have a responsive option for extensions (and probably some options and add-ons too)

**Comment by 033MaX** [comment]
Ho ! Thank you for notifying me. Great work !
