### ISSUE TITLE
Initializing mmenu() causes backgroundVideo plugin to break

### ISSUE THREAD

**Issue by hiphigi** [FrDH/jQuery.mmenu#670]
Just curious if you have any idea what might be causing this before I jump into the code blindly myself.

Plugin that is broken as a result of mmenu():
https://github.com/linnett/backgroundVideo

If you do a test, you will see that running the first instance of backgroundVideo() does not break with mmenu, but any subsequent instances of backgroundVideo() appear only as black when mmenu() is initialized.

Can provide fiddle if necessary.

**Comment by FrDH** [comment]
Have you read the basic tutorial? I think the part about "the page" might help out:
http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html

**Comment by mardanlin** [comment]
Happens regardless if you wrap the HTML or not in my tests.

**Comment by FrDH** [comment]
W/o an online example there is not much more I can do for you.
