### ISSUE TITLE
Issue while using with AngularJS

### ISSUE THREAD

**Issue by HimanshuHD** [FrDH/jQuery.mmenu#672]
_**`TypeError: Object mm-effect-slide-menu mm-shadow-page mm-shadow-panels mm-pagedim-black has no method 'join'`**_

Trying to implement jQuery.mmenu in my hybrid mobile application based on Ionic and AngularJS frameworks, but getting some TypeError.

Is this a issue, or am I doing something worng ?

**Comment by FrDH** [comment]
Sounds like the menu is being initialized a second time using the already parsed options: The extension option starts off as an array that's joined into a string.
Have you tried the [Angular wrapper](http://mmenu.frebsite.nl/documentation/framework-wrappers.html)?

**Comment by HimanshuHD** [comment]
Not used the Wrapper. But I m trying to initialize menu on click event, so there no chance that menu is being initialized for second time.

**Comment by FrDH** [comment]
Have a look at the wrapper and what it does, you might get an idea of what needs to be done in addition to usage in plain ol' webpages.
