### ISSUE TITLE
how to auto size navbar

### ISSUE THREAD

**Issue by moyarich** [FrDH/jQuery.mmenu#677]
How do I auto size the main navbars so that they can contain all the content that I want to put into it.
The content is dynamic, so setting the size to 80px using the code below, sometimes makes the area too big and or too small.

~~~javascript
                navbars     : [
                    {
                        content :'#navm',
                        height:2
                    },
                ]
~~~

**Comment by FrDH** [comment]
I guess you could count the amount of elements inside `#navm` and calculate the desired height based on a maximum number of elements per line. Something like this:
````js
    navbars: [{
        content: '#navm',
        height: Math.ceil( $('#navm').children().length / 6 )
    }]
````
Where `6` is the maximum number of elements per line.
