### ISSUE TITLE
Add Variable in Pagedim Extension

### ISSUE THREAD

**Issue by slavanga** [FrDH/jQuery.mmenu#678]
Can we add a variable for the opacity value in the pagedim extension?

https://github.com/FrDH/jQuery.mmenu/blob/master/src/extensions/pagedim/jquery.mmenu.pagedim.scss#L20

**Comment by FrDH** [comment]
Good idea, marked this issue as "enhancement".

**Comment by FrDH** [comment]
`$mm_pagedimOpacity` will be added in the next release.
