### ISSUE TITLE
Bug on iPhone with fixed menu.

### ISSUE THREAD

**Issue by dunice-lyakhov** [FrDH/jQuery.mmenu#679]
First of all - Thanks for the great plug!

There's a bug on iPhone. I have the fixed menu. When I open it in the top of the page it looks fine, but if you scroll down below and open a menu this is displayed incorrectly. For Android all works fine.

![img_0301](https://cloud.githubusercontent.com/assets/16898296/22020575/15a88ee2-dcca-11e6-8bc6-94638d2f1db8.png)
![img_0302](https://cloud.githubusercontent.com/assets/16898296/22020577/15ace5a0-dcca-11e6-9869-f96945fd8721.png)
![img_0303](https://cloud.githubusercontent.com/assets/16898296/22020576/15ab80d4-dcca-11e6-9a5c-b6e3c3e0c28c.png)

**Comment by FrDH** [comment]
Hi, 
That sounds odd. Can you also see this issue on mmenu.frebsite.nl?
If not, is there an online example I could have a look at?

**Comment by dunice-lyakhov** [comment]
Hi,

I haven't found a solution to this problem there. Yes, of course. http://dev.africa.krugerpark.com/

Thank you.

**Comment by FrDH** [comment]
It seems like the browser is some how resizing or zooming in. I had a look at the viewport meta but that looks OK, it should prevent the browser from doing such things.
I guess you could try and disable all other scripts (I'd start with the zopim chat) and see if that makes any difference.

**Comment by FrDH** [comment]
Had any luck with debugging the issue?

**Comment by NikitaLyahov** [comment]
Hi. Unfortunately no.

**Comment by dunice-lyakhov** [comment]
Hi. Unfortunately no.
