### ISSUE TITLE
Can't add any other content without the menu breaking

### ISSUE THREAD

**Issue by atlas24** [FrDH/jQuery.mmenu#680]
I have the plugin added here

$('#nav').mmenu({
    offCanvas: { position: 'left' },
    {% if settings.search_enabled %}
      searchfield : {
        add: true,
        search: true,
        noResults: '<a href="/search?q=" class="search_link">' + {{ 'general.search.advanced_search_html' | t | json }} + '</a>'
      },
    {% endif %}
   classes: "mm-{{ settings.mobile_menu_color }}"
  });

  $('.search_link').on("click", function(){
    $(this).attr("href", $(this).attr("href") + $(".mm-search input").val());  
  })

and here is my html

        <div id="nav">
          
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About us</a>
               <ul>
                  <li><a href="/about/history">History</a></li>
                  <li><a href="/about/team">The team</a></li>
                  <li><a href="/about/address">Our address</a></li>
               </ul>
            </li>
            <li><a href="/contact">Contact</a></li>
         </ul>
          </div>

Whenever I add anything to the html the entire menu disappears, I believe partly due to the classes changing.

<ul class="mm-panel mm-opened mm-current" id="mm-0">
/*this is when adding another ul menu with li elements*/

<ul class="mm-panel mm-hidden" id="mm-1">

/*normal menu is in here when that other menu is added*/

<ul class="mm-list mm-panel mm-opened mm-current" id="mm-0">
/*this is the original by itself with nothing added that works*/

website is www.aptoapparel.com

edit: this is my first time using github and my post is screwed up have no idea why it came out like that

**Comment by FrDH** [comment]
Where are yo adding the HTML? Not inside `<div #nav>` I hope?
Have a look at the [off-canvas tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/) for more info on how to set up the HTML for you menu and page.

**Comment by atlas24** [comment]
The html is added in my theme.liquid page and it works fine, until I try to add anything else inside of the div besides the ul menu. All I'm trying to do is add a div after the menu, but everything breaks.

**Comment by FrDH** [comment]
> Where are yo adding the HTML?  Not inside <div #nav> I hope?
