### ISSUE TITLE
pageSelector ignored

### ISSUE THREAD

**Issue by ohadbp** [FrDH/jQuery.mmenu#681]
Hey Guys,

I have the following html:

```
<body` id='main-mobile'>
   <div id="main-page">
      // Content goes here
   </div>
   <div id="extra-code">
   </div>
   <nav id="my-menu>
   </nav>
</body>

JS:
 $(#my-menu).mmenu({
        extensions: ["border-none", "theme-white", "fullscreen", "pagedim-black"],
        isMenu: false,
        navbar: {
            add: false
        },
        offCanvas: {
            zposition: "front",
            position: "bottom",
            pageSelector: "main-page"
        },
        onClick: {
            close: false
        }
    });
```

My goal was that the mm-page will wrap only the main-page div and be in same level as extra-code but the pageSelector is ignored and mm-page wrap both divs.

What am i missing?

Thanks.

**Comment by FrDH** [comment]
The `pageSelector` option is a [configuration setting](http://mmenu.frebsite.nl/documentation/options/configuration.html), not an [option](http://mmenu.frebsite.nl/documentation/options/).

**Comment by ohadbp** [comment]
damn, that was stupid of me... thanks!
