### ISSUE TITLE
Place open menu in DIV

### ISSUE THREAD

**Issue by abombelli** [FrDH/jQuery.mmenu#683]
Hello

Is it possible to have a menu placed in a specific DIV.
We would like to create  a sidebar who is always visible with the menu in it.

Thanks
Aldo

**Comment by FrDH** [comment]
you could set the [offCanvas option[(http://mmenu.frebsite.nl/documentation/addons/off-canvas.html) to false. More info [here](http://mmenu.frebsite.nl/on-and-off-canvas.html).

Or, try the [widescreen extension](http://mmenu.frebsite.nl/documentation/extensions/widescreen.html).

Hope this helps.

**Comment by abombelli** [comment]
Thanks a lot! Setting offCanvas to false did the trick.
On more thing. I'm using the autoheight addon, but the menu still expands to the fill height of the container where it is placed in. Any idea?

**Comment by FrDH** [comment]
The autoHeight add-on is intended for usage in an off-canvas menu only (check [the docs](http://mmenu.frebsite.nl/documentation/addons/auto-height.html) and you'll see the off-canvas add-on as a dependency).

I guess it could work for an on-canvas menu as well, I'll see if I can make that work in the next version.

**Comment by abombelli** [comment]
Thanks! Just realised it a bit later.
Is there any direction you could point to, to get a quick solution for autoHeight in an on-canvas context?

**Comment by FrDH** [comment]
For starters, you should remove the check for off-canvas usage:
https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/autoheight/jquery.mmenu.autoheight.js?r=19#L19

Next, remove the check if the menu is opened:
https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/autoheight/jquery.mmenu.autoheight.js?r=19#L62

Run Gulp in the command line to generate the distribution files.

**Comment by FrDH** [comment]
I just realized; if your menu is only a top-level menu (no submenus), you could just add some CSS to make it work. I did the same thing on the documentation pages: http://mmenu.frebsite.nl/documentation/addons/ (the options next to the example)

**Comment by FrDH** [comment]
Update: The autoHeight add-on will work for on-canvas menus in the next version.
