### ISSUE TITLE
bug with "selected" option

### ISSUE THREAD

**Issue by eclipzzze** [FrDH/jQuery.mmenu#684]
If you use selected on some lower level as this example the top option which is "back to higher level" in this case "Our address" does not work the menu freezes on that stage
![capture](https://cloud.githubusercontent.com/assets/20784959/22393835/1bfd6dfc-e518-11e6-8e4e-aa41c177a8da.PNG)

```
<nav id="my-menu">
   <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/about/">About us</a>
         <ul>
            <li><a href="/about/history/">History</a></li>
            <li><a href="/about/team/">The team</a></li>
            <li class="selected"><a href="/about/address/">Our address</a>
                  <ul>
	            <li><a href="/about/history/">a</a></li>
	            <li><a href="/about/team/">b</a></li>
	            <li><a href="/about/address/">c</a></li>
	         </ul>
            </li>
         </ul>
      </li>
      <li><a href="/contact/">Contact</a></li>
   </ul>
</nav>
```

**Comment by FrDH** [comment]
What version of the plugin are you using? I have never noticed this issue before in any of the releases.
Is there an online example of the issue I could have a look at?

**Comment by eclipzzze** [comment]
I'm using the current version downloaded 4 days ago. If you use the published code you can replicate the problem. Currently I don't have it online because it brakes the site navigation.

**Comment by FrDH** [comment]
Could you create an online example? I could not recreate the issue.

**Comment by eclipzzze** [comment]
Hi,

here is how to replicate the bug:
1. Go to: https://www.book.store.bg/mmbug.html
2. Shrink the window width to under 700 px to see the mobile version.
3. Click on top left icon for the menu
4. Click on the row with 29 subrows. I'm explaining it this way because I suppose that the language and the alphabet will be strange to you;)
5. Try to go back using the upmost option on the menu - it doesn't work.
6. The "selected" option is "Web design" - to my undertanding the menu should start opened to the level with the "selected" option and it doesn't.

**Comment by FrDH** [comment]
This is a weird issue, the link for the 29 subrows points to "#mm-2", but clicking it opens "#mm-5" without a proper animation.
My guess is there is an issue with the "lazySubmenus" add-on. It's improved in the next release, for now I'd suggest not to use it :/

Let me know if that fixes the issue.

**Comment by eclipzzze** [comment]
Yes, that fixes the issue.
