### ISSUE TITLE
Slider menu flicker in chrome

### ISSUE THREAD

**Issue by shamaaqua** [FrDH/jQuery.mmenu#685]
I am using this setting for display of menu:

      $("nav#menu").mmenu({

                 //offCanvas: false
                 
                extensions: ["pagedim-black"],
                offCanvas: {
               position  : "left",
               zposition : "front",
               transitionDuration:500,
               }

             });

Menu is flickering in chrome web browser. It is fine in all other browsers.

I am using the below downloaded files from http://mmenu.frebsite.nl/

jquery.mmenu.all.min.js

jquery.mmenu.all.css

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
I couldn't recreate any flickering in Chrome with the demo-files.
