### ISSUE TITLE
HTML 5 History API - Supported?  Advice?

### ISSUE THREAD

**Issue by villanus** [FrDH/jQuery.mmenu#687]
Is there a right approach to use HTML History api to dynamically load page content (similar to pjax method) , but also change the page url for refresh, and bookmarking?

I am trying to use this for an e-commerce shop and want to filter products as user drills down. 
Example:
Electronics --- Page = Show Everything
Electronics > Computers = Page shows only computers
Electronics > Computers > Apple = Page shows only apple products.  

I am guessing there needs to be an event for the current menu item?
What is the best approach for this use case. 

Thanks

**Comment by FrDH** [comment]
I'm not sure I understand the question, but you can use the API to open and close submenus and make list items appear as "selected":
http://mmenu.frebsite.nl/documentation/api.html

**Comment by villanus** [comment]
I dont want to change the menu.
I want to do an ajax call to change the page content, and url.  

Use it for a single page application without refeesh

**Comment by FrDH** [comment]
You can do ajax requests, but how is that related to the menu?

**Comment by villanus** [comment]
Is there an event that is triggered when each menu item is clicked?

Maybe I can listen for it and then do 2 things:
1. update url using html 5 history api
2. ajax request to change page content (not menu)

This will allow me to use the menu without page reload.  🙂

**Comment by FrDH** [comment]
I guess the best approach would be to specify a function for the [onClick.preventDefault](https://github.com/FrDH/jQuery.mmenu/blob/master/src/js/jquery.mmenu.oncanvas.js#L653) option. This function will be invoked every time an anchor in a listview is clicked.
It should return `true` if you want to prevent the default behavior ("default behavior" would be opening the page, doing an AJAX request is not default behavior).

Something like this:
````js
$("#my-menu").mmenu({
   onClick: {
      preventDefault: function()
      {
         if ( $(this).hasClass( "my-ajax-anchor" ) )
         {
            $.ajax( $(this).attr( "href" ), {
            });
            return true;
         }
      }
   }
});
````
