### ISSUE TITLE
API documentation lack.

### ISSUE THREAD

**Issue by YozhEzhi** [FrDH/jQuery.mmenu#688]
Hi! I've found in issues that we able to use this API methods:
```
const API = $menu.data('mmenu');
API.bind('closing', () => console.log('closing'));
API.bind('opening', () => console.log('opening'));
```

But I can't find them in documentation.
I've tried `closeAllPanels` & `closePanel` - but they doesn't work for me.

I'm using `jQuery mmenu v5.7.8`.
My mmenu config:
```
const $menu = $('#mobile-menu').mmenu({
  navbar: {
    title: 'Меню',
  },
}, {
  offCanvas: {
   pageSelector: '#desktop-wrapper',
  },
});
```

**Comment by FrDH** [comment]
The API documentation: http://mmenu.frebsite.nl/documentation/api.html

You should be able to invoke the methods like this:
````js
var API = $menu.data( "mmenu" );
API.closePanel( $("#my-panel") );
API.closeAllPanels();
````

Note that `closePanel` only works for vertical submenu's. To close a sliding submenu, you need to "open" it's parent.

**Comment by YozhEzhi** [comment]
@FrDH Sorry, but I don't want to trigger `close` method. I need to handle `open`\`close` events.
```
API.bind('closing', myCallbackFunction);
```

**Comment by FrDH** [comment]
Assuming `myCallbackFunction` is a function, that should work. If it doesn't, please provide an online example.

**Comment by YozhEzhi** [comment]
Yeah. That code works perfectly.
By opening this issue - I meant that I've didn't found `API.bind('closing', myCallback);` in lib documentation.
I've found `API.bind('closing', myCallback);` by issues research in this repo :)

So, there are 2 possible variants:
- Documentation **not** describes API events;
- Documentation **describes** API events, but I **can't** to find it;

**Comment by FrDH** [comment]
I agree the documentation for the API is a bit minimal, it'll be updated for the next release.

On the API page:
> If you're looking for methods for an add-on, check the add-ons pages.

... in the "bind new functions" section:
> The method to bind the function to.
Possible values: "closeAllPanels", "closePanel", closingPanel, closedPanel, "initPanels", "openPanel", openingPanel, openedPanel, "setSelected", "update"

... and on the off-canvas add-on page:
> Possible values for the method argument in the bind method:
"close", "closed", "closing", "open", "opened", "opening", "setPage".

**Comment by YozhEzhi** [comment]
Wah! Now I see. Thanks!
