### ISSUE TITLE
Instantclick + mmenu

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#694]
Hi,
I can't make work mmenu with instantclick,
and tutorial for turbolinks (similar to instantclick.io) seem broken, http://mmenu.frebsite.nl/tutorials/frameworks/turbolinks.html

instantclick have event "change" as explained here: http://instantclick.io/scripts

but when I wrap mmenu inside on change event then work only for first page load

InstantClick.on('change', function() {
// mmenu code
});

Any idea?

Thanks!

**Comment by kamov** [comment]
I was able to make it work checking plugin for turbolinks and this issue https://github.com/FrDH/jQuery.mmenu/issues/41

Work fine the open of menu, but not submenu, I can see this error in console:

`TypeError: o is undefined`

My code is below:

```js

var loadMmenu = function() {
    var $html = $('html');

    // reset any existing instance
    $html.removeAttr( 'class' );
    $.mmenu.glbl = false;

    if ($.fn.mmenu) {

        var API = $('#menu')
            .mmenu({
                extensions: [ 'widescreen', 'theme-white', 'effect-menu-slide', 'pagedim-black' ],
                counters: true,
                dividers: {
                    fixed: true
                },
                navbar: {
                    title: 'Navigation'
                },
                navbars: [{
                    position: 'top',
                    content : ['searchfield']
                }, {
                    position: 'top'
                }, {
                    position: 'bottom',
                    content : ['Footer']
                }
                ],
                searchfield: {
                    resultsPanel: true
                },
                setSelected: {
                    parent: true
                }
            }, {
                searchfield: {
                    clear : true
                }
            })
            .data( 'mmenu' );

        var $openMenu = $('#open-menu')
            .on('click',
                function(e) {
                    e.preventDefault();
                    if ( $html.hasClass('mm-opened')) {
                        API.close();
                    } else {
                        API.open();
                    }
                }
            )
            .children( '.hamburger' );

        API.bind( 'closed', function() {
            setTimeout(function() {
                $openMenu.removeClass( 'is-active' );
            }, 100);
        });
        API.bind( 'opened', function() {
            setTimeout(function() {
                $openMenu.addClass( 'is-active' );
            }, 100);
        });
    }
};

InstantClick.on('change', function() {
   loadMmenu();
});

```

Any idea?

Thanks!

**Comment by kamov** [comment]
I found a workaround but I don't think that will be cover all case.
Adding a timeout before reload menu work fine, example:



```js
InstantClick.on('change', function(isInitialLoad) {
    if(! isInitialLoad) {
        $('html').removeAttr( 'class' );
        $.mmenu.glbl = false;

         // Reload after timout
        setTimeout(function(){
            initMmenu();
        }, 250);

    } else {
        initMmenu();
    }
});
```

Seem that page menu is reload before page is loaded. But then I guess that when page take time to load menu will fail.

**Comment by kamov** [comment]
Back button of browser make stop work the menu again :(

**Comment by FrDH** [comment]
Adding a timeout sounds odd, but I'd stick with it if it works.
Normally, using the browser back button would not need to re-do any JS as it returns to the page how it was before leaving it. You could add some `console.log()`s to see what's happening when pressing the browser back button. Might give you some insight.

The Turbolinks wrapper will be updated in the next release to work with the latest version of Turbolinks and I'll put an Instantclick wrapper on the TODO list.

**Comment by kamov** [comment]
DId you have chance to make the instantclick wrapper?
