### ISSUE TITLE
JQuery mmenus can normal dispaly

### ISSUE THREAD

**Issue by tytom2003** [FrDH/jQuery.mmenu#695]
I added JQuery mmenu's menus to my web assignment . The web is abnormal. I click a link to other page at jquery mmenu. The web content will display at jquery menu. then, i found delete "". The jquery mmenu is normal. But all form is no jquery mobile effect.

How to solve the problem?

Below is my website:
http://tytom2003.byethost5.com/final3/l.php

Thank you very much.

**Comment by FrDH** [comment]
Please try including the jQuery mobile framework wrapper, it should fix issues between the jQuery mobile framework and the mmenu plugin:
http://mmenu.frebsite.nl/documentation/framework-wrappers.html
