### ISSUE TITLE
Open the menu on slide gesture

### ISSUE THREAD

**Issue by miten5** [FrDH/jQuery.mmenu#697]
I wanted to know that is there any way to open the menu with a gesture like "swipe left" or "swipe right"? The tutorial accompanying to the library has the example to open the menu on a "click".
Please reply.

Thanks

**Comment by FrDH** [comment]
Try the [drag](http://mmenu.frebsite.nl/documentation/addons/drag.html) add-on, it enables opening the menu with a dragging gesture.

**Comment by miten5** [comment]
But, where I can find this two file..

<script src="path/to/jquery.mmenu.dragopen.min.js" type="text/javascript"></script>
<link href="path/to/jquery.mmenu.dragopen.css" type="text/css" rel="stylesheet" />

If you have working Example of this drag add-on  then please provide me a link.

Thanks

**Comment by miten5** [comment]
Hey @FrDH can you please help me to solving this problem..??

**Comment by FrDH** [comment]
> After you've downloaded the latest version, you'll find there are a lot of files in the download pack. The .js and .css files you need for distribution are located in the "dist" folder. The original non-minified .js and .scss files are located in the "src" folder.
