### ISSUE TITLE
Fixed element

### ISSUE THREAD

**Issue by stacybirdy** [FrDH/jQuery.mmenu#698]
When using the fixed add on, the element to which I add the "Fixed" class is being pushed down to the end of the content. From its new incorrect location, if the menu button is pressed, it still disappears/does not remain fixed. Any idea what could be causing this? I also noticed that whichever element has the "Fixed" class no longer shows up in the dom, is that correct behavior?

**Comment by FrDH** [comment]
The fixed elements add-on moves elements with `class="Fixed"` from the "page" and inserts them in the DOM after the "page". 

[This CSS spec](http://stackoverflow.com/questions/31071046/fixed-element-in-transform-translate-container-not-working) is the only reason this workaround is needed.

So basically this:
````html
<body>
   <div id="page">
      <div id="header" class="Fixed">
         ...
      </div>
      <nav id="menu">
         ...
      </nav>
      ...
   </div>
</body>
````
Will result in:
````html
<body>
   <nav id="menu" class="mm-menu">
      ...
   </nav>
   <div id="page" class="mm-slideout">
      ...
   </div>
   <div id="header" class="mm-slideout">
      ...
   </div>
</body>
````

Due to the elements being moved, you might need to make some adjustments to your CSS. For example, the below CSS would no longer apply to the header:
````css
#page #header {
  position: fixed
}
````

**Comment by stacybirdy** [comment]
But if position: fixed is removed and replaced with something such as absolute with top: 0, though the element will move back to the top of the screen it wont stay **fixed** there..... so is the answer that you _can't_ truly use mmenu with fixed elements? What am I missing, do you have a working example of this? I can't seem to find one on the demo site.

**Comment by FrDH** [comment]
For a working example: The hamburger-icon on mmenu.frebsite.nl is a fixed element.

This comment explains best why fixed positioned elements are an issue:
http://stackoverflow.com/a/15256339/2613616

Basically, fixed positioned elements will be fixed to their first ancestor element with a `transform` CSS value. There is no way around this except for actually moving the element outside the ancestor.

This is all the fixed elements add-on does, it does not actually add `position: fixed` to the elements. You'll need to do that yourself (not that the classname "Fixed" will be removed from the element).

If you need to toggle an element between `position: fixed` and `position: absolute`, I'd suggest you create a clone from the fixed element which you give `position: absolute` and just show and hide the two.
For example this:
````css
#elem {
   position: absolute;
}
body.scrolled #elem {
   position: fixed;
}
````
Could be rewritten to:
#elem {
   position: absolute;
}
#elem-clone {
   position: fixed;
   display: none;
}
body.scrolled #elem {
   display: none;
}
body.scrolled #elem-clone {
   display: block;
}
````

Hope this helps.

**Comment by stacybirdy** [comment]
Well I feel silly for not noticing it was used on the actual site! I was able to look there and notice my problem was simply that I forgot to include positioning coordinates (left: 0; top: 0;). It went there automatically when it was the first element loaded, but needed them once moved via the script.
Nevertheless your detailed explanation was **very** much appreciated, I hate not thoroughly understanding why things function as they do.
Thanks!
