### ISSUE TITLE
Bootstrap modals issue

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#699]
I have issue with modals box of bootstrap.
My page structure is something like this:

```html
<div id="page">
<!-- content -->
</div>

<div id="footer">
<!-- footer -->
</div>

<nav id="menu">
<!-- mmenu -->
</nav>

<div id="modals">
<!-- different hiddens bootstrap modals -->
</div>
```

Mmenu move div#modals inside:

```html
<div id="mm-0" class="mm-page mm-slideout">
<div id="page">
<!-- content -->
</div>
<div id="modals">
<!-- different hiddens bootstrap modals -->
</div>
</div>
```

The result is that bootstrap `<div class="modal-backdrop fade show">` overlap also modal window, since is not moved by mmenu.

The strange thing is that footer remain where is, I mean is not wrapped inside div#mm-0, not sure why, is positioned absolute on bottom, like this sticky footer example of bootstrap https://v4-alpha.getbootstrap.com/examples/sticky-footer/

I guess how to avoid that mmenu wrap div#modals.

Thanks!

**Comment by FrDH** [comment]
Have you read [the basic tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/)?
Especially the page about [how to set up the page](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html) might explain why the plugin needs to wrap your DIVs and how you can (and why you should) prevent it from doing so.

**Comment by kamov** [comment]
Thanks, that helped me.
