### ISSUE TITLE
Toggle extension not working when using searchfield extension

### ISSUE THREAD

**Issue by jovanovskimiki** [FrDH/jQuery.mmenu#701]
Hi all,

I'm using the toggle extension with mmenu. The toggle checkbox (on - off) works ok with the initial elements of mmenu. But when you search for some element in the mmenu (using searchfield extension), the toggle checkboxes in the found results do not work (clicking on / off does not do nothing)
![untitled](https://cloud.githubusercontent.com/assets/26253771/23662819/ffa25e40-0350-11e7-919e-20a65650377f.png)

I think is connected with bind event for "toggles" of the search results, because those elements are dynamically added to results panel when searching.

Regards,
Miki Jovanovski

**Comment by FrDH** [comment]
The searchresults-panel clones the list items (and all its content), this results in two <input>s with the same ID. Therefor, if you click the label, only the first input is toggled.

For example, clicking either of the two labels will toggle only the first checkbox.
````html
<ul>
    <li><input id="a" type="checkbox"><label for="a"></label></li>
    <li><input id="a" type="checkbox"><label for="a"></label></li>
</ul>
````

For now, I guess the only solution would be to not use the resultspanel for showing the searchresults.

**Comment by FrDH** [comment]
Toggles and Checks are removed from the searchfield resultspanel in version 6.1.
