### ISSUE TITLE
Android 4.1 native browser support 

### ISSUE THREAD

**Issue by art-zhitnik** [FrDH/jQuery.mmenu#702]
Using very cool mmenu in one of our projects. Everything looks good except some older devices, in particular ones with Android 4.1 native browser on board. I can't formulate what a mess we get here in a couple of words. In one case looks like there are transparent menu covers all the page, in the other case menu is visible but [looking that way](http://shot.qip.ru/00SMnh-1soytzCq5/). Does mmenu support android 4.1 native browser?

**Comment by FrDH** [comment]
I think 4.1 should work. Native android browser on Android 2.4 has issues with fixed elements, but that's about it. How do the examples from the documentation website look on Android 4.1 native browser?
mmenu.frebsite.nl/demo/index.html?demo=menu-behavior-1&menu=default

**Comment by art-zhitnik** [comment]
The demo faces the same [problems with rendering](http://shot.qip.ru/00SMFS-6ZCpdk52P/).

**Comment by art-zhitnik** [comment]
The problem with invisible menues was due to the form elemets in one of menues. Now it's okey, with more simple layout, without forms.
The rendering issue maybe combination android studio, ubuntu desktop and hardware.
