### ISSUE TITLE
Change the mmenu options during runtime

### ISSUE THREAD

**Issue by ianzro** [FrDH/jQuery.mmenu#703]
Is there a way to change the current mmenu object that I am using during runtime?

**Comment by FrDH** [comment]
Technically yes, but it probably won't have much effect because most options are processed during the initialisation.
What are  you trying to achieve?

**Comment by ianzro** [comment]
I was trying to change the offCanvas value of position to top from bottom (something like that). . . without re initializing the whole mmenu panel.. or is the only way is to re-initialize the whole object?

**Comment by FrDH** [comment]
I don't think that's possible by default. 
Basically what you would need to do, is change the classes "mm-top" to "mm-bottom" on the menu and the <html>.
These classes are added to the menu after initialisation, changing that won't be much of a problem:
````js
$("#menu").mmenu();

$("button").click(function() {
   $("#menu").removeClass( "mm-top" ).addClass( "mm-bottom" );
});
````
The biggest problem would be to change the classes on the <html>, there are added on the fly before opening the menu and removed after it closed. Maybe you could use [the API](http://mmenu.frebsite.nl/documentation/api.html) to hook into the "open" methods:
````js
var API = $("#menu").data( "mmenu" );
API.bind( "open", function() {
   if ( _button_was_clicked_ )
   {
      $("html").removeClass( "mm-top" ).addClass( "mm-bottom" );
   }
});
````

Hope this helps.

**Comment by ianzro** [comment]
It works fine now.. thanks alot for the suggestion (y)!
