### ISSUE TITLE
Wordpress plugin has outdated JS code, causing error on Safari 10.0.1

### ISSUE THREAD

**Issue by icestormz164** [FrDH/jQuery.mmenu#704]
i was getting this error on safari for the wordpress mmenu, the wordpress plugin is outdated it is running version 5.7.4 JS code, and the current jQUery version has 5.7.8

the error i am getting is 

Error: Syntax error, unrecognized expression: .mm-vert

please update wordpress plugin with new JS code

**Comment by icestormz164** [comment]
what can i provide to help you diagnose this problem

**Comment by icestormz164** [comment]
found a work around

in the plugin/js folder open the mmenu.js

and find 

`var c = this.__findAddBack(n, "." + i.listview).children("." + i.selected).removeClass(i.selected).last().addClass(i.selected);`

which is located on line 173 and replace it with this
```

                i.vertical = 'mm-vert';
                var c = this.__findAddBack(n, "." + i.listview).children("." + i.selected).removeClass(i.selected).last().addClass(i.selected);
```

**Comment by FrDH** [comment]
That's odd, "mm-vert" isn't a used classname, it should be "mm-vertical". I guess the minifier might have messed up...
Anyway, The WP plugin will be updated soon. I you've downloaded it using a license key, you should be able to automatically update in the admin panel (/wp-admin).

**Comment by icestormz164** [comment]
ok thank you for the reply looking forward to the updated version
