### ISSUE TITLE
Add media query for widescreen inside scss with variable

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#705]
At the moment you need to include media query on link tag for widescreen extension, example:

`<link type="text/css" href="jquery.mmenu.widescreen.css" media="all and (min-width: 900px)"/>`

But since I have all assets minified inside one vendor.css file, I need to include this into separated file.

Would be good to include media query inside widescreen file, and add a variable, example:

```sass
$mm_ws_menuWidth: 30% !default;
$breakpoint: 900px;

    @media (min-width: $breakpoint) {
		CSS styles of widescreen......
    }
```

**Comment by kamov** [comment]
I solved in this way:

```sass
$breakpointWidescreen: 1430px !default;
$mm_ws_menuWidth: 20% !default;
@media (min-width: $breakpointWidescreen) {
  @import "../../vendor/jQuery.mmenu/src/extensions/widescreen/jquery.mmenu.widescreen";
}
```

but I think that if you add inside sass file it's even more quick

**Comment by FrDH** [comment]
In the next release, it'll be possible to (de)activate extensions based on a media query. So that would solve this issue.

**Comment by FrDH** [comment]
Check [the extensions documentation](http://mmenu.frebsite.nl/documentation/extensions/), the latest version supports (de)activating extensions when (un)matching a media query.
