### ISSUE TITLE
Bug - Safari mmenu home page overflow-x scroll

### ISSUE THREAD

**Issue by Quentame** [FrDH/jQuery.mmenu#707]
Hi !

### Test case
I've notices a Safari 9 (+) bug on you website homepage.
It is possible to scroll vertically because of non hidden content (images in that case).

### Screenshot
<img width="1440" alt="capture d ecran 2017-03-15 a 00 09 15" src="https://cloud.githubusercontent.com/assets/14821482/23926403/5b2e02a0-0914-11e7-93bd-9d2b46d763ee.png">

So it makes : 
<img width="1440" alt="capture d ecran 2017-03-15 a 00 09 07" src="https://cloud.githubusercontent.com/assets/14821482/23926414/6af71708-0914-11e7-96ef-0838b2fc11cd.png">

## Solution
Add : 
```css
/* layout.css:1268 */
body.home #page {
    overflow-x: hidden;
}
```

Result, it isn't possible to x scroll anymore : 
<img width="1440" alt="capture d ecran 2017-03-15 a 00 09 24" src="https://cloud.githubusercontent.com/assets/14821482/23926533/03316a50-0915-11e7-97fc-defd3a50bbe9.png">

Would like to contribute, but no git for the website 😉 

See you soon !

**Comment by Quentame** [comment]
PS : also in the "[What's new](http://mmenu.frebsite.nl/whats-new.html)" and "[WordPress plugin](http://mmenu.frebsite.nl/wordpress-plugin/)" page

**Comment by FrDH** [comment]
Thank's, I noticed this issue before but never really got around to find a fix for it as I usually use FireFox :/

I'll update the website along with the upcoming update to the plugin.

**Comment by FrDH** [comment]
Unfortunately, adding `overflow-x: hidden` disables `position: sticky` for the submenu. Fortunately, only the WordPress plugin pages uses both the overflowing images and the submenu.

**Comment by FrDH** [comment]
should be fixed now
