### ISSUE TITLE
Formatting SideNav with Columns

### ISSUE THREAD

**Issue by Nemo296** [FrDH/jQuery.mmenu#709]
I'm not quite sure where to put this but I was wondering if there was a way mmenu could do something like this.

![image](https://cloud.githubusercontent.com/assets/10834785/23965465/6b75b5fc-098e-11e7-928e-7c89404beee2.png)

The closest thing I was able to get was this

![image](https://cloud.githubusercontent.com/assets/10834785/23965533/9b2b82fe-098e-11e7-9572-c7ef28bf661b.png)

Basically I need everything to go right to left, instead of left to right.

**Comment by FrDH** [comment]
Getting the panels to open right to left will probably not work out of the box.
My best guess would be to use the columns add-on (as you already did) and create some custom CSS based on the [RTL add-on](https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/rtl/jquery.mmenu.rtl.scss)

Hope this helps.
