### ISSUE TITLE
Menu Seems to not work with HTML video

### ISSUE THREAD

**Issue by dankiuna** [FrDH/jQuery.mmenu#711]
I was adding an HTML video (as a background on autoplay with no sound) to to a site using the mmenu jQuery plugin, but one of the scripts stops the video after 1 second or less or loading.

**Comment by FrDH** [comment]
Have you read the part about [the page](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html) in the tutorial?

**Comment by dankiuna** [comment]
I took a look at that, and after implementing it, I still get the same issue. Any other suggestions/ideas?

Thanks

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
