### ISSUE TITLE
menu icon does nothing on firefox, ie; works on chrome

### ISSUE THREAD

**Issue by bschooly** [FrDH/jQuery.mmenu#714]
I have a situation where my page works fine on Chrome but not on Firefox or IE. When I resize the window to simulate a mobile device the menu disappears as expected (I see my content page) but a click on the menu icon does not bring up the menu. 

I'm using:

                extensions: ["fullscreen", "widescreen"],
                slidingSubmenus: false,

Any ideas where to start or debug this?

Bill

**Comment by FrDH** [comment]
Sounds odd. If it works in Chrome, it should work just as well in FireFox and IE.
Are you getting any errors in the console?
Is there an online example I could have a look at?

**Comment by bschooly** [comment]
Yes. Got to: https://customerportal.asist.net/login

Resize to small and you 'll get just the content but the hamburger icon does nothing. 

I don't have the slightest idea how to debug this. Suggestions on where to start?

**Comment by bschooly** [comment]
Well I just noticed that on Chrome, there appears to be a part of the hamburger that doesn't work as well. So it may be this has nothing to do with mmenu. Investigating right now...

**Comment by bschooly** [comment]
Yep... Put the menu tag by itself (see xxx) and it works.. Not sure of the difference:

        <a href="#menu">xxx</a>

        <div class="row">
            <div class="col-xs-2">
                <button id="my-icon" class="hamburger hamburger--collapse" type="button">
                    <a href="#menu">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </a>
                </button>
            </div>
            <div class="col-xs-8">
                <h1 class="text-center"><strong>Customer Portal</strong></h1>
            </div>
        </div>

**Comment by FrDH** [comment]
See this issue:
http://stackoverflow.com/questions/16280684/nesting-a-inside-button-doesnt-work-in-firefox

I don't think it's allowed to nest an <a> inside a <button>.

**Comment by bschooly** [comment]
Thanks. Dead right on that one... One last question. Is there a way through mmenu to not show the icon when the menu is open?

**Comment by FrDH** [comment]
when the (a) menu is opened, the class "mm-opened" is added to the HTML, you could use that to hide the icon with CSS:
````css
html.mm-opened #my-icon {
   display: none;
}
````

**Comment by bschooly** [comment]
Hmm. Sort of works. After a page load the icon can be present with the 
menu open. If you click on the icon it goes away and the behavior is 
fine thereafter as long as the page is not reloaded; will see what the 
fix is for this.

Bill
