### ISSUE TITLE
Working on Desktop But Not Mobile

### ISSUE THREAD

**Issue by DaveyJake** [FrDH/jQuery.mmenu#717]
When debugging on Mobile Safari, I keep getting this error: **TypeError: undefined is not an object (evaluating 'API.open').**

[Here's the complete Gist](https://gist.github.com/DaveyJake/a166ba5546cb0a1f2fac4a78f60a0ed3) of my jQuery.mmenu integration.  I'm using version 6.0.1.

Please advise. Thank you.

**Comment by FrDH** [comment]
There is no reason the API would be defined on desktop browsers but not on mobile browsers. The examples on the website (and the website itself) seem to work OK on mobile browsers.

Is there an online example of the integration?

**Comment by DaveyJake** [comment]
Because of the sensitive nature of the project I'm integrating this with, can we convert this conversation to private?  Upon doing so, I'll give you access to our live server where I can show you what's happening.

Additionally, something else interesting, I'm finding that Safari on Desktop works as expected while MobileSafari does not.  Even attempting to run API.getInstance() works fine in Desktop Safari but MobileSafari returns with **_TypeError: undefined is not an object (evaluating 'API.getInstance')_**

**Comment by DaveyJake** [comment]
I'm closing this issue as after 2 days of debugging, I finally realize that I forget to include the source file that contains the actual menu.  Do I feel like an idiot? Absolutely!

**Comment by FrDH** [comment]
noooooo! :|
Best of luck with the project!
