### ISSUE TITLE
How can I close mmenu on resizing window?

### ISSUE THREAD

**Issue by zverexe** [FrDH/jQuery.mmenu#719]
I have 2 menus, one for mobile and second is for desktop. I used clone option as suggested but it won't work. I gave ccs display: none for mobile menu >992 px but gray section left the screen size is bigger than 992px. 
![selection_172](https://cloud.githubusercontent.com/assets/17533287/24651219/aead86b8-1935-11e7-8923-e2d743ae0435.png)

**Comment by zverexe** [comment]
Here is js code:

**Comment by FrDH** [comment]
You can use the API to close the menu onWindowResize:
````js
$(window).on("resize", function() {
    API.close();
});
````
You could also use `matchMedia` to only close the menu onWindowResize if the window matches a media query:
````js
$(window).on("resize", function() {
    if (window.matchMedia("(min-width: 800px)").matches) {
        API.close();
    }
});
````

Hope this helps.
