### ISSUE TITLE
How to initialize mmenu after reloading the data when the <a> is clicked?

### ISSUE THREAD

**Issue by enb141** [FrDH/jQuery.mmenu#721]
Hi I'm trying to load mmenu data when the <a id="a_menu_mobile" href="#menu"></a> is clicked so I have this code:

````js
            $(document).ready(function () {
                $('#a_menu_mobile').click(function () {
                    $('#div_menu_mobile_content').load('menu.html');
                                        
                    $("#menu").mmenu(
                    {                        
                        offCanvas: {
                            position: "top",
                            zposition: "front"
                        }
                    });               

                    
                    $('#menu').data('mmenu').initPanels($('#ul_mobile_menu'));
                    $('#menu').data('mmenu').openPanel($('#ul_mobile_menu'));
                    $('#menu').data('mmenu').initPanels($('#ul_mobile_menu'));        
                   
                });
                
            });
````
the code works but the problem is that only works after the second time the <a> is clicked so I would like to know initialize it in order to make it to work when the first time is clicked.

**Comment by FrDH** [comment]
My guess is, the `load` did not finish loading the HTML. You should probably use the callback function. http://api.jquery.com/load/

**Comment by enb141** [comment]
Thank you very much, that was the problem, now it is working as it should.

Now it is an even simpler code.

`            $(document).ready(function () {
                $('#a_menu_mobile').click(function () {
                    $('#div_menu_mobile_content').load('menu.html', function () {
                        $("#menu").mmenu(
                        {                            
                            offCanvas: {
                                position: "top",
                                zposition: "front"
                            }
                        });
                    });
            });`
