### ISSUE TITLE
Events in documentation

### ISSUE THREAD

**Issue by MartinDM** [FrDH/jQuery.mmenu#722]
I was looking in the docs for events to bind to the API like this:

  ```
  API.bind("open:start", function () {
        console.log("This menu is opening "); 
    });
```

But in the docs there are no events, and while 'open' does work, it wasn't listed. Is this deliberate?
Are you able to suggest in the docs where I can find events that can be bound to the methods?

A contributer to the following question was able to find a bunch fo them by searching in the core MMenu library for 'trigger':
http://stackoverflow.com/questions/30559505/callback-event-when-jquery-mmenu-opened

**Comment by FrDH** [comment]
From the API docs:
> Note that add-ons might have their own set of API methods and hooks.

The off-canvas behavior is managed by the [off-canvas add-on](http://mmenu.frebsite.nl/documentation/core/off-canvas.html).

**Comment by MartinDM** [comment]
Ah I see. I thought the off-canvas behavior was now part of the core itself.  Thank you.
