### ISSUE TITLE
Output levels >0 into a separate div

### ISSUE THREAD

**Issue by MartinDM** [FrDH/jQuery.mmenu#725]
Hi Fred

Is it possible with this plug-in to output the sliding menu inside another div, let's say as part of a larger 'mega menu'  drop-down just confined to a separate area.
How would one select a specific containing element to show the remaining child links; Are there options in the plug-in for doing this?

Looking possible to option: `pageSelector: "#dropdownArea"` 

Thanks

**Comment by FrDH** [comment]
if you set the `offCanvas` option to `false`, the menu won't be prepended to the body, there will also be no "page" or any other off-canvas behavior.
Note that the menu will now fill up the available width and height from its parent. Use the ["auto-height" add-on](http://mmenu.frebsite.nl/documentation/addons/auto-height.html) to automatically adjust the height of the menu.
