### ISSUE TITLE
Menu opens automatically on iOS when using the browser backbutton

### ISSUE THREAD

**Issue by Koutis835** [FrDH/jQuery.mmenu#726]
First, I want to thank you for this wonderful plugin. Easily the best one I have seen out there. So easy to customize, and quick to implement.

The one particular issue I have appears on mobile iOS devices, when a user first navigates from page-1 to page-2 using the mmenu and then returns back to the page-1 using the browser backbutton. When returning to page-1, the menu is automatically opened and highlighting the link to page-2. 

You can see the behaviour on plugin homepage [http://mmenu.frebsite.nl/] by using the menu to navigate to another page and then hitting the browser backbutton.

I have tested this with iPhone6, iPhone7 and iPad2, and the behavior is the same regardless of the browser I use (I have tried Safari, Chrome and Firefox). On Android devices the menu on page-1 is nicely closed upon return.

My question: is there a way to keep the mmenu closed when returning to page-1 on mobile iOS devices?

**Comment by FrDH** [comment]
It is default browser behavior for most browsers to load the page out of the browser cache when using the back button.
Have a look at this article: http://blog.55minutes.com/2011/10/how-to-defeat-the-browser-back-button-cache/

Besides disabling browser cache, I don't think there is much you can do to prevent this behavior.

**Comment by Koutis835** [comment]
Thank you for the quick response.
