### ISSUE TITLE
Type definitions for TypeScript

### ISSUE THREAD

**Issue by ZoolWay** [FrDH/jQuery.mmenu#727]
Hello,

There are type definitions available through `typings` from May 2016. It would be great to have fixed current ones and even better when they would be part of the project and not just in typings.

The old version has at least the following problems:
- `initPanels()` is still `init()`
- `open()` missing
- `close()` missing

**Comment by FrDH** [comment]
Using TypeScript is on the todo list. I'll be sure to get involved with the project. Just to be sure, you're talking about this repo?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery.mmenu

**Comment by ZoolWay** [comment]
Yes, that it is. I could create a PR therre to fix the current issue I know about (see above). But library providers including the typings for their products is the more current way to go so if you want to use TypeScript yourself anyway the type definitions will be produced along anyways.

**Comment by FrDH** [comment]
I'll have to look into automatically generating the type definitions, I'm sure gulp-typescript lets me do this. For now, I'm working out all "errors" typescript produces.
