### ISSUE TITLE
overflow-y: auto not working on iPhone 6 

### ISSUE THREAD

**Issue by granite-digital** [FrDH/jQuery.mmenu#728]
Good Evening,

The menu does not scroll on iPhone6

Adding the following to the CSS does not seem to have any impact whatsoever.

.mm-menu {
    overflow-y: auto; 
    overflow-x: hidden; 
    -webkit-overflow-scrolling: touch;
}

Could anyone shed any light on this? 

Thank You

**Comment by FrDH** [comment]
I tested on an iPhone 7 (don't think there is much difference) but could not reproduce the issue.
What version of the plugin are you using? If not the latest, try updating to the latest version.
