### ISSUE TITLE
Drag addon not working

### ISSUE THREAD

**Issue by JoshKneale** [FrDH/jQuery.mmenu#729]
I've followed the instructions on the site, the drag addon doesn't appear to be working. Perhaps I've missed something?

Here is my code:

    <!DOCTYPE html>
    <html>

    
    
    

    <head>
    <meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes" />

    <link type="text/css" rel="stylesheet" href="mmenu/dist/jquery.mmenu.all.css" /> 
    <link type="text/css" rel="stylesheet" href="mmenu/dist/customcss.css" /> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="mmenu\dist\addons\searchfield\jquery.mmenu.searchfield.css"> 
    <link rel="stylesheet" href="mmenu\dist\addons\drag\jquery.mmenu.drag.css"> 

    <script type="text/javascript" src="mmenu/dist/hammer.min.js"></script> 
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>   
    <script type="text/javascript" src="mmenu/dist/jquery.mmenu.all.min.js"></script> 
    <script type="text/javascript" src="mmenu\dist\addons\searchfield\jquery.mmenu.searchfield.min.js"></script> 
    <script type="text/javascript" src="mmenu\dist\addons\drag\jquery.mmenu.drag.min.js"></script> 
    <script type="text/javascript" src="mmenu\src\jquery.mmenu.debugger.js"></script> 

    <script type="text/javascript">
    $(document).ready(function() {
      $("nav#my-menu").mmenu({
         counters: true,
         extensions: [
            "fx-menu-slide",
            "fx-panels-slide-0",
             "pagedim-black",
             "shadow-page",
             "theme-white",
             "multiline",
             "fullscreen"
         ],
         searchfield: {
            resultsPanel: true,
            showSubPanels: false,
            showTextItems: true
         },
         navbars: [
            {
               position: top,
               content: [
                  "searchfield"
               ]
            }
         ]
      }, {
         searchfield: {
            clear: true
         },
         drag: {
            page: {
                open: true
            },
            panels: {
                close: true
            }
            },
      });
    });
    </script>
    </head>

    
    
    

    <body>

I'm not seeing any errors in the console (debugger js is used).

The goal is to be able to open and close the menu with drag gestures.

p.s. some extra testing:

       if ( $.fn.hammer ) {
       alert("hammer is installed");
    } else {
       alert( "hammer isn't installed" );
    }

This returns as not installed

**Comment by FrDH** [comment]
First, the plugin does not need the jQuery wrapper for Hammer, so testing for `$.fn.hammer` might resolve to false. The plugin needs Hammer 2 (or newer), so the correct test would be:
````js
if ( typeof Hammer != 'function' || Hammer.VERSION < 2 ) {
   alert( "Hammer is NOT installed" );
}
````

If that doesn't help: are you getting any errors in the console?
If not: Is there an online example I could have a look at?
