### ISSUE TITLE
Ruby Sass?

### ISSUE THREAD

**Issue by agepoor** [FrDH/jQuery.mmenu#730]
Is there a reason you use gulp-ruby-sass and not gulp-sass? The gulp build and watch tasks failed at first. I changed gulp-ruby-sass to gulp-sass and it works fine now.

**Comment by FrDH** [comment]
I guess ruby-sass was used in some tutorial when I started using Gulp and I stuck with it. Are there any real reasons to switch?

**Comment by agepoor** [comment]
Gulp-sass is linked to node-sass/lib-sass and has more updates and active maintenance, if you look at their repositories on Github. I don't know how many people had my build problem, but switching would probably do more good than harm.

**Comment by FrDH** [comment]
Ok, thanks for the heads up. I'll see if I can switch to gulp-sass in the next version.

**Comment by FrDH** [comment]
FYI: the next release will be using gulp-sass. Thanks for the suggestion.

**Comment by Enkrod** [comment]
Ahh wonderful! Just came here to make a pull-request for switching to gulp-sass. Happy to see this will already be the case.
