### ISSUE TITLE
Old code not working with new version of mmenu

### ISSUE THREAD

**Issue by ilovegalya** [FrDH/jQuery.mmenu#732]
`API.bind( "opened", function() {
   setTimeout(function() {
      $icon.addClass( "is-active" );
   }, 100);
});
API.bind( "closed", function() {
   setTimeout(function() {
      $icon.removeClass( "is-active" );
   }, 100);`

In v5.7.8 it worked fine. In latest version it doesn't work.
I found it at tutorial on this link [http://mmenu.frebsite.nl/tutorials/animated-hamburger.html](url)
And it's still there

**Comment by ilovegalya** [comment]
I found the answer to my question on this page [http://mmenu.frebsite.nl/documentation/core/off-canvas.html](url)

**Comment by FrDH** [comment]
The hooks changed in version 6.0.0:

open:before
open:start
open:finish
open:after
