### ISSUE TITLE
Obsolete documentation?

### ISSUE THREAD

**Issue by nzy** [FrDH/jQuery.mmenu#733]
Hi!

On this page: http://mmenu.frebsite.nl/tutorials/animated-hamburger.html

Code example doesn't working.

Should be something like this:

```javascript
    var $menu = $(".mmenu").mmenu({
    });
    var $icon = $(".hamburger");
    var API = $menu.data("mmenu");

    $icon.on( "click", function() {
        API.open();
    });

    API.bind( "open:finish", function( ) {
        $icon.addClass( "is-active" );

    });
    API.bind( "close:finish", function( ) {
        $icon.removeClass( "is-active" );
    });
```

So is the "available API hooks" here:
http://mmenu.frebsite.nl/documentation/core/api.html

**Comment by FrDH** [comment]
Thanks! Must have missed that page when updating the docs :)
I'll update it shortly.

**Comment by nzy** [comment]
Thanks for this awesome piece of code.

When will you ressurect CarouFredSel from the ashes? :)

**Comment by MickL** [comment]
http://mmenu.frebsite.nl/documentation/core/api.html
This page seems to be out of date, too. None of the hooks are working.

**Comment by nzy** [comment]
Still, on this page: http://mmenu.frebsite.nl/tutorials/animated-hamburger.html

If you trying code from example, you will get error: Uncaught TypeError: Cannot read property 'top' of undefined.

To avoid error change "The icon" html to:

```
<a href="#my-menu" class="hamburger hamburger--collapse">
   <span class="hamburger-box">
      <span class="hamburger-inner"></span>
   </span>
</button>
```

Hooks are working perfectly.

**Comment by FrDH** [comment]
Thank you for reporting this issue, I'll update the docs.
