### ISSUE TITLE
Oddly slow loading time when using Mmenu on a specific test

### ISSUE THREAD

**Issue by chrisblakley** [FrDH/jQuery.mmenu#734]
I'll try to explain this as best I can, but I'm not 100% certain what is happening. All I know is that when I enable the Mmenu CSS on my website, WebPageTest.org says it takes 10+ seconds to load. Without the Mmenu CSS the same test says it loads in about 3 seconds.

The Mmenu JS does not appear to affect the load time. Some other details:
 - I am loading Mmenu via Cloudflare CDN. Specifically this file: `https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/6.0.2/jquery.mmenu.all.css`
 - I've tried changing to several previous versions of that file with no success.
 - This weirdness only happens when testing on the Oregon server on Web Page Test. When I test from Dulles, VA, it does not happen.
 - From the waterfall, the site **does not appear to be actually loading anything**, and all responses are 200. It's just sitting there seemingly doing nothing for 7-8 seconds.
 - The CPU utilization shows it's maxed out the whole time.
 - I've tested my site on two different servers each with the same results.

Here are two screenshots of the test results:

## With Mmenu CSS
https://www.webpagetest.org/result/170503_KV_XE0/

<img width="988" alt="with-mmenu" src="https://cloud.githubusercontent.com/assets/6349678/25663954/228501de-2fe7-11e7-940d-bd8716401013.png">

## Without Mmenu CSS
(You can see the unstyled menu in the screenshot)
https://www.webpagetest.org/result/170503_0P_XGR/

<img width="996" alt="without-mmenu" src="https://cloud.githubusercontent.com/assets/6349678/25663960/2a150318-2fe7-11e7-8694-17930a4d015d.png">

[I've also documented my investigation here (if that helps at all).](https://github.com/chrisblakley/Nebula/issues/1313)

I'm sure there is a possibility of it being something I'm doing, but at the moment the clues have led me here. I'm not super concerned because it is just this one server, but I'm curious if something is going on here.

**Comment by FrDH** [comment]
Hi, sounds really odd.
Have you tried including the css file from a local location? Something like "../css/jquery.mmenu.all.css"

Do other css files included from cloudflare have the same issue?

**Comment by chrisblakley** [comment]
I do not have issues with other files (5ish) loaded from Cloudflare. I tried copying the CSS to a local file and it still did the same thing (you can see `testmmenu.css` loaded from my domain): https://www.webpagetest.org/result/170503_KX_1009/

<img width="1015" alt="screen shot 2017-05-03 at 11 15 04 am" src="https://cloud.githubusercontent.com/assets/6349678/25667560/da948358-2ff1-11e7-9467-8a27ea6ecb25.png">

Appreciate your response- I'm happy to run more tests if you have other ideas.
