### ISSUE TITLE
Lazyload and setSelected on large menu

### ISSUE THREAD

**Issue by zilinski** [FrDH/jQuery.mmenu#735]
Hello,

First and foremost I wanted to thank you for a great menu! We have a large number of items loading through this plugin...In order to speed it up, we used lazy plugin add-on and setSelected. The issue that we ran into here is that setSelected does not allow us to drill down more than two levels into our category tree (We have four). Do you happen to know of a solution to this issue?

**Comment by FrDH** [comment]
I'll have to look into that. My guess is, the lazy-submenus add-on does not trigger the script that selects the correct menu item after loading a submenu.

**Comment by FrDH** [comment]
Had a look at the issue and found a fix, should be fixed in the next release.

**Comment by FrDH** [comment]
Should be fixed in version 6.1
