### ISSUE TITLE
$panel is not defined - 'use strict';

### ISSUE THREAD

**Issue by dutchenkoOleg** [FrDH/jQuery.mmenu#736]
___jQuery mmenu v6.0.2___
recive error `Uncaught ReferenceError: $panel is not defined`
if use with `'use strict'`.

I assume that the dist code is missing `var $panel`

![screen](http://image.prntscr.com/image/8bda4cb662bf4337bb910009c6d890cd.png)

**Comment by FrDH** [comment]
Thanks for the heads-up.
I'm currently implementing Typescript for this project, that helped locate some (if not all) of these issues. Should be fixed in the next version.

**Comment by dutchenkoOleg** [comment]
@FrDH glad to help ))

**Comment by FrDH** [comment]
Should be fixed in version 6.1
