### ISSUE TITLE
Issue when cloning menu item

### ISSUE THREAD

**Issue by mircobabini** [FrDH/jQuery.mmenu#737]
When you clone a menu item, you _should not_ keep the id attr. If some js relies on it to find the menu item, it will break because of two dom items with the same id.

**Comment by FrDH** [comment]
Where are menu items cloned?

**Comment by mircobabini** [comment]
Sorry, I actually refer to the wordpress plugin. I think you take the wordpress menu referred and clone the items into the mm wrapper.

**Comment by FrDH** [comment]
The WP- and the jQuery plugin should both prepend all ID's with "mm-", I'll have to check if I might have missed something. Thanks for bringing it to my attention.

**Comment by FrDH** [comment]
I (finally) had a look and found ID's on the menu, UL and LI's are removed, but other ID's are indeed not prefixed. Will fix this in the next version. Thanks again.
