### ISSUE TITLE
ScrollbugFix encountering "'that' is undefined" error.

### ISSUE THREAD

**Issue by logiczone** [FrDH/jQuery.mmenu#740]
Just noticed that I'm getting an error message in the console saying "'that' is undefined".  I traced it to line# 148 in the jquery.mmenu.scrollbugfix.js file.

In context, the snipped looks like this:

```
		glbl.$wndw
	    	.off( _e.orientationchange + '-' + _ADDON_ )
	    	.on( _e.orientationchange + '-' + _ADDON_,
	    		function()
	    		{
	    			that.$pnls
	    				.children( '.' + _c.opened )
			        	.scrollTop( 0 )
			        	.css({ '-webkit-overflow-scrolling': 'auto' })
			        	.css({ '-webkit-overflow-scrolling': "touch" });
				}
	    	);
```
I don't see the variable "that" defined anywhere in the plugin.

**Comment by FrDH** [comment]
Thanks for noticing,
should be fixed in v6.1
