### ISSUE TITLE
mm-selected not being applied

### ISSUE THREAD

**Issue by toffy-digital** [FrDH/jQuery.mmenu#741]
Hi all.
I recently bought the mmenu for wordpress, and I am trying to integrate the wordpress categories into the menu. 

Everything works fine except when a sub category is chosen or a root category is chosen the 
"mm-selected" does not seem to be applying to the div, therefore if I choose a subcategory it automatically jumps back to the root menu.

I would really like this to stick on the category that has been selected.

My Menu code in wordpress looks like:

```
<nav id="main-menu">
	<ul>
		<li><a href="/">Home</a></li>
			<?php wp_list_cats();?>
	</ul>
</nav>

```
I cannot figure out why this is not working in WordPress, it sure has me stumped. It works perfectly fine when I use the following code, which just displays a standard main menu:

```
<nav id="main-menu">
	<?php
		wp_nav_menu(
			array(
				  //Process nav menu using our custom nav walker
			  'menu' => 'main',
			  'depth' => 2,
			  'container' => false,
			)
		);
	?>
</nav>
```

Really need this menu to work with the category.

**Comment by minty-one** [comment]
My Menu code in wordpress looks like:

<nav id="main-menu">
	<ul>
		<li><a href="/">Home</a></li>
			<?php wp_list_cats();?>
	</ul>
</nav>

I cannot figure out why this is not working in WordPress, it sure has me stumped. It works perfectly fine when I use the following code, which just displays a standard main menu:

<nav id="main-menu">
	<?php
		wp_nav_menu(
			array(
				  //Process nav menu using our custom nav walker
			  'menu' => 'main',
			  'depth' => 2,
			  'container' => false,
			)
		);
	?>
</nav>

**Comment by FrDH** [comment]
Does `wp_list_cats()` add the class "current-menu-item" to the `<li>`? If not, that'll be the issue.

**Comment by minty-one** [comment]
Cool thanks FrDH
