### ISSUE TITLE
this.opts.extensions.join is not a function

### ISSUE THREAD

**Issue by posurreal** [FrDH/jQuery.mmenu#742]
When I add an extension, I get an error. I did find one thread about this issue but it's closed; so, I can't see the solution.

The Error:
jquery.mmenu.min.js:13
Uncaught TypeError: this.opts.extensions.join is not a function
    at e.(anonymous function)._initMenu

The script in my index.php file:
<script type="text/javascript">
			jQuery(function() {
				jQuery('nav#menu').mmenu(
					{
         			"extensions": ["theme-dark"]
      				}
				);
			});
		</script>

Although it tells me where the problem is, I'm not good at correcting javscript code.

**Comment by FrDH** [comment]
What version of the plugin are you using?
