### ISSUE TITLE
Goldman Sachs is using Mmenu?

### ISSUE THREAD

**Issue by dave7777** [FrDH/jQuery.mmenu#743]
Hello!
Take a look at side menu at https://www.credit-suisse.com/ch/en.html. 

Are they using your script? If only I knew how to hide it like they do on my website (on desktop version) - do you think you can provide a tutorial or a demo for that?
Dave

**Comment by FrDH** [comment]
I don't think they are, but if you want to use the mmenu plugin for mobile only, check out the "responsive layouts" part on the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html).
