### ISSUE TITLE
anchor tags are not working in mobile firefox

### ISSUE THREAD

**Issue by pratibhasharma5** [FrDH/jQuery.mmenu#745]
I have used "jquery.mmenu.min.all.js". This is working fine everywhere.
But when I open my website in mobile firefox then no anchor tags present on webpage are working (Not even simple links).
Please check.

Thanks

**Comment by FrDH** [comment]
I'm not sure I understand the question, I tested the documentation website (mmenu.frebsite.nl) in mobile FireFox (on an iPhone) and it seemed to work without any issues.
Please provide a working example of the issue.
