### ISSUE TITLE
Bootstrap wrapper example problem

### ISSUE THREAD

**Issue by esaesa** [FrDH/jQuery.mmenu#746]
The demo example of Bootstrap wrapper on the website http://mmenu.frebsite.nl/whats-new.html is not working. In Chrome latest version it does not open in portrait mode. and in landscape it conflict with bootstrap nav. 
![image](https://cloud.githubusercontent.com/assets/5354709/26649606/d5f6bd3c-4646-11e7-912d-64a2a1fda235.png)

**Comment by FrDH** [comment]
thanks for bringing it to my attention, I'll investigate what might be wrong here.

**Comment by FrDH** [comment]
Should be fixed :)
