### ISSUE TITLE
Anchor tags not working at all when mmenu installed

### ISSUE THREAD

**Issue by Tony-S** [FrDH/jQuery.mmenu#747]
mmenu is installed and working on my new site but it stops all the anchor tags working both within the menu and elsewhere on the site. The latest code has been used. 6.1.0
I've already used it another site where it's all working fine including links (Not a Magento site). This was version 5.7.8. The new site is a Magento 1 site and I've hand installed mmenu using the same principals as before. The menu opens and expands ok but no anchor tags work.
Files loaded are:
jQuery 1.8.3 (loaded in the site as standard)
jquery.mmenu.js
jquery.mmenu.navbars.js
jquery.mmenu.searchfield.js
mmenu_setup.js (see below)
jquery.mmenu.css
jquery.mmenu.navbars.css
jquery.mmenu.searchfield.css
jquery.mmenu.fullscreen.css

The failure is consistent across Edge, Chrome, FF, whether in desktop view or mobile emulation.
There are no console errors showing. There is a console warning showing in Chrome of "[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080". One of these appears for every anchor tag click including the ones which open and close the menu (which do work).

If I completely comment out a block of code as below from jquery.mmenu.js then all the anchor tags work again but the menu doesn't.
```
                    /*o.$body.on(r.click + "-oncanvas", "a[href]", function (i) {
                        var a = t(this), r = !1, o = e.$menu.find(a).length;
                        for (var l in t[n].addons)if (t[n].addons[l].clickAnchor.call(e, a, o)) {
                            r = !0;
                            break
                        }
                        var d = a.attr("href");
                        if (!r && o && d.length > 1 && "#" == d.slice(0, 1))try {
                            var c = t(d, e.$menu);
                            c.is("." + s.panel) && (r = !0, e[a.parent().hasClass(s.vertical) ? "togglePanel" : "openPanel"](c))
                        } catch (h) {
                        }
                        if (r && i.preventDefault(), !r && o && a.is("." + s.listview + " > li > a") && !a.is('[rel="external"]') && !a.is('[target="_blank"]')) {
                            e.__valueOrFn(e.opts.onClick.setSelected, a) && e.setSelected(t(i.target).parent());
                            var f = e.__valueOrFn(e.opts.onClick.preventDefault, a, "#" == d.slice(0, 1));
                            f && i.preventDefault(), e.__valueOrFn(e.opts.onClick.close, a, f) && e.close()
                        }
                    })*/
```
If I comment out just the contents of that function then the original problem remains.

I tried adding the debugger code but got the following console error on page load:
"jquery.mmenu.debugger.js:488 Uncaught TypeError: Cannot read property 'drop' of undefined" which refers to this line in the debugger file "if ( this.opts.dropdown.drop )". The original problem remains and nothing else appears in the console.

The mmenu_setup.js file has the menu setup as follows. This is directly based on my previous working site.
```
jQuery(document).ready(function () {
    //main mmenu
    jQuery("#nav-mobile-source").mmenu({
        // options
        "extensions": [
            "fullscreen",
            "multiline"],
        "offCanvas": {
            "position": "left",
            "zposition": "front"
        },
        "navbars": [
            {
                "content": ["prev", "title", "close"]
            },{
                "content": ["searchfield"],
                "postion": "top"
            },


        ],
        "searchfield": {
            "resultsPanel": true,
            "showSubPanels": false,
            "placeholder": "Search menu",
        },
    }, {
        // configuration
        "offCanvas": {
            "pageSelector": "#wrapper-main",
            "wrapPageIfNeeded": false,
        },
        "searchfield": {
            "clear": true
        }
    });
});
```
I have found a couple of other people reporting this same issue in the past but there were no solutions shown.
The site is x.kitchendoorhub.com (in development).

**Comment by FrDH** [comment]
That sounds odd, what exactly do you mean with "Anchor tags" and "not working"? Can you reproduce the issue on mmenu.frebsite.nl (it uses version 6.1.0)? That way I can do some debugging.
Are you by any change on a desktop with a touchscreen?

**Comment by Tony-S** [comment]
Any links you click on the site (other than the one to open the menu) don't go anywhere as it seems prevent Default is being applied. I am working on a non-touch PC desktop and the other site I used it on works fine. I test it in both standard desktop (where I can't access the mobile menu but the fault is still present) or mobile emulation or on my phone.
mmenu.frebsite.nl works fine for me. 
The site is accessible at x.kitchendoorhub.com
thanks

**Comment by FrDH** [comment]
If I understand the docs on https://www.chromestatus.com and your findings correctly, there is an issue when combining an onClick with an onTouchstart event. I find it really odd that commenting out the contents of a "bind" function results in an issue, where commenting out the entire "bind" does not.
Could you try commenting out the contents and add / replace it with a `return true;`?

````js
o.$body.on(r.click + "-oncanvas", "a[href]", function (i) {
    return true;
});
````

**Comment by Tony-S** [comment]
I tried that and it still fails. (I verified the code in the browser to make caches had cleared correctly). I also find it odd.
Thanks
Tony

**Comment by Tony-S** [comment]
I think the issue may be with o.$body

**Comment by Tony-S** [comment]
Ignore the comment abou o.$body - do you have any further thoughts on this?
Thanks
Tony

**Comment by FrDH** [comment]
Unfortunately I have no working Magento installation, so can're really do much debugging.
I did find that if you remove the onClick handler, the anchors work again:
````js
jQuery("body").off( "click.mm-oncanvas" );
//  anchors work!
````
Binding an onClick handler to the HTML (instead of the BODY) also breaks the anchors.
````js
jQuery("html").on("click", function() {
   alert("click");
});
//   anchors don't work...
````
It doesn't matter what's inside the onClick handler, returning `true`, `false` or nothing: all breaks anchors from working.

This (I think) means this issue does not restrict to only the jQuery.mmenu plugin. Could you try to remove it from your website and add something like this:
````js
jQuery("body").on("click", function() {
  alert( "test" );
  return true;
});
````

If the anchors still don't work (after alerting "test"), there's an issue in Magento and binding an onClick handler to the body, html and document.

**Comment by jerroydmoore** [comment]
I am also experiencing anchor tags not working in Chrome 53. Executing `jQuery("body").off( "click.mm-oncanvas" );` fixed the issue.

Files loaded are 
jQuery v2.1.4
knockout v3.4.1
cordova.js (for browsers)
js/index.js*
jQuery Mobile v1.4.5
jquery.mmenu.min.js v6.0.2

the `js/index.js` does the following
```
$.mobile.autoInitializePage = false; // disabled until an ajax call returns
// wait until data has been fetched
$.mobile.initializePage()
$.mobile.changePage("#main");
navigator.splashscreen.hide() //hide splash screen and show main page.
$("#nav-menu").mmenu({ }, {
    offCanvas: {
        // cordova-plugin-splashscreen adds HTML.
        // adding this page selector will prevent mmenu from breaking the splashcreen.
        pageSelector: "#main"
    }
});
```

Though removing the handler from `click.mm-oncanvas` now prevents my hamburger icon from opening the mmenu.

**Comment by FrDH** [comment]
Removing the handler from `click.mm-oncanvas` will indead remove all click-functionality the menu added.
Could you try removing the other scripts one by one and see at what point the anchors start working again? Thanks.

**Comment by Tony-S** [comment]
My problem seems to relate to jQuery being run in noconflict mode, which it has to be as prototype is also on the site. I basically stripped out everything other than jQuery-1.8.3, mmenu and the mmenu config code and there is still a problem.  The jQuery file has jQuery.noconflict() added to the end of it. If I remove this it works (but it has to be there for the rest of the site to work. As you can see from the setup code in my initial post I'm running mmenu with "jQuery" not "$" and indeed the menu is fully functioning other than no links work.
I've tried  running with the following config code but no different. Menu works, links don't:
`jQuery(document).ready(function ($) {
        $("#nav-mobile-source").mmenu({CONFIG HERE});
});`

**Comment by Tony-S** [comment]
I have finally got it working but it's not a nice solution. It involves loading another copy of jQuery, which has to be a different version. so that mmenu runs with standard jquery and the rest of the site runs with jQuery in noConflict mode. I tried loading the same version twice but that doesn't work. so this works:
```
<script type="text/javascript" src="/js/jquery/jquery-3.2.1.slim.min.js"></script>
<script type="text/javascript" src="/js/mmenu/jquery.mmenu.js"></script>
<script>
var $jq = jQuery.noConflict(true);
$jq(document).ready(function ($) {
        $("#nav-mobile-source").mmenu();
    });
</script>
<script type="text/javascript" src="/js/jquery/jquery-1.8.3.js"></script>
<script>jQuery.noConflict();</script>
Rest of scripts.
```

What I really need is a way of running mmenu after loading jQuery directly followed by jQuery.noConflict(). I have tried lots of different arrangements of noConflict settings and assigning jQuery to a different name but I couldn't get anything to work.
Thanks.

**Comment by FrDH** [comment]
I added `jQuery.noConflict();` to the demo files in the download pack, the menu and all anchors simply just worked. Adding a second version of jQuery should never be the solution, but if it works for now, I'd stick with it untill we find a better solution.

I'll do some more testing with other version of jQuery, but as far as I could find in the documentation, there is nothing wrong with binding a handler to the onClick event of the body.

If you will, could you remove all references to the mmenu plugin and simply replace them with something like this:
````js
$jq(document).ready(function ($) {
   $('body').on( 'click', 'a', function() {
      console.log( 'clicked' );
      return true;
   });
});
````
Normally, this should not prevent the default behavior for the anchor, but my guess is it does.

**Comment by Tony-S** [comment]
Well, after all that it appears one of the previous developers of my site had tampered with jQuery1.8.3 and it had a change made to it to do with preventdefault. I discovered this after testing with a different version of jQuery and getting things to work then back tracking through fresh download of 1.8.3 which also worked then unminifying the two copies and comparing them. I was doing this as part of the testing based on your above comment so I thank you greatly as, all be it for different reasons, that has led me to the solution. Thank you for your time and I apologise for using your time. Thanks. I shall now of course have to test everything on my site to see if unhacking jQuery has broken something else! Mmenu is up and running.

**Comment by FrDH** [comment]
Glad I could help.
