### ISSUE TITLE
mmenu not working on Typo3 page 

### ISSUE THREAD

**Issue by markeloop** [FrDH/jQuery.mmenu#748]
Hello, i buy license for Typo3 Integration of mmenu. I do everthing like said in the documentation here: http://blog.matthaa.de/menue-fuer-responsive-websites-mit-typo3-und-jquery-mmenu/ - Icon is displayed in mobile version of the site, but not open the menu like it should do. It only loads the homepage again. What could be the problem here? We use Typo3 7.6.18. 
![screen1](https://user-images.githubusercontent.com/29274707/26922285-f87fb7b6-4c3e-11e7-8113-16a62843af5c.jpg)

**Comment by FrDH** [comment]
HI,

I'm not much of a Typo3 expert, so I have no idea about the Typo3 stuff explained in that docs. As far as I can tell, the JS, CSS and HTML should work with the latest version of the jquery.mmenu plugin.

Are you getting any errors in the console?
