### ISSUE TITLE
Search result produces "orphan" links at top

### ISSUE THREAD

**Issue by iecwebmast** [FrDH/jQuery.mmenu#749]
Hello,
I am encountering a problem with the search results.  Some items in the results appear above the "menu" title and out of context with the rest.  I've prepared a jsfiddle to illustrate the problem (example... search for "tc 8".
https://jsfiddle.net/lbriquet/930jvzxs/

Could you take a look and let me know if I have done something wrong, or if this is a bug?

**Comment by FrDH** [comment]
Hi, 

I had a look at the jsfiddle but am not sure I understand the question, this is how the searchresults will de displayed if you use
````js
"searchfield": {
   "resultsPanel": true
},
````

**Comment by iecwebmast** [comment]
Thank you for taking a look.  When I search for "tc 8" the search results show many item with no header bar, then the tc 8 header... then a "menu" header.
![image](https://user-images.githubusercontent.com/5822962/27069520-6cd6e376-5015-11e7-89fe-81fd96061970.png)

I was expecting to see a header TC 8 (followed by TC 8 SC 8A and 8B)... then a header for TC 8 SC 8A (followed by it's WGs)... then a header for TC 8 SC 8B (followed by it's WGs)... Then a header for TC 82, TC 87 (followed by it's WGs) and then a header for TC 88.

If I search for "sc 8" (the subcommittees of  TC 8), I get a result which corresponds correctly.
![image](https://user-images.githubusercontent.com/5822962/27069658-1a8b303a-5016-11e7-9736-c792ced8d2e5.png)

I hope this helps

**Comment by FrDH** [comment]
that's strange, here's what I'm seeing.
<img width="359" alt="schermafbeelding 2017-06-13 om 14 11 53" src="https://user-images.githubusercontent.com/1387163/27081800-63fb0a3e-5042-11e7-9075-b4eee0c1b7de.png">

**Comment by iecwebmast** [comment]
Interesting.  I was working in Chrome.  I just checked in Firefox and Internet Explorer and I see what you are seeing.  So it appears to be a bug with Chrome.

**Comment by FrDH** [comment]
It's odd that Chrome shows the items in a different order, but somehow it does. I tried reproducing the issue on my site, but it showed the results as expected (in FF and Chrome). Please let me know if you find the reason for this bug.

**Comment by FrDH** [comment]
I did a bugfix on the searchfield add-on, could you try V6.1.7 and check if the issue is persists?
