### ISSUE TITLE
Menu sliding issue

### ISSUE THREAD

**Issue by arunspawoz** [FrDH/jQuery.mmenu#753]
Hi, I am facing an issue with jQuery mm-menu plugin.  When I click on the navigation icon, it reloads the page instead of expanding the menu. I got some javascript errors in the console and I attached the screen below. I am using jQuery mmenu v5.3.4 and the script I used is;

```
$("#menu").mmenu({
        "offCanvas": {
            "position": "right"
        }
  });
```

Any idea about this issue?

![mm_menuerror](https://user-images.githubusercontent.com/20816321/27436365-9cae3126-577c-11e7-8ee4-bca83f332090.png)

**Comment by FrDH** [comment]
Hi, not sure what could be the issue, but it might be the plugin can't find the DIV that it at first considered to be the page.
For better debuggins: could you please use the non-minified version of the plugin?
Also, is there an online example I could have a look at?

**Comment by FrDH** [comment]
By default, the offCanvas add-on tries to find the page like this:
````js
$page = $("body").find( "> div" );
````

I guess this could result in an empty object, but although that probably should not be possible, it should also not produce an error.

What does the console log if you type in:
````js
jQuery.mmenu.glbl.$page
````

**Comment by arunspawoz** [comment]
Hi, 

Sorry for the delayed response. jQuery.mmenu.glbl.$page value is undefined. And is this the non-minified version https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/6.1.0/jquery.mmenu.js?

Thank you.

**Comment by FrDH** [comment]
`glbl.$page` should not be undefined (I guess there should have been some sort failsafe).
You should probably have a look at your HTML and setup the [offCanvas add-on](http://mmenu.frebsite.nl/documentation/core/off-canvas.html) so it understands your HTML.

As there is no online example, I can not tell you what you need to change, but my guess is you need to set the `offCanvas.pageNodetype` and/or `offCanvas.pageSelector` configuration options.

Hope this helps.
