### ISSUE TITLE
ZIP-File from Download is empty

### ISSUE THREAD

**Issue by JWestarp** [FrDH/jQuery.mmenu#755]
http://mmenu.frebsite.nl/download.html

If I downlaod the Plugin from the Website the ZIP-File is empty.
If I enter my license first and download, the ZIP-File contains only "license-key.txt"

I'm using Firefox (Developer) and Win 10

**Comment by JWestarp** [comment]
Now my license-key is not accepted. The Error says: "We're sorry, but that's an invalid license key.
If you've purchased the plugin from codecanyon, please contact us to get a license key."

I few minutes ago it was working (active till Oktober 2017) 
I don't bought it at codecanyon..

**Comment by FrDH** [comment]
Hi,

I'm sorry the download link results in an empty ZIP, I've heard this before once or twice but could not find any reason for it to be so. 

All files (including the non-minified TS and SCSS files) can also be downloaded from this GitHub repo via the green "download" button in the "code" tab. You can include the "license-key.txt" file in those files, but it is not required for the plugin to work.

The license key should also be mentioned in the confirmation email you've received. Does that one validate?
