### ISSUE TITLE
.mm-title separate links from back button?

### ISSUE THREAD

**Issue by sensaetions** [FrDH/jQuery.mmenu#756]
Hello,

Is it possible to set what the links of each `.mm-title` would be?  Currently the nav title and the back arrow takes you back to the previous menu. I would like to be able to determine or set what each title would link to.  For example, I would like to have the title link to a page rather than back to the previous menu.  If this is possible, how would I go about doing so?

**Comment by FrDH** [comment]
By default, you can use the `navbar.titleLink` option (documentation [here](http://mmenu.frebsite.nl/documentation/core/options.html)). If you set it to `"anchor"`, the title wil link to the href attribure of the parent anchor.

If you want full control over what the title link does, you can use the navbars add-on and set the title information in the HTML. Something like this:

````js
$("#my-menu").mmenu({
    navbars: [{
        content: ["prev", "title"]
    }]
});
````
````html
<nav id="my-menu">
   <ul>
      <li>
         <span>About</span>
         <div>
            <ul>
               <li>History</li>
            </ul>
            <a class="Title" href="http://www.google.com">Go To Google</a>
         </div>
      </li>
   </ul>
</nav>
````

The classname "Title" tells the navbars add-on to copy the `href` attribute and the text to the "mm-title".

Hope this helps.

**Comment by sensaetions** [comment]
Thank you for the reply and the examples.  But it's not quite what I want it to do yet.

Is it possible to get something like this?
For example, when clicked on, I would like the `<span>`About`</span>` in your example above to become the title, and have it be linked to Google.

**Comment by FrDH** [comment]
Like this:
````html
<nav id="my-menu">
   <ul>
      <li>
         <span>About</span>
         <div>
            <ul>
               <li>History</li>
            </ul>
            <a class="Title" href="http://www.google.com" style="display: none;">About</a>
         </div>
      </li>
   </ul>
</nav>
````

**Comment by sensaetions** [comment]
That worked, thank you!
