### ISSUE TITLE
Chrome console violation somewhere between Mmenu and jQuery

### ISSUE THREAD

**Issue by chrisblakley** [FrDH/jQuery.mmenu#758]
This could be an issue with jQuery, but I can't determine the root cause. I don't think this is a very big deal, but I wanted to document it somewhere. It could be something in the way I'm calling Mmenu too.

Specifically there are two ~~identical~~ violations in the console. One for `touchstart` and one for `touchmove`:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
and are attributed to jquery.min.js on line 3, but in the call stack I see `jquery.mmenu.all.js` as well as my `main.js` file where I'm initializing Mmenu.

Here's the full call stack:
![screen shot 2017-06-30 at 12 27 06 am](https://user-images.githubusercontent.com/6349678/27720917-e2bbaf82-5d2a-11e7-8e11-464b44c58337.png)

If I take out my Mmenu initialization function, the violation goes away.

Here is the configuration object in my file:
```js
jQuery('#mobilenav').mmenu({
	//Options
	offCanvas: {
	    position: "left", //"left" (default), "right", "top", "bottom"
	    zposition: "back", //"back" (default), "front", "next"
    },
	navbars: [{
		position: "top",
		content: ["searchfield"]
	}, {
		position: "bottom",
		content: ["<span>Example Title</span>"]
	}],
	searchfield: {
    	add: true,
    	search: true,
    	placeholder: 'Search',
    	noResults: "No navigation items found.",
    	showSubPanels: false,
    	showTextItems: false,
    	resultsPanel: true,
    },
    counters: true,
    iconPanels: false,
    extensions: ["theme-light", "effect-slide-menu", "pageshadow"]
}, {
	//Configuration
	offCanvas: {
		pageSelector: "#body-wrapper"
	},
	classNames: {
		selected: "current-menu-item"
	},
	searchfield: {
		clear: true,
		form: {
			method: "get",
			action: "https://example.com/",
		},
		input: {
			name: "s",
		}
	}
});
```

I'm calling Mmenu from a CDN, and I'm happy to try any troubleshooting if it would help. Sorry to throw a couple weird ones at you- I really love your plugin!

**Comment by FrDH** [comment]
Thanks for bringing this to my attention.

mmenu uses the `touchstart` event (when the menu is opened) to:
1) Close the menu when touching the rest of the page (in the offCanvas add-on).
2) Prevent the page from scrolling when actually trying to scroll the menu (in the scrollBugFix add-on).

In both cases, the event listener is intended to block scrolling, so the warning is kind off irrelevant. If there is a better (and cross-browser) solution (that doesn't trigger a warning), I'd be happy to implement it.

For now, (as far as I know), jQuery has no way to make an event "passive".

**Comment by chrisblakley** [comment]
I wouldn't change any core functionality to the `touchstart` event, and I do agree that it blocking scroll is a ultimately benefit. I have looked into if/when jQuery will allow for passive event listeners and found the same conclusion you did.

That being said, this violation is triggered before the site is loaded, so maybe there is a way to defer the touchstart event listener until either after the page has loaded, or until the user opens the menu itself? (I'm just "thinking out loud" here)
