### ISSUE TITLE
Mobil keyboard open

### ISSUE THREAD

**Issue by otherprod** [FrDH/jQuery.mmenu#759]
Hi and thank you for your plugin, i have a little problem, the mobile keyboard open at the same time the menu open, is there a way to avoid that please ? 

For information i m using swift keyboard on android 7

Thank you

**Comment by FrDH** [comment]
Hi, sounds odd. Is there an online example of the issue? I could not recreate it on the documentation website or any of the examples.

**Comment by otherprod** [comment]
Hi, thank you, https://www.mobilparebrise.fr

**Comment by wearegoose** [comment]
Hello,

I also have the same issue. The keyboard opens when on mobile and opening the menu.

I'm using the WordPress plugin

Thanks

**Comment by otherprod** [comment]
I m using wordpress plugin also

**Comment by FrDH** [comment]
If you've enabled the advanced option "keyboard navigation", try disabling it.

**Comment by otherprod** [comment]
It works with  keyboardnavigation to false, thank you

**Comment by FrDH** [comment]
I'll fix this issue in the next version. Keyboard navigation should probably not be enabled on touch-devices.

**Comment by FrDH** [comment]
Should be fixed in version 6.1.4

**Comment by otherprod** [comment]
Great news , thank you :)
