### ISSUE TITLE
WordPress Plugin MMenu Logo Link

### ISSUE THREAD

**Issue by toffy-digital** [FrDH/jQuery.mmenu#762]
Hi there,
I have installed the WordPress plugin and all seems to be working fine.

Except I can't set up a link to go from the logo that is set up under 
"Add a logo or photo" 

When selecting the logo it does ask for 
"Link Image To:" 
Which I do enter. 
However, on the live site - I can only see the static image.

Can a link be set up to link the logo to a url , preferably the home page ?

**Comment by FrDH** [comment]
The logo can currently not be linked to any URL.
The "link to" field (like most other fields "alignment", "description", "etc") should not be visible.
I'lll see if I can implement this improvement. Thank you for the feedback.
