### ISSUE TITLE
Iconbar with self contained open close

### ISSUE THREAD

**Issue by iecwebmast** [FrDH/jQuery.mmenu#763]
Hello,
Is there a way to open the iconbar without using the external hamburger solution?
I'd like for it to open/close (expand/collapse) the iconbar menu onclick of a self contained left/right chevron.  Otherwise, if the iconbar would expand on mouseover and onclick, would also be very helpful. Now if you click on an collapsed iconbar icon with a submenu, only a small part of the submenu is visible as it remains collapsed.
Thank you in advance for your help.
Laila

**Comment by FrDH** [comment]
Hi, 
You could programmatically open the menu when opening a panel, that would make sence I guess:
````js
var $menu = $("#my-menu").mmenu({
   //  your options
});
var API = $menu.data( "mmenu" );

API.bind( "openPanel:start", function() {
   API.open();
});
````

I would advice against opening the menu onHover, as this would result in unexpected behavior when accidentally hovering over the menu. But if want, try something like this:
````js
var $menu = $("#my-menu").mmenu({
   //  your options
});
var API = $menu.data( "mmenu" );

$mmenu.on( "mouseover", function() {
   API.open();
});
````

Hope this helps.
