### ISSUE TITLE
Zip file at http://mmenu.frebsite.nl/download.html is dead on arrival

### ISSUE THREAD

**Issue by pkosenko** [FrDH/jQuery.mmenu#764]
Tried downloading (twice) the free mmenu zip from the web site to test the app. Windows is not able to open the .ZIP file.  The .zip is apparently corrupt.

http://mmenu.frebsite.nl/download.html

**Comment by FrDH** [comment]
Hi,

I'm sorry about that, there seems to be an issue with the download on some specific OS I could not jet figure out.
Untill that's fixed, you can simply download the plugin from [GitHub](https://github.com/FrDH/jQuery.mmenu/archive/master.zip) or use [the CDN](npm install jquery.mmenu).

If you're using NPM, just type `npm install jquery.mmenu`.

Hope this helps.

**Comment by pkosenko** [comment]
Yes, thanks.  I downloaded it with GIT.  I should have said that.  I could also have used NPM.  So there are alternatives.  I just wanted to note that the ZIP wasn't working in case you weren't aware.

**Comment by pkosenko** [comment]
I don't know why the issue is closed.  The problem still exists a year and a half later.  I had to download with GIT again.  The USUAL reason for an EMPTY zip file is that the URL is incorrect (or not accessible).  The browser (in this case Firefox) still creates the file, but with nothing in it.  I hope that helps.  Look at the URL that your download button is referencing.  Either it is incorrect or it requires some sort of access configuration that was not granted on the zip where it is located?

**Comment by FrDH** [comment]
The download button links to the correct url and should work on all  browsers. Not sure why, but everyone that encoumters this problem seems to be using Windows 7.
I havent been able to find what is causing Windows 7 to download an empty file, but it stil has my attention
