### ISSUE TITLE
menu not showing up on iOS 7/8 (mmenu 6.1.0)

### ISSUE THREAD

**Issue by derghostface** [FrDH/jQuery.mmenu#766]
Mmenu 6.1.0 is not working on iOS 8 and 7 and maybe lower. You can test it with http://mmenu.frebsite.nl/. There is no javascript error, but the menu is not visible when you open it. Seems to be a css issue.
It works fine on iOS 9 and 10.

Switching back to 6.0.2 iOS 7 and 8 are supported again.

**Comment by FrDH** [comment]
That's odd, I can't really think of any change that would not work in iOS 7 or 8. Unfortunately I do not have iOS 7 or 8 available to do some testing. Do you have any idea why the menu isn't showing? If there is no js error, is there some css preventing the menu from being shown?

**Comment by FrDH** [comment]
I think I found the issue. For some reason, after switching from "ruby-sass" to "libsass", the "autoprefixer" task is no longer used. And without a vendor prefix, older borwers do not support CSS3 stuff like `transition`, `transform` and `translate`.

I'll add the "autoprefixer" task in the next release.

**Comment by FrDH** [comment]
should be fixed in version 6.1.1, could you please check? thanks!

**Comment by derghostface** [comment]
Thanks a lot. Now it works again!
