### ISSUE TITLE
Empty ZIP

### ISSUE THREAD

**Issue by hugoderooij** [FrDH/jQuery.mmenu#767]
I have downloaded the zip for wordpress but it's empty. I'm interested in a full licence bit I would like to try the free wordpress version first before doing so. Can you tell me where I can download the wordpress trial (not the empty zip)? Many thanks!

**Comment by FrDH** [comment]
Hi,
I'm sorry the download doesn't work, there seems to be an issue I could not yet reproduce or explain.
I'll see if I can fix the issue, but for now you can download the plugin folder here: http://mmenu.frebsite.nl/wordpress-plugin/mmenu.zip

**Comment by danbramall** [comment]
This still seems to be an issue.  Empty zip if I download without adding my activation key.  If I add my activation key I get a zip containing just a txt file with the activation key in it.
