### ISSUE TITLE
Click on trigger for slide-panel in multi-level menu acts as anchor

### ISSUE THREAD

**Issue by ALLESxVERBOTEN** [FrDH/jQuery.mmenu#768]
I use the mmenu-plugin (http://mmenu.frebsite.nl/) for a multi-level navigation in the sidebar on: http://boendgen.buildmore.de/sortiment/

For the first link "Bauelemente" I have a submenu, which can be opened by clicking on the arrow-link. Unfortunately the trigger acts as an anchor and make the page scroll down at the same time, the submenu is slided in.

onClick { preventDefault: true } didn't wprk for me.

I've also tried to add a preventDefault(); on the link, but it doesn't work.

Anybody has a solution?

**Comment by FrDH** [comment]
I had a look but couldn't visit the website as I was redirected to the login page.

**Comment by FrDH** [comment]
Without a login there is nothing I can investigate.

**Comment by FrDH** [comment]
Closing this issue because no online example is provided.
