### ISSUE TITLE
Navbars: dynamic content

### ISSUE THREAD

**Issue by paulhaem** [FrDH/jQuery.mmenu#769]
Hello there,
I was searching for a way to set fixed buttons (via Navbars add-on) with dynamic content. Currently I set the content manually in the JS file. Is there a way to set the content dynamically through e.g. PHP? There were no hints in the documentation or on stackoverflow.

**Comment by FrDH** [comment]
Hi.
Well, I guess you could use PHP to output the JS, something like this:
````php
$myVar = '<a href="#">text</a>';
echo '
<script>
   $("#my-menu").mmenu({
      navbars: [{
         content: [ "' . $myVar . '" ]
      }]
   });
</script>';
````

Second (and probably better) option would be to have PHP output some HTML and target that HTML when using the navbars add-on:
````php
echo '
<a href="#" id="my-element">text</a>';
````
````js
$("#my-menu").mmenu({
   navbars: [{
      content: [ "#my-element" ]
   }]
});
````

**Comment by paulhaem** [comment]
Thanks for the answer! :+1: 

So I have to place some invisible elements in my html, which will be referenced by jQuery as I initialize mmenu? Is there no clean way as such as adding it dynamically via API?

**Comment by FrDH** [comment]
You don't need to use hidden HTML, but it's a good way to interact between PHP (server) and JS (client).
At this point you can not use the mmenu API to add, update or remove stuff from a navbar. But if you could, you'd still need to find a way to interact between PHP and JS.
