### ISSUE TITLE
mmenu styles broken on page load

### ISSUE THREAD

**Issue by MateenSalik** [FrDH/jQuery.mmenu#770]
mmenu style broken on page load or refresh

**Comment by FrDH** [comment]
Please read the [guidelines for contributing](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md):

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.
