### ISSUE TITLE
How to go to the most upper parent

### ISSUE THREAD

**Issue by sheez44** [FrDH/jQuery.mmenu#771]
I have submenu's within the menu's and the functionality works as expected. However, I can only go back to the closest parent. I want to add a new link which will allow the user to go back to the most upper parent in one go.

So lets say I have a menu like this: Food --> drinks --> soft drinks --> coca cola
If the user is at the coca cola level, I want a link that brings the user back to Food. How to solve this?

**Comment by FrDH** [comment]
Is it always the most top level panel you want to open? If so you could use the API to close all panels:
````js
var $menu = $("#my-menu").mmenu();
var API = $menu.data( "mmenu" );

$("#some-elem").on("click", function() {
    API.closeAllPanels();
});
````

**Comment by sheez44** [comment]
Thanks, that worked indeed! I could not find it in the documentation though.

**Comment by FrDH** [comment]
I'm not sure why, but the `closeAllPanels` is not in the API docs. I'll see if it can be added later on.
