### ISSUE TITLE
mm-selected is not set

### ISSUE THREAD

**Issue by sheez44** [FrDH/jQuery.mmenu#772]
I am really confused on how and when it sets this class to the menu item. 
- On default it seems like it is not set automatically, when i traverse to a submenu and click on a link it will correctly go to that page, but when I open the menu again it opens the uppermost parent and the  submenu item does not have the class 'mm-selected', nor does any item.
- When I manually add the 'active' class to a submenu item, and in the api I refer to that class with 'classNames' it will replace the 'active' class with 'mm-selected'. When I now refresh the page and open the menu it will always go to the submenu item which I had set the 'active' class to. It will not remove the 'mm-selected' class on that item and set it again on the item I did click.

How do i get the menu to set the 'mm-selected' class correctly/automatically? Or do I have to set the 'active' class manually via javascript on every subitem that is clicked?
I want it to behave exactly the same as on your demo site.

**Comment by FrDH** [comment]
Hi,

On page load, the plugin searches for the `LI` that has the class specified in the `classNames.selected` configuration. So you need to set that classname to the `LI` that you think should be selected... **on every page**.  The plugin does not keep track of what menu item was clicked in the previous page.

For example, you HTML on the homepage could look like this:
````html
<ul>
    <li class="Selected"><a>Home</a></li>
    <li><a>About</a></li>
    <li><a>Contact</a></li>
</ul>
````
And on the "about" page:````html
<ul>
    <li><a>Home</a></li>
    <li class="Selected"><a>About</a></li>
    <li><a>Contact</a></li>
</ul>
````

You could also try to use the [setSelected add-on](http://mmenu.frebsite.nl/documentation/addons/set-selected.html), it can try to find the current selected menu item by comparing the anchor href with the URL. It's not 100% guaranteed to work though.

Hope this helps.

**Comment by sheez44** [comment]
You are awesome! I had to put it on the li's and not the a's. Now it works with setting the active class at the right place on the right page! I tried the detect method before, but it didnt work.
