### ISSUE TITLE
Question: push menu from top/bottom

### ISSUE THREAD

**Issue by qzminski** [FrDH/jQuery.mmenu#774]
Sorry if this is a duplicate but I could not find the related issue. Is it possible to achieve the *push content* effect when the menu opens up in the top/bottom position? The documentation states that it is only possible for left/right position in combination with `zposition` set to `back`.

In version 4.2 you have deprecated the `zposition: back` for usage with the `position: top/bottom` in favor of the improved CSS framework. What is the reason this behavior was not created or re-created in the new version?

**Comment by FrDH** [comment]
In order to be able to push out the page to the top ot bottom, the page would need to have `overflow: hidden`. Although possible, this would often scroll the page back to the top when opening the menu. Also it didn't feel natural to push out the page to the top or bottom.

**Comment by qzminski** [comment]
The `body` tag seems to already have the `overflow: hidden` because of the `html.mm-blocking` CSS class, so I think it's just a matter of adding the respective `transform: translate3d` stuff. I understand the issue with the page scroll but that's a drawback by the concept which the users would have to be aware of.

Despite the drawbacks it has we actually would like to have that on our website – would you consider adding that feature if I provide a pull request?

**Comment by FrDH** [comment]
As I remember it had too many issues but feel free to give it a go.

**Comment by qzminski** [comment]
I haven't managed to apply this to the source code as there are more potential cases to cover but I was able to done it using regular callbacks. One thing to note is that I always use it with `autoheight` add-on. Reference:

```js
var wrapper = $('#wrapper'); // .mm-page
var blocker = $('#mm-blocker');

api.bind('open:start', function () {
    var offset = this.$menu.outerHeight();

    if (this.opts.offCanvas.position === 'bottom') {
        offset = offset * -1;
    }

    wrapper[0].style.setProperty('transform', 'translate3d(0,' + offset + 'px,0)', 'important');
    blocker[0].style.setProperty('transform', 'translate3d(0,' + offset + 'px,0)', 'important');
});

api.bind('close:before', function () {
    wrapper.css('transform', '');
    blocker.css('transform', '');
});
```
