### ISSUE TITLE
TurboLink and Mmenu

### ISSUE THREAD

**Issue by masterpieceicang** [FrDH/jQuery.mmenu#775]
I'm using turbolinks and mmenu, i always got this error when i click the menu
![ini](https://user-images.githubusercontent.com/14269158/28765322-695bf07e-75f4-11e7-850f-50038a429999.png)

How do i solve this? Thanks

**Comment by FrDH** [comment]
Are you using the turbolinks wrapper?
http://mmenu.frebsite.nl/documentation/framework-wrappers.html

**Comment by masterpieceicang** [comment]
but i'm using turbolinks 5, in your article posted it can be used for turbolinks 4 and below

**Comment by FrDH** [comment]
:)
You'll find two files in the download: "turbolinks" and "turbolinks legacy".
The "turbolinks legacy wrapper" can be uses for turbolinks 4 and below. The "default" turbolinks wrapper workshop for turbolinks 5.

Hope this helps.
