### ISSUE TITLE
target="_blank" should also append rel="noopener"

### ISSUE THREAD

**Issue by dep** [FrDH/jQuery.mmenu#776]
I noticed a reference in the library to create links that can target new windows.  It's recommended that links using target="_blank" also contain rel="noopener" for security reasons.

Could the lib be updated to attach rel="noopener" to links that contain target="_blank" ? Thank you!

References:
https://mathiasbynens.github.io/rel-noopener/
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

**Comment by FrDH** [comment]
Interesting read, I'll put it on the todo list to add `rel="noopener"` to the anchors.

**Comment by FrDH** [comment]
Implemented in version 2.6.2, now available for download

**Comment by dep** [comment]
Very cool!
