### ISSUE TITLE
bug with offcanvas and multiple JQM pages

### ISSUE THREAD

**Issue by jerroydmoore** [FrDH/jQuery.mmenu#777]
I have a single page application using jquery v2.1.4 and jquery mobile v1.4.5. I am using mmenu v6.0.2.

My intent is to use mmenu for two or more jqm pages. I could add a separate mmenu for each page, but that seems inefficient. I've tried setting offCanvas's pageSelector to select all pages with mmenu, however, according to the [documentation](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html), this ends up wrapping the pages in a DIV. This breaks navigation. Sample Code:

JavaScript:

        // start on a splash screen, load data, then go to #main
        $.mobile.changePage("#main");
        $("#nav-menu").mmenu(
        {
            // options
        }, {
            // configuration
            offCanvas: {
                pageSelector: ".has-mmenu",
            }
        });

My **simplified** `<body>`

```
<body>
<div data-role="page" id="main" class="has-mmenu">
    <nav id="nav-menu">
        <ul>
            <li><a href="#main">Home</a></li>
            <li><a href="#moregames">More Games</a></li>
        </ul>
    </nav>
</div>
<div data-role="page" id="moregames" class="has-mmenu"></div>
<div data-role="page" id="otherpage"></div>
</body>
```

The end result is I am unable to navigate to #moregames. The `<body>` looks like this:
```
<body>
<nav id="nav-menu" class="mm-menu mm-offcanvas">
    <!-- more mm-panels, mm-navbars, mm-listviews -->
</nav>
<div id="mm-0" class="mm-page mm-slideout">
    <div data-role="page" id="main" class="has-mmenu"></div>
    <div data-role="page" id="moregames" class="has-mmenu"></div>
</div>
<div data-role="page" id="otherpage"></div>
</body>
```

According to [four-year-old this forum post](https://forum.jquery.com/topic/nested-page-with-pages-in-different-containers), the proper JQM solution is to not pull multiple pages into the same DIV.

I have found a hacky solution that works. If I leave the pageSelector to #main and manually add the css classes `mm-page` and `mm-slideout` to the #moregames page, effectively duplicating the css classes added to #main by mmenu. Because of this hacky solution, I wondered if there's a part of the documentation I'm missing, telling us how to properly use mmenu across multiple JQM pages without this hack.

**Comment by FrDH** [comment]
I'm not a big fan of jqmobile, so I might not be up to date on this, but have you tried using the [jQuery mobile framework wrapper](http://mmenu.frebsite.nl/documentation/framework-wrappers.html)?
> Adds a workaround for having multiple "pages" in one webpage and helps navigating to a new page more fluent.
