### ISSUE TITLE
Splitting menu item into link and submenu

### ISSUE THREAD

**Issue by OPM87** [FrDH/jQuery.mmenu#779]
Hi there,
I didn't find an example or option for this but is it possible to split a menu item into a link and something like a button?
If someone clicks on the link, a page should open. A click on the right button or the arrow should open the submenu.

Something like this:
![img1](https://user-images.githubusercontent.com/4279913/29065088-46eb6c1c-7c2b-11e7-919b-0d922326760b.jpg)
![img2](https://user-images.githubusercontent.com/4279913/29065094-4b3f0a94-7c2b-11e7-9364-49166a4dd33f.jpg)

**Comment by FrDH** [comment]
That's the default behavior, have you read [the tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/the-menu.html)?

**Comment by OPM87** [comment]
Yes, I read the tutorial but I tried it with an old live example (v5). Sry :-/
What I finally wanted:
[example](https://jsbin.com/cimixuv)

Thank you for your help.
