### ISSUE TITLE
backButton is not working with "offCanvas": false

### ISSUE THREAD

**Issue by esaesa** [FrDH/jQuery.mmenu#780]
I can not get the backButton addon to work. I see in the code that if offCanvas is false it will return. I can not find such limitation in documentation. If the limitation is true can you implement it as it is important in App-like menus.  and if it is technically impossible can you illustrate more.

**Comment by FrDH** [comment]
Quote from the docs:
> To enable the menu to be closed by pressing the browser back button, include the "backButton" add-on .js file and use the backButton options.

The backButton add-on can close an opened menu when the browser back button is clicked. Only an off-canvas menu can be closed, on-canvas menus are always opened.

Hope that clarifies the add-on.
