### ISSUE TITLE
Sidebar disappears when clicking too quickly

### ISSUE THREAD

**Issue by Findus23** [FrDH/jQuery.mmenu#781]
When trying around with the menu I found out that quickly opening and closing a submenu (before the animation has finished) breaks the menu and makes it unusable.

I was able to reproduce it [in the playground example](http://mmenu.frebsite.nl/examples.html#h3) and in all browsers I could test (Chrome, Firefox, IE11, iOS Safari, Chrome and Firefox on Android)

![unbenannt](https://user-images.githubusercontent.com/6266037/29264336-ed6f6060-80dc-11e7-8f15-a620b207bf26.gif)

![output2](https://user-images.githubusercontent.com/6266037/29264654-31b5a5a8-80de-11e7-8fff-62e1f67ea723.gif)

**Comment by FrDH** [comment]
I'll see if I can fix this issue, thanks for reporting it.

**Comment by FrDH** [comment]
Should be fixed in the next release, coming shortly.
