### ISSUE TITLE
Sub items of parent siblings are visible if lazy submenu addon is enabled

### ISSUE THREAD

**Issue by Patta** [FrDH/jQuery.mmenu#782]
With lazy submenu addon, the sub items of the parent siblings are visible in opened menu.
Example on screenshot: if panel with item 1 - 4 is open, the sub items of the parent items (grey numbers) are visible. Without lazy submenu addon everything is ok. 

![bug_lazymenus](https://user-images.githubusercontent.com/2151127/29271921-25a00a7c-80fe-11e7-8225-86ac438044bb.png)
(i renamed the pages)

Maybe some styles are missing?

**Comment by FrDH** [comment]
Hi, thanks for bringing this to my attention.
I don't think the lazySubmenus add-on has been tested in combination with the iconPanels add-on.
I'll see if I can fix this shortly.

**Comment by FrDH** [comment]
I tried but could not reproduce the issue, what version of the plugin are you using?

**Comment by Patta** [comment]
in v6.1.8 this bug still exist

**Comment by FrDH** [comment]
Could you set up an online example of the issue? I can't seem to reproduce it.

**Comment by Patta** [comment]
currently not, sorry. issue still in 7.0.0

**Comment by FrDH** [comment]
Closing this issue due to lack of an online example. Please create a new issue if any further help is needed.
