### ISSUE TITLE
Bug when menu/hamburger button is clicked rapidly 5 times

### ISSUE THREAD

**Issue by Jesusislovely** [FrDH/jQuery.mmenu#783]
Hi,

Thanks for this great and beautiful plugin! I'm loving it.

If the overlay doesn't cover the menu/hamburger button, so the menu/hamburger button remains clickable, and then if the menu/hamburger button is clicked or tapped really quickly five times, the my-page div slides out to the right revealing a blank <body> below. 

The off-canvas menu then only closes if the button, and not anywhere else is clicked.

I've noticed that when this happens:
1) the html class remains .mm-opening only 
(and not .mm-opening .mm-opened .mm-blocking .mm-background .mm-top .mm-front .mm-theme-dark .mm-border-none).
2) the my-menu div doesn't have the classes .mm-current or .mm-opened applied to it.

Thanks very much in advance for fixing this!

From Nick

**Comment by FrDH** [comment]
Thank you for bringing this to my attention.
There's a similar issue with rapidly opening and closing panels. I'll be sure to fix both issues shortly.

**Comment by Jesusislovely** [comment]
Thanks very much! You're great!

**Comment by FrDH** [comment]
What version of the plugin are you using? I tried but could not reproduce the issue. Is there an online example of the issue?

**Comment by Jesusislovely** [comment]
Thanks. I'm using a version that's a year or two old I think. I never considered that something as simple as that might be the issue! I'm away from my computer until Sunday. I'll update my plugin then and check if this problem has resolved and get back to you. Have a fun few days!

**Comment by FrDH** [comment]
Try updating and let me know if the issue exists in the latest release.

**Comment by Jesusislovely** [comment]
Hi Fred. I was using version 5.6.2! And I updated today to the current version and the mmenu works beautifully. The rapid clicking problem that I reported is nonexistent. I'm sorry for all the trouble.

**Comment by Findus23** [comment]
Sounds like you ment the same issue as me 
#781
