### ISSUE TITLE
Menu does not always "stick" to the top when scrolling

### ISSUE THREAD

**Issue by martin9348** [FrDH/jQuery.mmenu#784]
Menu does not always "stick" to the top when scrolling up/down.

I am using Chrome on an Android 7.0 device, and the browser address bar sometimes appears or disappears when scrolling. When this happens, the menu does not "stick" to the top. See screenshots (one is OK, the other one shows the problem.). When touch is released (finger/thumb doesn't touch the screen anymore), the menu height is adjusted and sticks to the top again.

![screenshot_2017-08-17-08-27-00](https://user-images.githubusercontent.com/17345251/29412438-d1800048-8326-11e7-88ca-6e21d862315e.png)
![screenshot_2017-08-17-08-27-18](https://user-images.githubusercontent.com/17345251/29412437-d179bcb0-8326-11e7-9710-3cbe962809c0.png)

**Comment by FrDH** [comment]
I'm not sure why android doesn't update the height, position, etc for the menu while scrolling inside the menu, is does so for all other HTML elements. You could try to disable the "scrollBugFix" add-on and see if that makes any difference (it is designed to prevent unwanted scrolling behavior on touchscreens):
````js
$("#my-menu").mmenu({
    scrollBugFix: false
});
````
Let me know if that changes anything
