### ISSUE TITLE
sticky header got hidden when Menu open after scroll

### ISSUE THREAD

**Issue by preeety** [FrDH/jQuery.mmenu#785]
I am using Chrome on an Android and my website have fixed header. When I scroll down and open MMenu then header got hidden.

**Comment by FrDH** [comment]
That's a known side effect of animating the page with the `transform` CSS property.
Check out the [Fixed elements add-on](http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html), it has a workaround for fixed and sticky positioned elements.

In short: simply add the class "Sticky" to all elements that have `position: sticky` and "Fixed" to all elements that have `position: fixed`.

Hope this helps.

**Comment by preeety** [comment]
Not helpful for me. I am using bootstrap fixed navbar for header.  "Fixed elements add-on" Not working.

**Comment by FrDH** [comment]
Adding the class "Fixed" to the bootstrap fixed navbar does not work after including the FixedElements add-on? Is there an online example available? If not, please provide one.
