### ISSUE TITLE
Collapse menu to burger on screens smaller than x px

### ISSUE THREAD

**Issue by BridgeSoft** [FrDH/jQuery.mmenu#788]
Hi all. I can't figure out how to change the pixel value at which the menu collapses (or expands I guess due to mobile first) to burger menu mode. The standard bootstrap point is 768, and this is changeable by using css like: https://coderwall.com/p/wpjw4w/change-the-bootstrap-navbar-breakpoint

However this breaks the mmenu functionality. Is there any way changing the collapse point to etc 1024 pixels?

**Comment by FrDH** [comment]
Have you read the "responsive layouts" section on the [tips and tricks page](http://mmenu.frebsite.nl/support/tips-and-tricks.html)?
