### ISSUE TITLE
Prevent menu content from being styled

### ISSUE THREAD

**Issue by SvetlinStaev** [FrDH/jQuery.mmenu#789]
First let me tell you that the mmenu is a great piece of software and I really enjoy using it.

I have a special case, which might not be suitable for that menu or I might be missing something that's why I would like to ask. I use the menu for mobile navigation with an ul list and it works excellent. What I am trying to do is use it with purely custom HTML as a simple off-canvas pull/push mechnism without it touching the styles of the HTML in the target element. The problem is that when I add such a menu it tries to style it and messes up the styles of the HTML. Added `mm-nolistview` to the wrapping DIV but since this is only for UL element it doesn't do anything. Is there a way to use it with a div content without it trying to apply any logic or styles for the HTML inside?

The use case for this filters menu for a search page on a responsive template. When we are on desktop we have the search filters as a collection of selects, radio and check boxes all wrapped in a DIV. On mobile this DIV is hidden and a filters toggle is show which upon click shows the menu as an off-canvas menu which unlike the mobile navigation menu doesn't need menu elements or hierarchy but a simple output of the filters form elements.

Is this possible with the current implementation of the menu?

**Comment by FrDH** [comment]
Could you share the HTML?
Something like this should work:
````html
<nav id="my-menu">
   <div>
      <p>Some text</p>
      <ul class="NoListview">
         <li><a href="3">link</a></li>
      </ul>
   </div>
</nav>
````

**Comment by SvetlinStaev** [comment]
Here is a sample of the HTML:

```
<div id="search-filters">
    <div class="medium">
        <div class="input-group m-b">
            <input type="text" id="price_start" name="price[0]" class="numeric form-control" value="" placeholder="">
            <span class="input-group-addon"><svg class="svg-icon"><use xlink:href="/images/icons.svg?v=1.0#right"/></svg></span>
            <input type="text" id="price_end" name="price[1]" class="numeric form-control" value="" placeholder="">
        </div>
    </div>
    <div class="medium">
        <select id="attribute_280" name="attribute[280]" required="required" class="form-control">
        ...
        </select>
    </div>
    <div class="medium">
        <div class="form-inline">
            <div id="attribute_282">
                <div class="form-group">
                    <select id="attribute_282_from" name="attribute[282][from]" class="form-control">
                    ...
                    </select>
                </div>
            </div>
        </div>
    </div>
    ...
</div>
```

And on each node it some classes get added:

```
<div id="search-filters" class="mm-menu mm-offcanvas mm-iconpanel mm-hasnavbar-top-2 mm-theme-light mm-opened">
    <div class="mm-navbars-top">
        <div class="mm-navbar mm-navbar-size-2"></div>
    </div>
    <div class="mm-panels">
        <div class="medium mm-panel mm-opened mm-iconpanel-0" id="mm-2">
            <a href="#mm-2" class="mm-subblocker"></a>
                <div class="input-group m-b">
                    <input type="text" id="price_start" name="price[0]" class="numeric form-control" value="" placeholder="">
                    <span class="input-group-addon"><svg class="svg-icon"><use xlink:href="/images/icons.svg?v=1.0#right"/></svg></span>
                    <input type="text" id="price_end" name="price[1]" class="numeric form-control" value="" placeholder="">
                </div>
        </div>
        <div class="medium mm-panel mm-hidden" id="mm-3" aria-hidden="true">
            <a href="#mm-3" class="mm-subblocker"></a>
            <div class="btn-group bootstrap-select form-control">
            ...
            </div>
        </div>
        <div class="medium mm-panel mm-hidden" id="mm-4" aria-hidden="true">
            <a href="#mm-4" class="mm-subblocker"></a>
            <div class="form-inline">
            ...
            </div>
        </div>
    </div>
    ...
</div>
```

**Comment by FrDH** [comment]
If `div#search-filters` is your "menu" (e.g. when calling `$("#search-filters").mmenu()`) each `<div>` directly inside it (the ones with `class="medium"`) will be asumed to be a "panel". You can prevent this by wrapping it all in another `<div>`:

````html
<div id="search-filters">
    <div id="the-new-div">
        <div class="medium">
            <div class="input-group m-b">
                ....
            </div>
        </div>
    </div>
    ...
</div>
````

Now, the new `<div id="the-new-panel">` will be assumed to be a panel and all HTML inside it will be left as is.

Hope this helps.

**Comment by FrDH** [comment]
This tutorial might help:
http://mmenu.frebsite.nl/tutorials/advanced/

**Comment by SvetlinStaev** [comment]
Great, works excellent! Thanks.

On a side note and a small issue which I guess I might also have missed in the docs. This filters DIV visibility is controlled media queries so the filters are visible in the canvas on desktop but are hidden on mobile. The problem is that if I leave the menu visible on all resolutions there is a small delay until the mmenu kicks in to hide it off canvas but if I hide it with a media query when I trigger the menu it doesn't show (I guess it inherits the visibility of that element).

I tried with `"clone": true,` in the options but this doesn't help.

Thank you very much for the explanation and quick response.

**Comment by SvetlinStaev** [comment]
Nevermind, found it in the docs:

```
#search-filters:not(.mm-menu) {
   display: none;
}
```

Great product with excellent documentation. Will be purchasing a commercial license very soon.
