### ISSUE TITLE
Menu style conflict when using fullscreen extension

### ISSUE THREAD

**Issue by SvetlinStaev** [FrDH/jQuery.mmenu#790]
I have the following problem. I have 2 menus - a off-canvas with push effect from the right and a full screen slide up menu. When I try to open the fullscreen one everything works perfect but when I try to open the off-canvas one from the right it pushes the site wrapper outside of the viewport.

I narrowed it down to the following style:

```
html.mm-right.mm-opening .mm-menu.mm-fullscreen~.mm-slideout {
    -webkit-transform: translate(-100%,0);
    -ms-transform: translate(-100%,0);
    transform: translate(-100%,0);
    -webkit-transform: translate3d(-100%,0,0);
    transform: translate3d(-100%,0,0);
```

When I remove the transforms from that style everything works as expected as the following one kicks in:

```
html.mm-right.mm-opening .mm-menu~.mm-slideout {
    -webkit-transform: translate(-80%,0);
    -ms-transform: translate(-80%,0);
    transform: translate(-80%,0);
    -webkit-transform: translate3d(-80%,0,0);
    transform: translate3d(-80%,0,0);
```
Is there a way to have that working without disabling that style - is it a bug of the script or when having these two menus I am running into a conflict of the classes?

**Comment by FrDH** [comment]
That's odd, the mm-fullscreen class should obviously not be applied to both menu's. I'll have to do some debugging to find the reason for this issue. Is there an online example I could have a look at?

**Comment by SvetlinStaev** [comment]
I created a gist here - https://gist.github.com/SvetlinStaev/ab3855a2887b9b2eb2699554aea6dec8 - that illustrates the issue

**Comment by FrDH** [comment]
Thank you for the gist, I think I found the issue and will fix it shortly.

**Comment by FrDH** [comment]
Will be fixed in the next version, coming shortly.

**Comment by datune** [comment]
@FrDH 

After ugprading and pulling my hair for 14 hours, I finally found out I have the exact same problem as OP. I have created an updated gist for your perusal using all the latest versions to showcase the problem. 

Basically, as soon as fullscreen is added to one menu, it seems to affect all other menus.

https://gist.github.com/datune/9a4ac9a2e0c42fcbff7e325b44792bc4
