### ISSUE TITLE
Every page jumps to bottom on android

### ISSUE THREAD

**Issue by hjaltels** [FrDH/jQuery.mmenu#791]
After installing mmenu i have noticed that every time i use a android device it automatically jumps to the bottom of the page, every time i click around. I assume its because of the mmenu, as the menu always popup just before the page scrolls to the bottom of the page. Anyone knows what to do? I use prestashop, if that makes any difference :)

**Comment by FrDH** [comment]
Hi,

Haven't head about this issue before. Does the documentation site have the same issue?
http://mmenu.frebsite.nl

**Comment by hjaltels** [comment]
I finally figured out what was wrong. This bug occurred because of "Smart cache to CSS" Is there any way to fix this problem, or should i just leave it off, even though it slows my pagespeed? :)

**Comment by FrDH** [comment]
I'm not familiar with smart cache to css, maybe someone at stackoverflow knows about this issue?
