### ISSUE TITLE
Not work touch close a panel

### ISSUE THREAD

**Issue by Sv9t** [FrDH/jQuery.mmenu#793]
Hello! I do not understand how to close the menu with a touch? The menu opens with a touch of the hand from left to right, but the right to the left does not work.
 `drag: {
   menu: {
	 open: true
		},
  panels: {
         close: true
              }
}`

Look only this is test page (included the necessary scripts): https://goo.gl/aZV3sw
Sorry for my English! Tnx!

**Comment by FrDH** [comment]
Hi,

The menu can't be closed with a dragging gesture, panels can (therefor it is `menu.open` and `panels.close`).

Hope this helps.

**Comment by Sv9t** [comment]
Thank you for your reply!
Refinement for me: this menu: 
`<nav id="menu"><ul><li>...</li></ul></nav>` 
but what is the "panel"? I can not find in the search on the site that there is a panel.

**Comment by Sv9t** [comment]
FrDH, can you give a link to the full example of working with the above code I wrote? an example with a html, css structure and js options, so you do not have to write much here. Tnx!

**Comment by FrDH** [comment]
I don't know how to be more clear than the documentation page:
> To enable the menu to be opened by a dragging gesture or to enable a subpanel to be closed by a swiping gesture,
