### ISSUE TITLE
Wordpress plugin disappears

### ISSUE THREAD

**Issue by romanWienicke** [FrDH/jQuery.mmenu#794]
Hi,
I installed a licensed copy of the wordpress plugin and it disappeares from wordpress in irregular intervals.
It seems as the plugin is removed from the wordpress configuration - in the admin panel it disapeares completely. On the frontend page the burger is visible but has no action and the menu is not working.

When I reinstall the mmenu zip the frist time it complains that the folder ~/plugins/mmenu is existing - but a second time it's working and I can install mmenu. When the menu is installed all setting from the menu are restored.

Is there any solution for this?

Thank you
Roman

**Comment by FrDH** [comment]
That sounds odd, I haven't heard about it before.
For testing purposes: Does the issue persist if you deactivate other plugins and choose a default theme?
