### ISSUE TITLE
Menu won't close on page click after opening sub-menu

### ISSUE THREAD

**Issue by mfsumption** [FrDH/jQuery.mmenu#795]
I am attempting to implement mmenu in a SharePoint 2013 site. I have also added the Bootstrap js and css. I have wrapped all code (including the nav) inside the body tag with a wrapper div and specified that id in the pageSelector setting. When using the menu on a mobile device or in the Chrome mobile device simulator, the menu opens fine, and I can click the page area and it will close fine. However, when I open the menu and click a sub-menu, the sub-menu will slide in fine, but the whole menu will no longer close when I click in the page area. I added the debugger js per your docs, but it did not turn up any errors, nor do I see any other console errors. Just for fun, I opened the site in a desktop browser and made the window small enough to make the mmenu visible - in this scenario, the mmenu works perfectly fine, even when opening and closing sub-menus, the menu will close properly. So it appears to only be a problem on mobile devices. This site is not public yet, as I'm trying to get this working first.

**Comment by FrDH** [comment]
Hi,
That sounds odd. Can you reproduce this issue on a site that is publicly available? For example on any of the examples on mmenu.frebsite.nl ?

Without an online example there is not much I can debug.

**Comment by mfsumption** [comment]
Fred, thank you for your reply. I will try to make the site publicly available next week and let you know. Is there a private email address or other method I could use, as I would need to send you temporary credentials? Thanks.

**Comment by mfsumption** [comment]
Hi Fred, the site is now publicly accessible, but it does require a login. Is there a way I could send you the URL and login credentials privately? Thanks.

**Comment by FrDH** [comment]
You can send me an email: info[ at ]frebsite[ dot ]nl

**Comment by mfsumption** [comment]
For others - I'm not sure what change was the cure, but it just started working. I've been making a lot changes to the master page and the custom style sheet. If I figure it out, I will post the resolution here.
