### ISSUE TITLE
Widescreen plugin makes menu inaccessible for screenreader users

### ISSUE THREAD

**Issue by Findus23** [FrDH/jQuery.mmenu#796]
This issue is reproducible in this demo:
http://mmenu.frebsite.nl/demo/index.html?demo=widescreen

Normally `aria-hidden="true"` is added to the `<nav>` when the menu is closed and removed when the menu is opened again. 

But the widescreen plugin seems to circumvent this detection and always keeps `aria-hidden="true"` even when the menu is visible. As a result the whole menu is unusable for screenreader users.

**Comment by FrDH** [comment]
You could argue that screenreaders can still access the menu via the hamburger icon (my guess is, the hamburger icon does not get `aria-hidden="true"` applied to it?), but I think you're right.

The widescreen extension (like all extensions) is CSS only, there's no "callback" or such thing for when it's activated / deactivated. It's on the TODO list to turn the widescreen extension into an add-on (where it can have JS) for the sake of more functionality. I'll add this issue to the list.

**Comment by Findus23** [comment]
> You could argue that screen readers can still access the menu via the hamburger icon
Yes, but in our website (and in the demo) the hamburger gets hidden with an `display:none` which also hides it for screen reader users.

A workaround would be using something like the bootstrap `sr-only` class.

**Comment by Findus23** [comment]
Or the js solution:
```js
function handleResize() {
    if (window.innerWidth >= 1024) {
        $sidebarMenu.attr("aria-hidden", false);
    }
}

var resizeTimeout; // https://stackoverflow.com/a/24461911
$(window).resize(function () {
    if (!!resizeTimeout) {
        clearTimeout(resizeTimeout);
    }
    resizeTimeout = setTimeout(handleResize, 200);
});
handleResize();
```

**Comment by FrDH** [comment]
For now, I'd stick with the JS solution.
I'll see if I can implement a more generic fix in the upcoming changes.

**Comment by FrDH** [comment]
Good news.
The next release will have a `sidebar` add-on which is a combination of the `widescreen` and `iconbar` extensions. It will trigger the "open" method when the menu bevomes fully visible next to the page (where the widescreen extension didn't).

**Comment by Smod9** [comment]
Im not sure this is the same issue, but I struggle with having one menu (my main navigation menu) with position right using the widescreen extension, then another menu with position bottom. If widescreen is active for my right hand side menu, my position bottom menu slides up behind the menu on the right. Any chance this is a known/resolved issue, or an easy fix because im just doing it wrong :) ?
