### ISSUE TITLE
Duplicate Search Results

### ISSUE THREAD

**Issue by MasterProgrammer79** [FrDH/jQuery.mmenu#797]
I believe I found a bug with searchfield when using it on 2 mmenus. I'm cloning an mmenu to use one offcanvas for mobile view and one on canvas next to the content in question on desktop view. The second mmenu will show duplicate results while the first does not. Initially, I thought this was a product of cloning, but I initialized the menus separately and the issue remains. Here is my code followed by a couple screenshots. You'll notice that the second mmenu not only shows duplicate results, but also pulls in the search results of the first mmenu as well.

var options = {
	"navbar": {
		"title": "Products"
	},
	"navbars": [{
		"position": "top",
		"content": ["searchfield"]
	}],
	"searchfield": {
		"resultsPanel": true,
		"placeholder": "Search Categories"
	}
};

var $productsMenu = $('#products-menu');

$productsMenu.mmenu($.extend({}, options, {
	"offCanvas": {
		"pageSelector": "#page-container"
	}
}), {
	"clone": true
});

$productsMenu.mmenu($.extend({}, options, {
	"offCanvas": false
}));

First Menu search results:
![screen shot 2017-09-14 at 10 51 51 am](https://user-images.githubusercontent.com/7937566/30440325-cb2e642a-993b-11e7-9b13-b27a64ade31d.png)

Second Menu search results:
![screen shot 2017-09-14 at 10 52 22 am](https://user-images.githubusercontent.com/7937566/30440331-cec93ba0-993b-11e7-99a6-d3bdd67ce807.png)

**Comment by FrDH** [comment]
Hi, thanks for reporting this issue.
I'll have to investigate it.

**Comment by MasterProgrammer79** [comment]
You can see a live example here: http://www.yetterco.com/products .

**Comment by FrDH** [comment]
I think I found the issue, a common typo collected all panels om the page instead of just the ones in the current menu:
`$( ".mm-panel", this.pnls )` should have been `$( ".mm-panel", this.$pnls )`.
I'll upload a bugfix version shortly.

Thanks again for reporting the issue.

**Comment by MasterProgrammer79** [comment]
I just updated to the new version and it works perfectly. Thank you for fixing this so quickly.
