### ISSUE TITLE
Complexer menu structure

### ISSUE THREAD

**Issue by lorro** [FrDH/jQuery.mmenu#798]
Hi,

My main navigation ul item has a bit of a typical structure like this:
It's got div's nested within it as it's a megamenu with bootstrap columns in it.

```html
<ul class="nav navbar-nav navbar-left">
    <li class="dropdown  yamm-fw  megamenu">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-tint m-r-5"></i>Main</a>
        <ul class="dropdown-menu animated fadeIn yamm-content">
            <li>
                <div class="col-md-3">
                    <ul class="list-unstyled m-l-0">
                        <div class="row"><li class="menu-heading"><span>Header</span></li>
                        <li><a href="#">Link 1</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
</ul>
```

Apparently the mmenu isn't working quite normal within this structure, as no child items pop up. I can only see root items from the main ul.

Do you have any suggestion if this can be counterfeited in a way? :)
Thanks!

**Comment by FrDH** [comment]
I'm not sure if this is a copy/past error, but only `<li>`s should be directly inside an `<ul>`, not a `<div>`. Also, the `<div>` isn't closed.

Is there an online example of the menu I could have a look at?

If you're using the `clone` configuration option, you could use the `initMenu` callback option to make changes to the (cloned) menu, something like this:

````js
$("#my-menu").mmenu({
    initMenu: function( $menu ) {
        // whatever needs to be done to make the HTML fit the mmenu restrictions
        $menu.find( ".menu-heading" ).remove();
        $menu.find( ".row" ).each(function() {
            $(this).replaceWith( $(this).contents() );
        });
    }
})
````
Hope this helps.

**Comment by lorro** [comment]
Hi,
Did try that at first, but didn't help. 
That's why I did some effort and took the time to create a separate mobile menu that has the correct structure (so it only contains ul en li items like it should) and attached the mmenu plugin to that menu instead. Working properly now so will buy a license.

Thanks for the assistance nevertheless!
