### ISSUE TITLE
Anchor links have problem

### ISSUE THREAD

**Issue by pamjadz** [FrDH/jQuery.mmenu#800]
I have a responsive menu that uses mmenu. The menu links are anchors that point to locations on a single page. When I click on one of the menu anchors the page correctly moves to the right position on the page But menu will not close.
How can make this problem fix?
i wanna when i clicked on link, menu get close.

**Comment by FrDH** [comment]
Have a look at the `onClick.close` option in [the documentation](http://mmenu.frebsite.nl/documentation/core/options.html)
Basically, a menu will close after clicking a menu item if the default clicking behavior was prevented (with event.preventDefault()).

Hope this helps.
