### ISSUE TITLE
Menu not displaying in Firefox 57

### ISSUE THREAD

**Issue by amstr4d** [FrDH/jQuery.mmenu#802]
The menu is not displaying when clicking on open button in Firefox 57 Developer Edition. It works perfectly in Firefox 55, Chrome, Safari, IE & Edge. 

No JS errors in console and the plugin is correctly loaded and initialized.

To fix this, I had to force the display and top position of the .mm-menu nav block, just after calling mmenu  : 
```javascript
$menu.css('display', 'block'); 
$menu.css('top', $("header").outerHeight());
```
Maybe it's just Firefox fault ?

**Comment by FrDH** [comment]
Sounds odd, cant think of any reason for 'display: none' not to work. Might be a rendering issue in FF.

**Comment by FrDH** [comment]
Is this issue still relevant? I tried in FF 57 beta and 58 nightly, both didn't have a problem opening the menu on mmenu.frebsite.nl
