### ISSUE TITLE
Open submenus with hover event ?

### ISSUE THREAD

**Issue by dogee** [FrDH/jQuery.mmenu#804]
I would know if this is possible to open submenus with an hover event instead of a click event ?
I don't find anything on http://mmenu.frebsite.nl and Google.

Thank you for your ideas.

**Comment by FrDH** [comment]
The easy approach would be to trigger the click event onhover I guess:
````js
$(".mm-listview .mm-next").on( "mouseover", function() {
    $(this).click();
} );
````

I seriousely doubt this will result in a good user experience though.

**Comment by dogee** [comment]
I know and I agree but this is not my call.
It worked by the way.
Thanks for the tips :)
