### ISSUE TITLE
Prevents autoplaying video in Chrome

### ISSUE THREAD

**Issue by wickedurge** [FrDH/jQuery.mmenu#805]
Plugin is fantastic, but it prevents an autoplaying background video from working in Chrome. I've tested it and it works in Firefox and Safari. No errors appear in the console. Disabling the plugin fixes the video problem. 

I'm using Chrome Version 61.0.3163.100. Mac OS High Sierra, and WordPress 4.8.2.

**Comment by FrDH** [comment]
Have you read this tutorial? 
http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html

> If you let the plugin wrap all HTML, a VIDEO will restart (or not start at all), javascript in a SCRIPT will run twice, an IFRAME will reload and so on.

**Comment by wickedurge** [comment]
Ok, that helped a lot. I guess I was expecting too much from the WordPress plugin.

Is there a way to set the offCanvas pageSelector in the WordPress? If not, it's ok I can just put it together without using the WordPress plugin.

**Comment by FrDH** [comment]
Currently the wp plugin has no option for this. I’ll put it on the todo list.
