### ISSUE TITLE
Dividers in search un-escape text

### ISSUE THREAD

**Issue by LastZactionHero** [FrDH/jQuery.mmenu#806]
## Issue

We're using MMenu to display a tree of choices, including choices from user-generated data. With users being users, we need to properly escape any special characters in their content.

For example, here's a category title where the user entered HTML:
![screen shot 2017-10-06 at 10 11 16 am](https://user-images.githubusercontent.com/246122/31287639-22f0c4ce-aa7f-11e7-99c1-205f2c6cf2cd.png)

The example is contrived, but users have done weirder things, and we have to protect against XSS attacks.

We provided escaped text for the category when building our MMenu:

![screen shot 2017-10-06 at 10 22 56 am](https://user-images.githubusercontent.com/246122/31287946-4ec30f48-aa80-11e7-874d-547ce0cd5b8f.png)

However, when we use search, the divider displays the text unescaped:

![screen shot 2017-10-06 at 10 11 28 am](https://user-images.githubusercontent.com/246122/31287982-6d6ee48a-aa80-11e7-97d0-910cdb1e7bf8.png)

## Cause

I believe this line to be the cause:
https://github.com/FrDH/jQuery.mmenu/blob/1135b590d59e64f4fe6379e47b22d8410f36556e/src/addons/searchfield/jquery.mmenu.searchfield.ts#L333

```
$itms.add( '<li class="' + _c.divider + '">' + $(this).children( '.' + _c.navbar ).children( '.' + _c.title ).text() + '</li>' );
```

The divider is pulling it's content from the child element with the `text()` method. This provides the unescaped, human-readable string. This is then dumped into the list item as HTML, effectively unescaping a string.

## Solution

Changing `text()` to `html()` will pull the original, unescaped content.

**Comment by FrDH** [comment]
Thank you for reporting the issue, I'll have a look at it shortly.
I remember there was an issue before where the icons (`<i class="fa fa-home"></i>`) were escaped. Hopefully we can keep escaped text escaped and unescaped text unescaped :)

**Comment by FrDH** [comment]
Keep an eye out for the next release, it should fix this issue.
