### ISSUE TITLE
Error in example on site?

### ISSUE THREAD

**Issue by srivest** [FrDH/jQuery.mmenu#807]
[](http://mmenu.frebsite.nl/examples.html)

When I copy this example in a text editor, load the file in a browser, there is no "menu" button to click. What am I missing? 

I've changed the code to:
  
`<a href="#menu">Demo</a>`

So I can at least click on an element to trigger the menu to show.    

![2017-10-10_11-54-13](https://user-images.githubusercontent.com/997746/31364711-54a33430-adb2-11e7-9f42-5c43c53e1007.png)

**Comment by FrDH** [comment]
The example uses additional CSS to style the anchor like a hamburger-icon. 
Simply copy/pasting the example HTML into a text editor will probably not be enough to get things working. If you want, you can use the CSS from the demo files included in the (GitHub) download.

**Comment by srivest** [comment]
Where is the link to the demo files? thanks
