### ISSUE TITLE
Search when keypress to 3 character inserted

### ISSUE THREAD

**Issue by jorgemarioco** [FrDH/jQuery.mmenu#809]
I would like the search engine of the menu, search after the 3 character, because I have a lot of information and it gets slow when searching

Something like this ... but I do not know how to put it in the code of mmenu

```
$("#menu").find( ".mm-search input" ).on( "keyup", function() {
        if($(this).val().length > 3){
              code execute... 
        }
});
```
Please, help me.

**Comment by FrDH** [comment]
To do so, I guess you could prevent the input from doing the search like this:
````js
$('body').on( "keyup", "mm-search input", function( e ) {
    if ( $(this).val().length < 3 ) {
        e.stopImmediatePropagation();
    }
});

//  Note that you must do the above BEFORE firing the mmenu plugin.

$("#my-menu").mmenu();
````
Hope this helps.

**Comment by jorgemarioco** [comment]
Thank you very much for answering me quickly.

It is a great idea, but the thing is that it seems that the search triggers, in another event other than keyup, try with keypress and keydown, but only managed to block write.

It seems that the search fires when the value of the input changes, but I have no idea, in which event executes the search

**Comment by FrDH** [comment]
I had a look at the source, the search if triggered onkeyup and onchange:
https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/searchfield/jquery.mmenu.searchfield.ts#L411
https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/searchfield/jquery.mmenu.searchfield.ts#L420

**Comment by jorgemarioco** [comment]
Thank you very much, with this if I can solve what I needed.
