### ISSUE TITLE
Backbutton should open the parent menu panel instead of closing the menu

### ISSUE THREAD

**Issue by mywebstuff** [FrDH/jQuery.mmenu#810]
Hi!

I have the following feature request: I think that it would be much more sensible if the backbutton would only close the menu if you're in the "root" menu, but in any submenus it should just "go one up", meaning that it should open the parent menu panel.
For example right now I'm building a site in which we would use mmenu for a search functionality. I have the root panel set to contain the main search parameter options as a submenu link (like the "Set date" menu item opens the "#date" submenu and so on). When the user sets the date inside a submenu and clicks on the backbutton the "root" menu should appear where they could set additional search parameters.

I may be missing something about the backbutton functionality, though.

P.s.: sorry for using this terminology, I hope you can follow :)

**Comment by FrDH** [comment]
Good news, the next version will be able to close opened submenus using the back-button.

**Comment by FrDH** [comment]
Keep an eye out for the next release, should fix this issue
