### ISSUE TITLE
Fixed header not sliding out in Internet Explorer

### ISSUE THREAD

**Issue by stephenpurkis** [FrDH/jQuery.mmenu#812]
Apologies if this is covered elsewhere. I am a beginner and would appreciate some assistance.

If I create a position:fixed header to contain my "hamburger"  all seems well on any phone and in Chrome or Firefox but the header remains in place (doesn't slide out) in Internet Explorer. This makes nonsense of the lovely animated hamburger and obscures the top part if the menu. Also, I find I need to add the javascript to activate the animation at the foot of the page, not in the header where it doesn't work for me. I simply don't understand!

What I'm after is a header that remains page top at all times (but that slides), the animated hamburger and a few options such as the "dark theme", "page dim" etc for the look I'm after.

Apologies again if I am posting in the wrong place or inappropriately. I have spent ages trying to follow the tutorials and demo pages...

Very best wishes

Stephen

**Comment by FrDH** [comment]
Have you tried the "fixedElements" add-on? All you need to do (assuming you're including the ".all" js and css files), is add the classname "Fixed" to the elements with `position: fixed;`.

For more info on using options, extensions and add-ons, I'd suggest reading the documentation:
http://mmenu.frebsite.nl/documentation/core/options.html
http://mmenu.frebsite.nl/documentation/extensions/
http://mmenu.frebsite.nl/documentation/addons/

Hope this helps.

**Comment by stephenpurkis** [comment]
Thanks so much for your help. I have now managed to get roughly what I am after. The only issue I have now is that the animated "hamburger" when transformed to the "x" does not close the slide out. Think something to do with my header "top-nav" so have left in the clear in the code below. I should also mention again that including the menu script in the head section of the page doesn't work for me? Very best wishes. Stephen

--------------------------------------------------
<!DOCTYPE html>
<html>
<head>
<title>Attymass Parish. Co. Mayo Ireland</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  
   <script src="jquery.js" type="text/javascript"></script>
   <script src="jquery.mmenu.all.min.js" type="text/javascript"></script>
   
   <link href="jquery.mmenu.all.css" type="text/css" rel="stylesheet" />
   <link href="hamburger.css" type="text/css" rel="stylesheet" />

<style type="text/css">.top-nav {
	position: fixed;
	width: 100%;
	z-index: 99999;
	background-color: #808080;
	top: 0px;
	left: 0px;
	right: 0px;
	
}
button:focus {
     outline:none;
}
</style>

</head>

<body>
   <div id="main-content">
    

<div class= "top-nav Fixed">
  
   <button id="my-icon" class="hamburger hamburger--collapse" type="button">
   <span class="hamburger-box">
   <span class="hamburger-inner">
   </span> </span>
   </button>

</div>

<div id="my-content">
Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>T

est<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>Test<p>
      <div id="my-footer">footer</div>
   </div></div>
<nav id="my-menu">
   <ul>
      <li><a href="/">Home</a></li>
      <li><span>About us</span>         <ul>
            <li><a href="/about/history/">History</a></li>
            <li><a href="/about/team/">The team</a></li>
            <li><a href="/about/address/">Our address</a></li>
         </ul>
      </li>
      <li><a href="/contact/">Contact</a></li>
   </ul>
</nav>

 <script type="text/javascript">
var $menu = $("#my-menu").mmenu({
   //   options
 "extensions": [
                  "pagedim-black",
                  "theme-dark"
               ],
               "counters": true,
               "iconPanels": true
            
});
var $icon = $("#my-icon");
var API = $menu.data( "mmenu" );

$icon.on( "click", function() {
   API.open();
});

API.bind( "open:finish", function() {
   setTimeout(function() {
      $icon.addClass( "is-active" );
   }, 100);
});
API.bind( "close:finish", function() {
   setTimeout(function() {
      $icon.removeClass( "is-active" );
   }, 100);
});</script>		
</body></html>

**Comment by FrDH** [comment]
By default, the plugin places a `DIV#mm-blocker` over the page while the menu is opened. Clicking this DIV will close the menu.
Try changing some `z-index`s to position the `DIV#mm-blocker` over your animated hamburger.

If for some reason that doesn't work, you could also change the `href` of the hamburder so it targets the "page":
````js
var $menu = $("#my-menu").mmenu();
var API = $menu.data( "mmenu" );

API.bind( "open:start", function() {
    $("#my-icon").attr( "href", "#my-page" );
} );
API.bind( "close:start", function() {
    $("#my-icon").attr( "href", "#my-menu" );
} );
````

You do not need to include the JS files in the `<head>`, at the end of the `<body>` should work just as good.

**Comment by stephenpurkis** [comment]
Great. Setting my header with the hamburger in too z-index: 1; solves that problem. I am extremely grateful for your help and hope this little conversation will assist others.
