### ISSUE TITLE
No way to get to parent page link if it has submenu.

### ISSUE THREAD

**Issue by Stiofan** [FrDH/jQuery.mmenu#813]
If you have a parent link and it has sub menus then you can't get to the main page link.
I would suggest it auto adds the parent to the top of the sub menu? Or maybe you have a better solution?

**Comment by FrDH** [comment]
I don't think I understand the question, each panel has a "navbar" prepended to it with an anchor that links to the parent panel inside it.

![schermafbeelding 2017-10-17 om 19 31 02](https://user-images.githubusercontent.com/1387163/31679601-e6918c56-b371-11e7-872d-d7c0052ec1f8.png)

**Comment by Stiofan** [comment]
Thanks for the reply.
We use your script only on mobile widths, we also have it as a main menu.
If we take one of your examples http://mmenu.frebsite.nl/demo/index.html?demo=playground
Say for example the "About us" was an actual link to about.html there would be no way to reach that page but on desktop our menu you would be able to navigate to about.html and view the sub menu items.  Am i missing something?

**Comment by FrDH** [comment]
Have you tried it?
If "About us" was an actual link, it will be clickable. In the examples "About us" isn't clickable because they use a `<span>` instead of an `<a>`.

**Comment by Stiofan** [comment]
We are using an a tag but it does not work like that.
We are using it here: https://wpgeo.directory/starter/
The problem might be we are using it in a free WordPress theme and we have to use older version that has the GPL compatible licence, specifically we are using 4.7.5 (i'm sure the early 5.0+ versions that are GPL compatible had a bug we could not live with so we have to ship with 4.7.5)  
I just wanted to check with you first to see if this was something that had a setting or fix, or if i should fork  an old version?
Thanks for your time!

**Comment by FrDH** [comment]
I can't remember it ever worked like that, anchors have been clickable since the very first release.
Could it be someone changed the CSS?
Here's some CSS you can add to fix the issue:
````css
.mm-list a.mm-subopen {
    width: 40px;
}
````

**Comment by FrDH** [comment]
p.s. After purchasing a license, the "non-commercial" part of the CC license no longer applies, making the license compattible with GPL. I realise this is a pretty odd construction and am thinking about changing the license to GPL in the future.

**Comment by Stiofan** [comment]
You might be right, we have several devs working on the product, if i remember a customer complaining that if u have a menu link that just links to the "#" (all WP menus items need to link to something) then it would just close the mmenu and not open the sub menu so maybe someone implemented a css "fix".  If you have no way or plans for a # link to be able to open a submenu then we might have to add something with JS to fix it.

On the licencing topic, i'm not sure how that would work with the WordPress repo, things have to be fully GPL compliant to be accepted.  We changed all our products to GPL many years ago and it was a great success for us, i hope you will do the same in the near future so we can make great use of your products :)
