### ISSUE TITLE
Please provide an example of how menu can be revealed by sliding in view

### ISSUE THREAD

**Issue by tsarma** [FrDH/jQuery.mmenu#814]
On the page http://mmenu.frebsite.nl/on-and-off-canvas.html, it is mentioned that "**In other forms, the menu can be revealed by sliding in view, hiding the page behind it**", instead of sliding the page out of view . Can you please provide an example of that.

We have recently bought a multiple website license. But now, i need to change the way menu is revealed, can you please help.

**Comment by FrDH** [comment]
By setting the `offCanvas.zposition` option to `"front"`:
````js
$("#my-menu").mmenu({
   offCanvas: {
      zposition: "front"
   }
});
````

Just a quick notice, currently this also requires the "positioning" extension to be included, in the next release it will be completely extracted out of the "offCanvas" add-on.


http://mmenu.frebsite.nl/documentation/core/off-canvas.html
http://mmenu.frebsite.nl/documentation/extensions/positioning.html

**Comment by tsarma** [comment]
Thanks if does the trick

**Comment by tsarma** [comment]
Thanks it does the trick
