### ISSUE TITLE
Not working for me on iOS Safari or iOS Chrome

### ISSUE THREAD

**Issue by mywebstuff** [FrDH/jQuery.mmenu#816]
Hi!
I'm working on a site here: [officesport.hu](https://officesport.hu). On mobile I'm using three instances of mmenu. They all work good on Andorid browsers, but they don't seem to work on any iOS browsers I have tested it (Safara, Chrome). I don't have access to a Mac to debug the issue. Do you have any idea why this is happening?

Thanks in advance!

**Comment by FrDH** [comment]
Hi,

I just checked on my iPhone (Safari, Chrome and FireFox) and all three menus seem to be working as intended. Shouldn't matter much I think, but what version of iOS are you on?

Regards, Fred

**Comment by mywebstuff** [comment]
That's odd. Both phones was on iOS version 11.0.3.

**Comment by FrDH** [comment]
Hmm, I just revisited the site and this time the menu’s didn’t work... I’ll check with the debug tools later on.

**Comment by mywebstuff** [comment]
Hi!
I found the issue! :) It seems that it's not enough to add a `defer` tag on the main script, it's important for jQuery to run in a `$(document).ready()` block.
This also means that the problem was not with the plugin :)
Thanks for your help and your time spent on this issue!
