### ISSUE TITLE
Wordpress plugin, can't install

### ISSUE THREAD

**Issue by ithilethiel** [FrDH/jQuery.mmenu#818]
Hi! Has anyone had the problem of not being able to install the plugin on wordpress? I couldn't find any topics on github for this

I get this message:

Installing Plugin from uploaded file: mmenu.zip
Unpacking the package…
**Could not create directory.**

Wordpress version is Version 4.8.3 (fresh install)

Thanks in advance!

**Comment by FrDH** [comment]
Can you extract the .zip file manually?

**Comment by geckoseo** [comment]
That sounds like it it might be a permissions problem on your server. I've had no problem uploading the zip file as a plugin, also using WP 4.8.3

**Comment by ithilethiel** [comment]
Thank you! I will install it by uploading the folder and files directly :)
