### ISSUE TITLE
Is the API accessible when using the WordPress plugin? 

### ISSUE THREAD

**Issue by geckoseo** [FrDH/jQuery.mmenu#819]
Hi, the WP plugin works great, but is fairly limited out the box in comparison to the full jQuery version.

The big advantage of the WP version is that it allows us to hook into the Walker menu class and display our WP menus.

Before I start ripping things apart to add some of the options I see in the demos, can you advise me if the API can be used to its full capabilities in WordPress?

I have a reasonable level of proficiency in jQuery in terms of WP, so enqueueing scripts etc is no problem, but I'm struggling to find any detailed WP specific documentation for the API.

Thanks

**Comment by FrDH** [comment]
The API is stored in the data-mmenu attribute, you should be able to access it:
````js
var API = $(".wpmm-menu").data( "mmenu" );

API.open();
````

Hope this helps.

**Comment by geckoseo** [comment]
Thanks, I'll look into it. Unfortunately we ran into some problems with the fixed elements on the site and have run out of time for the moment, but I really like the clean simplicity of how it works so will try again when time permits.
