### ISSUE TITLE
How to switch off auto open on page load

### ISSUE THREAD

**Issue by jskibbe** [FrDH/jQuery.mmenu#822]
Hi,
every time I load a page using mmenu the menu automaticaly appears after a second. How do I switch this off? I want the menu to appear ONLY after clicking on the menu button. 
Thanks & regards

**Comment by FrDH** [comment]
The menu only opens if the url contains a hash that points to the menu, this is so the menu will open even if the user clicks the button before the menu was created.
If you remove the hash from the url, the menu should not open on pageload.

**Comment by ayoubkhan558** [comment]
I did not understand what you said, Please explain in detail. Thanks in advance.

**Comment by AlymAleksey** [comment]
> The menu only opens if the url contains a hash that points to the menu, this is so the menu will open even if the user clicks the button before the menu was created.
> If you remove the hash from the url, the menu should not open on pageload.

It was so easy. But I spent the whole evening looking for a solution. thank
