### ISSUE TITLE
Menu activates wrong item

### ISSUE THREAD

**Issue by dirckwaterschaats** [FrDH/jQuery.mmenu#823]
I have a menu like this:
```
home
item-1
  - subitem 1
  - subitem 2 [link: /item 3]
item 2
item 3
```
When I click the link from the subitem 2 which links to item 3  the menu opens in the second level with subitem 2 selected while it should select item 3 because thats where it is now.

How can I change this?

**Comment by FrDH** [comment]
The menu selects the menu item that has the class "Selected" (or to whatever the config option has been set). Are you sure the HTML is correct?

**Comment by dirckwaterschaats** [comment]
Sorry, you're right. The menu had two "selected" Classes and just activated the first occurence.
