### ISSUE TITLE
Setting "openingInterval" does not work

### ISSUE THREAD

**Issue by davidenco** [FrDH/jQuery.mmenu#824]
Using the code below, I want to remove the sliding open/close animation effect. By using the code below as per the documentation, the animation still occurs. I have also tried setting "transitionDuration" but to no avail.

Any ideas?

```
$("#fmenu").mmenu(
    {
        offCanvas: {
            position: 'top',
            zposition: 'front'
        },
        extensions: [
            'listview-large'
        ]
    },
    {
        openingInterval: 0
    }
);
```

**Comment by FrDH** [comment]
The `openingInterval` configuration option is used to add some time between certain actions, for example when opening the menu. It does not remove any animation. The `transitionDuration` configuration option is used to  should calibrate the CSS animation with a JS timeout. If you also build a custom build where you override the SCSS variable to be `0`, that should work.

But I'd suggest using the `panels-none` effect in [the effects extension](http://mmenu.frebsite.nl/documentation/extensions/effects.html)

````js
$("#my-menu").mmenu({
    extensions: [ "fx-panels-none" ]
});
````

Hope this helps
