### ISSUE TITLE
Bootstrap Wrapper for Version 4

### ISSUE THREAD

**Issue by SiteGefuehl** [FrDH/jQuery.mmenu#828]
Hi Fred, 
i tried your mmenu with a navbar of Bootstrap 4. Sadly it's not working. 
When I click on the navbar-toggler there are missing classes in the html tag (and maybe more). 
We bought a multiple licence and we would be happy, if you can publish a wrapper for bootstrap 4. 

Thank you!

**Comment by FrDH** [comment]
Thank you for bringing it to my attention, a wrapper for Bootstrap 4 is on its way :)

**Comment by FrDH** [comment]
Keep an eye out for the next release, it includes a Bootstrap 4 wrapper.
