### ISSUE TITLE
Logo not showing on mobile

### ISSUE THREAD

**Issue by gleenk** [FrDH/jQuery.mmenu#829]
Hi guys, with latest WP release, logo is not showing on mobile, i can see it with inspector / devtools but on native mobile it disappear. How to fix that? (problem is related to svg only)

**Comment by FrDH** [comment]
Hi,

Thank you for bringing this to my attention, the WP plugin needs to be tested with the latest WP anyway, so I'll have a look at it later on.

Regards

**Comment by gleenk** [comment]
FrDH, the only problem is caused by SVG, i suggest you not to put logo as background image but as a <img>. Is it possible? Ty for your work

**Comment by FrDH** [comment]
SVG images can be used as background images, can they not?

**Comment by gleenk** [comment]
Yes in theory but not with MMenu for wp, if you upload an SVG (having plugin such svg support) it doesn't appear on mobile

**Comment by FrDH** [comment]
Does this problem occur on all mobile devices in all browsers, or just some specific combinations?
Also, are you sure the .svg itself isn't broken? Have you tried other .svg images?

**Comment by gleenk** [comment]
It happens on all mobile devices, tested chrome and safari (mobile). Svg not corrupted

**Comment by FrDH** [comment]
Is this issue still relevant? I tried uploading some image including svg images but could not get it to not work.

**Comment by gleenk** [comment]
I haven't tested it longer with svg. With PNG it works.
