### ISSUE TITLE
Not documented hooks for open/close menu

### ISSUE THREAD

**Issue by Storky** [FrDH/jQuery.mmenu#830]
Hi,
http://mmenu.frebsite.nl/documentation/core/api.html
hooks listed there is working only for inner panels (2nd,3rd lvl ULs)
To hook on open/close mmenu itself I used this:

    api.bind('open:start', function () {
        console.log('open:start');
    });
    api.bind('open:finish', function () {
        console.log('open:finish');
    });

    api.bind('close:start', function () {
        console.log('open:start');
    });
    api.bind('close:finish', function () {
        console.log('open:finish');
    });

I installed via bower, maybe there is an issue. Than tried to connect the "jquery.mmenu.all.js" over bower's  from the "download button" and it doesn't helped.

**Comment by FrDH** [comment]
> Note that add-ons might have their own set of API methods and hooks.
The hooks for the off-canvas add-on are documented on the off-canvas add-on page:
http://mmenu.frebsite.nl/documentation/core/off-canvas.html#h4

**Comment by Storky** [comment]
Thank you!

**Comment by datune** [comment]
Perhaps a "Note: ..." would be useful, it took me about an hour until I realised...

**Comment by FrDH** [comment]
From the [API docs](https://mmenu.frebsite.nl/documentation/core/api.html):
> Note that add-ons might have their own set of API methods and hooks.

**Comment by datune** [comment]
@FrDH 

The main menu is considered to be an addon? 

Either way, I would suggest adding a note to the panel Api docs referencing the offcanvas addon specifically. I was pulling my hair wondering why binding to any event did not trigger...

Anyway, if you have a doc repo I‘d be happy to contribute...

**Comment by FrDH** [comment]
I realize it's a bit odd, but the off-canvas behavior is indeed considered to be added behavior.
The API page contains 3 notes about add-ons having their own set of api hooks and methods:
> Note that add-ons might have their own set of API methods and hooks.
> Note that add-ons might have their own set of API methods.
> Note that add-ons might have their own set of API hooks.

I guess I could add some specific note about the off-canvas add-on, but would that really make the difference? What would you suggest?

**Comment by datune** [comment]
@FrDH It's indeed a bit tricky and probably needs an overall terminology improvement. To me, everything seemed to be a panel. But it seems there is a difference between the root panel (off-canvas) and all other inside panels. Perhaps this is where the problem originates? 

The tricky bit, is that, when reading only the panel docs, api.close(); still produces the expected result, so naturally, I have no reason to believe I am reading the wrong piece of documentation. Once you try to bind to events, is where the hair pulling begins ;-)

I am not sure how to best word all of this. Somehow the difference between the root panel and inside panels needs to be made clear, and that they have different API's (which is a bit confusing to begin with).

PS: Don't get me wrong, I don't mean to belittle any of your work, quite the opposite really, I LOVE your work! I
