### ISSUE TITLE
Usage with Bootstrap

### ISSUE THREAD

**Issue by tanc** [FrDH/jQuery.mmenu#831]
Just wondering if you have any examples of mmenu working with Bootstrap? I've seen the Bootstrap framework wrappers docs but its not clear to me what the javascript fixes do.

Ideally I'd like to see an example of how to instantiate an mmenu on a Bootstrap menu and which options should be enabled.

**Comment by FrDH** [comment]
The "what's new" page has a working example of the Bootstrap wrapper:
http://mmenu.frebsite.nl/whats-new.html
http://mmenu.frebsite.nl/demo/index.html?demo=bootstrap-navbar

**Comment by tanc** [comment]
Perfect, thank you

**Comment by hohll** [comment]
Have you a working example for bootstrap 3 wrapper. I'am using BS 3.3.7 and the last Mmenu version with the "bootstrap3" wrapper but it doesn't work at all !? Thanks
