### ISSUE TITLE
Bootstrap wrapper compatibility with non-standard menu markup

### ISSUE THREAD

**Issue by tanc** [FrDH/jQuery.mmenu#833]
I'm experimenting with the Bootstrap wrapper and a Bootstrap Drupal theme and noticed that the toggle icon wasn't getting the proper mmenu handler assigned to it. This is because the Drupal theme adds more divs around the navbar-nav list and therefore isn't a direct child of the navbar-collapse element.

I created a pull request (#832) which switches to using 'find' rather than 'children' to search deeper in the nested elements for the navbar-nav class.

**Comment by FrDH** [comment]
Fix will be available in the next release. Thanks
