### ISSUE TITLE
keyboardNavigation appends tabindex=0 to labels

### ISSUE THREAD

**Issue by jaffadog** [FrDH/jQuery.mmenu#834]
I have a form with input fields in my mmenu nav. when I enable keyboardNavigation, not only do the inputs get tabindex=0, but also the labels - resulting in an undesirable user experience.

**Comment by FrDH** [comment]
Thank you for bringing this to my attention. I'll have a look at it shortly.

**Comment by FrDH** [comment]
I had a look at why the keyboard navigation add-on adds `tabindex="0"`. It is to ensure only visible tabbable elements inside the current panel are tabbable. It adds `tabindex="-1"` to all other tabbable elements.
I'll see if I can work around this fix.

**Comment by jaffadog** [comment]
While labels are visible, they normally are not table in a form. I also tried to explicitly set my labels to `tabindex="-1"`, but the plugin overrides this and sets them to `tabindex="0"`

**Comment by FrDH** [comment]
Dug a little further and am wondering why the tabindex needed to be set at all, the keyboard navigation add-on seems to be working fine without the altered tabindexes.

**Comment by FrDH** [comment]
I've removed the added tabindex in the next release. Should fix this issue.

**Comment by FrDH** [comment]
Try version 7.0.0, should have fixed the issue.
Let me know if not adding a tabindex causes other issues.
