### ISSUE TITLE
Specific 3rd party plugin (snapengage) being killed when mmenu loads

### ISSUE THREAD

**Issue by dpotter-snapshot** [FrDH/jQuery.mmenu#835]
So we're trying to use "snapengage" as a chat provider and having trouble that I've traced down to only being caused when Mmenu loads, only in IE (not Edge). The JS-built iframe html that the snapengage button uses will get blown away with no console errors or warnings. No other CSS is touched.

What could be causing this? It does the same thing with or without any extensions or options turned on. I've upgraded to the latest version with no change in behavior.

I'm trying to work around it now by providing a different menu for just IE that plays nicely with snapengage, but I wanted to get the issue noted in case anyone knows of anything similar I can look up.

Thanks!

**Comment by FrDH** [comment]
Problem with other chat scripts often is, they add a DIV to the DOM that mmenu wraps in a new DIV, causing the <SCRIPT> inside it to fail. Please read [this page](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html) from the tutorial.

The fix for the Olark chat was to add `"#olark"` to the `offCanvas.noPageSelector` configuration option:
````js
$("#my-menu").mmenu({
   // options
}, {
   // config
   offCanvas: {
      noPageSelector: [ '#olark' ]
   }
});
````

**Comment by FrDH** [comment]
Any update on this? Or should I close the issue?

**Comment by dpotter-snapshot** [comment]
we decided we didn't need mmenu for IE since we're just using it for our mobile menu and old IE doesn't have a mobile market share. we just don't initialize mmenu for old IE and that solved the problem. 

hopefully your solution will help others. that sounds very much like it might have been the right answer. thanks!
