### ISSUE TITLE
Mobile Safari fixed bottom bar covers nav fixed footer items

### ISSUE THREAD

**Issue by DanHashemi** [FrDH/jQuery.mmenu#837]
Amazing plugin!

So we've added in a fixed footer item in the slide out navigation, but when you have Safari open on an iPhone, you get that bottom fixed bar that has the back icon, forward icon, bookmark icon and new page icon. When that bottom safari bar is visible, it covers the fixed footer item in the navigation slide-out.

The only time this isn't an issue is if the user first scrolls a bit so that Safari hides that fixed bottom bar and then they click to show the slide out navigation. But if the user scrolls back in the up direction, Safari again re-displays that fixed bottom bar and again, if the user wants to see the slide out nav, the fixed footer inside it gets covered.

Is there anyway to get around this?

Thanks!

**Comment by FrDH** [comment]
Sounds like an issue with how mobile safari calculates `100vh` (it doesn't include that bottom fixed bar). Although this sounds odd to most, they actually say it is intended behavior:
https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html

I tested but could not reproduce the issue with the menu on mmenu.frebsite.nl
Is there an online example I could have a look at?

**Comment by DanHashemi** [comment]
Thanks for the quick reply!
After a few css adjustments, we were able to get it working.

Really awesome plugin...just did some testing to see if it matches what we need and will be purchasing the license shortly.

**Comment by davidmaxwaterman** [comment]
"few css adjustments"? What were they?

**Comment by huvijudo** [comment]
if you use position: fixed; let try height: 100%; instead. it works to me.

**Comment by healer-1205** [comment]
Hello, everyone, I also meet such this problem. Mobile Safari address bar cover my footer navbar.
But Mobile Chrome mode, it appears well.
How can fix this problem?
Please help me asap.
