### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stpaulme** [FrDH/jQuery.mmenu#840]
Getting this error when I try to setup the plugin after activation:

Notice: Undefined index: license in /var/www/rid.stpaulmedia.com/htdocs/wp-content/plugins/mmenu/php/mmenu_backend.php on line 200

**Comment by FrDH** [comment]
I'll see if I can fix this issue shortle, thank you for bringing it to my attention.

**Comment by FrDH** [comment]
Should be fixed in 2.7.1
If you have a license-key (you should have received one after purchasing a license), enter it in the settings page.
