### ISSUE TITLE
Need help: parallax for a single photo using background-attachment: fixed

### ISSUE THREAD

**Issue by madiko** [FrDH/jQuery.mmenu#841]
Dear Fred,

first of all: Thank you for the great tool box! I am very happy over all and looking forward to implement it in all my future web presentations. To do that, I created an prototype (html, js, css and so forth) with all the needed modules.

Your documentation is great and helped me a lot. Unfortunately I encounter an issue, I could not find in your tutorials / descriptions: PARALLAX for a single photo, that uses background-attachement: fixed.

**It works fine as long the menu is collapsed. As soon as the menu is in plain view, parallax doesn't work any more.**

http://prototyp-nav.rex-master.de/fotos_parallax_rows_with-sidebar.html

My html-code is pretty simple:

`<div class="row">// further code containing text</div>`

//that's the parallax module
`<div class="parallax Fixed" style="background-image: url();"></div>`

`<div class="row">// further code containing text</div>`

... and the css:
`.parallax {
	height: 100vh;
	background-attachment: fixed;
	background-position: center;
	background-repeat: no-repeat;
	background-size: cover;
}`

Further documents to specify the code I use (above your data for "all" of course):
http://prototyp-nav.rex-master.de/layout/css/nav-mmenu.css
http://prototyp-nav.rex-master.de/layout/js/madiko/madiko_js_mmenu_header_default_new.js

Any ideas? I would very much appreciate a point of direction.
May I kindly add: I am a novice to jquery and still learning.

Thank you very much in advance.

Best regards,
Franziska

PS: Hope, this finds you well as today blew a quite windy "Friederike" through Europe.

**Comment by FrDH** [comment]
Well I think I know why it behaves like that, but I don't think there is a (easy) solution.
When the menu opens, the page is moved out of view using `transform: translate3d()`. This creates a containing block for all its positioned descendants (and apparently fixed positioned backgrounds). 

Some info from https://developer.mozilla.org/en-US/docs/Web/CSS/All_About_The_Containing_Block:
> If the position property is absolute or fixed, the containing block may also be formed by the edge of the padding box of the nearest ancestor element that has the following: 
• A transform or perspective value other than none

You could try to use the "position-front" extension, that sets `transform: none;` to the page, so it will not turn into a containing block. I'm not sure that'll play well with the sidebar add-on though :/
