### ISSUE TITLE
Conflicting with Barba - a way around it?

### ISSUE THREAD

**Issue by DanHashemi** [FrDH/jQuery.mmenu#842]
So we wanted to utilize Barba (http://barbajs.org/index.html) to create smooth AJAX driven transitions between page loads...but this doesn't work with mmenu since once the document is ready, mmenu shifts the placement of things in the DOM.

We can get Barba to work properly, but then the menu doesn't load properly.
Once the page comes up with Barba, if we refresh it, the menu shows up.

Is it possible to call the menu again once Barba has finished to activate it?

**Comment by FrDH** [comment]
I'm not that familiar with barba, but I guess it has the same issue other PJAX libraries (like turbolinks and instantclick) have with mmenu. 
There's a turbolinks wrapper that might give you some insight about how to fix the issue:
[documentation](http://mmenu.frebsite.nl/documentation/wrappers/turbolinks.html), [code](https://github.com/FrDH/jQuery.mmenu/blob/master/src/wrappers/turbolinks/jquery.mmenu.turbolinks.ts)
