### ISSUE TITLE
Sidebar replacing widescreen - way to control menu width

### ISSUE THREAD

**Issue by youngcrv** [FrDH/jQuery.mmenu#844]
The sidebar menu width seems to default to 440px.  I can adjust the menu width using the custom build technique, however there doesn't seem to be a setting for the sidebar's menu width.

**Comment by FrDH** [comment]
You can set the size of the exanded sidebar using the `sidebar.sidebar.size` option. By default you can set it to 25, 30 or 35 %.
To override these values, try chaning the `$mm_sidebarExpandedSizes` SCSS variable in a custom build (I just noticed the documentation is incorrect about its default values).

Note that (for now), this value is always in percentages.

Hope this helps.

**Comment by youngcrv** [comment]
Thank you for the quick reply.  Using your clarification I was able to solve my issue.
