### ISSUE TITLE
Mmenu tabbing issues

### ISSUE THREAD

**Issue by KevinPark89** [FrDH/jQuery.mmenu#847]
Hi there,

I have enabled the 'Dropdown' add-on using the class of 'Vertical' on some of my ul's in my mmenu's.

However, even though I have Keyboard Navigation enabled and enhance set to 'true', I have been experiencing some difficulty tabbing through the menu.

I have changed the focus to my liking (font color changes on focus rather than background) and everything works well until I open one of the 'Dropdown' menus. Once one of the dropdown menu's is opened, it will successfully tab through it, but I am not able to tab OUT of it. 

When I continuously click the Tab key, it just goes on an infinite loop through the dropdown menu content.

If anyone has encountered this, is there a fix for it?

Thanks!

**Comment by FrDH** [comment]
Hi,
I had a look at the keyboard navigation source but could not find a reason for the behavior you described. Is there an online example I could have a look at?

**Comment by KevinPark89** [comment]
Hi there,

Sorry for the delay! 

Turned out to be a 'tabindex' issue, and changing the values resolved the issue.

This can be closed and I appreciate the response!
