### ISSUE TITLE
Browserify Import

### ISSUE THREAD

**Issue by kaspar-allenbach** [FrDH/jQuery.mmenu#848]
How di I have to import mmenu via Browserify?

`require('jquery.mmenu');` imports the mmenu javascript correctly but when I excecute it I get 

> jQuery.Deferred exception: $(...).mmenu is not a function

What's the catch here?

**Comment by FrDH** [comment]
I'm not sure, the UMD part is handled by [Gulp UMD](https://www.npmjs.com/package/gulp-umd), it results in this:
````js
;(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery'], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require('jquery'));
  } else {
    root.jquery_mmenu_js = factory(root.jQuery);
  }
}(this, function(jQuery) {
````

**Comment by FrDH** [comment]
If no further help is needed, I'm going to close this issue.
