### ISSUE TITLE
api is undefined when clone: true

### ISSUE THREAD

**Issue by mkrappitz** [FrDH/jQuery.mmenu#849]
Hi,

I'm using mmenu v6.1.8 and try to do some stuff with the api as follows and following the documentation at http://mmenu.frebsite.nl/documentation/core/api.html:

<pre>
// mmenu
var $menu = $('#main-nav');
$menu.mmenu({
   extensions: [
      'pagedim-black'
   ],
   offCanvas: {
      position: 'right',
      pageSelector: '#my-wrapper'
   },
   navbar: {
      title: '...'
   },
   navbars: [
      {
         position: 'top',
         content: [
            '<form method="post" id="mmsearch" action="...">...</form>',
            'close'
         ]
      }
   ]
}, {
    clone: true
});

var api = $menu.data('mmenu');
api.bind('open:finish', function () {
    $('#mm-1 ul.mm-listview > li:last-child > a:last-child').click(function (event) {
        event.preventDefault();
        return false;
    });
});
</pre>

The problem is that api is undefined. So $menu.data("mmenu") is not returning an instance of the api. How can that be? Am I doing something wrong?
So far I found out, that everything works when I remove the option part , { clone: true }. But we need that feature.
Tested also with mmenu master 7.0.0. Same behaviour.

**Comment by FrDH** [comment]
After firing the plugin with `clone: true`, $("#main-nav") is not the mobile menu (the clone is).
Try it like this:
````js
var $menu = $('#main-nav').mmenu({
    // opions
}, {
    clone: true
});

var api = $menu.data( "mmenu" );
````

Hope this helps.

**Comment by mkrappitz** [comment]
Yes, that was the solution. Thanks a million. Still this could be mentioned in the documentation about accessing the api though.
