### ISSUE TITLE
Please, check my code!

### ISSUE THREAD

**Issue by Egretta** [FrDH/jQuery.mmenu#850]
after adding navbars lines, code stopped working, what is wrong?

````js
$("#main-menu").mmenu({
               "extensions": [
                  "pagedim-black",
                  "position-right",
                  "theme-dark"
               ]
               }, 
                 "navbars": [
                       {
               "position": "top",
               "type": "tabs",
               "content": [
                  "<a href='#main-menu'>Menu</a>",
                  "<a href='#languages'>Language</a>"
               ]
            }
         ], {
              // configuration
                offCanvas: {
            pageSelector: "#my-page"
         },
               clone: true
            });
````

ps. navbars css and js files has been added

**Comment by FrDH** [comment]
Are there any errors in the console?

**Comment by Egretta** [comment]
chrome's code inspector agree: "Uncaught SyntaxError: missing ) after argument list"

could you please tell me, where i have to insert ) ? [my site](http://hostelsiiram.fi/)

**Comment by Egretta** [comment]
if i remove this part from code, error disappears

`  "navbars": [
                       {
               "position": "top",
               "type": "tabs",
               "content": [
                  "<a href='#main-menu'>Menu</a>",
                  "<a href='#languages'>Language</a>"
               ]
            }
         ], `

i don't get it...

**Comment by dutchenkoOleg** [comment]
@Egretta if you format the code, you will see an error.  
You closed the bracket (for the options object) in the wrong place.

try this

```js
$("#main-menu").mmenu({
    "extensions": [
        "pagedim-black",
        "position-right",
        "theme-dark"
    ],
    "navbars": [{
        "position": "top",
        "type": "tabs",
        "content": [
            "<a href='#main-menu'>Menu</a>",
            "<a href='#languages'>Language</a>"
        ]
    }]
}, {
    // configuration
    offCanvas: {
        pageSelector: "#my-page"
    },
    clone: true
});
```

**Comment by Egretta** [comment]
thank you, oleg, no syntax error anymore!
but could you tell me, why "language" tab not working?

**Comment by FrDH** [comment]
The `navbars` option can be an object (for a single navbar) or an array of objects (for multiple navbars). Both work just fine, if you only need one navbar you don't need to wrap the object in an array.

**Comment by Egretta** [comment]
thank you fred for explaining! i will give a try

**Comment by FrDH** [comment]
Please create a new issue if you have any further questions about the navbars add-on. I'm closing this one as it's original question has been answered.
