### ISSUE TITLE
openPanel:this hooks has been called already when i registered

### ISSUE THREAD

**Issue by Hansuku** [FrDH/jQuery.mmenu#852]
`$('#menu').mmenu({
              "extensions": [
                "pagedim-black",
                "position-right",
                "border-offset",
                "shadow-page"
              ],
              "navbar": {
                title: 'column'
              },
              "setSelected": true,
              hooks:{
                "openPanel:before": function( $panel ) {
                  alert('111');
                   console.log( "This panel is now opening: #" + $panel.attr( "id" ) );
                },
                "openPanel:after": function( $panel ) {
                  alert('111');
                   console.log( "This panel is now opening: #" + $panel.attr( "id" ) );
                },
                "openPanel:finish": function( $panel ) {
                  alert('111');
                   console.log( "This panel is now opening: #" + $panel.attr( "id" ) );
                }
              }
            });`
it's working in VUE , when i reload page , init mmenu , the hooks working now...
in fact , i think it's working when i open the mmenu........right?

**Comment by FrDH** [comment]
I’m not sure what the question is, but the ‘openPanel’ hooks are invoked when the menu is created because initially, all panels are closed.
