### ISSUE TITLE
position-right and drag

### ISSUE THREAD

**Issue by bench-artwork** [FrDH/jQuery.mmenu#855]
having the menu positioning on right and using the drag extension does not work on the latest 7.0 version.
Drag is still left to right. You can test it by add following to the onepage.html demo:

```
extensions: {
	'all': ['position-right']
},
```

**Comment by FrDH** [comment]
Hi thank you for reporting the issue, looked into it and found that how the drag add-on checks the set position is wrong.
I'll fix this in the next version.

**Comment by FrDH** [comment]
Should be fixed in 7.0.3
