### ISSUE TITLE
Navigation scrolling issue in iPhone

### ISSUE THREAD

**Issue by mateensalik** [FrDH/jQuery.mmenu#856]
Menu scrolling issue in iPhone. Please see here. 
How can I fix this issue?

**Comment by FrDH** [comment]
Could you please be a bit more specific? 
What do you mean with "menu scrolling issue".
Where is the menu located? (I visited the website but could not find any active menus created with mmenu)

**Comment by mateensalik** [comment]
![download](https://user-images.githubusercontent.com/34804494/36021723-7febb18e-0da8-11e8-9e02-0d8ccbbde53f.png)

**Comment by FrDH** [comment]
Thanks, but what do you mean with "menu scrolling issue"?

**Comment by FrDH** [comment]
I see what you mean, the menu isn't scrollable on touch devices (or at least iPhones).
First try updating to the latest version of the plugin, the issue might already have been fixed.

If that doesn't help, try removing all custom css for the menu (most probably the `margin-top` for the menu and `max-height` for the panels).

If that also doesn't help, try disabling the `scrollBugFix` add-on, it might be too enthusiastic about preventing unwanted default scrolling behavior :/

Hope this helps.
