### ISSUE TITLE
including searchfield.js and .css - not working

### ISSUE THREAD

**Issue by Flaschenzug** [FrDH/jQuery.mmenu#861]
Hi,

i just try to set up the mmenu with some add ons.
When I include the .all css and js it works fine.
`<link href="assets/components/mmenu/dist/jquery.mmenu.all.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/jquery.mmenu.all.js"></script>

      <script>
         jQuery(document).ready(function( $ ) {
            $("#ocmenu").mmenu({
               "iconPanels": true,
               "counters": true,
               
               "navbars": [
                {
                     "position": "top",
                     "content": [
                        "<a class='fa fa-home' href='#/'></a>",
                        "<a class='fa fa-shopping-cart' href='#/'></a>",
                        "<a class='fa fa-envelope' href='#/'></a>"
                     ]
                  },
                  {
                        "position": "top",
                        "content": [
                           "searchfield"
                        ]
                  }
               ],
               "searchfield": {
                    "panel": true
               }
            });
         });
      </script>`

But when I try to add the Add-ons manually, than the searchfield ist not displayed:
`<link href="assets/components/mmenu/dist/jquery.mmenu.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/jquery.mmenu.js"></script>

<link href="assets/components/mmenu/dist/addons/counters/jquery.mmenu.counters.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/addons/counters/jquery.mmenu.counters.js"></script>
<link href="assets/components/mmenu/dist/addons/iconpanels/jquery.mmenu.iconpanels.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/addons/iconpanels/jquery.mmenu.iconpanels.js"></script>
<link href="assets/components/mmenu/dist/addons/navbars/jquery.mmenu.navbars.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/addons/navbars/jquery.mmenu.navbars.js"></script>
<link href="assets/components/mmenu/dist/addons/searchfield/jquery.mmenu.searchfield.css" rel="stylesheet" />
<script src="assets/components/mmenu/dist/addons/searchfield/jquery.mmenu.searchfield.js"></script>

      <script>
         jQuery(document).ready(function( $ ) {
            $("#ocmenu").mmenu({
               "iconPanels": true,
               "counters": true,
               
               "navbars": [
                {
                     "position": "top",
                     "content": [
                        "<a class='fa fa-home' href='#/'></a>",
                        "<a class='fa fa-shopping-cart' href='#/'></a>",
                        "<a class='fa fa-envelope' href='#/'></a>"
                     ]
                  },
                  {
                        "position": "top",
                        "content": [
                           "searchfield"
                        ]
                  }
               ],
               "searchfield": {
                    "panel": true
               }
            });
         });
      </script>`

There is no error. All files are found.
The HTML Tag for the searchfield ist just empty:
`<div class="mm-navbar"></div>`

The other add-ons are working.

Any ideas? Any dependencies that I missed?
Thanks

**Comment by Flaschenzug** [comment]
css Files are also included. Actually I don't know why github is removing the files.
Wanted the whole thing to be in the code blocks. But its not working.

**Comment by FrDH** [comment]
The navbars add-on is split up in seporate files:
https://github.com/FrDH/jQuery.mmenu/tree/master/dist/addons/navbars

For the searchfield to work in a navbar, you need to include the " 	_jquery.mmenu.navbar.searchfield.js" file.

**Comment by Flaschenzug** [comment]
Perfect. Thanks!
Just in case that someone else struggles with the same thing.
This is how it works:
`mmenu/dist/addons/searchfield/jquery.mmenu.searchfield.css
mmenu/dist/addons/searchfield/jquery.mmenu.searchfield.js
mmenu/dist/addons/navbars/_jquery.mmenu.navbar.searchfield.js`
