### ISSUE TITLE
2 problems with tabs

### ISSUE THREAD

**Issue by Flaschenzug** [FrDH/jQuery.mmenu#862]
Hey,

actually I have to things that I can't solve. Don't know if it is a failure or if I just made something wrong.
After including the necessary js files, the tabs are display correct.

1. problem: When i click on the second tab, the menu is displayed like the second level menu from the original menu (but should be full size within the slider on the left?(:

![bildschirmfoto 2018-03-02 um 00 00 27](https://user-images.githubusercontent.com/2140638/36874606-d13d9728-1dac-11e8-8536-333eaf6431b1.JPG)

2. problem: When i navigate to a submenu within tab one (for example "fruits" > "banana", "apples"), click on tab 2 afterwards ("Language" Tab), than I can't go back to the main menu from tab 1. The overlay from tab one is kept alive. Even when I close the menu it is not working.

![bildschirmfoto 2018-03-02 um 00 00 48](https://user-images.githubusercontent.com/2140638/36874607-d1832ff4-1dac-11e8-969b-b834672691d5.JPG)

Any ideas? Thanks

here is my config:
> jQuery(document).ready(function( $ ) {
>             $("#ocmenu").mmenu({
>                extensions: ["pagedim-black"],
>                "iconPanels": {"add": true, "visible":1, "blockPanel":true},
>                "counters": true,
>                
>                "navbars": [                
>                   {
>                         "position": "top",
>                         "content": [
>                            "searchfield"
>                         ]
>                   },
>                   {
>                      "position": "top",
>                      "content": [
>                         "<a class='fa fa-home' href='#'></a>",
>                         "<a class='fa fa-shopping-cart' href='#' target='_blank'></a>",
>                         "<a class='fa fa-envelope' href='#'></a>"
>                      ]
>                   },
>                   {
>                         "position": "top",
>                         "type": "tabs",
>                         "content": [
>                             "<a href='#panel-page'>Menu</a>",
>                             "<a href='#panel-shop'>Language</a>"
>                         ]
>                   }
>                ],
>                "searchfield": {
>                     "noResults": "Keine Ergebnisse gefunden","panel": true, "placeholder": "Menü durchsuchen"
>                }
>             });
>          });

**Comment by FrDH** [comment]
Overall I think using the tabs combined with the iconPanels will result in behavior that feels odd or buggy.

The iconPanels add-on does not close an opened panel when opening a new panel, it basically assumes the already opened panel is the parent. 
On mmenu.frebsite.nl I ran into the same issue with the search panel: when focussing the searchfield, the search panel would be displayed as a submenu, I had to add `left: 0` for it:
```css
.mm-panel_search {
    left: 0 !important;
}
```
I guess you could do the same for `#panel-page` and `#panel-shop`, but it surely isn't an elegant solution. A better fix would be to close all opened panels before opening the new panel. I don't think you can do this without introducing new issues, I'd have to make some changes to the script.

I can't explain the second issue, is there an online example for it?

**Comment by Flaschenzug** [comment]
Thanks for your quick replies!

You're right. It's the same "problem" (issue) with the searchfield. It opens in the second panel.
So for the moment I am going to deactivate the iconPanels. CSS Workaround isn't working really well.

I guess the second issue is because the tabs are not closing the iconPanels.
Actually there is no online demo available, sorry.

**Comment by Flaschenzug** [comment]
Is there a way to change the 
> mm-navbar__title
for the individual tabs ?

Actually it is always "MENU". Would be great if it would be something individual for each tab.

**Comment by FrDH** [comment]
You can set the `navbar.title` option to be a function:
```js
$("#my-menu").mmenu({
   navbar: {
      title: function() {
         // "this" refers to the panel DOM node
         if ( $(this).is( "#my-panel" ) ) {
            return "My panel title";
         }
      }
   }
});
```

Note that the "panel" is not the UL, but the surrounding DIV. You might need to check for `$(this).children( "#my-panel" ).length`.

**Comment by Flaschenzug** [comment]
It's not working. But thats not to important. Thanks!

Is there a way to select the second / third tab as selected ?

**Comment by FrDH** [comment]
The tab that links to a (ancestor of) the current panel should automatically be selected. Adding the class "Selected" to a LI should do the trick:
http://mmenu.frebsite.nl/tutorials/off-canvas/styling-lists.html

**Comment by anjey58** [comment]
Such a solution to the problem 1.
Code piece:

`<nav id="menu">
    <div id="root-panel-menu">
        <ul>
        </ul>
    </div>
    <div id="root-panel-account">
        <ul>
        </ul>
    </div>
    <div id="root-panel-cart">
        <ul>
        </ul>
    </div>
</nav>`


`new Mmenu('#menu',
    {
        navbars: [
            {
                type: 'tabs',
                content: [
                  '<a href="#root-panel-menu"><i class="lnr lnr-home uk-margin-small-right"></i>Раздел 1</a>',
                  '<a href="#root-panel-account"><i class="lnr lnr-apartment uk-margin-small-right"></i>Раздел 2</a>',
                  '<a href="#root-panel-cart"><i class="lnr lnr-history uk-margin-small-right"></i>Раздел 3</a>'
                ]
            }
        ],

        hooks: {
            'openPanel:start': function(el) {
                if (el.id.indexOf('root') != -1) {
                    $(el).removeClass(function (index, css) {
                        return (css.match (/\bmm-panel_iconpanel-\S+/g) || []).join(' ');
                    });
                }
            }
        }
    }
);`

**Comment by anjey58** [comment]
Such a solution to the problem 1.
Code piece:


> <nav id="menu">
    <div id="root-panel-menu">
        <ul>
        </ul>
    </div>
    <div id="root-panel-account">
        <ul>
        </ul>
    </div>
    <div id="root-panel-cart">
        <ul>
        </ul>
    </div>
</nav>


```
new Mmenu('#menu',
    {
        navbars: [
            {
                type: 'tabs',
                content: [
                  '<a href="#root-panel-menu"><i class="lnr lnr-home uk-margin-small-right"></i>Раздел 1</a>',
                  '<a href="#root-panel-account"><i class="lnr lnr-apartment uk-margin-small-right"></i>Раздел 2</a>',
                  '<a href="#root-panel-cart"><i class="lnr lnr-history uk-margin-small-right"></i>Раздел 3</a>'
                ]
            }
        ],

        hooks: {
            'openPanel:start': function(el) {
                if (el.id.indexOf('root') != -1) {
                    $(el).removeClass(function (index, css) {
                        return (css.match (/\bmm-panel_iconpanel-\S+/g) || []).join(' ');
                    });
                }
            }
        }
    }
);
```
