### ISSUE TITLE
IE issue on mmenu.frebsite.nl

### ISSUE THREAD

**Issue by Enkrod** [FrDH/jQuery.mmenu#864]
In the Async CSS loading, there is the line `head.append( link );` and it throws errors at least on my IE 10 (most likely because IE wont append Elements that have been created with `document.createElement("tagname")`).

Everything's working fine in every other of my browsers.

I'd recommend switching to [the method actually recommended by google](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery).

**Comment by FrDH** [comment]
should be fixed

**Comment by Enkrod** [comment]
Confirmed fixed
