### ISSUE TITLE
Fixed header dissapers after opening

### ISSUE THREAD

**Issue by STREEET** [FrDH/jQuery.mmenu#865]
Hi! I have a problem. When I scroll page down and click button menu, menu opens but the header and button hides and scrolls to the page, please help me. http://dommadamvu.tmweb.ru to see mmenu you should reduce the resolution of the browser to less than 1200px

**Comment by FrDH** [comment]
Instead of adding the classes "mm-sticky mh-sticky" to `<div id="my-header" />`, add the class "Sticky". Otherwise the mmenu plugin does not know this element is sticky.

**Comment by STREEET** [comment]
I did so, but it still does not work.

**Comment by FrDH** [comment]
Is this issue still relevant? I couldn't find a fixed header anymore.

**Comment by STREEET** [comment]
Thank you, but I use header fixed to the top of page.

**Comment by jesus-morales12** [comment]
I had a similar problem

You need to remove the "position: relative;" from the body.

I'm using this for my header

<div id="my-header" class="mh-head Sticky">...</div>

And this for my css

* {
    padding: 0;
    margin: 0;
    font-family: 'Lato', sans-serif;
    box-sizing: border-box;
}
