### ISSUE TITLE
[Question / Feature Request] Newer buildstacks and licensing-comments

### ISSUE THREAD

**Issue by Enkrod** [FrDH/jQuery.mmenu#867]
### Problem
I am using jQuery.mmenu in a project with gulp v4 and gulp-uglify v3, this does not support the previous `preserveComments: 'license'` option of older uglify versions. So the jQuery.mmenu licensing comments become lost if I do not include each and every multiline comment. 

### Solution
It seems to be best practice to introduce your licence comments with a bang `/*!` (jQuery and Bootstrap do this for example) and run uglify v3 with the following options:
``` 
output: {
    comments: "/^!/"
}
```
This works for your build without changing your uglify options (tested it on a fork just now). So your comments will stay intact for people who use older **and** more recent setups.

You already use this syntax in your SCSS-files [jquery.mmenu.oncanvas.scss](https://github.com/FrDH/jQuery.mmenu/blob/master/src/core/oncanvas/jquery.mmenu.oncanvas.scss) because clean-css supports it too.

### Question
I would like to see this implemented and am willing to make a pull-request with the appropriate changes.

The question now is: Should every licensing comment be treated that way or just the one appearing at the top (like with your CSS)?

My recommendation would be to just bang the topmost comment so uglified files don't become completely riddled and unnecessarily big with dozens of your comments for every little addon and extension included. (Like your jquery.mmenu.all.js is right now to be honest)

But I'll do it anyway you want it so I can have a working build that includes your licence.

**Comment by Enkrod** [comment]
So... this is getting weird and a mess and took me down an entire rabbit hole of things working very efficently together to create problems.

It took me some hours to find out what exactly was going on, because the folks over at gulp-umd made their own questionable choices on some things but it turned out there's a more obvious culprit, let me give you the short version:

- Uglify resolves `(function(){ ... })()` to `!function(){}`
- [Uglify can not see comments that are not attached to AST nodes](https://github.com/mishoo/UglifyJS2/issues/2500)
- Executing a function via `!function(){...}` is an expression, and does not seem to count as an AST node
- So if you run the resulting JS through uglify again... the comments that got preserved on the first run get dropped in the second one, because they are now no longer attached to anything... :-/ 
- Because the entire module is first uglified into the dist-version and then I'm including it into my own app and then uglifying everything again means all the licensing-comments in front of `(function(){})()`-calls get inevitably lost...

This means that right now I don't see a solution to the problem of including your licensing if I run my app through uglify.

**Comment by FrDH** [comment]
So, changing the comment blocks so they start with `/*!` would solve the issue?
I'll change this in the next version.

You should probably stop wasting your time on this :) Just let the build process remove the license info for now.

**Comment by FrDH** [comment]
Try v7.0.5, the licensing comments should have been imporved, although I could not test this with Gulp v4.
