### ISSUE TITLE
Editor give error using [ ] for sass collection

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#870]
My editor give me error for variable declared in this way:

$mm_sidebarCollapsedSizes: [ 40, 60, 80 ] !default;

I am not sure if this is correct or not, but checking SASS docs seem that collection use (), like:

$mm_sidebarCollapsedSizes: (40, 60, 80) !default;

Both seem work fine, but since I don't know how to remove that error notice from phpstorm, I have to change this.

**Comment by Enkrod** [comment]
Had the same problem, 
but this is clearly an error with PhpStorm, since [lists in square brackets are supported by the sass documentation](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#bracketed_lists).

**Comment by FrDH** [comment]
@Enkrod Agreed

**Comment by kamov** [comment]
Thanks, I see..
It's very annoying.. @Enkrod did you find a way to remove that notice? It make red all folders and the file underlined with red error
