### ISSUE TITLE
Example of menu like frebsite.nl

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#871]
In your website there is icon like as iconbar, but check source code is not iconbar.

There is some option to do similar or is required custom css?

**Comment by Enkrod** [comment]
It's the [Iconpanel](http://mmenu.frebsite.nl/documentation/addons/icon-panels.html) with the option for visible set to 1

**Comment by kamov** [comment]
Thank you, but I don't see on that demo that work ..

I mean I see always menu open or completely closed, even if I change the option available to on/off

**Comment by FrDH** [comment]
mmenu.frebsite.nl uses the iconPanels add-on combined with the sidebar add-on:
````js
$("#my-menu").mmenu({
    iconPanels:{
        add: true,
        visible:"first"
    },
    sidebar: {
        collapsed: 550,
        expanded: 1430
    }
});
````

**Comment by kamov** [comment]
Thanks, I will try that
