### ISSUE TITLE
Title for the main panel

### ISSUE THREAD

**Issue by Egretta** [FrDH/jQuery.mmenu#872]
by default is "Menu". How i could change it for something else?
tried this, but it's not working:

`$("#menu").mmenu({
   // options    
    "extensions": [
        "pagedim-black",
        "position-right"
    ],
    "navbars": [
  {
               "position": "top",
               "title": "JK"
            }
        ]
  },
    {
    // configuration
    offCanvas: {
        pageSelector: "#container"
    },
    classNames: {
            fixedElements: {
               fixed: "fix",
               sticky: "stick"
            }
         },
    clone: true
});`

**Comment by Egretta** [comment]
[found here](https://github.com/FrDH/jQuery.mmenu/issues/629) same issue, copied solution, but still not working:

`
$("#menu").mmenu({
   // options    
    "extensions": [
        "pagedim-black",
        "position-right"
    ],
    navbars: {
               title: "JK"
            }
  },
    {
    // configuration
    offCanvas: {
        pageSelector: "#container"
    },
    classNames: {
            fixedElements: {
               fixed: "fix",
               sticky: "stick"
            }
         },
    clone: true
});

`

**Comment by Egretta** [comment]
PS: can anybody teach me, how to correctly insert the code? my code is always in one row...

**Comment by craigpotter** [comment]
`$("#menu").mmenu({ // options "extensions": [ "pagedim-black", "position-right" ], navbar: { title: "JK" } }, { // configuration offCanvas: { pageSelector: "#container" }, classNames: { fixedElements: { fixed: "fix", sticky: "stick" } }, clone: true });`

You had a typo. navbar not navbars

**Comment by Egretta** [comment]
thanks!
