### ISSUE TITLE
Cloned menu with nested lists doesn't work when I switch li elements for div's

### ISSUE THREAD

**Issue by moymadethis** [FrDH/jQuery.mmenu#874]
I'm using the plugin for off-canvas navigation. On mobile the main menu slides in from the left when a toggle button is clicked. On desktop I hide the toggle and the menu is displayed across the top of the browser. To keep things simple I've just hidden the menu on 'desktop' as that's not the problem - and it saves me added loads of CSS that's not needed.

The problem I'm having is on desktop I have nested lists that act like a mega menu. This all works in principle but the styling is a bit off as I have one li that acts as a heading which contains another nested list with all the options for that section.

Here's a CodePen of that working: https://codepen.io/moy/pen/NYjpPG

You can see when clicking "Fresh Meat" the panel slides along. Then if you click one of the sub-categories it slides along again, revealing more content.

If I get rid of the nested lists and use div tags instead it stops working. But I really would like to do this and I don't see a reason why it shouldn't work?

Here's a forked CodePen where I've replaced the nested lists with div elements and removed the li from around the 'title': https://codepen.io/moy/pen/oqWZXa

The problem is now, all the options within "Fresh Meat" now display on the same panel!
Can anyone with a bit more experience of this shed some light on why this isn't working and hopefully help me fix it? Not using as many nested lists will give me a lot less headaches.

**Comment by FrDH** [comment]
I used the "initPanels:before" hook to update the HTML:
https://codepen.io/anon/pen/VXrxMz?editors=1010

Hope this helps.

**Comment by moymadethis** [comment]
Thanks! Would you advise that over changing the `li` which just has a title for a div? Maybe it's not possible for that to work when cloning the nav? Just thought I'd check as previously you mentioned the nested lists was a bit messy. But I don't see a way around it in this instance?

**Comment by FrDH** [comment]
Having semantic HTML is always better. But if you change the HTML, you’ll have to make charges to your CSS and JS as well.

**Comment by moymadethis** [comment]
So if I wrap the child menus in too many divs (like this version: https://codepen.io/moy/pen/oqWZXa) so there's not as many list-items. I'd maybe need to write more JS to accommodate that?

As I'm not really JS proficient maybe I should stick to what I have for now and your example has helped so I don't need to overwrite as much CSS.

In future, as I'll probably want to use this approach again what would you advise ideally?

**Comment by FrDH** [comment]
The JS I wrote was to alter the HTML you provided. If you change the HTML, the JS will have to change too.
If you provide a new example I'd be happy to have a look at it.

**Comment by moymadethis** [comment]
Ah ok, I think the other example I have is this:
https://codepen.io/moy/pen/oqWZXa

Where I removed the nested lists and used div's instead. The problem with
that was that is that in the menu if you click "Fresh Meat" it spits all
the content out onto the same panel rather than clickable titles that slide
to reveal the children. I guess that is because there's too many divs?

Cheers again.
Steve

**Comment by FrDH** [comment]
I updated the codepen:
https://codepen.io/anon/pen/RyRaYp

For future references, I'm using the "initPanels:before" hook to alter the HTML so the plugin knows how to interpreted it.
Have a look at [the basic tutorial](http://mmenu.frebsite.nl/tutorials/off-canvas/the-menu.html) for more information on what the HTML should look like.

**Comment by moymadethis** [comment]
That looks great! The `initPanels:before` still confuses me but I'm sure
the next time I use it it'll be clearer hopefully :)

I'm not sure if you have an iPhone but as a bit of an aside, have you
experienced this issue where you scroll down the page and then open the
menu. The iOS address bar increases in size so the website header goes
behind it? I thought it might be to do with the `href="#my-page"` on the
toggle but it doesn't look like it is.

Example: http://www.moymadethis.com/sites/gbm/product-index.html

Thanks again for all your help, I do really appreciate it!
Steve
