### ISSUE TITLE
mmenu and webpack

### ISSUE THREAD

**Issue by Malin88** [FrDH/jQuery.mmenu#875]
Hi, I trying import mmenu to my app where I compile all JS script by webpack.

In my `app.js` I add `import 'jquery.mmenu'`.
In my webpack config I have:
```
new webpack.ProvidePlugin(
            {
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery'
            }
        )
```
to make jquery visible by other plugins and It's works with another scripts but with mmenu I have message `module not found: Error: Can't resolve 'jquery'`

How can I fix this ?

**Comment by FrDH** [comment]
I'm not much of a webpack expert, but I think the plugin uses ["jquery"](https://github.com/FrDH/jQuery.mmenu/blob/master/dist/jquery.mmenu.all.js#L1). Would it help to add "jquery"?

````js
new webpack.ProvidePlugin(
            {
                $: 'jquery',
                jQuery: 'jquery',
                'window.jQuery': 'jquery',
                'jquery': 'jquery'
            }
        )
````

Seems a bit odd and unnecessary, but worth a shot.
