### ISSUE TITLE
mh-head Sticky disappears

### ISSUE THREAD

**Issue by jesus-morales12** [FrDH/jQuery.mmenu#876]
Hi Fred!

My Sticky header disappears and appears as I press the button that opens my mmenu.

Here's the link: https://cdn.rawgit.com/jesus-morales12/kuroda-landing-page-v2/2608d543/mmenu-demo.html

Please let me know if you need more context

It's for devices with a width equal or lower than 992px

**Comment by FrDH** [comment]
This is due to the short delay between the "setup" and "execute" functions for opening the menu. 
It's on the whishlist to remove this delay, but I can't guarantee that'll work any time soon.
