### ISSUE TITLE
Add new variable for change top when exist fixed header

### ISSUE THREAD

**Issue by kamov** [FrDH/jQuery.mmenu#877]
As you suggest here https://github.com/FrDH/jQuery.mmenu/issues/868#issuecomment-375923754
I try to add top: 56px; but since there is top: 0!important in your code, without variable, it's hard to override, even with !important; 

For avoid to change that css file, can you add new variable?

This is the code:

![screen shot 2018-04-07 at 09 10 20](https://user-images.githubusercontent.com/2345000/38452392-e1d69d1a-3a43-11e8-8c51-b0e8119803e1.png)

Thank You!

**Comment by FrDH** [comment]
I’m not proud of those “!important”s, but they were needed in case you’d use the sidebar add-on combined with other add-ons or extensions that for positioning the menu.

I’ll see if I can find a better solution for the next release. For now, you could simply ocerride the CSS with a more important selector and “!important”

**Comment by kamov** [comment]
I create a custom variable for now.

**Comment by FrDH** [comment]
In a future release, you should be able to use a CSS variable:
````css
.mm-menu {
    --mm-offset-top: 50px;
}
````

**Comment by FrDH** [comment]
As of 7.2, you can use the [positioning CSS variables](http://mmenu.frebsite.nl/documentation/core/scss.html)
