### ISSUE TITLE
Transition issue on IE11

### ISSUE THREAD

**Issue by dakio** [FrDH/jQuery.mmenu#879]
The transition of Sidebar, jQuery mmenu version 7.0.3, on IE11 is not smooth when screen size is less than ~500px.
How to reproduce: Open "http://mmenu.frebsite.nl/documentation/core/api.html" with IE11 v11.0.14393.0 and resize the browser width to 500px. Then click on the hamburger menu => The Sidebar transition is strange.

**Comment by FrDH** [comment]
On smaller screens (< 550px), the page is animated out in VW (80% of the viewport width), on larger screens (>= 550px) the page is animated out in PX (440 pixels). My guess is IE11 has issues animating the VW value.
I don't think there is much to do about this "bug", are there a lot of visitors viewing the site in IE11 with a small screen?

**Comment by dakio** [comment]
Thanks for your answer. Yes, I agree that not much visitor use IE11 with small screen. So just accept it.
