### ISSUE TITLE
Make first level items in mmenu from <span> to hyperlink

### ISSUE THREAD

**Issue by GhMalek** [FrDH/jQuery.mmenu#881]
I make a menu with the mmenu plugin in my typo3 website. the Menu has only one level ! in the Mobile sight (Hamburger) they are all <span> and not clickable !!!

```
<ul class="mm-listview">
    <li><span>First</span></li> 
    <li><span>second</span></li> 
  </ul>
```

this is my main javascript

$("#my-menu").mmenu({

        "extensions": [
            "theme-topit",
            "fullscreen"
        ],
        "autoHeight": {
            "height": "highest"
        },
        "navbars": [
            {
                "position":"top",
                "height": 2,
                "content":[
                    "<div id='searchinMobileNav'></div>","close"
                ]
            },

            {
                "position": "bottom",
                "height": 2,
                "content": [
                    "<div id='socialLinksMobileNav'></div>"
                ]
            }
        ]

    },
    {
        classNames: {
            selected: 'cur'
        }
    }
);
What should I do to change the `<span>` to `<a href>`

**Comment by FrDH** [comment]
Hi,
What does your HTML look like before the plugin is fired? The plugin does not change a `<a>` into a `<span>`, so my guess is your HTML already contains `<span>`s.
