### ISSUE TITLE
Using blockUI:false doesnt allow the user to use the page while the menu is open.

### ISSUE THREAD

**Issue by eshiett1995** [FrDH/jQuery.mmenu#882]
I have an application using mmenu and this is my code:

`$("#mmenu").mmenu({
    position: "left",
    //zposition: 'next',
    blockUI: "false",
    moveBackground: false
  });`

I want the users to be able to use the page while the side bar is out, but it is still not working.

**Comment by FrDH** [comment]
What version of the plugin are you using? Is this a duplicate issue for https://github.com/FrDH/jQuery.mmenu/issues/884?
