### ISSUE TITLE
Bootstrap 3 menu issue

### ISSUE THREAD

**Issue by cskott** [FrDH/jQuery.mmenu#883]
Is it possible to show a working example of the Bootstrap 3 wrapper menu. Or have anybody managed to implemented it with success?

I can't make it work as it should. When implemented, nothing happens clicking on the menu icon. I do see it generates the menu, it's hidden. So I guess something happens to the function that should open/slide in the menu. I don't get any js errors.

Cheers

**Comment by cskott** [comment]
Hi, thanks for answering :)

Yes, i have this setup on a demo site. http://skabelon.siteworks.dk/Template03 

First try was on a different site, and the burgermenu btn did not work. I ses now, the btn does work on this site, but still open the bootstrap menu.

Anyways. If I inspect the code, i do see the mmenu is generated. I can change the z-index and it shows. So, something does work :)

It's not looking perfect, but it has generated something.

Thanks for helping.

**Comment by FrDH** [comment]
I'm not sure how or why, but the generated menu appears to be generated by a newer version of the plugin than you've included in the site.

Can you check what version is being used? I found CSS and JS files for version 5.7.2, but the menu HTML is generated by version 7.

**Comment by FrDH** [comment]
Took a little while, but I think I found the problem.
The BS3 wrapper uses a deprecated (and removed) option.
I'll see if I can update the wrapper shortly.

**Comment by cskott** [comment]
Sounds amazing. Hope it will work :)

**Comment by FrDH** [comment]
Should be fixed in 7.0.6
