### ISSUE TITLE
mmenu still won't close with API.close() if it's cloned 

### ISSUE THREAD

**Issue by artursopelnik** [FrDH/jQuery.mmenu#888]
Like written in #621 by @FrDH this bug should have been already fixed - but it still does occur.

Any plans on this?

**Comment by Miw0** [comment]
Yes I can confirm this bug still exists using version v7.0.2.

**Comment by FrDH** [comment]
Bug is fixed, you just can't get the API from the original node (that just simply isn't posible).

Best practise is to store the menu in a variable when creating it:
```js
var $menu = $("#my-menu").mmenu({
    // options
});
```
And then access the API using the variable:
```js
var API = $menu.data( "mmenu" );
```

**Comment by artursopelnik** [comment]
@FrDH Thanks. [It works!](https://codepen.io/artursopelnik/pen/WJgWmd?editors=1010)
