### ISSUE TITLE
Make search (navbar) a site-wide search

### ISSUE THREAD

**Issue by moymadethis** [FrDH/jQuery.mmenu#890]
My menu is working really, really well now. So thanks for all your help so far! :)

I have the search navbar displayed which returns results within the navigation as expected. The request I have is to change the navbar search into a search form that triggers a content/product search on the website and diverts the user (after they've submitted a search term) to the `/search` results page.

Here is my current mmenu setup:

```
$(document).ready(function() {
	$(".site-nav").mmenu({
    hooks: {
      'initPanel:before': function( $panel ) {
        $panel.find('.megamenu')
          .each(function() {
            $(this)
              .wrapInner('<ul />')
          .children('ul')
          .unwrap();
          });

        $panel.find('.megamenu__block')
          .each(function() {
            $(this)
          .wrap('<li />')
              .children('ul, div')
              .unwrap()
          });
      }
    },
		// Options
		navbar: {
			title: false
		},
		navbars: {
			"position": "top",
			"content": [
				"searchfield"
			]
		},
		"searchfield": {
            "panel": true,
            "showSubPanels": false,
            "showTextItems": true
		}
	}, {
		// Configuration
		clone: true,
		offCanvas: {
			pageSelector: "#page"
		},
		classNames: {
			selected: "active",
			fixedElements: {
				fixed: "mm-fixed",
				sticky: "mm-sticky"
            }
		},
	});
	
	var API = $(".site-nav").data("mmenu");
	var $icon = $(".mmenu-toggle");
      
	$icon.on("click", function() {
		API.open();
	});

	API.bind( "open:finish", function() {
		setTimeout(function() {
			$icon.addClass( "is-active" );
		}, 100);
	});
	
	API.bind( "close:finish", function() {
		setTimeout(function() {
			$icon.removeClass( "is-active" );
		}, 100);
	});
});
```

I realised that I can maybe amend `content` bit in the following code to inject the same search form I have in my website header:

```
navbars: {
	"position": "top",
	"content": [
		"searchfield"
	]
}
```

Is that correct/the best way to handle this? If so I guess I should remove the `"searchfield": {}` options as they'll be no longer needed?

So the previous section of code I posted would be updated to:

```
navbar: {
	title: false
},
navbars: {
	"position": "top",
	"content": [
		'<form action="/search" method="get" role="search" class="mm-search"> <input type="search" name="q" class="mm-search__input" value="" placeholder="Search"> <button type="submit" class="mm-search__btn"> <svg class="icon icon--search"><use xlink:href="#icon-search"></use></svg> </button> </form>'
	]
}
```

Note I had to change the double quote mark to single otherwise it broke and make all the code on one line ...does that all look ok?

It _seems_ to work but I'm unsure if it's the best method to achieve this?

Thanks again,
Steve

**Comment by FrDH** [comment]
You can use the `searchfield.form` and `searchfield.submit` configuration options to wrap the searchfield in a `<form />` tag and append a `<input type="submit" />` button to it.
http://mmenu.frebsite.nl/documentation/addons/searchfield.html

You can set the `searchfield.search` option to `false` to prevent the live-search while typing in the searchfield.

The JS would look something like this:
````js
$("#my-menu").mmenu({
   searchfield: {
      add: true,
      search: false
   }
}, {
   searchfield: {
      form: {
         method: "POST",
         action: "/search.php"
      }
   }
})
````

Hope this helps.

**Comment by moymadethis** [comment]
Thanks that works pretty well, just need to figure out how to include the button. The one problem with that is the search doesn't remain fixed at the top of the menu always. With that in mind would I be better setting something like:

```
navbars: {
	"position": "top",
	"content": [
		"searchfield"
	]
}
```

I couldn't get `position: top` to work on your example code but I'm probably doing it wrong! Likewise `submit: true` - which I thought it how you'd also include a submit button?

**Comment by moymadethis** [comment]
Sorry I forgot to include my CodePen: https://codepen.io/anon/pen/aGeReJ

I think it looks right ...I've prevented the live/menu search but it doesn't look like the form/button has been added. Is that to do with where I've positioned my code within a navbar?

**Comment by moymadethis** [comment]
Thanks, that works great! Although I didn't declare `add: true, search: false` again in the config bit as it seems to work with it only set in the options - is that ok?

The only additional thing I added was `input: {name: "q"}` which meant the form now brings back results just like the main (desktop) website search now.

Thanks again for all your help :)
