### ISSUE TITLE
LiveChatInc widget disappearing after page load

### ISSUE THREAD

**Issue by MichalPaszowski** [FrDH/jQuery.mmenu#894]
Hello, one of our mutual clients has reported problem with our chat widget. It disappears after page loads when mm-menu is present on page. It seems that mm-menu damages one of our iframes because it has src="about:blank" parameter. After mm-menu is loaded innards of this iframe looks like this: `<html><head></head><body class=""></body></html>`

We have come up with patchwork solution that waits for mm-menu to be loaded, and only then it loads our script. It looks like this:
`
var waitForEl = function(selector, callback) {
    if (jQuery(selector).length) {
        callback();
    } else {
        setTimeout(function() {
            waitForEl(selector, callback);
        }, 100);
    }
};

var loadLC = function() {
    window.__lc = window.__lc || {};
    window.__lc.license = <your_license_here>;
    window.__lc.visitor = {
        name: '',
        email: ''
    };
    (function () {
        var lc = document.createElement('script');
        lc.type = 'text/javascript';
        lc.async = true;
        lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(lc, s);
    })();
}

waitForEl('.mm-page', function() {
    loadLC();
});
`

We know it is not perfect, but it works. Has anyone come up with something, less-patchworky?
For example - how to configure plugin so it will ignore our iframes?

**Comment by FrDH** [comment]
Please read [this page](http://mmenu.frebsite.nl/tutorials/off-canvas/the-page.html) in the "basic off-canvas" tutorial.
> You probably don't need to make any changes to the HTML of your webpage. But if you can, it is recommended to wrap all HTML in only one DIV.

> If you let the plugin wrap all HTML, a VIDEO will restart (or not start at all), javascript in a SCRIPT will run twice, an IFRAME will reload and so on.

Hope this helps.
