### ISSUE TITLE
Plugin Activation Not Working

### ISSUE THREAD

**Issue by docBrand** [FrDH/jQuery.mmenu#895]
I am trying to activate my license in the plugin admin area, but it says my license key is invalid. It allows me to download a new zip of the plugin when I go to the site, so I know my license is valid since it asks for it there as well.

**Comment by docBrand** [comment]
This wouldn't normally be a problem, but now since the Footer Button options are locked behind a license key activation it has become a problem that I need addressed ASAP!

**Comment by FrDH** [comment]
Did I mail you yesterday? Or is this a new issue?
