### ISSUE TITLE
Boostratap 4 wrapper - third level-items show up on second-level

### ISSUE THREAD

**Issue by wini2** [FrDH/jQuery.mmenu#899]
Refers to https://github.com/FrDH/jQuery.mmenu/issues/863. I overlooked that it has been closed.

I have the same problem as internetstyle.

The counter on first level is wrong (counts all children and grandchildren). When I slide to level two, it contains all entries of level two and three.

Maybe it has something to do with bootstrap-classes or other bs-attributes because mmenu works fine, if i use a ul - li without any class.

**Comment by wini2** [comment]
On http://www.typopro.de/cms23/index.php?id=34 you can see, who the structure should be (is the sitemap). The main-Menu should be ul - li. It also contains a simple menu in pure html ul-li. 

For today I can let the faulty template be activated. If you want me to acitvate it at another point in time, please tell me when yout got time to take a look.

**Comment by wini2** [comment]
I realized that the problem might have something to do with ul class="navbar-nav" and the dropdown-menu class.

Unfortunatly i can't compare with your example on http://mmenu.frebsite.nl/demo/index.html?demo=bootstrap-navbar. Would you please be so kind to extend it to a thrid level?

**Comment by wini2** [comment]
It seems that the bootstrap-wrapper does not work with more than two levels. On https://codepen.io/wini2/pen/WKvKje i made two menus - one with and one without boostrap classes.

**Comment by FrDH** [comment]
Athough I doubt dropdowns are supposed to be nested, the next releaes will support it.
