### ISSUE TITLE
setSelected	API not working

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/jQuery.mmenu#900]
I just upgraded from 6.1.8 to 7.0.6.   all of my menus are dynamically generated and some use sub-menu and highlight the active menus.   for some reason they no longer highlight . -- 

here one of the areas that is not working.

```
var ul = '<ul class="my-sublist">';
 ul += '<li class="sel0"><a onclick="setRepeat('+ID+', 0);">Never<span >' + 'x' + '</span></a></li>';
 ul += '<li class="sel1"><a onclick="setRepeat('+ID+', 1);">Every Day<span >' + 'd' + '</span></a></li>';
        ul += '</ul>';
        $(".repeat").append( ul );
        if (repeated == 0) api.setSelected( $(".sel0"));   // hightlight current value of repeated
        if (repeated == 1) api.setSelected( $(".sel1"));

```

 

bill a
licensed user

**Comment by FrDH** [comment]
Could you provide a (simplyfied) example of the issue?
The `setSelected` method seems to be working as intended on my test pages. The logic isn't that complex anyway:
````js
setSelected: function( $li )
{
	this.$menu
		.find( '.' + _c.listitem + '_selected' )
		.removeClass( _c.listitem + '_selected' );

	$li.addClass( _c.listitem + '_selected' );
},
````

Are you getting any errors in the console? 

Could you check if `$(".sel0")` actually exists in the menu?
````js
console.log( $("#my-menu").find( ".sel0" ).length );
````

**Comment by pigsinspace** [comment]
Fred

got a little more info...

no errors on console
yes .sel0 exist
works on version 6
works on 2 menus that i have that do not have sub menus. — only does not highlight on sub-menus (3 different sub-menus)

here is some screen shots




week should have been selected.  aka sel7



here is where it does work 






more info on where it is not working





here is where i call setSelect and i added some debug code to ensure it is being called



console log




does your test code setSelect a subMenu?

please advice

thanks

bill a

**Comment by FrDH** [comment]
I think something went wrong with your post :/
An online example (preferrably a jsfiddle or codepen) would be very helpful.

**Comment by pigsinspace** [comment]
Fred

Built some test code and of course it worked.    But then working with another engineer figured out what is going on…

image a menu system with country,  State (submenu) , City (submenu) .    

first time you use it you select your city.    US -> CA. -> San Francisco

next time you go to the menu to change it to Cupertino.     or just to check what you have selected.     so when you enter and navigate the menu  US AND CA AND San Francisco are Each selected as you go from panel to panel…

your code appears to clear out all selected items in the entire menu before it selects the new item.   so in the above example would remove selection from US and CA and leave it on San Francisco

setSelected: function( $li )
{
	this.$menu
		.find( '.' + _c.listitem + '_selected' )
		.removeClass( _c.listitem + '_selected' );

	$li.addClass( _c.listitem + '_selected' );
},



in version 6 the code i believe looked like this

setSelected:function(e)
{
  this.$menu.
	find("."+s.listview).children("."+s.selected).
	removeClass(s.selected;

  e.addClass(s.selected);
}

only remove the class from the children menus???

I hope that made sense….    How do i use setSelected and do not clear out parent selected items or not clear out anything at all.

thanks for your help with this

bill a

**Comment by FrDH** [comment]
The logic in v6 is not much different from v7, both clear out all selected listitems.

I guess you could hook into the `setSelected` method using the `setSelected:after` hook to recursively add the "mm-listitem_selected" class to the parent LIs
Something like this:

````js
$("#my-menu").mmenu({
   hooks: {
      "setSelected:after": function( $li ) {
         var $panel = $li.closest( "mm-panel" );
         var $parent = $panel.data( "mm-parent" );
         while ( $parent ) {
            $parent.addClass( "mm-listitem_selected" );		
            $parent = $parent.closest( "mm-panel" ).data( "mm-parent" );
         }
      }
   }
});
````

Hope this helps.
