### ISSUE TITLE
api.closeAllPanels() not clearing submenu in 7.0.6

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/jQuery.mmenu#901]
I just upgraded to 7.06 from 6.1.8.     now if i blur off one of the sub menus and then re-open the menu it returns to the sub-menu.   

here is how i am closing the menu

```
      <nav id="taskDialog">
         <ul id="my-list"></ul>
      </nav>

  function closeTaskDialog() {
    var api = $("#taskDialog").data("mmenu");
    api.closeAllPanels();         // close subMenu & goes back to the first panel
    api.close();                  // close main panel
  }

```

please advice 

bill a

licensed user

**Comment by pigsinspace** [comment]
Fred

looking closer at this i see what is actually happening

i need to detect when a blur closes the menu. (aka clicked outside of the menu which closes the menu).     looking at the code this is how i do it and works in 6.1.8

    $("body > div").click(function() {
        if ($(this).attr("id") == "mm-blocker") {
          closeTaskDialog();            // Mmenu auto closes the menu but does not clear the subMenu showing first
          console.log("clicked outside task Dialog");
        }
    });


  function closeTaskDialog() {
    var api = $("#taskDialog").data("mmenu");
    api.closeAllPanels();         // close subMenu & goes back to the first panel
    api.close();                  // close main panel
    startRefresh();
  }

StartRefresh is my function that restarts the refresh function that refreshes the data on the page every 10 seconds.    i stop the refresh when i open the menu.

this does not work in 7.0.6 because looking at your code mm-blocker is no longer used.   Is there a replacement for it or….   

why i did this in the first place.    2 reasons

1)  it appears your code calls close when one clicks outside of the menu but does not call closeAllPanels
2) i need to restart the data refresh whenever the menu is closed.    I bet i could solve this with a hook function but that would not address 1) above or is that the best way to address both.    

aka.   
use closePanel:before hook which would call closeTaskDialog.       



oh. just this

https://stackoverflow.com/questions/33617684/mmenu-close-all-submenus-and-return-to-top-level-default-state <https://stackoverflow.com/questions/33617684/mmenu-close-all-submenus-and-return-to-top-level-default-state>

but when i added this it never appears to  triggers
      var api = $("#taskDialog").data("mmenu");
      api.bind( "closePanel", function() {
        	api.closeAllPanels();         // close subMenu & goes back to the first panel
       		 startRefresh();
      });


any help much appreicated

bill a

**Comment by FrDH** [comment]
If you want to close all panels every time the menu closes, I'd hook into the `close:finish` hook to trigger the `closeAllPanels` method:
````js
var api = $(#my-menu).data( "mmenu" );
api.bind( "close:finish", function() {
   api.closeAllPanels();
});
````
Should work I think.

**Comment by pigsinspace** [comment]
Fred

that works perfect.   much cleaner.   

i was using closePanel:after but it never triggered.     ahh.  now see the docs on this.   
http://mmenu.frebsite.nl/documentation/core/off-canvas.html <http://mmenu.frebsite.nl/documentation/core/off-canvas.html>
i was looking on the core API page

so is it preferred to close panels after menu or before.   or does it matter….  finish seems to be working perfect

thanks!!!

bill a

**Comment by FrDH** [comment]
Wouldn't make much of a difference. The ":finish" hook is invoked after the animation completes and should result in a less jumpy effect.
