### ISSUE TITLE
dynamic set menu title

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/jQuery.mmenu#903]
in version 6 i would 

			var titleText = 'Task Menu';
			$("#taskDialog").find( ".mm-title" ).text( titleText );
		
in version 7 i tried

			var titleText = 'Task Menu';
			$("#taskDialog").find( ".mm-navbar__title" ).text( titleText );	

but it did not work	

what is the preferred method of doing this.    could not find it in the documents

thanks
bill

**Comment by FrDH** [comment]
Is `$("#taskDialog")` a "panel" in the menu (does it start out as an `<ul />`)?
If so, try using a function for the `navbar.title` function, you can return a custom string for each panel:
http://mmenu.frebsite.nl/documentation/core/options.html

Something like this:
````js
$("#my-menu").mmenu({
   navbar: {
      title: function() {
         var $panel = $(this);
         if ( $panel.attr( "id" ) == "taskDialog" ) {
            return "Task Menu";
         }
      }
   }
});
````

Hope this helps.

**Comment by pigsinspace** [comment]
Fred

sorry for the confusion.    the menu title i am trying to change is the main menu title.   

so in menus that have a static title this works

    $(“#my-menu").mmenu({
      navbar: {
        title: “NEW MENU TITLE"
      },
   });

or this would work but is over kill

$("#my-menu").mmenu({
   navbar: {
	title: function() {
		return "“NEW MENU TITLE";
      }
      },
   });


yet the title is dynamic as is the menu items.      so the following 2 work for each version but i have not found a cleaner way todo this.   

      /$(“#my-menu").find( ".mm-title" ).text(  “NEW MENU TITLE" );			// change name of title  version 6
      $(“#my-menu").find( ".mm-navbar__title" ).text(  “NEW MENU TITLE");		// change name of title   version 7


what API call can i make to set the main navBar title?

thanks for all your help

bill a

**Comment by FrDH** [comment]
Are you using the "navbars" addon? Or just the default navbar (where the navbar isn't fixed but it's prepended to each panel seporately)?

**Comment by pigsinspace** [comment]
I have the full version installed…

jquery.mmenu.all.js

so I asume Navbars addon

**Comment by FrDH** [comment]
Having it included does not mean you're using it. What does your JS for creating the menu look like?

If you ARE using the navbars add-on (and have a single fixed navbar prepended to the menu instead of a navbar prepended to each panel), you could swap out the "title" content for a hardcoded title:
````js
$("#my-menu").mmenu({
    navbars: [{
        content: [ "prev", "<span>Your text here</span>" ]
    }]
});
````

Anyway, there's no API call for setting the menu title.
If your current solution works, I'd stick with it.

**Comment by pigsinspace** [comment]
thanks

what works now is the following for dynamic titles

      $("#my-menu").find( ".mm-title" ).text( “your test here" );			// change name of title  version 6
      $("#my-menu").find( ".mm-navbar__title" ).text( “your test here" );	// change name of title   version 7

and for static title text i use

      navbar: {
        title: “your test here"
      },

**Comment by pigsinspace** [comment]
feature request.    and API to change title

thanks for the great product!!!

bill a

**Comment by anjey58** [comment]
Just add data-mm-title
```
<nav id="menu">
    <div id="root-panel-menu" data-mm-title="Меню раздела 1">
        <ul>
        </ul>
    </div>

    <div id="root-panel-account" data-mm-title="Меню раздела 2">
        <ul>
        </ul>
    </div>
</nav>
```
