### ISSUE TITLE
bug rtl sidebar

### ISSUE THREAD

**Issue by vahidalvandi** [FrDH/jQuery.mmenu#905]
in sidebar rtl mode have a bug

**Comment by FrDH** [comment]
Thank you for reporting the issue.

**Comment by vahidalvandi** [comment]
please fix it . i need it . 

thank you

**Comment by FrDH** [comment]
Will be fixed in the next release, although I might rethink the whole sidebar when in a RTL language. Seems to make more sence to place it on the right (both for the user and the code).

**Comment by FrDH** [comment]
Give version 7.1 a try, the bug should generally be fixed, although I don't think it's perfect yet. Improving the sidebar add-on is on the TODO list for future updates.

**Comment by vahidalvandi** [comment]
thank you

**Comment by vahidalvandi** [comment]
it  not fixed  yet ! why rename rlt addons tp _rtl

**Comment by FrDH** [comment]
The RTL add-on is now part of the core, it is no longer a separate add-on. the directory "_rtl" should have been removed :/

**Comment by vahidalvandi** [comment]
fixed !
