### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by Best4uCMS** [FrDH/jQuery.mmenu#906]
First off all; loving this menu!
I have been looking for a solution for quite sometime now, but strange enough I can't find a solution. And I'm wondering if it would be possible at all with mmenu.

When the menu is always visible on desktop (like http://mmenu.frebsite.nl/)
Would it be possible to have a hero section above the menu?

{hero section}
{menu} {content}

So when scrolling down it sticks to the top and is always visible when scrolling down; but when going back up it stops at a certain point. Like this: https://www.elegantthemes.com/blog/wp-content/uploads/2017/07/FixedNavigation.gif

**Comment by FrDH** [comment]
Not by default, but if you disable the off-canvas behavior, I guess you could get something like that to work.

Disabling the off-canvas behavior will create a menu in its current container:
````js
$("#my-menu").mmenu({
   offCanvas: false
});
````

Add some CSS for the sticky behavior:
````css
#my-menu {
    position: sticky;
    top: 0;
}
````

Hope this helps.
````
