### ISSUE TITLE
Popup & Autoheight

### ISSUE THREAD

**Issue by netzwwwerk** [FrDH/jQuery.mmenu#907]
Hi :-),

first of all, you're menu is absolutley fantastic. Thanks a lot for your great work!
But in one case I'm getting stucked. So if you'd like to help me, I'd be very glad and thankful.

I tried popup and autoheight getting to work. I tried for over 3 days. So I don't know how to go on.
The Problem: These both features together always ending up calculating the wrapper height as 0px.
So the popup is not visible.

The working-place can be found at:
[http://ub.webdesign-spotlight.de/wp-content/themes/netzwerk/tmp_index-mmenu-autoheight.html]([(http://ub.webdesign-spotlight.de/wp-content/themes/netzwerk/tmp_index-mmenu-autoheight.html))
Debugger is included.

Best regards,
Robert

**Comment by FrDH** [comment]
That's odd,

The dropdown add-on should work just fine combined with the autoHeight add-on, it's even in the docs: https://mmenu.frebsite.nl/documentation/addons/dropdown.html

I noticed some additional CSS for the menu, does the issue persist if you remove that?

**Comment by netzwwwerk** [comment]
Hi :-),

thanks a lot for you're relply, I'm glad to hear from you. Unfortunately the issue persits even when removing all css except the mmenu-css. 

In this example I removed the additional css:
http://ub.webdesign-spotlight.de/wp-content/themes/netzwerk/tmp_index-mmenu-autoheight.html

In this example I removed every css and js except the mmenu-files:
http://ub.webdesign-spotlight.de/wp-content/themes/netzwerk/tmp_index-mmenu-autoheight-blank.html
(The trigger-button is "Navigation" here)

So if you'd like to help me, I'd be very glad and thankful.
Wish you a nice day,

Best regards,
Robert

**Comment by FrDH** [comment]
I noticed you include the JS files separately (which normally should not be a problem), could you try and include them in alphabetic order? The order in which the dropdown- and autoHeight add-ons are included could fix the issue.

**Comment by netzwwwerk** [comment]
Hi :-),

lifesaver!!! As you can see in the examples it works now. I would never find that solution by myself.
Thanks a lot for your patience and support.
Have a nice day.

Best regards,
Robert

**Comment by FrDH** [comment]
It's a shame the order is important, but in some rare cases one depends on another to work properly. The .all.js is concatenated in alphabetic order, therefor I would always recommend including the add-ons in alphabetic order. I'll give a hint in the docs about this.
Regards, Fred
