### ISSUE TITLE
Plugin mmenu breaks user triggers on window element like scroll

### ISSUE THREAD

**Issue by 7iomka** [FrDH/jQuery.mmenu#908]
Hi.
In my project I try to use simple trigger scroll event:
`$(window).on('scroll pagescroll', toggleAffixHeading).trigger('pagescroll');`
But this doing nothing!
But working If I set timeout (1s+)..
I used offCanvas;
Question is: why?
I do not want to use custom timeout or overwrite custom triggers!
Also the documentation is so confusing that I never found a method that would fired at the moment when the DOM was changed (offcanvas changes) so that at that moment I could trigger my events;

Thanks!

**Comment by FrDH** [comment]
I'm not sure I understand the question, but the offCanvas add-on (and some other add-ons) indeed make changes to the DOM. If you want some JS to be invoked after the menu was created, you can simply add that JS after invoking the mmenu plugin:
````js
$("#my-menu").mmenu();

$(window).on('scroll pagescroll', toggleAffixHeading).trigger('pagescroll');
````

Hope this helps.
