### ISSUE TITLE
Weird z-index issue?

### ISSUE THREAD

**Issue by joshbedo** [FrDH/jQuery.mmenu#913]
I'm trying to set this up on a Shopify theme using Bootstrap 4.0 but seeing a weird z-index issue where the page slides open/closed and shows visibly behind the menu. Not sure whats going on here or how to fix it. Anyone seen this before or have any ideas?

Here are screenshots
<img width="1440" alt="screen shot 2018-08-13 at 5 39 58 pm" src="https://user-images.githubusercontent.com/607239/44059764-6ec9ebf0-9f20-11e8-87f5-e657520ec0fe.png">
<img width="1440" alt="screen shot 2018-08-13 at 5 39 56 pm" src="https://user-images.githubusercontent.com/607239/44059766-6edadf46-9f20-11e8-9851-599c53104ab8.png">

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
Do some of those elements have `position: fixed;` or `position: sticky;`?
