### ISSUE TITLE
Open never-closing menu in a container?

### ISSUE THREAD

**Issue by gameshirtz** [FrDH/jQuery.mmenu#914]
Hi,

i have a little problem here.
i want to have a open never-closing menu in a container div #Menutest (which has a dynamic width and is somewhere on the page, not a side menu).
 
When i try to use :

            $("#menu2").mmenu({
              // options
              offCanvas: true,
              slidingSubmenus: false
            }, {
              // configuration
              offCanvas: {
                menuInsertMethod: "appendTo",
                menuInsertSelector: "#Menutest",
              }
            });

            var API = $("#menu2").data( "mmenu" );
            API.open();  

Now, the Menu will be shown on the left side (not in the #Menutest). But when i click on any point of the page or the Menu itself, the Menu disappears. 

When i use pageSelector for the parent div from #Menutest  in the offCanvas Configuration nothing changes.

So i thought i use the the option "offCanvas false" like that:

            $("#menu2").mmenu({
              // options
              offCanvas: false,
              slidingSubmenus: false
            }, {
              // configuration
            });

But there is no menu on the page because the mm-wrapper on body has css position: relative. Only when i manually remove the position: relative the menu is fullscreen visible on the page and can be used without dissapering by a click. But now i have the problem, that i want to have the menu in the container #Menutest and i want to see the rest of the page. An there is no pageSelector, menuInsertMethod and menuInsertSelector for that, because thats only for the configuration the offCanvas Addon, right?

So now i am asking for a solution :) 
Like a pageSelector, menuInsertMethod and menuInsertSelector for OnCanvas.
Or can i implement my requirement (open never-closing menu in a container) with the existing option/configurations?

Thank you for your help :)

Simon

**Comment by FrDH** [comment]
Setting the `offCanvas` option to `false` should create the menu without moving it. The menu has `position: absolute`, therefor the parent node (".mm-wrapper") needs a width and height specified.

Try the "autoHeight" add-on if you don't want a fixed height.

If you create a jsfiddle or codepen I'd be happy to make it work.
