### ISSUE TITLE
How to import addons via webpack?

### ISSUE THREAD

**Issue by kaspar-allenbach** [FrDH/jQuery.mmenu#915]
I want to import mmenu addons via webpack.

I've tried everything but nothing works:

Doesn't work: `import 'jquery.mmenu.fixedelements';`
Doesn't work: `import '/dist/addons/fixedelements/jquery.mmenu.fidexelements';`
Doesn't work: `'jquery.mmenu.fixedelements': require.resolve('jquery.mmenu/dist/addons/fixedelements/jquery.mmenu.fidexelements')`

How would I have to do this?

**Comment by dutchenkoOleg** [comment]
@kaspar-allenbach the second case was almost correct )) you lost _jquery.mmenu_ at the begin of path
`import 'jquery.mmenu/dist/addons/fixedelements/jquery.mmenu.fixedelements'`

**Comment by dutchenkoOleg** [comment]
and in webpack.config.js

```js
resolve: {
  modules: [
    './node_modules/'
  ]
}
```

**Comment by kaspar-allenbach** [comment]
thanksyou. javascript imports are such a mistery 🙈

**Comment by kaspar-allenbach** [comment]
Hmm. As soon as I import the fixed elements extension mmenu stops working altogether with the console error: `TypeError: s[t] is undefined      …mmenu.fixedelements.js:5:45`

**Comment by FrDH** [comment]
The add-ons are not wrapped in a UMD wrapper, just the "jquery.mmenu.js" and "jquery.mmenu.all.js" files are.
You can import the ".all.js" file or -if you really don't want those extra few bytes- create a [custom build](https://mmenu.frebsite.nl/documentation/custom-build.html)

Hope this helps.
