### ISSUE TITLE
Extensions and responsive / media queries

### ISSUE THREAD

**Issue by 033MaX** [FrDH/jQuery.mmenu#916]
Hello guys,

I'm having trouble understanding how your system with the media queries works. I'm pretty sure that it is a bug, or if not maybe you can help me out to understand what I did wrong in the configuration.

Here is a configuration I made to test the feature : 

`var extensions = {`
`    "(min-width: 600px) and (max-width: 800px)": ["fullscreen"],`
`    "(min-width: 360px) and (max-width: 500px)": ["fullscreen"],`
`    "all": ["fullscreen"]`
`};`

The result is having the menu fullscreen on desktop when you first open it. When you reach the first media query ( 600 > 800 ), the menu is still in fullscreen mode. Then, if you go back to a value for the viewport > 800px, the menu falls back to the non fullscreen version.

I've tried to put the "all" key above the two other media queries, and the result is the same, the only difference is that the menu never starts fullscreen and switch to fullscreen when between 360 and 500 or 600 and 800.

My initial assumption was that, if you had "fullscreen" in the "all" key, whatever you say in any other media query would not overwrite it because of what your documentation says : "Use the "all" key for extension that should always be activated".

Is there something I did wrong ? Or am I mistaken on how to configure it ?

**Comment by FrDH** [comment]
The extensions are enabled or disabled in order in which they are specified. Except for those in the "all" key, these are enabled or disabled first (if I'm correct).
This basically means you can not add an extension to multiple media queries and you should create a single media query targeting all screen sizes. I think you can do so using the comma:
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries
````js
var extensions = {
   "(min-width: 360px) and (max-width: 500px), (min-width 600px) and (max-width: 800px)": ["fullscreen"]
};
````
This should enable the fullscreen extension if the screen width is between 360px and 500px, or between 600px and 800px.

Hope this helps.

**Comment by 033MaX** [comment]
Fred, thank you very much for the clarification. It works perfectly.
