### ISSUE TITLE
WordPress sub-menu not working with mmenu

### ISSUE THREAD

**Issue by kaycray** [FrDH/jQuery.mmenu#917]
I'm having an issue with submenus when using mmenu on a WP site. I've done the following (based on the code generated from the WP plugin & a combination of other examples). I'm getting the same issue regardless if I use the plugin developed for WP or include it in my own files. The submenu won't open when I click on the mm-btn_next. What is supposed to happen when that button is clicked?

			jQuery(document).ready(function($){
				
				$("#wpadminbar")
					.css( "position", "fixed" )
					.addClass( "mm-slideout" );				
				
				var $menu 	= $("#header-nav").first().clone(),
					$button = $("#menu-toggle");
			
				var $selected = $menu.find( "li.current-menu-item" );
				var $vertical = $menu.find( "li.Vertical" );
				var $dividers = $menu.find( "li.Divider" );
			
				$menu.children().not( "ul, ol, div" ).remove();
				$menu.add( $menu.find( "ul, li" ) )
					.removeAttr( "class" )
					.not( "[id^='wpmm-']" )
					.removeAttr( "id" );
			
				$menu.addClass( "wpmm-menu" );
			
				$selected.addClass( "Selected" );
				$vertical.addClass( "Vertical" );
				$dividers.addClass( "Divider" );				
				
		        $menu.mmenu({
					extensions: {
						"all": ["position-right", "theme-dark"]
					},
					navbars: [
						{
							content: [ "prev", "title" ]
						}
					],
					
					offCanvas: {
						pageSelector: "> div:not(#wpadminbar)",
						zposition: "front"
					},
					clone: true,
					classNames: {
						selected: "active",
						fixedElements: {
							fixed: "mm-fixed",
							sticky: "mm-sticky"
			            }
					},					

				});
		        
				var api = $menu.data( "mmenu" );
			
				$button
					.addClass( "wpmm-button" )
					.off( "click" )
					.on( "click", function( e ) {
						e.preventDefault();
						e.stopImmediatePropagation();
						api.open();
					});
			
				api.bind( "open:finish", function() {
					setTimeout(function() {
						$button.addClass( "is-active" );
					}, 100);
				});
				
				api.bind( "close:finish", function() {
					setTimeout(function() {
						$button.removeClass( "is-active" );
					}, 100);
				});	
			});

**Comment by FrDH** [comment]
Clicking the button for opening a submenu should open the submenu, I'm not sure why that wouldn't work,is there an online example I could have a look at?
