### ISSUE TITLE
'matchMedia' Error

### ISSUE THREAD

**Issue by srmass** [FrDH/jQuery.mmenu#918]
Object doesn't support property or method 'matchMedia'
Console Error in "IE 9".

**Comment by FrDH** [comment]
Thank you for bringing this to my attention, wasn't aware of IE9 not supporting MatchMedia
I'll include a check for support and ignore it when not supported.

**Comment by FrDH** [comment]
Have you tried including the matchMedia polyfill? https://github.com/paulirish/matchMedia.js
