### ISSUE TITLE
Shadows extension, shadow-menu

### ISSUE THREAD

**Issue by 033MaX** [FrDH/jQuery.mmenu#919]
I have recently extended the CSS to allow an additionnal shadow setting. I thought it could be useful to some of you and could be implemented in a future release.

``<script>``
``jQuery(document).ready(function( $ ) {``
``$("#menu").mmenu({"extensions": ["shadow-menu"] });``
``});``
``</script>``

``.mm-menu_shadow-menu .mm-panels { box-shadow: 0 0 25px -10px #444; }``

**Comment by FrDH** [comment]
Thank you for contributing.

In general, animations become slow when a box-shadow is involved. I'll check how this one performes and include it in the shadows extension if it's OK.

**Comment by FrDH** [comment]
`shadow-menu` has been added in 7.2
