### ISSUE TITLE
Plugin initiates session on front-end

### ISSUE THREAD

**Issue by rommeled** [FrDH/jQuery.mmenu#920]
When using the plugin with WordPress it initiates a session on the front-end. Going through the plugin it seems that the session is supposed to run on the admin page.
We found the issue while implementing GDPR compliance and we strongly recommend the session to  be initiated only on the admin page and not for all website visitors.
/php/mm_html.php line: 24 - 27

Quick-fix could be something like this:
add_action( 'admin_init', function () {
    if ( ! is_session_started() ) {
        session_start();
    }
} );

**Comment by FrDH** [comment]
Thank you for bringing this to my attention. The session is indead not needed on the frontend. Come to think about it, I'm even sure it is needed at all anymore.

**Comment by rommeled** [comment]
Hi there
Thanks for fast respond. I would suggest not initiating the session to store/keep the data as it's "kind of" not the WordPress way to save the data. None the less - it would be great if it could be merged-in or fixed so we only do it on the admin side.
Also - thanks for a great plugin.

**Comment by FrDH** [comment]
What version of the plugin are you using? I just checked but couldn't find any references to the session at all.
