### ISSUE TITLE
Mmenu tabs not work with clone

### ISSUE THREAD

**Issue by cmichael-de** [FrDH/jQuery.mmenu#921]
When I set the clone configuration to true, the tabs are not working any more. Just set the clone to false and it works like a charme again.

Here is a demo: 
https://jsfiddle.net/xh6uvqcz/18/

**Comment by FrDH** [comment]
Makes sence :)
The `clone` option prepends each `id` with "mm-" to ensure there are no duplicate `id`s in the document.
Try prepending the `href` "mm-" as well, should work:
https://jsfiddle.net/xh6uvqcz/19/

**Comment by cmichael-de** [comment]
Yeahh! Of Course! Thats it, thanks!
