### ISSUE TITLE
Mmenu Tabs with external ul

### ISSUE THREAD

**Issue by cmichael-de** [FrDH/jQuery.mmenu#922]
I try to use an external ul which is outside of the nav wrapper. Is it possible?

The documentation  (http://mmenu.frebsite.nl/documentation/addons/navbars.html) says:

content
-> An array of strings (for text or HTML), jQuery objects ...

Maybe "jQuery objects" is the solution and my hope that it is possible. I there a way?

https://jsfiddle.net/xh6uvqcz/23/

**Comment by FrDH** [comment]
This can work, you just need to put the external UL inside the menu manually:
https://jsfiddle.net/mzucv63x/
````js
$("#panel-language").appendTo( $("#menu") );
$("#menu").mmenu({
   "navbars": [
        {
            "position": "top",
            "type": "tabs",
            "content": [
                "<a href='#mm-panel-menu'>Menu</a>",
                "<a href='#mm-panel-language'>Language</a>"
            ]
        }
    ]
},{
    clone: true
});
````

Hope this helps.

**Comment by cmichael-de** [comment]
Good idea - thank you Fred!
