### ISSUE TITLE
drag addon is too sensitive on iphone

### ISSUE THREAD

**Issue by pmosch** [FrDH/jQuery.mmenu#926]
I have integrated the drag option for the mmenu. But i think it is too sensitive on iphone. When i try to scroll down with my thumb, often the panel close and slide back to higher level.

Is there any chance to get a better handling? On Android it works perfectly.

**Comment by FrDH** [comment]
The dragging and panning is handled by [Hammer.js](https://hammerjs.github.io/)
I think that's where the issue is. If you can, please setup a Hammer-only example and see if the issue persists.
