### ISSUE TITLE
To disable or change screenReader text

### ISSUE THREAD

**Issue by baiduing** [FrDH/jQuery.mmenu#928]
Hi, thank you very much for this best plugin and I'v used it for a long while. There's a problem when I use version 7.1.0.

When I use the code below

<pre>$("#menu").mmenu({
  navbar: {
    title: "abc"
  },
  screenReader: {
    text: false,
  },
})</pre>

I can simply disable the screen reader text output. But when I use these

<pre>$("#menu").mmenu({
  navbar: {
    title: "abc"
  },
  screenReader: {
    text: {
      closeMenu       : '22222',
      closeSubmenu    : '3333',
      openSubmenu     : '444',
      toggleSubmenu   : '5',
    },
  },
})</pre>

the text will be output as default, such as "Close menu".

Can you please show me how to change the text?

**Comment by FrDH** [comment]
There's a difference between the `screenReader.text` option and `screenReader.text` configuration. The first en-/disables the text, the latter tells the plugin what text to use:
````js
$("#menu").mmenu({
    // options
    screenReader: {
        text: true
    }
}, {
    // config
    screenReader: {
        text: {
            closeMenu: "Sluiten",
            closeSubmenu: "Submenu sluiten"
        }
    }
});
````
Hope this helps.

**Comment by baiduing** [comment]
Got it, thanks!
