### ISSUE TITLE
Set Active Panel

### ISSUE THREAD

**Issue by nuryagdym** [FrDH/jQuery.mmenu#929]
Hi, 
I have a menu with panels/tabs. 
According some conditions I want to make active either of tabs.
I checked js codes did find anything that I can accomplish this.
Tried to give css classes to panel and anchor links to accomplish this but it did not work too.

**Comment by FrDH** [comment]
The plugin compares the current opened panel ID to the HREF on the tabs. This is done in the "openPanel:start" hook, I guess you could override this using the API. Somthing like this:

````js
var $menu = $("#my-menu").mmenu({
   // options
   navbars: {},
   hooks: {
      "openPanel:start:" function() {
         var $tabs = $(".mm-navbar_tabs").children();
         $tabs.removeClass( "mm-navbar__tab_selected" );

         if ( YOUR_CONDITION ) {
            $tabs.first().addClass( "mm-navbar__tab_selected" );
         } else {
            $tabs.last().addClass( "mm-navbar__tab_selected" );
         }
      }
   }
});
````

**Comment by FrDH** [comment]
I'll see if I can add a more flexible ay for setting a tab selected.

**Comment by theodorosploumis** [comment]
You can also trigger a click on the `.mm_btn-next` after the menu appears.

```
const $menu = $("#mymenu");
const $burger = $("#burger");
const $mobileMenu = $menu.data("mmenu");

$burger.on("click", function() {
  $mobileMenu.open();
  $menu.find(".menu-item--active-trail.menu-item--expanded > .mm-btn_next").click();
});
```

In my case I am using **Drupal CMS 8.x**. In Drupal by default the menu parent that has submenus with at least **one active link** has the utility classes ```menu-item--active-trail menu-item--expanded```.

```

```
