### ISSUE TITLE
Keyboard Navigation add on not working

### ISSUE THREAD

**Issue by dubsteph** [FrDH/jQuery.mmenu#936]
After enabling the keyboard navigation add on, I am still having an issue of not being able to tab into and close out of the slider menu. Trying to fix issues for ADA.

Below are my javascript options:
```
$('#cart').mmenu({
      keyboardNavigation: {
        enable: true,
        enhance: true
      },
      navbar: {
        add: false
      },
      offCanvas: {
        zposition: 'front',
        position: '{{ settings.side_cart_position }}',
        pageSelector: "#content_wrapper"
      },
      "extensions": [
        "theme-{{ settings.mobile_menu_color }}"
      ]
    });
```

**Comment by FrDH** [comment]
Hi, what version of the plugin are you using?
The keyboardNavigation addon has been improved quite a bit the last few versions.

**Comment by stephenhebert** [comment]
It seems that at least the enhance option does not function as documented.

**Comment by alandesigns** [comment]
I had this issue too but it turned out to be Chrome's device toolbar registering the view as a touch-enabled device.
