### ISSUE TITLE
There are empty list items in subpanels within the Boostrap4 wrapper

### ISSUE THREAD

**Issue by derek36** [FrDH/jQuery.mmenu#937]
I would revert the change on line 107 of the boostrap4 wrapper.
The children() line is not penetrating deep enough to find the actual links, the find() you had would work better.

$d.find( '.dropdown-item, .dropdown-divider' )

**Comment by FrDH** [comment]
The problem with `find()` is that it finds links in sub-dropdowns as well. Although (as far as I know) sub-dropdowns are not a documented feature in Bootstrap, it sort of works by default.

**Comment by derek36** [comment]
Yes, that worked for me, great idea with the .add!
