### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by fussigabor** [FrDH/jQuery.mmenu#939]
Hello. The mobile menu is working on our site, however the mobile submenu not. Could you please take on it what is the issue? website url: http://sportfogadj.hu/mesotica

**Comment by fussigabor** [comment]
I am trying to use the same menu structure as it visible on desktop with mmmenu plugin on mobile. The main menu elements are visible, but the submenu isnt unfortunately. The arrows are there but you cant click on the element to open the submenu on mobile. This is what i would like to say.

**Comment by FrDH** [comment]
I visited the website but that mobile menu is not created with mmenu.
Am I missing something here? Please provide a working example.
