### ISSUE TITLE
Auto-Height size adjust after window resize

### ISSUE THREAD

**Issue by robhuska** [FrDH/jQuery.mmenu#941]
Let me start with saying how great this plugin is!

So, I have a menu that is in my own container, so I am not using the OffCanvas feature.  And I have the Auto-height add-on working great between panels. But if I resize my browser to a point that adjusts my font-size (in my own css), the auto-height does not recalculate the height needed to show the menu. However if I switch to a different panel and go back to the original panel in question, everything adjusts properly.

So what I am looking for is some type of API method to re-size the container that gets the height set to it.

I have tried a few things like:

- `api.closeAllPanels();` this only works if you are on a panel other than the first
- `api.openPanel($('.mm-panel_opened'));` but these won't work because it is trying to "open" the currently active panel

Is there any sort of method that I can use to recalculate the size of the currently opened panel?

Resizing to Smaller
![image](https://user-images.githubusercontent.com/2412155/47738687-0b4bae80-dc4a-11e8-890f-3e5108373c7e.png)
![image](https://user-images.githubusercontent.com/2412155/47738739-28807d00-dc4a-11e8-9c17-86c9fb4e7f5c.png)

Resizing to Larger (this is where the main issue lies)
![image](https://user-images.githubusercontent.com/2412155/47738796-4b129600-dc4a-11e8-9f42-bd8bafabfe17.png)
![image](https://user-images.githubusercontent.com/2412155/47738828-5ebdfc80-dc4a-11e8-8664-6ea1a0490ca0.png)

**Comment by FrDH** [comment]
Unfortunately the height isn't calculated onWindowResize.
I'll see if I can add an option or a method to the API for this.

For now, I guess you could use "getInstance" to get the menu class instance and trigger [one of the hooks used by the add-on](https://github.com/FrDH/jQuery.mmenu/blob/master/src/addons/autoheight/jquery.mmenu.autoheight.ts#L117-L132) onWindowResize. For example the "updateListview" hook (which actually would make sense):

````js
var api = $('#menu').data('mmenu');
var instance = api.getInstance();
$(window).resize(function() {
   instance.trigger( "updateListview" );
});
````

**Comment by robhuska** [comment]
Excellent!! This is exactly what I needed. I didn't even think to look into the resize addon. However a core resize method may still be a nice addition for the future.

Thanks for the fast and helpful response!

**Comment by robhuska** [comment]
So just out of curiosity, could you point me in the direction in the documentation where that hook is? Everything is working great, I am just looking to see where that hook is documented so I can see what else I may be missing out on... Thanks again!!

**Comment by FrDH** [comment]
You're not missing out on anythig, the "instance" is the entire mmenu class instance. It normally isn't available for usage (and therefor not documented), because using it in a wrong way can really mess things up. 
The "API" exposes a selection of methods that are safe to use and are all documented.
