### ISSUE TITLE
After connecting jquery.mmenu.js to WordPress, body adds element.style {top: -32px; }

### ISSUE THREAD

**Issue by Lugovou-Nazariy** [FrDH/jQuery.mmenu#942]
After it connects jquery.mmenu.js to WordPress, if I'm logged in (wpadminbar is present) after the start of scrolling, element.style {top: -32px; is added to the body; } and to remove it you just need to reload the page.

**Comment by FrDH** [comment]
Are you using the WP plugin? Or just the jQuery plugin?

**Comment by FrDH** [comment]
Sounds odd, nowhere in the script does it add a style to the body. My guess is the WP admin bar does this, but I have no idea why.

**Comment by Lugovou-Nazariy** [comment]
the question was resolved.
The problem was in the function of the sticky menu not related to the plugin jquery.mmenu
