### ISSUE TITLE
Question: Nested mmenus (not panels): is it possible?

### ISSUE THREAD

**Issue by graycrow** [FrDH/jQuery.mmenu#943]
For my project I need to implement not just nested panels, but nested menu, e.g. 3-column sliding mmenu where one of the panels have sliding tileview (another mmenu instance, with it's own config, etc.), which slides only in the boundaries of that panel (column).

Both menus works perfect by itself, but when I place one into another, glitches starts to appear (positioning, actions on child mmenu affects parent, etc.) and both menus stops working properly. 

So, am I trying to accomplish something terribly wrong which never was considered to be possible or am I missing something, some trick to make it work?

**Comment by FrDH** [comment]
I don't think that will work as the plugin was not designed to do so. But if you create a jsfiddle I'd be happy to take a look.

**Comment by graycrow** [comment]
If you have a time - please take a look, I created [an example](https://jsfiddle.net/xpvt214o/927607/).

Links "Open Level 2 Menu" and "Open Level 3 Menu" works as intended. Also navbar's back buttons  works (with a little hack). Link "Open Tile Menu" correctly opens a second level panel on column 2 and there I need to display a TileView menu which has it's own hierarchy (parent/child items) and it should traverse (slide in/out) that hierarchy in the boundaries of a second column (like as in iframe). I tried to accomplish this with a new instance of mmenu (`#menu-two`), but this doesn't work - items not having 50% width and navigation is broken.

**Comment by FrDH** [comment]
I played around a bit with the jsfiddle, but that isn't going to work :(

**Comment by graycrow** [comment]
@FrDH thank you for looking into. And thank you for a great plugin. I will try to find some solution, because I like that layout so much so it's hard for me to reject it. I will probably create a stripped-down version of the "on-canvas" module to play with it and see how changing the plugin name and css prefixes affects my layout (e.g. another copy of the plugin with different name and having all extra functionality removed to minimise overhead).

**Comment by FrDH** [comment]
Not sure what exactly you're trying to achieve, but if you want to apply the tileview extension to only a single panel, you should be able to do so by default. From [the documentation](https://mmenu.frebsite.nl/documentation/extensions/tileview.html):
> If you want to style only some listviews like a tileview, add the classname "mm-tileview" to the listview.

Hasn't been tested much, but worth a shot.

**Comment by graycrow** [comment]
@FrDH, I moved my tile-items from its own menu to the parent menu and added `mm-tileview` class, but it has no effect, menu works but all items looks the same. [jsfiddle](https://jsfiddle.net/xpvt214o/929263/).

**Comment by FrDH** [comment]
I think the docs need to be updated :/

If you add the class "mm-panel_tileview" to the parent `<div />`, all should work as intended:
https://jsfiddle.net/kh5xevwr/

**Comment by graycrow** [comment]
@FrDH, it's a big improvement, thank you! I think you can close this issue.

**Comment by FrDH** [comment]
Oo
