### ISSUE TITLE
Adding the menu to a bootstrap page

### ISSUE THREAD

**Issue by geforce9600gt** [FrDH/jQuery.mmenu#945]
Hey there!

If it is possible, how can i add this mmenu to a horizontal bootstrap navbar?
Can someone show me a theme or some sample for that?

**Comment by FrDH** [comment]
Check the [bootstrap wrapper](https://mmenu.frebsite.nl/documentation/wrappers/bootstrap.html) docs for the Bootstrap navbars.
If you right-click the tablet and select "open in new window", you can check the example.
Hope this helps.

**Comment by geforce9600gt** [comment]
Does it work with bootstrap 3? I dont wanna change to 4.

**Comment by FrDH** [comment]
It should.
> To enable creating a menu from a Bootstrap navbar collapse, include the "bootstrap3" or "bootstrap4" wrapper .js file and add "bootstrap3" or "bootstrap4" to the wrappers option.
