### ISSUE TITLE
Problem with scroll menu on Firefox Mobile

### ISSUE THREAD

**Issue by uapixart** [FrDH/jQuery.mmenu#946]
I have problem with scroll menu on Mobile Phone on Firefox browser version 63.0.2. Tested on Xiaomi Redmi 4X, Oneplus 6. For scroll menu i must make scroll twice or do it very slow.
Please help!
http://mmenu.frebsite.nl/demo/index.html?demo=mhead-1

**Comment by FrDH** [comment]
What exactly do you mean when you say "scroll menu"?

**Comment by uapixart** [comment]
![img_20181121_161334_990](https://user-images.githubusercontent.com/13638129/48846709-6c2d5900-eda8-11e8-8b26-1b518ffdf80a.jpg)
I mean when i scroll up and down left menu - i need scroll twice to effect scrolling. When i take scroll bar and down or up - that work fine for me!

**Comment by uapixart** [comment]
This problem only on Firefox!

**Comment by FrDH** [comment]
I can't reproduce the issue (using FireFox on an iPhone).
Are there any new insights about on what devices this issue occurs?

**Comment by uapixart** [comment]
![screenshot_2018-12-06-22-07-32-833_com android settings](https://user-images.githubusercontent.com/13638129/49609208-815ad800-f9a3-11e8-8ddf-dd06c0279e4a.png)
![screenshot_2018-12-06-22-07-32-833_com android settings](https://user-images.githubusercontent.com/13638129/49609224-861f8c00-f9a3-11e8-82f6-5b584237ff4c.png)
And I make video https://vimeo.com/304900391
