### ISSUE TITLE
searchfield.panel.splash is not working when I set search: false

### ISSUE THREAD

**Issue by dhavalwd** [FrDH/jQuery.mmenu#947]
Hello @FrDH 

Thanks for an awesome plugin and all the work that you do. I am not sure if I am missing something in my setup but when I set `search: false` and then try to use `panel.spalsh`, it doesn't work. As per my requirement, I would like to use that splash screen to show some suggested searches but then also keep the search to do the global search.

Here is the codepen with exmaple.
https://codepen.io/cooldhavs/pen/rQrxad

Let me know if there is a way to do it or if I am missing something. Thanks in advance for your help.

**Comment by FrDH** [comment]
As it appears, the searchpanel is only opened when the searchfield is initialized to actually search the listitems.
Your best change to work around this logic is to set the `search` option to `true` and remove the "input" event from the input:
https://codepen.io/anon/pen/ZmjZgm

Note that the "input" event is re-added each time a panel is initialized, I therefor added it to the "initPanels:after" hook.

**Comment by dhavalwd** [comment]
@FrDH I don't see `initPanels:after` hook in the codepen you provided. I tried to add that in my codepen but it doesn't seem to work. Here is my codepen with `initPanels: after` hook. Let me know if I have anything wrong in there. https://codepen.io/cooldhavs/pen/RqYgGy

But, I tried with `open:after` method to remove the `input` event from the `input` and that worked.
Here is the pen for that. https://codepen.io/cooldhavs/pen/LXJLEy

**Comment by FrDH** [comment]
Small typo: `initPanel:after` should be `initPanels:after` (panels with a "s", plural) :)

The `open:after` hook would probably also work but is a bit unlogic: Lets say you add/insert a new panel when the menu is opened, the newly added/inserted panel would invoke the `initPanels` hooks but not the `open` hooks.

**Comment by dhavalwd** [comment]
Totally makes sense. I have updated my codepen and that works like a charm. Here is the URL. https://codepen.io/cooldhavs/pen/RqYgGy

@FrDH Thanks again for your quick help and clarification. Love mmenu plugin.
