### ISSUE TITLE
this.opts.extensions[t].join is not a function

### ISSUE THREAD

**Issue by ividyon** [FrDH/jQuery.mmenu#949]
There's two other tickets for this, but none of them helped me resolve my problem (and they're closed now).

Running jQuery.mmenu 7.2.2. This is my code setup:

```
var mmenuOptions = {
            extensions: [
              'position-right',
              'shadow-page',
              'multiline'
            ],
            offCanvas: {
              moveBackground: false
            },
          };

          var mmenuConfig = {
            offCanvas: {
              page: {
                selector: '.site-wrapper',
                wrapIfNeeded: false
              }
            }
          };

          menu.wrap('<nav id="mobile-mmenu"></nav>').parent().mmenu(mmenuOptions, mmenuConfig);
```

Execution pops up the following error:

`Uncaught TypeError: this.opts.extensions[t].join is not a function`

Going into `jquery.mmenu.all.js` and formatting it, the offending code is the following:

```
this.trigger("initExtensions:before");
        var e = this;
        for (var t in this.opts.extensions.constructor === Array && (this.opts.extensions = {all: this.opts.extensions}), this.opts.extensions) {
          this.opts.extensions[t] = this.opts.extensions[t].length ? p.menu + "_" + this.opts.extensions[t].join(" " + p.menu + "_") : "", this.opts.extensions[t] && function (t) {
            e.matchMedia(t, function () {
              this.$menu.addClass(this.opts.extensions[t])
            }, function () {
              this.$menu.removeClass(this.opts.extensions[t])
            })
          }(t);
        }
        this.trigger("initExtensions:after")
```

Setting a debug breakpoint on `this.opts.extensions[t] = this.opts.extensions[t].length ? p.menu + "_" + this.opts.extensions[t].join(" " + p.menu + "_") : "", this.opts.extensions[t] && function (t) {`, it is visible that the code is ran twice.

For the first loop, the value of `this.opts.extensions[all]` is:

```
this.opts.extensions.all: Array(3)
0: "position-right"
1: "shadow-page"
2: "multiline"
length: 3
```

For the 2nd loop, it becomes:

`"mm-menu_position-right mm-menu_shadow-page mm-menu_multiline"`

which causes the error.

Is this an error on my side?

**Comment by FrDH** [comment]
Could you please check what `menu.length` returns?
Imo the script should work regardless of the number of menus, but worth checking.

**Comment by ividyon** [comment]
Hi FrDH,

thank you, that was indeed the issue. My selector for `menu` stupidly also included sub-menus within the menu I wanted to select. Thank you for addressing that issue.

However, I suppose it's also good to know that the script breaks when applying to multiple menus. I'm not sure if you consider this closed, so I'm keeping it open.

**Comment by FrDH** [comment]
It's a bug, having multiple menus should not break the plugin.
I'll see if I can fix it in the next release.

**Comment by FrDH** [comment]
will be fixed in the next release.
