### ISSUE TITLE
MMenu not work with Internet Explorer 9

### ISSUE THREAD

**Issue by whitedevils** [FrDH/jQuery.mmenu#951]
HI, i've a problem, my mmenu that i developed in my company site doesn't work on IE 9. This is a serious problem because some client has that old version of browser and can't update it.
Anyone know some "procedure" to get it work?
Thanks
![capture](https://user-images.githubusercontent.com/10058904/49508964-63e31c80-f884-11e8-9011-6e1566803028.PNG)

**Comment by whitedevils** [comment]
I have an update:
I had converted all translated3d in translate 2d and now the menu is hidden. But if i try to click on the hamburger mmenu does not come out.
I had open the firebug console in IE 9 and i find that "windows does not support matchmedia". Anyone know this problem? thanks

![capture](https://user-images.githubusercontent.com/10058904/49512721-2041e000-f88f-11e8-85ff-b816e6bf438a.PNG)

**Comment by whitedevils** [comment]
New Update:
i added this two javascript libraries (matchmedia, matchmedia.addListener) and now the side menù come out! but al least there is an other problem: the arrow when the <li> item is a href link is positioned under the link and not on the righ (in the picture is highlighted in blu).
I think is a css compatibility problem. Anyone can help me? After this all seems to work well!

![capture](https://user-images.githubusercontent.com/10058904/49519228-d3670500-f8a0-11e8-894b-72f8cd87e678.PNG)

**Comment by FrDH** [comment]
Hi, sorry for the late reply.

If you need support for IE9, I would recommend downgrading to version 6(.1.8), it has 2D transitions fallbacks for IE9 and doesn't crash if `window.matchMedia` isn't available. It also uses less modern CSS techniques.

I had a look at the CSS, but can't think of any reason for the arrow not to be next to text on IE9, as I don't have access to a computer with IE9 installed, I don't think I can help you with that.

Hope this helps.

**Comment by whitedevils** [comment]
I'll try that version, but also i have to convert from 3d to 2d Hamburgers library. If you want to try with IE9 you can use BrowserStack platform that can emulate al browser version of all browser (chrome, firefox, etc)

**Comment by whitedevils** [comment]
Sorry, i have an'other problem, now with mmenu, in all span doesn't work css vertical-align property! do you know something about it?
Thanks
