### ISSUE TITLE
WordPress bug with 2.8.0

### ISSUE THREAD

**Issue by gleenk** [FrDH/jQuery.mmenu#952]
Hello, in WordPress version 2.8.0 if you reach a page that is not listed in menu (for example a post of a blog), side mmenu will become empty. If you trigger it, it shows the empty menu with inside the button to call it. In 2.6.2 it works correctly.

**Comment by FrDH** [comment]
Thank you for reporting this issue. I don't recall changing anything to that logic, but I'll investigate and fit it asap.

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
I had a look at the source but as I expected the WP plugin doesn't really do any logic on what panel it should open and so by default, it should open the main panel.

**Comment by gleenk** [comment]
@FrDH have you been able to see it? I need to revert back to a working solution to put that site on production site :)

**Comment by FrDH** [comment]
I had a closer look and figured out why the menu isn't working as expected, you have a `<div id="pull />` inside the `<nav id="site-navigation" />`. As this DIV is the first node in the NAV, it is assumed to be the main panel of the menu (and therefor opened when no menu-item is selected).
If you can, you should move the DIV out of the NAV, or at least not as the first child in the NAV.

**Comment by FrDH** [comment]
In the next release, there will be some advance options that should be able to work around issues like this.
