### ISSUE TITLE
Can't understand how showSubPanels affect search

### ISSUE THREAD

**Issue by vk5880** [FrDH/jQuery.mmenu#955]
Spend half an hour to get the difference, and I can't find any.
http://mmenu.frebsite.nl/documentation/addons/searchfield.html

**Comment by vk5880** [comment]
And there is a bug: I can't find 'Services' menu
![image](https://user-images.githubusercontent.com/2523837/49887865-46531b80-fe5f-11e8-8cd3-749f0e0a4ba4.png)

**Comment by FrDH** [comment]
The `searchfield.showSubPanels` option will show a submenu (and all items in it) if it's parent item matches the search query. Note that this only works if you do not use the `searchfield.panel` option as this will show all (and only) marching items in a single panel.
