### ISSUE TITLE
Gulp file Breaks using Gulp 4.0

### ISSUE THREAD

**Issue by theller5567** [FrDH/jQuery.mmenu#958]
When using Gulp 4.0
After running gulp or npm run build
Terminal Error: AssertionError [ERR_ASSERTION]: Task function must be specified

**Comment by FrDH** [comment]
Do you have any idea how to fix this (in such a way it won't break when using Gulp 3)?

**Comment by FrDH** [comment]
next release will use gulp 4.

**Comment by FrDH** [comment]
version 7.3 uses gulp 4.
