### ISSUE TITLE
height: 100vh recommendation problematic in mobile browsers

### ISSUE THREAD

**Issue by jaffadog** [FrDH/jQuery.mmenu#959]
I am creating a webapp which runs full screen (100% width and height). Using height 100vh  recommendation (http://mmenu.frebsite.nl/support/tips-and-tricks.html) does not work for me in IOS Safari  because the viewport height can change in Safari (URL and button bar automatically resize/disappear) and the vh height is calculated once based on the maximum height within this dynamic behavior. This is not a mmenu issue; it's a IOS Safari issue; making it darn difficult to make good use of height 100vh in webapps that will run in a mobile webapp. see https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html.

Anyway - I'm having to go down the road of making body, mm-page, mainwrapper, and the div containing my webapp content all height 100%...

**Comment by godsdog** [comment]
If anyone need a solid solution for the 100vh mobile issue:
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
