### ISSUE TITLE
v7 browser support

### ISSUE THREAD

**Issue by danbramall** [FrDH/jQuery.mmenu#962]
Hi,

I can't see any details on browser support for the various versions of mmenu.  Specifically I'm wondering what the browser support is for v7.2.2.

If this could be documented somewhere (or if someone can point me to it if I've missed it) that would be great.

Many thanks.

**Comment by FrDH** [comment]
The plugin used to support "all" major browsers (down to IE9), that changed as of version 7.
I'll add a section about browser support sometime soon, untill then:

v6.1.8 should support IE9, without any restrictions.
v7.0.0 should support IE9, but you'll need a polyfill for `matchMedia`.
v7.1.0 shouid support IE10, but you won't be able to use the [CSS variables](https://mmenu.frebsite.nl/documentation/core/scss.html) (or any of the extensions that rely on the css variables)
