### ISSUE TITLE
Adding extra top (32px) in wp-admin bar

### ISSUE THREAD

**Issue by bilalmalkoc** [FrDH/jQuery.mmenu#963]
I am using **jquery.mmenu.all.js** with headroom.js. Everything is fine but i got this problem when admin is shown. 

    var $menu = $("#neon-menu").mmenu({
            "extensions": [
                //"theme-white",
                "border-full",
                "multiline",
                "pagedim-white",
                //"shadow-page"
            ],
            "navbar": {
                "title": themeObject.menu
            },
            "navbars": [
                {
                    "position": "bottom",
                    "content": [
                        "<a class='fa fa-envelope' href='#/'></a>",
                        "<a class='fa fa-twitter' href='#/'></a>",
                        "<a class='fa fa-facebook' href='#/'></a>"
                    ]
                }
            ],
            "counters": true,
            "iconbar": {
                "add": true,
                "top": [
                    "<a href='#/'><i class='fa fa-home'></i></a>",
                    "<a href='#/'><i class='fa fa-user'></i></a>"
                ],
                "bottom": [
                    "<a href='#/'><i class='fa fa-twitter'></i></a>",
                    "<a href='#/'><i class='fa fa-facebook'></i></a>",
                    "<a href='#/'><i class='fa fa-linkedin'></i></a>"
                ]
            }
        },
        {
            classNames: {
                fixedElements: {
                    sticky: "fixed-site-header"
                }
            }
        });

https://vgy.me/A2tbsp.gif

**Comment by lkraav** [comment]
Keep in mind at a certain breakpoint admin bar height will increase to 46px.

**Comment by bilalmalkoc** [comment]
@lkraav what is this answer? It not relevant to my question 😄

**Comment by FrDH** [comment]
Try adding this JS somewhere:
````js
jQuery("#wpadminbar")
    .css( 'position', 'fixed' )
    .addClass( 'mm-slideout' );
````
