### ISSUE TITLE
Page dim extension and fixed elements with a `position:fixed` position don't integrate properly

### ISSUE THREAD

**Issue by cjd118** [FrDH/jQuery.mmenu#965]
When using the page dim extension and the fixed elements add-on, the `position:fixed` header always shows above the dimmed page. Is this a known bug?

![image](https://user-images.githubusercontent.com/1626209/51487661-80d3a080-1d9b-11e9-8acd-ca4fc0a512d6.png)

(top white bar should be dimmed)

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
My guess is, you could check the z-index of the fixed element (or the menu an blocker) and adjust it to fit your needs.
