### ISSUE TITLE
Bootstrap Wrapper SPAN Submenu

### ISSUE THREAD

**Issue by fjherzog** [FrDH/jQuery.mmenu#966]
Hi Fred

Clicking the entire menu item to open a submenu is not possible with Bootstrap Wrapper.
When using SPAN in Bootstrap Nav, the wrapper always creates an A.

https://codepen.io/fjherzog/pen/bzGgvV

I'd guess the bootstrap nav html is only used, when using the same code for desktop nav and for mmenu mobile navigation. Using that SPAN in the bootstrap desktop nav could create some other issues, like mouseover misbehaviour or problems with existing css. Of course it could all get manually fixed but I guess thats not the point of the wrapper.

Check on codepen by adding navbar-expand-lg to the NAV.

The best solution for the bootstrap wrapper would be to always replace the A with a SPAN for parent elements (.dropdown-toggle) because in bootstrap these elements are never clickable and I guess a bootstrap wrapper should stick to bootstrap logic.

Thanks a lot!

**Comment by FrDH** [comment]
The bootstrap wrapper creates a new element for the anchors, it is always an `<a>`, I'll see if I can fix this to be a `<span>` when needed.

**Comment by FrDH** [comment]
Should be fixed in 7.3

**Comment by fjherzog** [comment]
Thank you Fred!!
