### ISSUE TITLE
Searchfield "cancel" button visible when extension "position-front" set

### ISSUE THREAD

**Issue by leavesoftea** [FrDH/jQuery.mmenu#970]
I am having an issue with the searchfield when it is prepended to the top of the navbar and the extension "position-front" is set. It seems that the "cancel" button flies out and stays visible. Is it possible to stop this behavior or change the way "cancel" is hidden?

![image](https://user-images.githubusercontent.com/5243858/52891543-461e1780-3151-11e9-8b56-6e57817a25c2.png)
![image](https://user-images.githubusercontent.com/5243858/52891633-d197a880-3151-11e9-9ebb-b8856a49df15.png)

**Comment by FrDH** [comment]
That's odd, I would have thought at least one of the surrounding elements had `overflow: hidden`.
I'll check and see if it can be fixed.

**Comment by FrDH** [comment]
I think this is a bug, although I need to test if the fix has consequences. You can try to add this CSS:
````css
.mm-menu {
    overflow: hidden;
}
````

**Comment by FrDH** [comment]
Should be fixed in 7.3.2

**Comment by leavesoftea** [comment]
Confirmed fixed in 7.3.2
