### ISSUE TITLE
Custom configuration is broken in the last version

### ISSUE THREAD

**Issue by graycrow** [FrDH/jQuery.mmenu#971]
When extending the configuration object, `opts` is passed to the `extend` method instead of `conf`.

https://github.com/FrDH/jQuery.mmenu/blob/6720611cf1d9191eb78a96271de26e5c670c360a/src/core/oncanvas/jquery.mmenu.oncanvas.ts#L1072

**Comment by FrDH** [comment]
:/ seriously bad copy/paste
thanks!

**Comment by graycrow** [comment]
No, thank **you**. Glad to help.
