### ISSUE TITLE
Dropdown add-on: Cannot read property 'button' of undefined

### ISSUE THREAD

**Issue by mrDinckleman** [FrDH/jQuery.mmenu#974]
I have created a simple example https://codepen.io/mrDinckleman/pen/WPmXwb
Included scripts from CDN:

- jquery/3.3.1/jquery.min.js
- jQuery.mmenu/7.3.0/jquery.mmenu.all.js

There is an error while clicking link or button:
`Uncaught TypeError: Cannot read property 'button' of undefined`

**Comment by FrDH** [comment]
Probably an issue with 7.3.0 which should be fixed in 7.3.1
