### ISSUE TITLE
Cloning in options, not in configuration

### ISSUE THREAD

**Issue by mrDinckleman** [FrDH/jQuery.mmenu#975]
I think, that in case to clone the menu from https://mmenujs.com/support/tips-and-tricks.html#tt-responsive-layouts you should not use options, but configuration.

Here is an example https://codepen.io/mrDinckleman/pen/XOGVwL

If I trying to set `clone: true` in configuration, cloning is not happened. Maybe documentation is out of date? Is it possible to add docs to repo?

**Comment by FrDH** [comment]
The clone option should be in the configuration.
There was a bug in 7.3.0 that probably causes this issue, please update to 7.3.1

**Comment by mrDinckleman** [comment]
Ok, seems to been fixed, thanks.
