### ISSUE TITLE
Close button inside menu

### ISSUE THREAD

**Issue by otterslide** [FrDH/jQuery.mmenu#978]
Is there any way to add a X button inside the menu that slides out off canvas?
I want to put the menu button on the top right. Then the menu slides out, and in the same top-right location, I want to have an X to close it.. so the X would have to be part of the menu.

I believe people mostly use the right thumb to quickly move around while holding the phone in the right hand, so I'm not sure why all your examples use a left-sided menu. Is there a reason to this or it was just preference?
Thanks!

**Comment by otterslide** [comment]
You can close this, I just used the example with the gradient colors that already has the close button beside the search box.

**Comment by FrDH** [comment]
ok
