### ISSUE TITLE
On-Canvas for Contao

### ISSUE THREAD

**Issue by greenskyes** [FrDH/jQuery.mmenu#988]
I'm trying to get on work On-Canvas Option for Contao 4.4 mmenu-Plugin. Unfortunately it not works with

```
<script type="text/javascript">
  $(document).ready(function() {
      $("#mmenu").mmenu({
          offCanvas: true;
      });
  });
</script>
```
Do have any idea how to solve this?

**Comment by yangkennyk** [comment]
how did you solve this?

**Comment by greenskyes** [comment]
Unfortunately not. I have addressed the subject here below: https://github.com/dklemmt/contao_dk_mmenu/issues/31
