### ISSUE TITLE
Turn off uglify (or called minify?) when with gulp watch

### ISSUE THREAD

**Issue by baiduing** [FrDH/jQuery.mmenu#990]
Hi,

in develop branch, how to get the unUglified version of this file `\dist\mmenu.js` ?

**Comment by FrDH** [comment]
Webpack minifies the script by default. According to [the webpack docs](https://webpack.js.org/configuration/optimization/) you should be able to configure it not to.

Open the file "gulp/js.js", go to the JSpack function and add the `optimization.minimize` rule.
````js
return src( input + '/mmenu.js' )
    .pipe( webpack({
        mode: 'production',
        output: {
            filename: 'mmenu.js',
        },
        optimization: {
            minimize: false
        }
    }) )
    .pipe( dest( dir.output ) );
````

Haven't tested it, but should work I think.

**Comment by baiduing** [comment]
Yea, thank you.
